### ISSUE TITLE
Non optimistic mode

### ISSUE THREAD

**Issue by SebDominguez-zz** [arachnetech/homebridge-mqttthing#102]
Some times, my devices experiment short disconnection and I'm ending up with the "get state" on Homekit not correctly reflecting the device real state.

Is there a way to make mqttthing working on a non optimistic mode ?

Homebridge publish on a set topic, then wait for a feedback on the get topic. If after some delay there isn't any get from the device the initial state is restored.

Maybe this is already supported but I can't find how to use it correctly.

**Comment by arachnetech** [comment]
There isn’t a way to do exactly that, but if you set the retain flag on published messages by using `”mqttPubOptions”:{“retain”: true}` then your MQTT server should send the message to your devices as soon as they resubscribe.

**Comment by arachnetech** [comment]
You may find the new `confirmationPeriodms` setting useful.
