### ISSUE TITLE
Sonoff POW running Tasmota Example

### ISSUE THREAD

**Issue by deon-wentzel** [arachnetech/homebridge-mqttthing#105]
Hi

I would like to use a Sonoff POW running Tasmota on the EVE App to monitor power. Does anyone have a working sample for me to work with or is this not supported?

**Comment by tobekas** [comment]
You can have a look at the Outlet Type (with option `"history": true`).
For topic `getWatts` you may have to use the apply-feature like this:

```
"getWatts": {
    "topic": "sonoff_pow_1/tele/SENSOR",
    "apply": "return JSON.parse(message).ENERGY.Power;"
},
```

**Comment by deon-wentzel** [comment]
Thank you...

**Comment by desq42** [comment]
@deon-wentzel 
Would you share your working config, or add it to the wiki?

Thank you…

**Comment by deon-wentzel** [comment]
Hi

Please find the following example

{
            "accessory": "mqttthing",
            "type": "outlet",
            "name": "Main Lights",
            "url": "mqtt://192.168.0.38",
            "mqttOptions": {
                "keepalive": 30
            },
            "mqttPubOptions": {
                "retain": true
            },
            "topics": {
                "getOn": "stat/manlight/POWER",
                "setOn": "cmnd/manlight/power",
                "getOnline": "tele/manlight/LWT",
                "getWatts": {
                    "topic": "tele/manlight/SENSOR",
                    "apply": "return JSON.parse(message).ENERGY.Power;"
                },
                "getVolts": {
                    "topic": "tele/manlight/SENSOR",
                    "apply": "return JSON.parse(message).ENERGY.Voltage;"
                },
                "getAmperes": {
                    "topic": "tele/manlight/SENSOR",
                    "apply": "return JSON.parse(message).ENERGY.Current;"
                }
            },
            "history": "true",
            "logMqtt": true,
            "onValue": "ON",
            "offValue": "OFF",
            "onlineValue": "Online",
            "startPub": {
                "cmnd/manlight/power": ""
            },
            "manufacturer": "ITEAD",
            "model": "Sonoff POW",
            "serialNumber": "20005784"
        }

I hope this helps?

**Comment by desq42** [comment]
Works. Thank you! Perhaps you should publish this on "Tested Configurations" in the wiki!

**Comment by deon-wentzel** [comment]
Done
