### ISSUE TITLE
mqttthing garagedoor

### ISSUE THREAD

**Issue by alexair777** [arachnetech/homebridge-mqttthing#108]
I am using the mqttthing garagedoor accessory but I run into some problems.
If I am using the garage icon in the homekit app, everything works fine. Opening, Closing. I publish the target value via the homekit app and receiving the status from an external device. But if I am trying to set the state of the garage externally, via set target, get target and/or with just using get current door state the icon just shows opening if I am trying to close the door externally. I previously used the homebridge-http-webhooks garagedoor accessory and that works with changing the status externally.

I love your mqtt plugins, how can I fix that problem?
Thanks so much!

**Comment by cbrandlehner** [comment]
You might workaround the problem by using contact sensor instead. Home App allows you to configure what kind of contact sensor you use - one of them is Garage Door.
All you have to send to Homebridge is status "open" or "closed".

**Comment by tobekas** [comment]
If you set the target state externally with `setTargetDoorState, you have to make sure, that your device will publish both `getTargetDoorState` and `getCurrentDoorState`properly. Otherwise this plugin does not get the change.

If target state is still OPEN, it will show opening.

**Comment by alexair777** [comment]
@cbrandlehner and @tobekas, thanks for your fast replies!
I will try it out today evening :)

**Comment by alexair777** [comment]
I have tried to set the door state externally with the same mqtt topic setTargetDoorState and the getTargetDoorState simultaneously but it do not refresh the homekit state instantly. Just after closing the homekit app and reopening shows the correct status. For this trial I opened the garage door manually per app and just tried to close the door externally.

**Comment by alexair777** [comment]
wow, thanks to tobekas for that troubleshooting.. how am I possible to update / get this changes?
best regards!

**Comment by tobekas** [comment]
should be available as soon as pull request #114 is merged.

**Comment by arachnetech** [comment]
Apologies, I missed this. Will have a look later...

**Comment by tobekas** [comment]
available in 1.0.42

**Comment by alexair777** [comment]
I updated to the latest 1.0.42 version of mqttthing, and now the garagedoor plugin works! I can change the door state externally and the status changes while the home app is still open.. thank you so much @arachnetech and @tobekas!!!

**Comment by arachnetech** [comment]
Great fix of my stupid error, @tobekas, thanks!

**Comment by RaymondMouthaan** [comment]
Hi guys, today I have added two garage doors to control two gates, all works perfectly fine. 
One question I have is, how to set the initial state of the garage door to "closed" instead of "open"? Each time I restart homebridge the state is "open" but it should be set to "closed".

**Comment by EjvindHald** [comment]
The garage door is working absolute fine both with inputs from phone and from the mqtt client.
Thanks.

**Comment by rasgeek** [comment]
> I am using the mqttthing garagedoor accessory but I run into some problems.
> 
> If I am using the garage icon in the homekit app, everything works fine. Opening, Closing. I publish the target value via the homekit app and receiving the status from an external device. But if I am trying to set the state of the garage externally, via set target, get target and/or with just using get current door state the icon just shows opening if I am trying to close the door externally. I previously used the homebridge-http-webhooks garagedoor accessory and that works with changing the status externally.
> 
> 
> 
> I love your mqtt plugins, how can I fix that problem?
> 
> Thanks so much!
> 
> 

How did you get it working.what Matt switch are you using

**Comment by jeylites** [comment]
Hello, I'm testing the tasmota [garage door opener project](https://github.com/arendst/Tasmota/issues/3942). I got the relay to trigger but can't seem to get the state to work. Would you mind checking to see if the config is correct?

Plugin
[HB Plugin](https://github.com/arachnetech/homebridge-mqttthing#readme)[](https://user-images.githubusercontent.com/9190080/159613970-9c9df6e4-9185-44df-aad4-650f3902b91e.png)

HB Config

"type": "garageDoorOpener",
            "name": "AUTO",
            "url": "192.168.1.200",
            "accessory": "mqttthing",
            "topics": {
                "getTargetDoorState": "stat/GarageDoor/STATE",
                "getCurrentDoorState": "stat/GarageDoor/STATE",
                "getLockTargetState": "tele/tasmota_65E47F/STATE",
                "setTargetDoorState": "cmnd/tasmota_65E47F/POWER"
            },
            "doorCurrentValues": [
                "Open",
                "Closed",
                "Opening",
                "Closing",
                "Stopped"
            ],
            "doorTargetValues": [
                "on",
                "off"
            ],
            "lockValues": [
                "Unsecured",
                "Secured",
                "Jammed",
                "Unknown"
            ]
Wemos D1 - Settings & Logs
2022-03-23

03:44:21.859 MQT: stat/tasmota_65E47F/RESULT = {"Var1":"0"}
03:44:22.088 MQT: stat/tasmota_65E47F/RESULT = {"Var2":"0"}
03:44:22.314 MQT: stat/tasmota_65E47F/RESULT = {"Var3":"0"}
03:44:22.541 MQT: stat/tasmota_65E47F/RESULT = {"Var4":"1"}
03:44:22.772 MQT: stat/tasmota_65E47F/RESULT = {"T1":15,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}
03:44:22.972 MQT: stat/tasmota_65E47F/RESULT = {"Event":"Done"}
03:44:23.047 RUL: EVENT#PSTATE performs "publish stat/GarageDoor/STATE CLOSING"
03:44:23.053 MQT: stat/GarageDoor/STATE = CLOSING
03:44:25.392 RUL: SWITCH1#STATE=1 performs "backlog event Opened"
03:44:25.422 MQT: stat/tasmota_65E47F/RESULT = {"Event":"Done"}
03:44:25.493 RUL: EVENT#OPENED performs "Backlog var 1; var2 0; var3 0; var4 0; ruletimer1 0; event PState=OPEN"
03:44:25.520 MQT: stat/tasmota_65E47F/RESULT = {"Var1":"0","Var2":"0","Var3":"0","Var4":"1","Var5":"","Var6":"","Var7":"","Var8":"","Var9":"","Var10":"","Var11":"","Var12":"","Var13":"","Var14":"","Var15":"","Var16":""}
03:44:25.729 MQT: stat/tasmota_65E47F/RESULT = {"Var2":"0"}
03:44:25.957 MQT: stat/tasmota_65E47F/RESULT = {"Var3":"0"}
03:44:26.171 MQT: stat/tasmota_65E47F/RESULT = {"Var4":"0"}
03:44:26.402 MQT: stat/tasmota_65E47F/RESULT = {"T1":0,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}
03:44:26.521 RUL: SWITCH1#STATE=0 performs "backlog event Closing"
03:44:26.545 MQT: stat/tasmota_65E47F/RESULT = {"Event":"Done"}
03:44:26.619 RUL: EVENT#PSTATE performs "publish stat/GarageDoor/STATE OPEN"
03:44:26.624 MQT: stat/GarageDoor/STATE = OPEN
03:44:26.837 MQT: stat/tasmota_65E47F/RESULT = {"Event":"Done"}
03:44:26.910 RUL: EVENT#CLOSING performs "Backlog var1 0; var2 0; var3 0; var4 1; ruletimer1 15; event PState=CLOSING"
03:44:26.931 MQT: stat/tasmota_65E47F/RESULT = {"Var1":"0"}
03:44:27.170 MQT: stat/tasmota_65E47F/RESULT = {"Var2":"0"}
03:44:27.395 MQT: stat/tasmota_65E47F/RESULT = {"Var3":"0"}
03:44:27.620 MQT: stat/tasmota_65E47F/RESULT = {"Var4":"1"}
03:44:27.848 MQT: stat/tasmota_65E47F/RESULT = {"T1":15,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}
03:44:28.099 MQT: stat/tasmota_65E47F/RESULT = {"Event":"Done"}
03:44:28.177 RUL: EVENT#PSTATE performs "publish stat/GarageDoor/STATE CLOSING"
03:44:28.184 MQT: stat/GarageDoor/STATE = CLOSING
03:44:28.215 RUL: SWITCH1#STATE=1 performs "backlog event Opened"
03:44:28.247 MQT: stat/tasmota_65E47F/RESULT = {"Event":"Done"}
03:44:28.317 RUL: EVENT#OPENED performs "Backlog var 1; var2 0; var3 0; var4 0; ruletimer1 0; event PState=OPEN"
03:44:28.346 MQT: stat/tasmota_65E47F/RESULT = {"Var1":"0","Var2":"0","Var3":"0","Var4":"1","Var5":"","Var6":"","Var7":"","Var8":"","Var9":"","Var10":"","Var11":"","Var12":"","Var13":"","Var14":"","Var15":"","Var16":""}
03:44:28.554 MQT: stat/tasmota_65E47F/RESULT = {"Var2":"0"}
03:44:28.781 MQT: stat/tasmota_65E47F/RESULT = {"Var3":"0"}
03:44:29.009 MQT: stat/tasmota_65E47F/RESULT = {"Var4":"0"}
03:44:29.239 MQT: stat/tasmota_65E47F/RESULT = {"T1":0,"T2":0,"T3":0,"T4":0,"T5":0,"T6":0,"T7":0,"T8":0}
03:44:29.488 MQT: stat/tasmota_65E47F/RESULT = {"Event":"Done"}
03:44:29.564 RUL: EVENT#PSTATE performs "publish stat/GarageDoor/STATE OPEN"
03:44:29.572 MQT: stat/GarageDoor/STATE = OPEN
03:45:09.195 MQT: tele/tasmota_65E47F/STATE = {"Time":"2022-03-23T03:45:09","Uptime":"0T00:05:09","UptimeSec":309,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SMILE","BSSId":"98:77:E7:72:CB:65","Channel":6,"Mode":"11n","RSSI":40,"Signal":-80,"LinkCount":1,"Downtime":"0T00:00:03"}}
03:45:09.231 MQT: tele/tasmota_65E47F/SENSOR = {"Time":"2022-03-23T03:45:09","Switch1":"ON","Switch2":"ON","Switch3":"ON"}
03:48:41.123 MQT: stat/tasmota_65E47F/RESULT = {"POWER":"ON"}
03:48:41.126 MQT: stat/tasmota_65E47F/POWER = ON
03:48:41.879 MQT: stat/tasmota_65E47F/RESULT = {"POWER":"OFF"}
03:48:41.883 MQT: stat/tasmota_65E47F/POWER = OFF
