### ISSUE TITLE
fakegato history not working for occupancy sensor

### ISSUE THREAD

**Issue by odx** [arachnetech/homebridge-mqttthing#111]
From the documentation I understand that fakegato history should work for motion sensors. I have configured a few occupancy sensors (Xiaomi via zigbee2mqtt).
For other sensors such as contact or temperature sensors the history in the eve app is working well... Only the occupancy sensors are troublesome.

**Comment by tobekas** [comment]
Not sure if Eve supports history for occupancy sensors at all. If so, adding this would be easy work. Bit I think it is limited to motion sensors.

btw: What is the difference between motion and occupancy sensors in homekit?

**Comment by odx** [comment]
actually I was assuming there is no difference...

**Comment by tobekas** [comment]
Ok, please try motion sensor type with history option (see Readme), for me this is working fine!

**Comment by odx** [comment]
works fine. thanks.
