### ISSUE TITLE
Problem with sonoff  switch and tasmota software

### ISSUE THREAD

**Issue by lulek2007** [arachnetech/homebridge-mqttthing#112]
Hello ,

I am trying to properly configure the sonoff switch with the tasmota software installed

I currently have the following configuration
```
{
        "accessory": "mqttthing",
        "type": "switch",
    	"name": "Lampka biurkowa gabinet LED",
	"url": "mqtt://192.168.4.10",
	"username": "admin",
	"password": "12345",
        "topics": {
                "setOn": "cmnd/DVES_5A6400/POWER",    
                "getOn": {
    		    "topic": "tele/DVES_5A6400/STATE",
    		    "apply": "return JSON.parse(message).POWER;"
    		},
                "getOn": "stat/DVES_5A6400/POWER",    

	"getOnline": {
                    "topic": "tele/DVES_5A6400/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
                }
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "logMqtt": true
        },
```
the problem is to use "getOn" twice:

this is needed because the switch gives the following information

in topic
```
MQT: tele / DVES_5A6400 / STATE = {"Time": "2019-05-13T15: 47:45", "Uptime": "0T02: 18: 30", "Vcc": 3.196, "SleepMode": "Dynamic" "Sleep" 50 "loadavg" 19, "POWER", "ON", "WiFi": { "AP" 1 "SSID", "Ceres", "BSSID", "10: 9A: DD 8A: 91: CB "," Channel "2" RSSI "88" LinkCount "1" downtime "" 0T00: 00: 04 "}}
```
reported every 5 second "POWER": "ON" or "OFF" representing the state of the switch

but when I press a button on the switch housing in the HOME application, I have such a lag in changing the status

in the second topic
```
MQT: stat / DVES_5A6400 / RESULT = {"POWER": "ON"}
```
the reaction of the HOME application is immediate. The problem is when you restart homebridge. Then the device status is not updated (it is not known in the HOME application the device is actually turned on or off). The update takes place after switching the switch in the HOME application or pressing the button on the switch housing and the status is correct.
This is because 
```MQT: stat / DVES_5A6400 / RESULT = {"POWER": "ON"} ``` is only published after changing the status of the device. After homebridge restart, until the change is not published and status not updated

Is it possible to put in one "getOn" both topics with function or?

i.e.  

```
  "getOn": {
    		    "topic": "tele/DVES_5A6400/STATE",
    		    "apply": "return JSON.parse(message).POWER;"
    		    
OR
                "getOn": "stat/DVES_5A6400/POWER",    
                 },


Best regards, Marcin Kowalik

**Comment by NorthernMan54** [comment]
How similar is this device to my dimmable light switch?  Config is here

https://github.com/arachnetech/homebridge-mqttthing/wiki/Tested-Configurations#ce-smart-wifi-smart-dimmer

**Comment by lulek2007** [comment]
Hi  NorthernMan54

Thank you for the hint

I was looking in the official documentation in the switch section and did not look at the tested examples ! 

Now 
```
{
        "accessory": "mqttthing",
        "type": "switch",
    	"name": "Lampka biurkowa gabinet LED",
	"url": "mqtt://192.168.4.10",
	"username": "admin",
	"password": "12345",
        "topics": {
                "setOn": "cmnd/DVES_5A6400/power",    
                "getOn": "stat/DVES_5A6400/POWER",    
		"getOnline": {
                    "topic": "tele/DVES_5A6400/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
            	    }
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "startPub": {
        	"cmnd/DVES_5A6400/power": "",
        	"stat/DVES_5A6400/POWER": ""
    		},
            "logMqtt": true
        },
```
work perfectly,

Regards Marcin Kowalik
