### ISSUE TITLE
Security System..

### ISSUE THREAD

**Issue by dezral** [arachnetech/homebridge-mqttthing#113]
Right now i using an node-red plugin for this and it works.. but i would like to move that part away from node-red to homebridge that i use for so many other things.

but i can't get Security System to work right.. it will only switch to disarm all the others it just hangs or at least do not switch..

i have been reading the other posts about Security System and it seems no one confirms that it works for them either.

i have try'd this 

```
{
            "accessory": "mqttthing",
            "type": "securitySystem",
            "name": "hus Alarm",
            "url": "mqtt://localhost:1883",
            "topics": {
                "setTargetState": "home/sec/",
                "getTargetState": "home/sec/current",
                "getCurrentState": "home/sec/current"
            },
            "currentStateValues": [
                "STAY_ARM",
                "AWAY_ARM",
                "NIGHT_ARM",
                "DISARMED",
                "ALARM_TRIGGERED"
            ],
            "targetStateValues": [
                "STAY_ARM",
                "AWAY_ARM",
                "NIGHT_ARM",
                "DISARM"
            ]
        }
```

on another note.. homekit supports disabling some values i do it on node-red with this "Characteristic Properties"

{
    "SecuritySystemTargetState": {
        "validValues": [1, 3]
    }
}

so i will only get AWAY_ARM and DISARM (and trigger)..

would this be possible?

**Comment by arachnetech** [comment]
mqttthing just exposes Homekit's properties through MQTT - so the actual behaviour comes entirely from Homekit. With a service like security system and garage door, Homekit expects to set a state (the target state) then requires the device to confirm this by updating current state correspondingly.

It's possible to change the state of garage door externally (although the Home app doesn't show this unless you close then re-open it), but I can't remember whether this is possible for security system.

I'll add support for limiting the valid target states.

**Comment by tobekas** [comment]
I found the bug:

If you update these states via get-topic, the `callback()` is not evaluated, because `callback()` is in the wrong line (only for multiCharacteristic types). Thus, the new value is not updated to HomeKit but only within mqttthing. That also explains why it is sometimes updated after closing and re-opening.

This might also be related to #108, #79, #75, #73, #14, #1.
I already fixed this within my TV Accessory Pull-Request (#114)

**Comment by tobekas** [comment]
does it work now?

**Comment by dezral** [comment]
i have not tested it, had not had much time lately to play ,-), but i do have a few days off now and will look at it soon

**Comment by dezral** [comment]
testet, but there are missing a  "setCurrentState": "home/sec/current" in exsample in README. as you write  it need an confirm on setCurrentState

My following and it seems working config is:

```
{
            "accessory": "mqttthing",
            "type": "securitySystem",
            "name": "Alarm",
            "topics": {
                "setTargetState": "home/sec/Settarget",
                "getTargetState": "home/sec/Gettarget",
                "getCurrentState": "home/sec/Getcurrent",
                "setCurrentState": "home/sec/Setcurrent"
            },
        "restrictTargetState": [ 1, 3 ]
        },
```


i could not get it to work with currentStateValues and targetStateValues so used the ones from homekit.

will work on it an get back with a better one.

**Comment by tobekas** [comment]
In the Readme, a lot of things get mixed up. A setCurrentState does not exist in Homekit! Sometimes get and set are reversed in the description.
setTargetState is send to the device to set the target state and it should answer with getTargetState. If target state is changed on the device itself, getTargetState will inform about the change. CurrentState is the State that is really accepted/active. This cannot be set. Typically current state should match the target state. In case of an alarm, current state is changed to ALARM_TRIGGERED, but target state remains unchanged. 

@arachnetech: Can you fix the readme?

**Comment by arachnetech** [comment]
Thanks I’ll take a look

**Comment by arachnetech** [comment]
Agreed - my description was wrong in a few places, and predated the changes/fixes allowing security system to be controlled externally. I've corrected it now (hopefully).

**Comment by EjvindHald** [comment]
I am using this, and it is working absolute fine. Both with commands from the phone and from that native security system.
However, the logic for the client can be a challenge. Try go to this [link](https://github.com/ccutrer/openhab2-addons/blob/2.5.0-cody2/addons/io/org.openhab.io.homekit/README.md) and scroll down to the example at the bottom. I know it is written in openHAB code, but it is fairly easy to understand. Try understand the logic from the client, and if you combine it with the fine description in this mqtt plug-in you can make a fine solution.

**Comment by EjvindHald** [comment]
So the conclusion is that this is working as intended and the documentation is correct.

This issue can be closed.

**Comment by arachnetech** [comment]
Thanks.
