### ISSUE TITLE
Smoke Sensor Shelly

### ISSUE THREAD

**Issue by mientki** [arachnetech/homebridge-mqttthing#115]
I have Shelly Smoke Sensor and try add accessory to Homebridge, but is missing the temperature characteristics that this device has. Is it possible to add such characteristics to additionally show the temperature as a separate tile? The weather station is similarly done. One accessory - two tiles in homekit. 
My config:
````
        {
            "accessory": "mqttthing",
            "type": "smokeSensor",
            "name": "Czujnik dymu",
            "url": "mqtt://localhost",
            "logMqtt": true,
            "topics": {
                "getSmokeDetected": "shellies/shellysmoke-743B66/sensor/smoke",
                "getCurrentTemperature": "shellies/shellysmoke-743B66/sensor/temperature",
                "getBatteryLevel": "shellies/shellysmoke-743B66/sensor/battery"
            },
            "onValue": "true",
            "offValue": "false",
            "resetStateAfterms": 300000
        }
````

**Comment by tobekas** [comment]
In principle it is possible to add multiple services(!) to one accessory. But you could also add a second accessory as well for the TemperatureSensor service. In the Home App this makes no difference. However, within the Eve App the services would be nicely grouped, if added to one accessory.

I would advise you to simply configure a second accessory:

```
{
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "Czujnik dymu",
            "url": "mqtt://localhost",
            "logMqtt": true,
            "topics": {
                "getCurrentTemperature": "shellies/shellysmoke-743B66/sensor/temperature"
            }
        }
```

**Comment by mientki** [comment]
I did it before, but I wanted to have one accessory.

**Comment by pbksol** [comment]
HomeKit does not support Temperature in Smoke Sensors. If you need the Temp, you have to add a Temperature accessory.
