### ISSUE TITLE
Online Status notification

### ISSUE THREAD

**Issue by Simonv92** [arachnetech/homebridge-mqttthing#119]
Hi, I'm trying to configure the oline status on my devices. I have some ESP8266 modules that sends "1" every loop to a kwown topic. (I also set "integerValue": "true" on Json file on Homebridge).
On Homebridge I'm monitoring the same topic with the ""getOnline":" function but on my Home app the devices are always shown as online even when I turn them off... What I'm doing wrong?
Thank you very much!

Simone

**Comment by tobekas** [comment]
Apple's home app does not update the availability status continuously. You have to reopen the app or switch between rooms to trigger a new request.

I don’t know if there is a better way for implementing „not responding state“.

**Comment by tobekas** [comment]
This topic was discussed here in great detail: https://github.com/KhaosT/HAP-NodeJS/pull/556

@arachnetech: At the end there are some interesting comments regarding ‚get‘ events. It seems worthwhile to forego the get events and use the hap-nodejs cache instead of your own status-object cache?

**Comment by aboulfad** [comment]
@arachnetech , I have not used HB or this plugin, but started reading on both/checking issues. Indeed as discussed and summarized here https://github.com/KhaosT/HAP-NodeJS/pull/556#issuecomment-487034618 , the usage of **get** event will be problematic especially for services such as security system and accessories that make up a security system (contact switches, smoke detector,...)

Don’t know if in the current version of this plugin, if real time events are pushed in real-time to HomeKit using the get event listener implementation when the accessory updates its state (without switching rooms or re-opening the Home app)

**Comment by tobekas** [comment]
There is no problem for all the standard characteristics. They all will be pushed immediately after state chance.

In this topic, it‘s about the notification that an accessory is not available. Because for this, there is no specific HAP characteristic.

**Comment by aboulfad** [comment]
^^^ Good to know for when I start to use HB and this plugin. From my discussion in issue 55), I was under the impression that a .get event listener only triggers when a user changed rooms/open Home.

I understand the scope of this topic, apologies for having mixed another subject. I was responding/commenting based on your suggestions above.

**Comment by tobekas** [comment]
Anyway, a get listener is implemented additionally in this plugin. It is not really necessary, but it is not a problem either.
It is right, that a get request is only triggered in the cases mentioned. But as long as this plugin makes use of the update/set calls on every state change (triggers by incoming mqtt message), there is no need for the get request. It’s pushed directly from his plugin to the Homekit universe (Home App, ...).

**Comment by aboulfad** [comment]
> ... But as long as this plugin makes use of the update/set calls on every state change (triggers by incoming mqtt message), there is no need for the get request. It’s pushed directly from his plugin to the Homekit universe (Home App, ...).
Gotcha, I was reading the code and saw multiple set calls, so it’s a non issue what I mentioned above. Thanks for the clarification.
