### ISSUE TITLE
Fan accessory

### ISSUE THREAD

**Issue by mientki** [arachnetech/homebridge-mqttthing#12]
How add fan accessory ? After entering the "type": "fan", homebridge does not start.

**Comment by arachnetech** [comment]
You can use type `outlet` for a fan, then change it in to a fan in the Home app (giving it an animated fan icon).

**Comment by mientki** [comment]
Will there be support in the future for a fan? homebridge-ui-x with plugin "accessories" does not display the correct icons: http://prntscr.com/k6fgkw

**Comment by mientki** [comment]
very nice. I am waiting for an update :)

**Comment by mientki** [comment]
When can you expect an update? :)

**Comment by arachnetech** [comment]
I'll try to have a look this weekend!

**Comment by arachnetech** [comment]
Version 1.0.12 now supports the Fan service. You can use this just like an outlet by using setOn/getOn topics only (changing type to "fan"), but I've also supported rotation direction and rotation speed optionally.
