### ISSUE TITLE
Switch with more buttons like hue dimmer

### ISSUE THREAD

**Issue by dezral** [arachnetech/homebridge-mqttthing#120]
I have a hue dimmer and in homekit it just registers as one device with 4 buttons..

i kinder can do that with statelessProgrammableSwitch but with but that would be single, doble  and long... 

Switch can only do one..

is it possible to make a homekit "device" with 4 buttons i can activate from mqtt..

something like this.
![](https://photos5.appleinsider.com/gallery/23380-29428-Image-34-l.jpg)

**Comment by dezral** [comment]
I have try'd the statelessProgrammableSwitch with this config:
{
        "accessory": "mqttthing",
        "type": "statelessProgrammableSwitch",
        "name": "Clicker",
        "url": "mqtt://127.0.0.1:1883",
        "topics": {
                "getSwitch": "home/clicker",
                "apply": "return( ( JSON.parse(message).click === single ) ? 1 : null || ( JSON.parse(message).click === double ) ? 0  : null || ( JSON.parse(message).click === triple ) ? L  : null );"
        }
}

but it does not work.. i get single,double,triple and quadruple as an output like this:
payload '{"linkquality":63,"battery":100,"voltage":3125,"click":"single"}'

if i just do "mosquitto_pub -t home/clicker -m 2" it works..

have try'd with "" and ' ' around the output from zigbe2mqtt and L.. no luck

but would still love a way to to it with a switch lige the hue dimmer.

**Comment by odx** [comment]
I have implemented my IKEA tradfri remote to be represented as three separate statelessProgrammableSwitches in HomeKit so I can use all buttons and actions on the remote. They all use the same topic the statelessProgrammableSwitch will ignore any switchValues that are not listed in the array.

Here an example to use the same topic to act according to four different actions:
```
{
            "accessory": "mqttthing",
            "username": "YY",
            "password": "XX",
            "type": "statelessProgrammableSwitch",
            "name": "Remote 1",
            "topics": {
                "getSwitch": {
                    "topic": "zigbee/Remote",
                    "apply": "return JSON.parse(message).action"
                }
            },
            "switchValues": [
                "arrow_left_click",
                "arrow_left_hold",
                "foo"
            ]
        },
        {
            "accessory": "mqttthing",
            "username": "YY",
            "password": "XX",
            "type": "statelessProgrammableSwitch",
            "name": "Remote 2 ",
            "topics": {
                "getSwitch": {
                    "topic": "zigbee/Remote",
                    "apply": "return JSON.parse(message).action"
                }
            },
            "switchValues": [
                "arrow_right_click",
                "arrow_right_hold",
                "foo"
            ]
        },
```

**Comment by tobekas** [comment]
odx‘s solution is currently the best solution.
In principle it is possible to make one device with multiple buttons. For that the code would have to be extended:
- multiple instances of the „Stateless Programmable Switch“ service must be added to the accessory.
- each of these services must include the characteristic „Service Label Index“ with a fixed unique value (1, 2, 3...)
- optional: Service „Service Label“ with characteristic „Service Label namespace“ may be added to specify the naming schema: 0 = Button (1Dot, 2Dots...)  1 = Button 1, 2, ... (numerical)

**Comment by tobekas** [comment]
see also: https://github.com/KhaosT/HAP-NodeJS/issues/563

**Comment by dezral** [comment]
this worked yes..  thank you ;-)

i now have some other buttons built in to the house i think i called "Momentary switch/button" that goes 0 -> 1 on every push and back to 0.. 

i have shelly devices behinde them all and shelly supports Momentary and the input(switch) have longpush also built in to shelly.

my 2 part question is.. can mqttthing and the "Apply" function count like 1 push 2 push within 1 sec and then do the following "single or double" push action?

Q2. witch i guess is no but here goes: does mqttthing support reading 2 topics? like:
shellies/shellyswitch25-******/input/0
shellies/shellyswitch25-******/longpush/0

if ($input == 1 && $longpush == 0 ){ do "single";}
elseif $input == 2 && $longpush == 0 ){do "double";}
elseif $input == 1 && $longpush == 1 ){do "longpush";}

or will have to make those possible through node-red or other.

**Comment by tobekas** [comment]
In my opinion, this function goes too far to be implemented in Mqttthing. This plugin is primarily a bridge between HomeKit and Mqtt... not for creating the Mqtt message itself. Maybe the double-tab detective can be implemented but I can not decide that. Logical connections go a little too far. 
That's exactly what NodeRed is perfect for!

An open topic would be the originally extension for multiple button support, as described above.

**Comment by piotrbielaska** [comment]
Hi Guys. I'm out of options with Hue Dimmer. I have finished with part of config.yaml which shows switch in HomeKit and publish it's battery level. Problem is that switch doesn't work when buttons are pressed. I can see that Mosquitto receives correct information from zigbee2mqtt (for example: `{"battery":100,"linkquality":73,"counter":1,"brightness":193,"update_available":false,"action":"on-press","duration":0}`). I have assigned light to turn on with switch in HomeKit. I'm pressing button and nothing happens. Am I doing something wrong here?

`        {
            "type": "statelessProgrammableSwitch",
            "name": "Hall Entry",
            "url": "mqtt://10.0.100.11:1883",
            "username": "username",
            "password": "password",
            "topics": {
                "getSwitch": {
                    "topic": "zigbee2mqtt/0x0017880104e6c096",
                    "apply": "return JSON.parse(message).action;"
                },
                "switchValues": [
                    "on-press",
                    "up-press",
                    "down-press"
                ],
                "getStatusLowBattery": {
                    "topic": "zigbee2mqtt/0x0017880104e6c096",
                    "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
                },
                "getBatteryLevel": {
                    "topic": "zigbee2mqtt/0x0017880104e6c096",
                    "apply": "return JSON.parse(message).battery;"
                }
            },
            "accessory": "mqttthing",
            "loggMqtt": "true"
        },`

**Comment by arachnetech** [comment]
Hard to see when the config is all in one block, but your issue is that `switchValues` shouldn't be inside `topics`. Here's my working config:

```json
        {
            "type": "statelessProgrammableSwitch",
            "name": "Hall Entry",
            "url": "homebridge",
            "topics": {
                "getSwitch": {
                    "topic": "zigbee2mqtt/0x0017880104e6c096",
                    "apply": "return JSON.parse(message).action;"
                },
                "getStatusLowBattery": {
                    "topic": "zigbee2mqtt/0x0017880104e6c096",
                    "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
                },
                "getBatteryLevel": {
                    "topic": "zigbee2mqtt/0x0017880104e6c096",
                    "apply": "return JSON.parse(message).battery;"
                }
            },
            "switchValues": [
                "on-press",
                "up-press",
                "down-press"
            ],
            "accessory": "mqttthing",
            "logMqtt": true
        }
```

Note `"logMqtt": true` too. You had an extra `g` and `"true"`.

**Comment by arachnetech** [comment]
Also your true and false values are "true" and "false" so returning 1 and 0 from statusLowBattery won't work.

Here's an alternative config fixing that and using the JSON codec to remove two of the apply functions:

```json
        {
            "type": "statelessProgrammableSwitch",
            "name": "Hall Entry",
            "url": "homebridge",
            "topics": {
                "getSwitch": "zigbee2mqtt/0x0017880104e6c096",
                "getBatteryLevel": "zigbee2mqtt/0x0017880104e6c096",
                "getStatusLowBattery": {
                    "topic": "zigbee2mqtt/0x0017880104e6c096",
                    "apply": "return message < 20;"
                }
            },
            "switchValues": [
                "on-press",
                "up-press",
                "down-press"
            ],
            "codec": "json",
            "jsonCodec": {
                "properties": {
                    "switch": "action",
                    "batteryLevel": "battery",
                    "statusLowBattery": "battery"
                }
            },
            "accessory": "mqttthing",
            "logMqtt": true
        }

```
