### ISSUE TITLE
Status lightbulb after Homebridge reboot

### ISSUE THREAD

**Issue by oigroigm** [arachnetech/homebridge-mqttthing#121]
After a restart of Homebridge the status of the light bulb is not updated.
My configuration is the following
{
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Lampadari Cucina",
            "caption": "Lampadari Cucina",
            "topics": {
                "getOn": "stat/Lampadari_Cucina/POWER",
                "setOn": "cmnd/Lampadari_Cucina/power",
                "getOnline": "tele/Lampadari_Cucina/LWT"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "onlineValue": "Online"
}

**Comment by deon-wentzel** [comment]
Have you tied this, see examples in the wiki

"startPub": {
        	"cmnd/Lampadari_Cucina/power": "",
        	"stat/Lampadari_Cucina/POWER": ""
    		},

**Comment by oigroigm** [comment]
I've tried, but the problem is when I restart Homebridge and not when I restart the accessory

**Comment by deon-wentzel** [comment]
So when restarting homebridge I run the following. Please note the results

tail -F ~/.homebridge/homebridge.log |grep Lampadari_Cucina
[5/27/2019, 10:10:59 AM] [Reception Lights] Publishing MQTT: cmnd/Lampadari_Cucina/power =
[5/27/2019, 10:10:59 AM] [Reception Lights] Publishing MQTT: stat/Lampadari_Cucina/POWER =
[5/27/2019, 10:10:59 AM] [Reception Lights] Received MQTT: tele/Lampadari_Cucina/LWT = Online
[5/27/2019, 10:10:59 AM] [Reception Lights] Received MQTT: stat/Lampadari_Cucina/POWER =
[5/27/2019, 10:11:00 AM] [Reception Lights] Received MQTT: stat/Lampadari_Cucina/POWER = ON

**Comment by deon-wentzel** [comment]
Some times existing HOME App and then loading it will refresh the status of devices

**Comment by oigroigm** [comment]
Issue solved.
Thanks

**Comment by DedMsk** [comment]
> Issue solved.
> Thanks

How did you solve the status problem after restarting the homebridge?
