### ISSUE TITLE
Security system restrict target state

### ISSUE THREAD

**Issue by oigroigm** [arachnetech/homebridge-mqttthing#123]
Is it possible to insert the option to restrict some target state in homekit as for the "restrictHeatingCoolingState" in the thermostat?

Thanks

**Comment by arachnetech** [comment]
Yes, on my list of things to do (requested in #113 too)!

I'm hoping to find some time to do this over the weekend.

**Comment by arachnetech** [comment]
Security system target states can now be restricted with:
`"restrictTargetState": [ 1, 2, 3 ]`
in version 1.0.43.
