### ISSUE TITLE
Weather Station Wind Speed Unit

### ISSUE THREAD

**Issue by mwkchan** [arachnetech/homebridge-mqttthing#124]
Is that possible to let user customise whether to use meter per second or km per hour as the unit of the wind speed? My PWS would either publish mm for rain and mps for speed or cm for rain and kph for speed.

**Comment by tobekas** [comment]
Think it’s not possible. It’s a custom Characteristic defined by Eve App.
But you can scale your value via apply-feature, if you have to.

**Comment by mwkchan** [comment]
I finally used WeeWX to change the unit there.
