### ISSUE TITLE
SecuritySystem: Home app icon shows "disarming" after receiving "SA"

### ISSUE THREAD

**Issue by aboulfad** [arachnetech/homebridge-mqttthing#126]
Hello,
whenever mqttTopic getCurrentState receives "SA", the home app icon for SecuritySystem shows disarming and stays there until I send a "D" disarm. Unsure if this related to mqttthing or not.

iOS 12.3.1
Mosquitto 1.6.2, HB/MQTTThing git master
Macos High Sierra
[debug_logs.zip](https://github.com/arachnetech/homebridge-mqttthing/files/3278918/debug_logs.zip)

**Comment by arachnetech** [comment]
The documentation on npm is misleading. Please see the latest version at https://github.com/arachnetech/homebridge-mqttthing#security-system which may help. (I've just made some corrections, but have yet to publish a new version to npm.)

The target state needs to change as well as the current state. The target state is typically set by homebridge. The current state is set by your MQTT-based alarm system. However, if you want to change the target state externally you can do so by publishing the topic configured for `getTargetState`. If you want, you can set `getTargetState` and `getCurrentState` to the same topic - then when you publish to that topic you'll update both the target state and the current state together.

**Comment by aboulfad** [comment]
Thanks for the reply. I already have both topics set in config.json, and was just analyzing the DEBUG logs, I only see iid:10 which corresponds to one of `[getCurrentState, getTargetState]`.

```
[2019-06-12, 5:53:49 a.m.] [Security System Partition 1] Received MQTT: home/dsc/Get/Partition1 = SA
[2019-06-12, 5:53:49 a.m.] [Security System Partition 1] State seccur is now: 0
  EventedHTTPServer [::ffff:appleTV] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":0}]} +13s
```

```
        {
            "getCurrentState":    "home/dsc/Get/Partition1",
            "getTargetState":    "home/dsc/Get/Partition1",
            "setTargetState":     "home/dsc/Set"
        },
        "targetStateValues": ["1S", "1A", "1N", "1D"]
```

**Comment by taligentx** [comment]
@arachnetech I've seen this issue as well, the HomeKit state doesn't update if the state is changed outside HomeKit, even if the target state and current state are set.  The iOS Home app shows the spinning progress indicator as though it's trying to change back to its last known HomeKit state.

I've tested with sending MQTT messages manually using mosquitto_pub/_sub so the actual security system isn't a factor.

For example, arming away outside HomeKit:
1. Initial status:  
    * Security system: disarmed
    * Home app: displays "Off"
2. Send `AA` to `getTargetState`
    * Security system: arming in progress (the exit delay)
    * Home app: displays "Off"
        * Expected behavior: display "Arming..." with spinning progress indicator
3. Send `AA` to `getCurrentState`
    * Security system: armed away
    * iOS: push notification that system was armed away
    * Home app: displays "Disarming..." with spinning progress indicator
        * Expected behavior: display "Armed away"

The HomeKit states work fine if everything is done through HomeKit but any kind of external change doesn't seem to be registering correctly.  The behavior is as if `getTargetState` is being ignored.

```
npm list -g homebridge-mqttthing
homebridge-mqttthing@1.0.42  (git://github.com/arachnetech/homebridge-mqttthing.git#9b0d1a36deb6fee0a6f2dfab1571730076e39a03)
```

**Comment by aboulfad** [comment]
@taligentx , thanks for confirming. My debug log above shows only one of two characteristics is being updated to HomeKit which I believe may be the issue within Homebridge/MQTTthing.

**Comment by tobekas** [comment]
Your target state "SA" is ignored, because this value is not part of your defined targetStateValues. If your security system needs different values for setting states and getting the current state, you cannot use the same topic for getCurrentState and getTargetState. getTargetState and setTargetState must use the same values, because internally it‘s the same characteristic.

**Comment by aboulfad** [comment]
> Your target states "SA" or "AA" are ignored, because this value is not part of your defined targetStateValues. 

Are you referring to `"targetStateValues": ["1S", "1A", "1N", "1D"]`, these are used to set the alarm system partition 1 to the appropriate status. (HomeKit -> Alarm System).

We are discussing the other direction: Alarm System -> HomeKit in this issue.

From the readme: 

> Security System current state can be STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED or ALARM_TRIGGERED. By default, these events are raised when values of SA, AA, NA, D and T respectively are published to the getCurrentState topic. However, these values may be overriden by specifying an alternative array in the currentStateValues setting.

**Comment by tobekas** [comment]
Yes, but if you change the state externally, you also have to change the *target* state (via getTargetState). And for this you must use your target state values.

**Comment by aboulfad** [comment]
> Yes, but if you change the state externally, you also have to change the _target_ state (via getTargetState). And for this you must use your target state values.

Ok wow ... this is really twisted (I guess I need to read more). I just tried the following based on your note and the states and icon update correctly ! thank you a bunch :-)
```
Homekit (HK) is OFF
pi@rpi3:~$ mosquitto_pub -t home/dsc/Get/Partition1 -m 1S -> HK is Arming
pi@rpi3:~$ mosquitto_pub -t home/dsc/Get/Partition1 -m SA -> HK is set to Home
pi@rpi3:~$ mosquitto_pub -t home/dsc/Get/Partition1 -m 1D -> HK: Disarming
pi@rpi3:~$ mosquitto_pub -t home/dsc/Get/Partition1 -m D -> HK: OFF
```

**Comment by arachnetech** [comment]
Delighted it’s working. Thanks again, Tobekas, for all your help here!

Yes, in hindsight it would have been simpler to use a single set of states for both target states and current states to avoid this confusion.  My original implementation also had a bug which stopped getTargetState from working properly (which tobekas found and fixed).

**Comment by aboulfad** [comment]
There was always something missing that I couldn't figure out until now, is that for an external change SS->HK, I couldn't figure out how to tell HK that the SS is Arming, and then tell it is armed.

Thanks to all!

**Comment by taligentx** [comment]
@tobekas Thanks for clearing that up, make sense and I should have tested with a clean config without the customized `targetStateValues`.  Tested and looks great!

For background, this is for a security system interface, where the security system can have up to 8 partitions - each of these would appear in HomeKit as a separate `SecuritySystem` object.  

Changing the `targetStateValues` with a numeric prefix 1-8 was a way to allow an Arduino/esp8266/esp32 subscribe to a single MQTT topic and control all 8 partitions without having to subscribe to 8 different topics (which can have issues with the PubSub MQTT library).  

@arachnetech Thanks for homebridge-mqttthing!  It's the example I've been using for HomeKit integration.

**Comment by aboulfad** [comment]
@taligentx , I am confused by your above comment, can you share your config.json and how did you accomplish setting the state to Arming then to Armed?

**Comment by taligentx** [comment]
@aboulfad We can pick this up in the dscKeybusInterface repo, I only had time to verify that using the same custom values for `setTargetState` and `getTargetState` and then using the default values for `getCurrentState` results in the expected behavior so as far I can tell there's no issue in homebridge-mqttthing.

**Comment by aboulfad** [comment]
Agreed there is no issue, just confusion :lol: ok closing for good this time !
