### ISSUE TITLE
One button garage door opener

### ISSUE THREAD

**Issue by WEZANGO** [arachnetech/homebridge-mqttthing#127]
Hello. I have a garage door opener that has only 1 button, to open the doors. After that they got closed automatically in 30 seconds. So I added this one button as a garage door opener to homekit, but of course when I open it, it stays in opened position and if I try to close it, it stucks "Closing" position and never closes in Homekit app. Is there any method to set door position to "Closed" after a certain amount of time? Because I have only garage door open command I don't know how can simulate "Closed" state. 
Here is my config

>   {
            "accessory": "mqttthing",
            "type": "garageDoorOpener",
            "name": "Garage",
            "topics": {
                "setTargetDoorState": "cmnd/DVES_FA863F_fb/backlog"
            },
            "doorValues": [
                "rfraw AAB0230404017200FA02B259EC380808081A1A1A0808080808080A080A080A080A0A0A0A080A55",
                "Closed",
                "Opening",
                "Closing",
                "Stopped"
            ]
        }

**Comment by arachnetech** [comment]
Sorry you've waited so long for a response to this - I get more requests for help than I have time to answer, and garage doors seem particularly problematic. I've just done some work to try to simplify them. I'll try to look at this soon.

**Comment by jdtsmith** [comment]
I wonder if you'd like some help with your garageDoorOpener logic?  I suspect most systems using MQTT for control will not have situational awareness of all the possible states Homekit provisions (opened, closed, opening, closing, stopped, obstructed).  

I have a PI running as a GPIO based garage door opener that uses [homebridge-gpio-garagedoor](https://github.com/kraigm/homebridge-gpio-garagedoor) with a single reed sensor which closes when the door is closed.  

It works using a timeout (duration of open/close): if the sensor says door is closed, and target is open, during timeout returns status OPENING, afterwards return _whatever the reed switch tells you the door state is_.  This works if you reversed it, it hit an obstruction and reversed, etc.  And visa versa if your switch indicates opened to start (except, in my case, you can return CLOSED as soon as the reed switch closes, you don't have to wait for the timeout).  And if the sensor changes state without any prompting whatsoever (external to HomeKit), this is the logic used by the GPIO-based plugin:

```js
        // Handle external state change.
        if ((this.isClosed && targetState == Characteristic.TargetDoorState.OPEN)
            || (!this.isClosed && targetState == Characteristic.TargetDoorState.CLOSED)) {
            this.service.getCharacteristic(Characteristic.TargetDoorState)
                .setValue(this.isClosed ? Characteristic.TargetDoorState.CLOSED : Characteristic.TargetDoorState.OPEN);
        }
```

to forcibly update Homekit.  I can confirm this works fine, immediately updating the Home app and sending any notifications.  The only thing you miss when operating the garage externally (like with your remote in your car) is you don't get to see "Opening" and "Closing". 

I'm planning to move this to a Shelley v1 that has just one MQTT topic equivalent to "press garage door button" (Shelly's default firmware lets you set an off timeout duration, e.g. 500ms or so), and another topic for the reed switch state (open or closed).  

Happy to chat this through with you for systems with zero, one (top or bottom) or two sensors (top _and_ bottom).   Thanks for MQTTThing; works wonderfully with Shelly's, ESP32's, etc.

**Comment by arachnetech** [comment]
I think this can best be dealt with either through isMoving or using a codec to implement any custom logic that's required now?

**Comment by jdtsmith** [comment]
Yeah, with the new codec support you can probably offload this kind of thing.  Are you planning to document it?  Did you converge on a way to "load" codecs?  I still think just letting different codec plugins bloom on npm is the right approach.  I'd be glad to roll this logic into an "mqttthing-garagedoor" codec if you go that route.

**Comment by arachnetech** [comment]
Thanks. Closing this issue for now. See also #225 and #254.
