### ISSUE TITLE
Feature Request: config to control motionSensor updates

### ISSUE THREAD

**Issue by aboulfad** [arachnetech/homebridge-mqttthing#129]
Hi, could an additional configuration be added to control wether motionSensor updates are sent to HomeKit or not based on a criteria?

One use case: Security System is OFF, as occupants are moving around their premises, the motionSensor will continuously update the Homekit icon, and if notifications are enabled, user(s) will get a storm of notifications.

Of course, user can turn off notification in the accessory settings in Home app, but it would be desirable to know which motionSensor triggered the alarm. This could also apply to other accessories, just with `turnOffAfterms`.

Thoughts/comments or other way to work around that ?

Thank you.

**Comment by aboulfad** [comment]
I would like to _attempt_ to implement this, would appreciate some guidance.

1. Add config item, follow any example (`turnOffAfterms`)
2. Pass the state of securitySystem to motionSensor (.getCharacteristic ?)
3. Based on criteria value, call `.setValue` or not ?

Of course, its simple from a 10,000 ft view !

**Comment by tobekas** [comment]
In my opinion you should do this logic outside of mqttthing. Using nodered, you can send the motion sensor topic and the security system state to nodered and then create a new motion sensor topic, which can be configured in the config.json?

**Comment by aboulfad** [comment]
Thank you for the suggestion, I'll check nodered. In the meantime, I've decided to continue using HAP-Node directly to implement a simple/basic solution for SecuritySystem.
