### ISSUE TITLE
Outlet accessory measurement

### ISSUE THREAD

**Issue by Scialla** [arachnetech/homebridge-mqttthing#130]
Good morning,

i've installed a pzem004t with a wemos D1 mini flashed by tasmota.
This is what i see on tasmota web page:
![Schermata 2019-06-17 alle 20 19 18](https://user-images.githubusercontent.com/49528981/59626890-4b11c880-913d-11e9-9f0e-da4f9991a48b.png)

This is the console string with measurement:
19:19:23 MQT: tele/pzem004t/SENSOR = {"Time":"2019-06-17T19:19:23","ENERGY":{"TotalStartTime":"2019-06-10T16:56:51","Total":29.974,"Yesterday":8.787,"Today":7.311,"Period":7,"Power":440,"ApparentPower":476,"ReactivePower":183,"Factor":0.92,"Voltage":237,"Current":2.010}}

This is my HomeBridge config:

```
>         {
>             "accessory": "mqttthing",
>             "type": "outlet",
>             "name": "Pzem Prova",
>             "url": "mqtt://127.0.0.1",
>             "topics": {
>                 "getOn": "stat/pzem004t/POWER",
>                 "setOn": "stat/pzem004t/power",
>                 "getInUse": "tele/pzem004t/STATE",
>                 "getWatts": {
>                     "topic": "tele/pzem004t/SENSOR",
>                     "apply": "return JSON.parse(message)['ENERGY'].Power;"
>                 },
>                 "getVolts": {
>                     "topic": "tele/pzem004t/SENSOR",
>                     "apply": "return JSON.parse(message)['ENERGY'].Voltage;"
>                 },
>                 "getAmperes": {
>                     "topic": "tele/pzem004t/SENSOR",
>                     "apply": "return JSON.parse(message)['ENERGY'].Current;"
>                 },
>                 "getTotalConsumption": {
>                     "topic": "tele/pzem004t/SENSOR",
>                     "apply": "return JSON.parse(message)['ENERGY'].Total;"
>                 }
>             },
```
and this is what i see in EVE app:
![IMG_3084](https://user-images.githubusercontent.com/49528981/59627104-c3788980-913d-11e9-9e5e-dea820572f68.PNG)

The problem is that in EVE app i can see only power and total power measurement but i can't see voltage and amperes. 

I've tried many type of configuration but nothing change....

What can i do?

Best regards

Davide

**Comment by tobekas** [comment]
Go to „modifica“.
Amp als Voltage May be hidden by default.

**Comment by Scialla** [comment]
I can't believe it was that simple..... i'm sorry!

Thanks!!!!
