### ISSUE TITLE
HeaterCooler improvements

### ISSUE THREAD

**Issue by iondarie** [arachnetech/homebridge-mqttthing#136]
Thank you for your work. I have been using your plugin for my alarm and motion sensors for some time now and it works flawlessly.

I would like to control my AC using HeaterCooler and i have some questions/ideeas

1. Can a poling be set to check for the current state of the AC? If my son starts the AC from the phisical remote, in the Home app the AC appears as OFF.

2. Is there possible to make the fan speed use a personalized array? i see it uses numbers but the IRremote library seems to be using values like: auto, min, low, medium, high, max.

**Comment by arachnetech** [comment]
1. The ‘get’ topics allow your device to report its current state back to homebridge. 

2. Yes, you could use https://github.com/arachnetech/homebridge-mqttthing/blob/master/README.md#applying-functions-to-mqtt-messages-custom-payload-encodingdecoding for this.

**Comment by iondarie** [comment]
I am using the get topics but it does not seem to work... This is from my config:

"setActive": "gree/ac/cmnd/power",
"getActive": "gree/ac/stat/power",

The "gree/ac/stat/power" has the correct info in it but it seems mqttthing ignores it...

**Comment by arachnetech** [comment]
Are you able to try publishing the messages manually, to see whether mqttthing responds correctly?

I’ll try testing getActive too, in case there’s a bug...

**Comment by iondarie** [comment]
ok it seems it's kinda my fault, it needs: "onValue": "on" and "offValue": "off" to work properly.

now i just have to solve my second problem and the temperature increments, it needs to be fixed numbers not "25,5" etc

**Comment by arachnetech** [comment]
Just tested and it's working with true and false by default. As you say, you can change those to on and off with `onValue` and `offValue`.

**Comment by arachnetech** [comment]
Rotation speed goes from 0 to 100 so mapping could be done with something like:

```
        "setRotationSpeed": { "topic": "test/heatcool/setRotationSpeed", 
            "apply": "return [ 'off', 'min', 'low', 'medium', 'high', 'max' ][ Math.floor( message / 20 ) ];" }
```

**Comment by iondarie** [comment]
And for get rotation speed is this correct?:

"getRotationSpeed": {
                    "topic": "gree/ac/stat/fanspeed",
                    "apply": "return [ 'off', 'min', 'low', 'medium', 'high', 'max' ][ Math.floor( message / 20 ) ];"
                }

**Comment by pasna** [comment]
Good evening,
I need advise on my config setting, below 
        {
            "accessory": "mqttthing",
            "type": "heaterCooler",
            "name": "Living Room AC",
            "url": "http://192.168.0.96:1883",
            "logMqtt": true,
            "topics": {
                "setActive": "living_rm/ac/cmnd/power",
                "getActive": "living_rm/ac/stat/power",
                "getCurrentHeaterCoolerState": "living_rm/ac/stat/mode",
                "setTargetHeaterCoolerState": "living_rm/ac/cmnd/mode",
                "getTargetHeaterCoolerState": "living_rm/ac/cmnd/mode",
                "getCurrentTemperature": {
                    "topic": "living_rm/ac/stat/temp",
                    "apply": "return Math.round ( message );"
                },
                "setCoolingThresholdTemperature": "living_rm/ac/cmnd/temp",
                "setTemperatureDisplayUnits": {
                    "topic": "living_rm/ac/cmnd/use_celsius",
                    "apply": "return Math.round( message * 10 );"
                },
                "getTemperatureDisplayUnits": "living_rm/ac/stat/use_celsius",
                "setSwingMode": "living_rm/ac/cmnd/swingh",
                "getSwingMode": "living_rm/ac/stat/swingh",
                "setRotationSpeed": {
                    "topic": "living_rm/ac/cmnd/fanspeed",
                    "apply": "return [ 'off', 'min', 'min', 'max', 'max', 'max' ][ Math.floor( message / 20 ) ];"
                },
                "getRotationSpeed": {
                    "topic": "living_rm/ac/stat/fanspeed",
                    "apply": "return [ 'off', 'min', 'min', 'max', 'max', 'max' ][ Math.floor( message / 20 ) ];"
                }
            },
            "swingModeValues": [
                "off",
                "auto"
            ],
            "minTemperature": 20,
            "maxTemperature": 30,
            "restrictHeaterCoolerState": [
                1,
                2
            ]
        }
with this I can send control to IRMQTTServer module to control my aircon from Homekit without problem. But when control from real remote Homekit doesn't reflect actual state. I may did something wrong but I cannot debug what went wrong. 

Thank you and best regards

**Comment by ldellus** [comment]
> now i just have to solve my second problem and the temperature increments, it needs to be fixed numbers not "25,5" etc

Hi, I have the same problem with the temperature increments. I need increments of 1. How can I do that?

Thanks!

**Comment by ldellus** [comment]
> Rotation speed goes from 0 to 100 so mapping could be done with something like:
>         "setRotationSpeed": { "topic": "test/heatcool/setRotationSpeed", 
>             "apply": "return [ 'off', 'min', 'low', 'medium', 'high', 'max' ][ Math.floor( message / 20 ) ];" }

Hi, one more thing, I don't want the 'off' state as it turns off my AC and I don't want to use the rotation speed for that. How can I have only 4 states as follow:
"apply": "return [ 'low', 'med', 'high', 'auto' ][ function to be used ];" }
Where 'low' is not 0 rotation speed but 20 - 40, 'med' is 40 - 60, 'high' is 60 -80, and 'auto' is 80 -100?

Thanks!

**Comment by arachnetech** [comment]
Did you get this working in the end?
