### ISSUE TITLE
Adding selectable times to HomeKit

### ISSUE THREAD

**Issue by nixmeer** [arachnetech/homebridge-mqttthing#137]
Hello :) thank you for this great plugin. This is another feature request concerning the sprinkler but I don't know if it's even possible.

My pumps are too strong, so in 5 min (which is the shortest selectable time in the Apple HomeApp) all plants are flooded. I currently change all minute values to seconds, so if I set 5 mins in HomeKit, the pump runs for 5 seconds. This also means the max time is 60 s since HomeKit's max time is 60 mins. 

Before further changes that makes conversion harder (like "wait, what do I have to set to get 2 mins actual pump time??"): is there any way for the device to publish more time options to choose from?

When changing the duration or turning a sprinkler on, my devices reply the time they're actually set to and this works perfectly fine. But I recognized that if I go to settings again, the converted time that my device replied to Homebridge is shown as one option. That made me think that there might be an API for the device to tell HomeKit more options

Best and thank you all for your work!

**Comment by arachnetech** [comment]
I've added support for changing the default duration range (1-3600 seconds) in version 1.0.45. Unfortunately HomeKit seems to insist on setting default run time in 5 minute intervals in iOS 12, but this seems to have been improved in the iOS 13 Beta - this is with `"maxDuration": 180` configured:

![image](https://user-images.githubusercontent.com/24389384/61996492-bc259380-b08c-11e9-81ed-a886890ef304.png)

**Comment by nixmeer** [comment]
So it does not work with iOS 12?

**Comment by arachnetech** [comment]
You seem to end up with no choice of default run times if `maxDuration` is below 5 minutes, but I haven't tested what it actually does as I don't have a sprinkler.

**Comment by nixmeer** [comment]
Ok. I will test it within the next week! Thank you so much!

Another quick question: can you check, if it is possible to include a sprinkler into a scene or automate it? That’s not possible with iOS 12 :/

**Comment by arachnetech** [comment]
I couldn’t see any way to add sprinklers to automations in iOS 13, but “schedules” are mentioned in the settings. Maybe this is an unfinished feature?
