### ISSUE TITLE
Valve - Sprinkler

### ISSUE THREAD

**Issue by jiribohm** [arachnetech/homebridge-mqttthing#138]
Hi, I use ESP 8266 Wifi Based board to run Valve, sprinkler type. I use mqttthigs plugin to home bridge. I have some issues with "getInUse" topic. I think, this state should be set "true", when the valve is open. (If the pin state is HIGH, then publish value true and in home app the state changes from Inactive to Running). Should i publish to "getInUse = true" from ESP 8266 when the pin is HIGH and "getInUse = false" when the pin is LOW? Thanks you very much!

**Comment by tobekas** [comment]
Right!
A short summary for Active / InUse - Logic:

- Active=0, InUse=0 -> Off
- Active=1, InUse=0 -> Waiting [Starting, Activated but no water flowing (yet)]
- Active=1, InUse=1 -> Running
- Active=0, InUse=1 -> Stopping

Active is like the target state and InUse the actual state.

**Comment by jiribohm** [comment]
Thanks you very much for answer! I have still some questions.
1. Is this right? 
"setActive":            "home/set/sprinklers",
"getActive":            "home/set/sprinklers",
"getInUse":            "home/set/sprinklers/inUse",

And what does it mean: "getStatusActive": -> What topic should I use and how to publish a value for this?

2. 
When my arduino pin is HIGH a publish a message to "home/set/sprinklers/inUse", "on"
When my arduino pin is LOW a publish a message to "home/set/sprinklers/inUse", "off"

When a send "true" or "false", it doesn't work. I have to use on/off. Is this because i set values "onValue": "on" and "offValue": "off" instead of "true"/"false"??

3. I very often see the valve in my home app as inactive, not responding, running but in red color with exclamation, etc. but physically the device is responding. How to tune the communication homeApp <-> home bridge <-> arduino?
![IMG_0635](https://user-images.githubusercontent.com/6672749/62272833-53e40280-b43c-11e9-8148-7a04c4921ff8.PNG)

**Comment by EjvindHald** [comment]
> Right!
> A short summary for Active / InUse - Logic:
> 
> * Active=0, InUse=0 -> Off
> * Active=1, InUse=0 -> Waiting [Starting, Activated but no water flowing (yet)]
> * Active=1, InUse=1 -> Running
> * Active=0, InUse=1 -> Stopping
> 
> Active is like the target state and InUse the actual state.

I can confirm that it works exactly as described above. You just send to send the messages according to this, and it will appear fine on your phone.
