### ISSUE TITLE
Need Non-String Topic

### ISSUE THREAD

**Issue by jreyn88** [arachnetech/homebridge-mqttthing#140]
Can I change the lockValues to floating integer?  I have an ESP device that will only subscribe to a floating integer.  I tried "lockValues":["0","1","8","9"] and "lockValues":0,1,8,9]. I can Publish to a string but it won't let me subscribe to one.

    {
      "accessory": "mqttthing",
      "type": "lockMechanism",
      "name": "Test Lock",
      "url": "http://192.168.10.35:1883",
      "logMqtt": true,
      "topics":
      {
          "setLockTargetState":       "test/lock/target",
          "getLockTargetState":       "test/lock/current",
          "getLockCurrentState":      "test/lock/current"
      },
      "lockValues": [ "Unsecured", "Secured", "Jammed",  "Unknown" ]
    },

**Comment by arachnetech** [comment]
Just confirming, do you want mqttthing to be able to publish integers on MQTT, or to accept integer payloads when subscribing?

I suspect currently it will only support strings. I believe MQTT just sends 'binary data' as its payload, but strings are a common format to send/receive.

**Comment by jreyn88** [comment]
Accept integer payloads when subscribing.

**Comment by arachnetech** [comment]
Do you have the Arduino code that publishes these integers so that I could test?

I don't know whether the Node.js MQTT library than I'm using decodes integers - in which case you could probably handle them in mqttthing already by adding an apply function like `return '' + message;` - or whether they'll appear as binary payloads which need to be decoded.

**Comment by arachnetech** [comment]
... for example, is it the byte-array publishing variant of https://pubsubclient.knolleary.net/api.html#publish3 , and if so how many bytes are published for your integers?

Note that 'floating integer' doesn't make sense. If you're publishing floating-point values they are probably single precision (4 bytes) or double precision (8 bytes) IEEE 754 (https://en.wikipedia.org/wiki/IEEE_754).
