### ISSUE TITLE
[Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.

### ISSUE THREAD

**Issue by sherazan** [arachnetech/homebridge-mqttthing#141]
What is the meaning of this message?

[Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.

**Comment by bryangauvin** [comment]
I got the same thing going on. Any ideas?

**Comment by arachnetech** [comment]
This sounds like a general homebridge question, not something related to the homebridge-mqttthing plugin. You should be able to find an answer at https://www.reddit.com/r/homebridge/.
