### ISSUE TITLE
Eve App v3.8.1 breaks history

### ISSUE THREAD

**Issue by sieren** [arachnetech/homebridge-mqttthing#142]
Just to track this here, the most recent eve app breaks the history. It's not displayed anymore. Seems like a widespread issue affecting a bunch of plugins (tracked also in german here: https://forum.smartapfel.de/forum/thread/3769-eve-app-v3-8-1-history-fakegato-wird-nicht-mehr-überall-angezeigt-fehlt-komplett/ and as an issue in a separate repo https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/73)

Might take a stab at this.

**Comment by sieren** [comment]
Tracked upstream https://github.com/simont77/fakegato-history/issues/76 - feel free to close, though I'm gonna leave this open for others to see for now.

**Comment by EjvindHald** [comment]
Looping in @tobekas ...fyi

**Comment by tobekas** [comment]
I already followed this discussion.
@ebaauw did a great job. He has discovered many functional relationships. 
For now if you use the weatherStation type with temp, humidity and airPressure, then the history will appear in the app. Temp only, Humidity only and Temp/Hum won’t work for now. But there is also another workaround. 
I would recommend to wait a bit, if in the other thread even more is found out.

**Comment by sieren** [comment]
We can close this ... https://github.com/simont77/fakegato-history/issues/76 - Latest update brings history back
