### ISSUE TITLE
getPositionState in windows

### ISSUE THREAD

**Issue by serbasan** [arachnetech/homebridge-mqttthing#143]
Hi. I have my windows configured with this fantastic plugin.
From homekit, everything is handled and represented perfectly.

When I act manually and the blind ends, the percentage, closed or open in homekit is represented perfectly.

I just need to show the status (decreasing increasing stopped) when I operate manually and the blind is moving.

In my sonoff with tasmota I have a rule that sends to "getPositionState" status "decreasing"."increasing" or "stopped" when going up or down.

With Node-red I have also sent the topic "getPositionState" but it doesn't change in Homekit

Where is the problem.

This is my config:

 {
            "accessory": "mqttthing",
            "type": "window",
            "name": "Habitación Invitados",
            "url": "mqtt://192.168.1.3:1883",
            "topics": {
                "getCurrentPosition": "stat/persiana3/SHUTTER1",
                "setTargetPosition": "cmnd/persiana3/shutterposition",
                "getTargetPosition": "stat/persiana3/SHUTTER1",
                "getPositionState": "stat/persiana3/status"
            },
            "positionStateValues": [
                "decreasing",
                "increasing",
                "stopped"
            ]
        },

**Comment by davidm-mdxt** [comment]
Your config looks correct to me. Let me try to reproduce...

**Comment by arachnetech** [comment]
Your config looks correct to me. Let me try to reproduce...

**Comment by arachnetech** [comment]
Adding `"logMqtt": true` and publishing to `stat/persiana3/status` I can see that homebrige-mqttthing is subscribing to this topic and updating Homekit's state. However, the Home App doesn't appear to show the PositionState characteristic in any way.

https://github.com/KhaosT/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts indicates that Service "Window" should have a `Characteristic.PositionState`, so perhaps this is just a limitation of the Home app currently?

From my testing, changing the window position through the Home App results in it showing 'Opening...' or 'Closing...' until the accessory updates its current position by publishing (with your configuration) a value to `stat/persiana3/SHUTTER1`. At this point the window stops opening or closing and shows the position indicated.

**Comment by serbasan** [comment]
Ok. Thank you. The truth, how it is working is enough. It is a joy.
