### ISSUE TITLE
Can't read temperature with tasmota (Sonoff) and two DS18B20

### ISSUE THREAD

**Issue by rikray02** [arachnetech/homebridge-mqttthing#145]
Helo,

First, Thanks for this plugins.  So, i try to read temperature from 1 Sonoff with tasmota and 2 DS18B20 but i can't read any temperature.  Can you help?

**This is the console of SONOFF TH 16:**
03:57:46 WIF: Checking connection...
03:57:46 WIF: Connected
03:58:02 MQT: tele/thermopompe/STATE = {"Time":"2019-09-03T03:58:02","Uptime":"11T01:12:10","Heap":15,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Airport_Maison","BSSId":"84:16:F9:9B:10:9C","Channel":11,"RSSI":60,"LinkCount":17,"Downtime":"0T00:03:30"}}
03:58:02 MQT: tele/thermopompe/SENSOR = {"Time":"2019-09-03T03:58:02","DS18B20-1":{"Id":"021192450438","Temperature":17.75},"DS18B20-2":{"Id":"0417A2FB43FF","Temperature":18.12},"TempUnit":"C"}
03:58:02 SRC: MQTT

**This is the config.json files:**
 {
        	"accessory": "mqttthing",
       	 	"type": "temperatureSensor",
        	"name": "TEST-THP-OUT",
        	"url": "mqtt://xx.xx.xx.xx",
       	 	"username": "username",
        	"password": "password",
        	"topics": {
            	"getCurrentTemperature": {
                	"topic": "tele/thermopompe/SENSOR",
                	"apply": "return JSON.parse(message).DS18B20.Temperature;"
            		}
       			 }
    	}

**This is the message from Homebridge:**
[9/2/2019, 10:58:01 PM] [TEST-THP-OUT] Decode function apply( message) { return JSON.parse(message).DS18B20.Temperature; } failed for topic tele/thermopompe/SENSOR with message {"Time":"2019-09-03T03:58:02","DS18B20-1":{"Id":"021192450438","Temperature":17.75},"DS18B20-2":{"Id":"0417A2FB43FF","Temperature":18.12},"TempUnit":"C"} - TypeError: Cannot read property 'Temperature' of undefined

Can you help me to fix my config.json file because i am absolutely sure that the problem is my configuration.

Thanks for your help  :-)
Riki

**Comment by Andi1968** [comment]
Hi Riki,

shouldn't it be
"apply": "return JSON.parse(message).**DS18B20-1**.Temperature;"
or
"apply": "return JSON.parse(message).**DS18B20-2**.Temperature;"

in your config ?

Regards,
Andreas

**Comment by rikray02** [comment]
Thanks Andreas!

Yes, i try both without any success.  When i use the - (minus sign) between DS18B20 and 1 or two, Homebridge won't start.

Regards,
Richard

**Comment by Andi1968** [comment]
Hi Richard,

try:

"apply": "return JSON.parse(message)["DS18B20-1"].Temperature;"


Regards,
Andreas

**Comment by rikray02** [comment]
Hi Andreas,

Thanks for your help.

I tried it and Homebridge won't start again.  This is the Error:

SyntaxError: Unexpected token D in JSON at position 6245
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:212:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)

Regards, 
Richard

**Comment by Andi1968** [comment]
And this ?

"apply": "return JSON.parse(message)[\"DS18B20-1\"].Temperature;"

**Comment by arachnetech** [comment]
or you might need to escape the embedded quotes:

`"apply": "return JSON.parse(message)[\"DS18B20-1\"].Temperature;"`

**Comment by Andi1968** [comment]
That is what I wanted to write, the backslashes were just removed by accident

**Comment by arachnetech** [comment]
:-) I was trying to see the difference between what you'd written before!

**Comment by rikray02** [comment]
YEAH!!!  :-)
Thank you so much guys!

This works fine:
**"apply": "return JSON.parse(message)[\"DS18B20-1\"].Temperature;"**

Thanks for your help.  I appreciate.

Regards,
Richard

**Comment by Andi1968** [comment]
Hi Richard, 

glad we could help. And now the backquotes in your reply were removed just like in my reply ;-)
Think it has to be posted as "Code" here so then backquotes survive.

**Comment by rikray02** [comment]
OUPS!

This work fine:
`"apply": "return JSON.parse(message)[\"DS18B20-1\"].Temperature;"`

Same problem for me with backslashes.
Sorry!

Richard

**Comment by arachnetech** [comment]
Thank you, both. I'll close this issue now.
