### ISSUE TITLE
Thermostat - disable possibility to change temperature

### ISSUE THREAD

**Issue by jiribohm** [arachnetech/homebridge-mqttthing#146]
Hi, thanks you very much for the plugin. I find it awesome. Would it be possible to disable the possibility to change the target temperature in state HEAT and AUTO? Something like in OFF state, when the temperature wheel is inactive. Thanks you very much for answer.

**Comment by tobekas** [comment]
Not possible since Temperature characteristics are mandatory in Apple‘s HomeKit protocol for Thermostat service.
In any case nothing that can be done within this plugin.

**Comment by jiribohm** [comment]
Thanks for your answer!
