### ISSUE TITLE
I need help with homebridge and homebridge Mqttthing

### ISSUE THREAD

**Issue by zsq19958629** [arachnetech/homebridge-mqttthing#147]
My system operation scheme:

Docker runs oznu/homebridge to install homebridge Config UI X, homebridle-dummy v0.4.0, homebridle-homeassistant v3.1.0, homebridger-mqttthing v1.0.45 and homebridger-yeelight v0.0.21，to configure the content
`{
    "bridge": {
        "name": "Homebridge",
        "username": "xx.......xx",
        "port": 51369,
        "pin": "123-45-678"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "http://127.0.0.1:8123",
            "password": "mypassword",
            "supported_types": [
                "binary_sensor",
                "climate",
                "cover",
                "fan",
                "garage_door",
                "device_tracker",
                "input_boolean",
                "light",
                "lock",
                "media_player",
                "rollershutter",
                "sensor",
                "scene",
                "switch"
            ],
            "default_visibility": "visible",
            "verify_ssl": false
        }
    ]
}`

However, when I want to add espruna switch 3ch to homebridge Mqttthing, configure the content
`{
    "accessory": "mqttthing",
    "type": "lightbulb",
    "name": "OnOffTest",
    "url": "http://127.0.0.1:1883",
    "username": "user",
    "password": "mypassword",
    "logMqtt": "true",
    "topics": {
        "getOn": "ESPURNA-D34ECA/relay/0",
        "setOn": "ESPURNA-D34ECA/relay/0/set"
    },
    "onValue": "1",
    "offValue": "0"
}`
It doesn't work and causes homebridge to restart repeatedly.
How do I fill out the configuration file? thank you

**Comment by mitchwd** [comment]
Wonder if the url should be "mqtt://127.0.0.1" instead?

**Comment by arachnetech** [comment]
Closing as inactive
