### ISSUE TITLE
Problem with state 

### ISSUE THREAD

**Issue by mientki** [arachnetech/homebridge-mqttthing#15]
I have a problem updating the light switches. Works correctly when I turn on / off the light in the Home App on iOS or in the plugin accessories at homebridge-ui-x. However, it does not work as I turn it off I turn off the light with a physical switch on the wall (sonoff touch T1). What do I have wrong in configuration?
Take a look at the video: [https://youtu.be/ZjzXG4jKIPk](https://youtu.be/ZjzXG4jKIPk)

My config:
>{
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Sypialnia światło",
            "url": "mqtt://192.168.99.100",
            "username": "",
            "password": "",
            "caption": "",
            "topics": {
                "getOn": "stat/sypialnia/Power",
                "setOn": "cmnd/sypialnia/Power",
                "stateGet": "tele/sypialnia/STATE"
            },
            "integerValue": "true",
            "onValue": "ON",
            "offValue": "OFF"
        }
>

**Comment by arachnetech** [comment]
Hi,

What are you using `"stateGet": "tele/sypialnia/STATE"` for, if anything? This isn't a valid topic configuration setting for mqttthing. Is this the subject used by the physical switch on the wall?

If you want to control a light from a switch, you have two options:

1. Publish the `setOn` topic from your switch to drive the light directly, and make sure that the light responds to a `setOn` with a corresponding `getOn` to update the homekit status.

2. Add the switch separately to homekit (perhaps using mqttthing type Switch), and configure automations in Homekit to switch on/off the light when the switch state changes.

If your light doesn't publish to confirm that it's state has changed (through its `getOn` topic), you might be able to configure a simpler version fo the first option by using the same topic for the light and the switch and configuring this as the light's `getOn` and `setOn`, but I haven't tried this.

**Comment by mientki** [comment]
This work property with plugin "mqtt-switch-tasmota" :
  
       {
             "accessory": "mqtt-switch-tasmota",
             "switchType": "light",
            "type": "light",
            "url": "mqtt://192.168.99.100",
            "username": "",
            "password": "",
            "topics": {
                "statusGet": "stat/salon_lampa/POWER",
                "statusSet": "cmnd/salon_lampa/power",
                "stateGet": "tele/salon_lampa/STATE"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/salon_lampa/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/salon_lampa/TelePeriod",
            "startParameter": "120",
            "manufacturer": "Itead",
            "model": "Sonoff Basic",
            "serialNumberMAC": "5C:CF:7F:7A:6C:4D",
            "name": "Salon Lampa Switch"
        }

How do I properly set the light bulb accessories with mqttthing?

**Comment by mientki** [comment]
OK I already know :) The meaning is case-sensitive in topic. Not "Power" and "POWER":

        {
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Salon lampa",
            "url": "mqtt://192.168.99.100",
            "username": "",
            "password": "",
            "caption": "",
            "topics": {
                "getOn": "stat/salon_lampa/POWER",
                "setOn": "cmnd/salon_lampa/power"
            },
            "integerValue": "true",
            "onValue": "ON",
            "offValue": "OFF"
        }

I do not understand the "integerValue" parameter until the end. Is he supposed to be "true" or "false" in my case?

**Comment by arachnetech** [comment]
`integerValue: true` can be used instead of `onValue: "1", offValue: "0"` - as the default on/off values are "true" and "false". However, since you're setting them to "ON" and "OFF" it will have no effect. Configuration `onValue` and `offValue` take precedence over any `integerValue` setting.

> Boolean types like on/off use true/false unless `integerValue: true` is configured, in which case they default to 1/0. Alternatively, specific values can be configured using `onValue` and `offValue`. Integer and string types are not affected by these settings.

**Comment by Kepete** [comment]
@mientki Did you solve the problem with state? 
I can switch the light but it won't update the state if used with a wall switch. 

My config: 
`
       
        "accessory": "mqtt-switch-tasmota",
               "name": "NAME OF THIS ACCESSORY",
                "url": "mqtt://ip",
                "username": "",
                "password": "",
                "topics": {
                        "statusGet": "stat/sonoff_d_tuba/POWER",
                        "statusSet": "cmnd/sonoff_d_tuba/POWER",
                        "stateGet": "tele/sonoff_d_tuba/STATE"
                          },
                "onValue": "ON",
                "offValue": "OFF",
                "activityTopic": "tele/sonoff_d_tuba/LWT",
                "activityParameter": "Online",
                "startCmd": "cmnd/sonoff_d_tuba/TelePeriod",
                "startParameter": "60",
                "manufacturer": "Itead",
                "model": "Sonoff Basic",
                "serialNumberMAC": "11:11:11:11:11:11",
                "name": "test142"
`

What for are "startCmd": "cmnd/sonoff_d_tuba/TelePeriod", and "activityTopic": "tele/sonoff_d_tuba/LWT", ?

**Comment by mientki** [comment]
try:

"statusSet": "cmnd/sonoff_d_tuba/**power**",

"power"small letters.

**Comment by Kepete** [comment]
@mientki Didn't help. Still not updating the state.

**Comment by Kepete** [comment]
@mientki 
So I also tried mqttthings plugin. Set it up and exactly the same problem. I can switch the light, but I can't get the state. The state is not updating. 
Is there any possibility to make sure that the topic is correct? I'm running mosquitto MQTT server.

**Comment by arachnetech** [comment]
I recommend issuing a wildcard MQTT subscription externally to see what messages are being sent and when if you haven’t already tried this. 

It’s also possible to enable logging of the messages received by mqttthing by adding ‘"logMqtt": true’ to your configuration.

**Comment by Kepete** [comment]
@mientki problem solved. Easy mistake. As I was using Sonoff dual, it had to be power1 and POWER1 (or power2 and POWER2).

The only problem now is if I restart the homebridge then the default is always light off. Even if it is actually on. Is there a possibility to fix this?

**Comment by Kepete** [comment]
Also, if a Sonoff is offline, then the status is not updated in the home app to not responding. Is there a fix for it?

**Comment by deon-wentzel** [comment]
Hi, homebridge-mqtt-switch sees the status after a restart. Could this not be implemented into this plug-in?

**Comment by arachnetech** [comment]
Just confirming the feature request here: you would like mqtt-thing to republish all MQTT topics at start-up with current values in Homekit?

**Comment by deon-wentzel** [comment]
Hi, yes and to check the status of devices status continuously.

**Comment by matej** [comment]
The inverse is also true. If the Switch is updated if homebridge is offline, the state will not be Synced up - if you want the device to hold the ground truth of the system. 

> you would like mqtt-thing to republish all MQTT topics at start-up with current values in Homekit?

What I would find useful would be to have the plugin get the current state of the device on homebridge startup. E.g., with `mqtt-switch-tasmota` you could use the startup command for this: 

```
"startCmd": "cmnd/lights/POWER1",
"startParameter": ""
```

**Comment by mosaid88** [comment]
Yes I believe we need the extra start cmnd,

```
"startCmd": "cmnd/lights/POWER1",
"startParameter": ""
```

startParameter is really handy as it can be used in 2 ways, Empty: will return current state switch, or if value provided (ON or OFF) then it can be used to set a default value on start of homebridge.

**Comment by arachnetech** [comment]
Closing as feature request is now in separate issue https://github.com/arachnetech/homebridge-mqttthing/issues/31.
