### ISSUE TITLE
Password logged in syslog

### ISSUE THREAD

**Issue by t-j-n** [arachnetech/homebridge-mqttthing#150]
Hi. 
I just saw that homebridge-mqtt logs the MQTT broker username and password in clear text in the syslog. I think they should both be masked out.

Edit: this happens if logMqtt is set to true.

**Comment by davidm-mdxt** [comment]
Thanks, I agree we should mask at least the password.

**Comment by arachnetech** [comment]
Thanks. I agree we should mask at least the password.

**Comment by arachnetech** [comment]
Done in 1.0.46.

**Comment by t-j-n** [comment]
Thanks!
