### ISSUE TITLE
No connection with MQTT broker

### ISSUE THREAD

**Issue by angel41671** [arachnetech/homebridge-mqttthing#153]
Hello everybody.
I am kind of desperate with this issue. I can´t get to connect with the MQTT broker.

I have installed homebridge with mqttthing script both in a QNAP and a Mac. I have also tried to connect with different MQTT brokers: QIoT (MQTT broker of QNAP), CloudMQTT and IoTicos, but it was impossible. No broker receives messages from homebridge.

One example of the config.json I used:

{
    "bridge": {
 "name": "Homebridge2",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154" 
 },
    "accessories": [{
        "accessory":"mqttthing",
        "type":"lightbulb",
        "name":"Kitchen Bulb",
        "url":"m21.cloudmqtt.com:18359",
        "username":"sgrdhxcs",
        "password":"2sdk*******",
        "mqttOptions": {"keepalive": 30},
        "mqttPubOptions": { "retain": true },
        "logMqtt":true,
        "topics":
        {
            "getOn":"test/lightbulb/getOn",
            "setOn":"test/lightbulb/setOn"
    },
        "integerValue": true,
        "onlineValue": "Online"       
    }  
    ],    
    "platforms": []
}

The message I receive over the Terminal when I launch Homebridge is:

[Kitchen Bulb] MQTT options: {"keepalive":30,"clientId":"mqttthing_Kitchen Bulb_73a55f98","protocolId":"MQTT","protocolVersion":4,"clean":true,"reconnectPeriod":1000,"connectTimeout":30000,"will":{"topic":"WillMsg","payload":"Connection Closed abnormally..!","qos":0,"retain":false},"username":"sgrdhxcs","password":"2sdk*******","rejectUnauthorized":false}

When I turn on/off the device on Homekit, I receive these messages on the Terminal:

[24/9/2019 19:18:44] [Kitchen Bulb] Publishing MQTT: test/lightbulb/setOn = 1
[24/9/2019 19:18:47] [Kitchen Bulb] Publishing MQTT: test/lightbulb/setOn = 0

Exceptionally, I get a connection clue on the CloudMQTT log panel:

2019-09-24 17:34:35: New client connected from 46.********* as cloudmqtt-ws-ui-0.8701533199277488 (c1, k60, u'sgrdhxcs').
2019-09-24 17:42:18: Client cloudmqtt-ws-ui-0.8701533199277488 disconnected.

Could anybody give me a hand with this? It would be much appreciated!!

Thank you ver much!!

**Comment by arachnetech** [comment]
I think you might need to change the format of your `url` to: `"url": "http://m21.cloudmqtt.com:18359"` or `"url": "https://m21.cloudmqtt.com:18359"`.

**Comment by arachnetech** [comment]
I suspect (and hope!) you probably need to provide a login to use cloudmqtt.com too. You'd need `username` and `password` settings for this, as shown in https://github.com/arachnetech/homebridge-mqttthing#common-settings.

Note that it's very easy to run a local MQTT broker. I run Mosquitto, which is installed with just:
```
sudo apt-get install mosquitto
sudo apt-get install mosquitto-clients
```

**Comment by angel41671** [comment]
Working! I missed the "http://" :( :(

I can't believe I spent the last 2 weeks of my free time on this.


Thank you very much for your help, and for the incredible script ;)

**Comment by arachnetech** [comment]
Great to hear it was so simple in the end! I think I've made that mistake myself too.
