### ISSUE TITLE
Siri reports invalid temperature 

### ISSUE THREAD

**Issue by duculete** [arachnetech/homebridge-mqttthing#157]
I have more temperature accessories setup and in HomeKit app the value (in C) is ok. But for some reason Siri is reporting temperature in F (i have -5 in my Livingroom). I checked everything and all settings (location, weather, etc) are ok (display in Celsius). I also changed to F in system location on IOS 13 and siri is reporting the actual value (from homekit app). I think that for some reason Homekit knows that the accessory reports temperature in F.

**Comment by tobekas** [comment]
See https://github.com/nfarina/homebridge/issues/2330

**Comment by tobekas** [comment]
So I guess it’s a bug on Apples side.

**Comment by DewGew** [comment]
This was fixed in IOS 13.1.3
