### ISSUE TITLE
Sonoff Tasmota web doesn't update HomeKit 

### ISSUE THREAD

**Issue by jat80** [arachnetech/homebridge-mqttthing#158]
Hi there, 

Firstly thanks for an awesome plugin :)

I'm just wondering if I'm able to configure a Sonoff basic switch in this plugin's config so that if the Tasmota web turns on or off the switch it will update the homekit accessory state as well?  Obviously this works the other way from HomeKit to Sonoff Tasmota but just wondering if it's possible?

Hopefully this makes sense.  

Many thanks! 

JT.

**Comment by Andi1968** [comment]
Works fine for my outlet running Tasmota and configured as a sprinkler valve in mqttthing.
Could you post the relevant part of your config.json ?

**Comment by jat80** [comment]
> Works fine for my outlet running Tasmota and configured as a sprinkler valve in mqttthing.
> Could you post the relevant part of your config.json ?

sure,  I'm just using the tested configs as below updated with my topic info and Mqtt server:

{
        "accessory": "mqttthing",
        "type": "switch",
    	"name": "Sonoff basic",
	"url": "mqtt://mymqtthostipaddress",
	"username": "admin",
	"password": "123456",
        "topics": {
                "setOn": "cmnd/mysonoff/power",    
                "getOn": "stat/mysonoff/POWER",    
		"getOnline": {
                    "topic": "tele/mysonoff/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
            	    }
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "startPub": {
        	"cmnd/mysonoff/power": "",
        	"stat/mysonoff/POWER": ""
    		},
            "logMqtt": true
        },

**Comment by Andi1968** [comment]
That looks OK to me. 
I would check with
`mosquitto_sub  -v -t '#'`
if the stat/mysonoff/POWER messages are triggered when you switch on/off via web. 
If so restart your iPhone or iPad (honestly!), I had a similar problem and it got resolved by this.

**Comment by jat80** [comment]
> That looks OK to me.
> I would check with
> `mosquitto_sub -v -t '#'`
> if the stat/mysonoff/POWER messages are triggered when you switch on/off via web.
> If so restart your iPhone or iPad (honestly!), I had a similar problem and it got resolved by this.

Yeah they both are showing up fine in Mosquitto it's just when I turn it on or off via Tasmota web it doesn't update the STATE in HomeKit.

If I turn it on or off via HomeKit it will update the state in Tasmota web.

Hopefully I've explained myself well enough.  It's not a big deal but I would assume it should update the HomeKit state if triggered via the Tasmota web.  

JT.

**Comment by Andi1968** [comment]
Really strange, I temporarily added your config to mine (just removing the mqtt server part and replacing "mysonoff" with "sonoff1202": 


`{
            "accessory": "mqttthing",
            "type": "switch",
            "name": "Sonoff basic",
            "topics": {
                "setOn": "cmnd/sonoff1202/power",
                "getOn": "stat/sonoff1202/POWER",
                "getOnline": {
                    "topic": "tele/sonoff1202/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
                }
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "startPub": {
                "cmnd/mysonoff/power": "",
                "stat/mysonoff/POWER": ""
            },
            "logMqtt": true
        },`

and it works perfectly. If I power on/off using the "Toggle" button in the tasiota web interface the status is reflected in HomeKit immediately.
No further idea from my side at the moment :-(

**Comment by jat80** [comment]
> Really strange, I temporarily added your config to mine (just removing the mqtt server part and replacing "mysonoff" with "sonoff1202":
> 
> `{ "accessory": "mqttthing", "type": "switch", "name": "Sonoff basic", "topics": { "setOn": "cmnd/sonoff1202/power", "getOn": "stat/sonoff1202/POWER", "getOnline": { "topic": "tele/sonoff1202/LWT", "apply": "return message == 'Online' ? 'ON' : 'OFF';" } }, "integerValue": false, "onValue": "ON", "offValue": "OFF", "startPub": { "cmnd/mysonoff/power": "", "stat/mysonoff/POWER": "" }, "logMqtt": true },`
> 
> and it works perfectly. If I power on/off using the "Toggle" button in the tasiota web interface the status is reflected in HomeKit immediately.
> No further idea from my side at the moment :-(

Thanks for looking into it.  I'm stumped! :(

**Comment by Andi1968** [comment]
If you make the tasiota a sprinkler like I did:

`{
            "accessory": "mqttthing",
            "type": "valve",
            "valveType": "sprinkler",
            "name": "Sprenger",
            "mqttOptions": {
                "keepalive": 30
            },
            "topics": {
                "getActive": "stat/mysonoff/POWER",
                "getInUse": "stat/mysonoff/POWER",
                "setActive": "cmnd/mysonoff/POWER"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "durationTimer": true,
            "minDuration": 600,
            "maxDuration": 7200
        },`

Same problem ?

**Comment by jat80** [comment]
Ok some more info and log/console information on this issue.

I have found a couple of my sonoffs that work fine as in when toggling the power of them via Tasmota web it updates HomeKit.

Sonoff8 below works (as in when toggling the power of them via Tasmota web it updates HomeKit)
Sonoff6 below doesn't (as in when toggling the power of them via Tasmota web HomeKit accessory is NOT updated)

Configs are exactly the same for Homebridge plugin other than the accessory name.
Tasmota configs are the same in the web UI.

Here's the info from Homebridge log when turning each on and off:

[2019-10-7 19:24:49] [sonoff 6] Set power state on 'sonoff 6' to true
[2019-10-7 19:24:51] [sonoff 6] Set power state on 'sonoff 6' to false
[2019-10-7 19:25:33] [sonoff 8] Set power state on 'sonoff 8' to true
[2019-10-7 19:25:33] [sonoff 8] sonoff 8 ( POWER ) - Power from Status ON
[2019-10-7 19:25:35] [sonoff 8] Set power state on 'sonoff 8' to false
[2019-10-7 19:25:35] [sonoff 8] sonoff 8 ( POWER ) - Power from Status OFF

Here's the info from the Tasmota console when turning each on and off:

Sonoff 8

19:32:49 MQT: stat/sonoff8/RESULT = {"POWER":"ON"}
19:32:49 MQT: stat/sonoff8/POWER = ON
19:32:50 MQT: stat/sonoff8/RESULT = {"POWER":"OFF"}
19:32:50 MQT: stat/sonoff8/POWER = OFF

Sonoff 6

19:36:11 MQT: stat/sonoff6/RESULT = {"POWER1":"ON"}
19:36:11 MQT: stat/sonoff6/POWER1 = ON
19:36:13 MQT: stat/sonoff6/RESULT = {"POWER1":"OFF"}
19:36:13 MQT: stat/sonoff6/POWER1 = OFF

For some reason Sonoff 6 uses power1??

**Comment by Andi1968** [comment]
Google for „Tasmota SetOption 26“

**Comment by jat80** [comment]
> Google for „Tasmota SetOption 26“

@Andi1968 THIS FIXED IT!!!  Thanks so much!!! 👍 💯

**Comment by jat80** [comment]
@Andi1968 I have a sonoff s22 and for some reason the button won’t update HomeKit.  It updates the tasmota web UI though.  The HomeKit button updates tasmota and tasmota updates HomeKit.  It’s just the physical button that doesn’t for some reason.  I’m wondering if this is a switch option or topic setting as well?

**Comment by Andi1968** [comment]
The physical button doesn't update HomeKit but it switches the device on/off, right ?
So the button configuration would be correct. 
If you monitor MQTT do you get messages like

`
18:53:39 MQT: stat/sonoff1202/RESULT = {"POWER":"ON"}
18:53:39 MQT: stat/sonoff1202/POWER = ON
18:53:47 MQT: stat/sonoff1202/RESULT = {"POWER":"OFF"}
18:53:47 MQT: stat/sonoff1202/POWER = OFF
`

On my device this is what I see in thconsole when switching on and off by button.

Andreas

**Comment by Andi1968** [comment]
What does console command ButtonTopic return ? 

19:44:59 CMD: ButtonTopic
19:44:59 MQT: stat/sonoff1202/RESULT = {"ButtonTopic":"0"}

**Comment by jat80** [comment]
23:19:53 MQT: stat/sonoff10/RESULT = {"POWER":"ON"}
23:19:53 MQT: stat/sonoff10/POWER = ON
23:20:15 MQT: stat/sonoff10/RESULT = {"POWER":"OFF"}
23:20:15 MQT: stat/sonoff10/POWER = OFF
23:20:37 CMD: ButtonTopic
23:20:37 MQT: stat/sonoff10/RESULT = {"ButtonTopic":"0"}

What's weird is I've tested it again tonight and it's working properly.  

I have rebooted Homebridge though.  I'll watch it and see if it reacts wrong again. iOS 13 seems more buggy with homekit.
