### ISSUE TITLE
new Accessories CO2

### ISSUE THREAD

**Issue by samsonovss** [arachnetech/homebridge-mqttthing#16]
Please add CO2 Accessories

**Comment by arachnetech** [comment]
Would an air quality sensor be appropriate?


/**
 * Service "Air Quality Sensor"
 */

Service.AirQualitySensor = function(displayName, subtype) {
  Service.call(this, displayName, '0000008D-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.AirQuality);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.StatusActive);
  this.addOptionalCharacteristic(Characteristic.StatusFault);
  this.addOptionalCharacteristic(Characteristic.StatusTampered);
  this.addOptionalCharacteristic(Characteristic.StatusLowBattery);
  this.addOptionalCharacteristic(Characteristic.Name);
  this.addOptionalCharacteristic(Characteristic.OzoneDensity);
  this.addOptionalCharacteristic(Characteristic.NitrogenDioxideDensity);
  this.addOptionalCharacteristic(Characteristic.SulphurDioxideDensity);
  this.addOptionalCharacteristic(Characteristic.PM2_5Density);
  this.addOptionalCharacteristic(Characteristic.PM10Density);
  this.addOptionalCharacteristic(Characteristic.VOCDensity);
  this.addOptionalCharacteristic(Characteristic.CarbonMonoxideLevel);
  this.addOptionalCharacteristic(Characteristic.CarbonDioxideLevel);
};

**Comment by samsonovss** [comment]
sorry bad English
 this.addOptionalCharacteristic(Characteristic.CarbonDioxideLevel);
Carbon Dioxide Level - CO2
Good

**Comment by Damontir** [comment]
HI :)

Can i use already a co2 sensor with tasmota on homebridge?

kind regards
Robert

**Comment by arachnetech** [comment]
I've added Carbon Dioxide Sensor and Air Quality Sensor in 1.0.26.

**Comment by Damontir** [comment]
> I've added Carbon Dioxide Sensor and Air Quality Sensor in 1.0.26.

And it works perfect, thanks!

Is there a reason why the Eve App doesnt show the History-Chart? logMqtt and history is true but no chart for co2.

Thanks!

**Comment by mrdc** [comment]
> Is there a reason why the Eve App doesnt show the History-Chart?

`History is currently supported for:

    Temperature Sensor
    Humidity Sensor
    Air Pressure Sensor
    Air Quality Sensor
    Motion Sensor
    Contact Sensor
    Outlet (power consumption)
`
