### ISSUE TITLE
Doorbell - StatelessProgrammableSwitch - Sonoff RF Bridge

### ISSUE THREAD

**Issue by jat80** [arachnetech/homebridge-mqttthing#160]
Hi there,

I have a RF doorbell that I wanted to hookup to my Sonoff RF Bridge (flashed with Tasmota)

I tried the doorbell accessory but it says it's not supported when added.  So I then used the StatelessProgrammableSwitch accessory which shows up and when the doorbell is pressed it shows it on the accessory.

But how do I get notifications for this?  I can assign one of the button presses a scene but I don't have any accessories that will give me a notification as it won't let me choose the motion sensor.

Hopefully this makes sense.  All I want is to receive a notification to my phone when someone presses the doorbell.  

This is my config:

`
{
        "accessory": "mqttthing",
        "type": "statelessProgrammableSwitch",
        "name": "Doorbell",
        "url": "mqtt://IP ADDRESS",
        "username": "",
        "password": "",
        "caption": "",
        "topics":
        {
            "getSwitch":   {
              "topic": "tele/sonoffrf/RESULT",
          "apply": "return( ( JSON.parse(message).RfReceived.Data == 'RF CODE' ) ? 1 : null);"
              }
        },
        "switchValues": ""
    },

`

This is what is looks like in HomeKit:

![IMG_7298](https://user-images.githubusercontent.com/23650727/66924732-9dc9a580-f087-11e9-8fca-dc3828fff6cb.jpg)

![IMG_7297](https://user-images.githubusercontent.com/23650727/66924741-a5894a00-f087-11e9-96d0-1847b5a16656.jpg)

Thanks,

JT.

**Comment by arachnetech** [comment]
I think I used MQTTThing configured as a motion sensor for my doorbell. That allows notifications. 

I’m not sure that the stateless programmable switch supports notifications in homekit.

**Comment by jat80** [comment]
> I think I used MQTTThing configured as a motion sensor for my doorbell. That allows notifications.
> 
> I’m not sure that the stateless programmable switch supports notifications in homekit.

@arachnetech thanks for your reply.

I tried the below config for motion sensor and it isn't returning anything on the accessory.  Any tips on getting this to work?

{
        "accessory": "mqttthing",
        "type": "motionSensor",
        "name": "Doorbell",
        "url": "mqtt://IP ADDRESS",
        "username": "",
        "password": "",
        "caption": "",
        "topics":
        {
            "getMotionDetected":   {
              "topic": "tele/sonoffrf/RESULT",
          "apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCODE' ) ? 1 : null);"
              }
        },
        "turnOffAfterms": "6000"
    },

**Comment by Andi1968** [comment]
Just to confirm: Did you replace the IP_ADDRESS in the configuration template with your real MQTT broker IP address ? And also the RFCODE with the real rf code you receive from your door bell (check on the Tasmota console) ?
Andreas

**Comment by jat80** [comment]
> Just to confirm: Did you replace the IP_ADDRESS in the configuration template with your real MQTT broker IP address ? And also the RFCODE with the real rf code you receive from your door bell (check on the Tasmota console) ?
> Andreas

Hi @Andi1968 thanks for your reply.  Yes I've put in the IP address for my MQTT server and the RF code which shows up in the Sonoff RF Bridge web console.

**Comment by jat80** [comment]
This is the output of the Sonoff RF Bridge web console for the doorbell button:

00:38:12 MQT: tele/sonoffrf/RESULT = {"RfReceived":{"Sync":3170,"Low":120,"High":320,"Data":"RFCode","RfKey":"None"}}

**Comment by Andi1968** [comment]
Then I would change the line

`"apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCODE' ) ? 1 : null);"`

to

`"apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCode' ) ? 1 : null);"`

and try again.

Andreas

**Comment by jat80** [comment]
Sorry I don’t see the difference between the two.  I’m pretty new to this so sorry if I’m missing the obvious. The RFCode and RFCODE is actually numbers I’m just not posting the actual code.

**Comment by Andi1968** [comment]
It's case-sensitive, attribute "Data" contains "RFCCode" but in the config you compare it with "RFCCODE"

**Comment by Andi1968** [comment]
Soory, I mean "RFCode" vs. "RFCODE"

**Comment by jat80** [comment]
Yeah that’s where the actually number code goes in.  I’m not posting the number here as it’s sensitive info.

**Comment by Andi1968** [comment]
Ah, of course. 

But shouldn't the return values be true or false so:

`"apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCODE' ));`

or

`"apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCODE' ) ? 1 : 0);"`
together with option integerValue: true

Andreas

**Comment by jat80** [comment]
> Ah, of course.
> 
> But shouldn't the return values be true or false so:
> 
> `"apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCODE' ));`
> 
> or
> 
> `"apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCODE' ) ? 1 : 0);"`
> together with option integerValue: true
> 
> Andreas

@Andi1968 the second one worked! 
"apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCODE' ) ? 1 : 0);" 
together with option integerValue: true

Thanks so much again for your help!

**Comment by Andi1968** [comment]
The first one gives syntax error because the double quotes at the end were lost  ?
I think 

`"apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCODE' ));"`

should also work  ?

**Comment by jat80** [comment]
> The first one gives syntax error because the double quotes at the end were lost ?
> I think
> 
> `"apply": "return( ( JSON.parse(message).RfReceived.Data == 'RFCODE' ));"`
> 
> should also work ?

yeah I saw the error (I always paste my config into json lint before committing so knew it was there and even with the double quotes on the end it didn't work.  I didn't add the integer value for the first one though only the second one so not sure if that was the issue.
