### ISSUE TITLE
getName works only intermittently when using `topic`

### ISSUE THREAD

**Issue by dxdc** [arachnetech/homebridge-mqttthing#161]
Having an issue with `getName` when using it with a topic. I've tried this way (shown below) as well as just a pure topic.

It *does* work sometimes, I've seen the title pop up in HomeKit, but it seems very unreliable especially after additional MQTT updates.

Since there aren't really custom characteristics baked into HomeKit, I've been using this so that I can click on the sensor and then see additional data. Does HomeKit not support name updates like this?

(Also, if it could possibly be related, I have multiple sensors reading from the same MQTT topics.)

Excerpted JSON:
```json
"topics": {
        "getBatteryLevel": "car/VIN/fuel", 
        "getCurrentTemperature": "car/VIN/temperatureC", 
        "getName": {
          "apply": "return 'Odometer ' + message + ' mi';", 
          "topic": "car/VIN/odometer"
        }, 
        "getOnline": "car", 
        "getStatusActive": "car/VIN/isActive", 
        "getStatusLowBattery": "car/VIN/lowFuel"
      },
"type": "temperatureSensor", 
```

BTW.. the car/VIN/odometer just returns a simple string like "9323". I've removed any special characters that could appear there. The fact that it works sometimes suggests there may be an issue updating it, but I'm not sure.

**Comment by tobekas** [comment]
By Apple HAP spec, Name characteristic should not change during the lifetime.
I mean that there is a specific handling for the Name characteristic implemented in Homebridge itself. Not absolutely sure about this.

**Comment by dxdc** [comment]
@tobekas I was wondering about that as one possibility. But, it seems `getName` was implemented like this so wasn't sure why unless it could be used for this purpose?

Do you know of another way to store 'custom' data fields? I've been wanting to store things like numeric integers, dates/times, GPS coordinates, but there doesn't seem to be a great way to do it within HomeKit so that a user can see it.

**Comment by arachnetech** [comment]
Closing as I think the reported issue is down to HomeKit behaviour and I’m not aware of any way to represent custom data fields, unfortunately.
