### ISSUE TITLE
Light Bulb WW mode only

### ISSUE THREAD

**Issue by Denny5667** [arachnetech/homebridge-mqttthing#163]
is it possible to add support of warm white and cool white lights to light bulb only?

**Comment by arachnetech** [comment]
I think you can use a combination of `setColorTemperature`, `setOn` and (optionally) `setBrightness`, but you'd need to work out the logic to fade between warm and cold LEDs from the published temperature. I don't believe my logic for doing this (as in `setRGBWW`) is available without RGB currently.

**Comment by dezral** [comment]
i have been trying to get the temperature of a shelly bulb(2018 model) working.. it reports temperature in kelvin like so:
`shellies/shellybulb-XXXXXX/color/0/status {"ison":true,"mode":"white","red":255,"green":92,"blue":0,"white":0,"gain":100,"temp":6465,"brightness":100,"effect":0}
`

where "temp" is the kelvin temperature.. the bulb does not report in RGB, and i can't use "apply" function to convert RGB to kelvin.. the calculations fills to much i think.

could this be included? kelvin light temperatures? i have found  some ex. online.

found this on apples [dev homekit](https://developer.apple.com/documentation/homekit/hmcharacteristictypecolortemperature) page:

**Comment by dezral** [comment]
Ohh found out that mqtthing uses Mired color temperatures.. (it seems i can work with that).

it should be noted in the wiki that it is Mired ;-).

**Comment by arachnetech** [comment]
mqttthing just passes through the colour temperatures that Apple use in HomeKit. Interesting to find out what standard is being used, thanks!

From my own brief tests, the numbers used range from about 140 (cold) to 600 (warm) with 150 being neutral if I remember correctly.

I’ll close this issue, but I do one day plan to add support for publishing ‘warm white’ and ‘cold white’ components based on the HomeKit colour temperature and brightness.
