### ISSUE TITLE
Config Help for BlitzWolf BW-LT11 Smart LED Light Strip running Tasmota

### ISSUE THREAD

**Issue by peros550** [arachnetech/homebridge-mqttthing#164]
This is not really an issue, only a request for help. 

Is it possible for somebody to provide a base config that would work with BlitzWolf BW-LT11 led strip? 
This is basically a RGBW led strip and it can run Tasmota. 

Here is the tasmota template: 

`{"NAME":"BW-LT11 Strip","GPIO":[17,255,255,255,37,40,255,255,38,255,39,255,255],"FLAG":0,"BASE":18}`

Many Thanks,

**Comment by arachnetech** [comment]
Is the Tasmota template what the MQTT looks like? Do you know which of those numbers represent the red, green, blue and white values?

**Comment by peros550** [comment]
This may help: https://github.com/ct-Open-Source/tuya-convert/wiki/Compatible-devices-(HTTP-firmware)#lights

I have finally followed a different route and flashed HAA on this nice led strip
