### ISSUE TITLE
How to catch LED controller remote commands

### ISSUE THREAD

**Issue by ceraz68** [arachnetech/homebridge-mqttthing#166]
Hi I configured tasmota on a magic home controller and use it successfully with mqttthing.

When you select a colour, or brightness on the remote the information is sent back to the broker. Colour example: MQT: stat/sonoffLEDtv/RESULT = {"POWER":"ON","Dimmer":89,"Color":"E42000","HSBColor":"8,100,89","Channel":[89,13,0]}

The HomeKit icon is not updated with such information. Is it possible to catch this stat topic and update HomeKit with the  information?

Thanks

**Comment by serbasan** [comment]
Hi. I have the same problem.
With a bulb without RGB (only white) this works perfectly for me. Homekit synchronizes the status of getBrightness and getColorTemperature if I change them from the Tasmota website:

        {
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Luz Pasillo",
            "url": "mqtt://192.168.1.3:1883",
            "topics": {
                "getOn": "stat/philipspasillo/POWER",
                "setOn": "cmnd/philipspasillo/POWER",
                "getInUse": "tele/philipspasillo/STATE",
                "getBrightness": {
                    "topic": "stat/philipspasillo/RESULT",
                    "apply": "return JSON.parse(message).Dimmer"
                },
                "setBrightness": "cmnd/philipspasillo/Dimmer",
                "getColorTemperature": {
                    "topic": "stat/philipspasillo/RESULT",
                    "apply": "return JSON.parse(message).CT"
                },
                "setColorTemperature": "cmnd/philipspasillo/CT"
            },
            "integerValue": "false",
            "onValue": "ON",
            "offValue": "OFF",
            "startPub": {
                "cmnd/philipspasillo/power": ""
            }
        },
Tasmota returns this in stat/philipsrecibidor/RESULT:
17:14:51 MQT: stat/philipsrecibidor/RESULT = {"POWER":"ON","Dimmer":48,"Color":"2753","HSBColor":"0,0,0","Channel":[15,33],"CT":389}





With an RGB LED strip I cannot get Homekit to synchronize the status of HSBCOLOR if I change it from the Tasmota website. I have this configuration:

 {
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Led comedor",
            "url": "mqtt://192.168.1.3:1883",
            "topics": {
                "getOn": "stat/ledcomedor/POWER",
                "setOn": "cmnd/ledcomedor/POWER",
                "getInUse": "tele/ledcomedor/STATE",
                "getHSV": {
                    "topic": "stat/ledcomedor/RESULT",
                    "apply": "return JSON.parse(message).HSBCOLOR"
                },
                "setHSV": "cmnd/ledcomedor/HSBCOLOR"
            },
            "integerValue": "false",
            "onValue": "ON",
            "offValue": "OFF",
            "startPub": {
                "cmnd/ledcomedor/power": ""
            }
        },

Tasmota returns this in stat/ledcomedor/RESULT:
17:04:35 MQT: stat/ledcomedor/RESULT = {"POWER":"ON","Dimmer":18,"Color":"0B2E0A","HSBColor":"118,79,18","Channel":[4,18,4]}

The difference is that in CT it is a single value and in HSBCOLOR they are three separated by commas.
Any ideas?.
Thank you.

**Comment by serbasan** [comment]
Already solved. Everything is fine except that Tasmota returns HSBColor and not HSBCOLOR:

{
"accessory": "mqttthing",
"type": "lightbulb",
"name": "Led comedor",
"url": "mqtt://192.168.1.3:1883",
"topics": {
"getOn": "stat/ledcomedor/POWER",
"setOn": "cmnd/ledcomedor/POWER",
"getInUse": "tele/ledcomedor/STATE",
"getHSV": {
"topic": "stat/ledcomedor/RESULT",
"apply": "return JSON.parse(message).HSBC**olor**"
},
"setHSV": "cmnd/ledcomedor/HSBCOLOR"
},
"integerValue": "false",
"onValue": "ON",
"offValue": "OFF",
"startPub": {
"cmnd/ledcomedor/power": ""
}
},

**Comment by ceraz68** [comment]
> The difference is that in CT it is a single value and in HSBCOLOR they are three separated by commas.
> Any ideas?

Did you try changing in tasmota `setoption17 1`.

In the end I developed tasmota rules to detect colour changes triggered by the remote and publish them to the broker e.g. `on Color publish stat/LED/COLOR %value% endon`
