### ISSUE TITLE
Contact Sensor - Sonoff RF Bridge - Tasmota - last state when power cut

### ISSUE THREAD

**Issue by jat80** [arachnetech/homebridge-mqttthing#168]
Hi there,

I've got some contact sensors working for a couple of windows that work well.  Only thing is I moved the bridge while the sensors were opened (powered off the bridge) to another location and when I switched it back on, the sensors showed as closed.  I had to close the windows then open them again for it to show correct state.

Is this a setting I need to change in Tasmota console for the Sonoff RF Bridge or something in my config for this plugin?

This is my config:

{
    "accessory": "mqttthing",
    "type": "contactSensor",
    "name": "ensuitewindowsensor",
    "url": "mqtt://SERVERIPADDRESS",
    "username": "",
    "password": "",
    "caption": "",
    "topics":
    {
        "getContactSensorState": {
          "topic": "tele/sonoffrf/RESULT",
            "apply": "return( ( JSON.parse(message).RfReceived.Data == 'OPENRFCODE' ) ? 1 : null || ( JSON.parse(message).RfReceived.Data == 'CLOSEDRFCODE' ) ? 0  : null);"
            },
    "getStatusTampered": {
          "topic": "tele/sonoffrf/RESULT",
            "apply": "return( ( JSON.parse(message).RfReceived.Data == 'TAMPERRFCODE' ) ? 1 : null );"
          },
        "getStatusLowBattery": {
          "topic": "tele/sonoffrf/RESULT",
            "apply": "return( ( JSON.parse(message).RfReceived.Data == 'LOWBATTRFCODE' ) ? 1 : null );"
          }
    },
      "integerValue": true,
            "logMqtt": false
    },

any help would be appreciated.  

Thanks,

JT.

**Comment by jat80** [comment]
Anyone?

**Comment by arachnetech** [comment]
The only solution currently is to use `startPub` to set everything to a specific state on start-up. I’m compiling a list of feature requests to which I’ve added persistence of state - so I’ll close this issue for now.
