### ISSUE TITLE
Garage Door - mqttthing

### ISSUE THREAD

**Issue by psyciknz** [arachnetech/homebridge-mqttthing#169]
I have a garage door where teh state is on one topic (a reed switch) with an open and closed state.

The control is via my alarm.  I don't use an open, close command, but a direction to my alarm to pulse an output.

So I can see the door values:
```
"doorValues": [ "open", "closed", "Opening", "Closing", "Stopped" ],
```
But there doesn;t seem to be a value for the commands that can be sent, in my case it would be 'pulse' to close and 'pulse' to open

**Comment by iondarie** [comment]
hi, did u find a solution to this i am looking for the same thing

**Comment by psyciknz** [comment]
I had to tell the alarm how to send a pulse upon receiving a command from homebridge.    Once I did that it was fine for me.

**Comment by arachnetech** [comment]
Closing as I think this is resolved now.
