### ISSUE TITLE
Support newer versions of homebridge-lib

### ISSUE THREAD

**Issue by feld** [arachnetech/homebridge-mqttthing#176]
Hello,

Just had to do a bunch of manual jumping through hoops to get this homebridge-mqttthing to work with a newer homebridge and homebridge-lib. Please change your dependency definitions to not require specific versions of homebridge-lib.

Thanks!

**Comment by arachnetech** [comment]
Thanks for the tip - very happy to.

I'm surprised that you had issues though - I'm using homebridge 0.4.50 which appears to be the latest version from https://www.npmjs.com/package/homebridge. Am I missing something?

The current homebridge-lib 4.4.8 is much newer than the version specified in mqttthing dependencies, so perhaps that's the issue. I've added a `^` which should help.
