### ISSUE TITLE
Versions of googleapis prior to 39.1.0 are vulnerable to Improper Authorization.

### ISSUE THREAD

**Issue by diegoweb100** [arachnetech/homebridge-mqttthing#178]
https://npmjs.com/advisories/791

Could you please update googleapis?

**Comment by arachnetech** [comment]
I don’t believe I have googleapis as a dependency?

**Comment by diegoweb100** [comment]
... well the fakegato is including googleapis and homebridge-mqttthing is including fakegato with old googleapis...

**Comment by NorthernMan54** [comment]
What happens if you do an npm audit fix?

It is my module in fakegato that brought in google apis, and I thought I had updated everything

**Comment by diegoweb100** [comment]
Yes I've already tried this but still not working...

**Comment by NorthernMan54** [comment]
The version of fakegato is the issue, version 0.5.5 or greater uses the new google library

In the package.json the version is locked at 0.5.3 change it to “>0.5.5” and it should now work.  This sets the minimum version as greater than 0.5.5

**Comment by arachnetech** [comment]
Thanks, @NorthernMan54. I'll change that.

**Comment by arachnetech** [comment]
Now using latest homebridge-lib too.
