### ISSUE TITLE
Aqara water leak as Motion Sensor

### ISSUE THREAD

**Issue by Luftloch80** [arachnetech/homebridge-mqttthing#179]
How can i add aqara water leak Sensor as Motion Sensor?

{
      "accessory": "mqttthing",
      "type": "motionSensor",
      "name": "Regen",
      "topics": {
        "getMotionDetected": {
          "topic": "zigbee2mqtt/0x00158d00044be829",
          "apply": "return !(JSON.parse(message).water_leak);"
        }
      },
      "integerValue": "false",
      "onValue": "true",
      "offValue": "false"
    },

**Comment by Luftloch80** [comment]
I think the underscore in water_leak Is the problem

**Comment by arachnetech** [comment]
I think you might need `"integerValue": false` without the quotes around false?

Do you have an example of your message format?

Note that mqttthing supports the leak sensor accessory too, if that's of interest.

**Comment by arachnetech** [comment]
Closing as inactive.

**Comment by nikmosyl** [comment]
Hello, I have the same problem.

      {
            "accessory": "mqttthing",
            "type": "leakSensor",
            "name": "Xiaomi Leak Sencor",
            "topics": {
                "getCurrentRelativeHumidity": {
                    "topic": "zigbee2mqtt/0x00158d0003580ff5",
                    "apply": "return JSON.parse(message).water_leak;"
                }
            }
        }

But Homebridge always gives "Leak Detected 0"
How is JSON parsed in this case? Am I getting boolean? Do I need to somehow transform the input?

**Comment by nikmosyl** [comment]
Hello, I have the same problem.

  {
        "accessory": "mqttthing",
        "type": "leakSensor",
        "name": "Xiaomi Leak Sencor",
        "topics": {
            "getCurrentRelativeHumidity": {
                "topic": "zigbee2mqtt/********",
                "apply": "return JSON.parse(message).water_leak;"
            }
        }
    }

But Homebridge always gives "Leak Detected 0"
How is JSON parsed in this case? Am I getting boolean? Do I need to somehow transform the input?

**Comment by arachnetech** [comment]
If you have a `leakSensor` type accessory, you need to configure a `getLeakDetected` topic not a `getCurrentRelativeHumidity` topic.

Details at https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Accessories.md#leak-sensor.
