### ISSUE TITLE
Sonoff tasmota temperature readings 

### ISSUE THREAD

**Issue by Kepete** [arachnetech/homebridge-mqttthing#18]
I'm trying to get the temperature reading from a DS18B20 sensor connected to Sonoff tasmota. 
What should the correct MQTT topic be? 

`cmnd/sonoff_test/status -m 10` 
will return this: 
`stat/sonoff_test/STATUS10 {"StatusSNS":{"Time":"2018-09-08T09:39:41","Switch1":"OFF","Switch2":"ON","DS18B20":{"Temperature":25.3},"TempUnit":"C"}}`

How can I extract the temperature reading from there?

**Comment by arachnetech** [comment]
Currently mqttthing can’t extract a value from a JSON payload. Is it possible to configure the task tasmota so that it just publishes the temperature on its own?

**Comment by Kepete** [comment]
I think not, but I will look at it once again.

**Comment by Kepete** [comment]
It is not possible to configure on Tasmota side. But there is a ready plugin that read it from the Json payload, so I got the problem solved. Thank you fo the support.

**Comment by Kepete** [comment]
@arachnetech I reopen the issue as the other plugin has some problems and now mqttthing also supports LWT as there is actually no need for any other plugin besides to extract JSON temperature/humidity readings. 
I'm sure the big number of Tasmota users would benefit from this possibility.

**Comment by bartoszwas** [comment]
I would love it too.

**Comment by arachnetech** [comment]
This can be done with custom payload encoding now, I believe?
https://github.com/arachnetech/homebridge-mqttthing#applying-functions-to-mqtt-messages-custom-payload-encodingdecoding
