### ISSUE TITLE
Support for electrical indicators from zigbee2mqtt

### ISSUE THREAD

**Issue by vekunz** [arachnetech/homebridge-mqttthing#183]
Hi, I have an Zigbee outlet, which measures the power consumption. I integrate this outlet with zigbee2mqtt into my MQTT server. The problem is that homebridge-mqttthing cannot read the power consumption data from MQTT.

zigbee2mqtt sends the following data to MQTT:
`{"voltage":224,"linkquality":34,"power":14,"current":0.063,"state":"ON"}`
'voltage' ist Volt, 'power' is Watt and 'current' is Ampere.

Can you extend homebridge-mqttthing so it can handle this data? I am aware that I can only see the power data in the Eve app, but this is not a problem.

**Comment by vekunz** [comment]
After reading a bit more of the readme, I found it out myself how to do it with functions:
```javascript
{
    "accessory": "mqttthing",
    "type": "outlet",
    "name": "Outlet",
    "topics": {
        "getOn": {
            "topic": "zigbee2mqtt/steckdose_1",
            "apply": "return JSON.parse(message).state"
        },
        "setOn": "zigbee2mqtt/steckdose_1/set",
        "getInUse": {
            "topic": "zigbee2mqtt/steckdose_1",
            "apply": "return JSON.parse(message).state === 'ON'"
        },
        "getWatts": {
            "topic": "zigbee2mqtt/steckdose_1",
            "apply": "return JSON.parse(message).power"
        },
        "getVolts": {
            "topic": "zigbee2mqtt/steckdose_1",
            "apply": "return JSON.parse(message).voltage"
        },
        "getAmperes": {
            "topic": "zigbee2mqtt/steckdose_1",
            "apply": "return JSON.parse(message).current"
        }
    },
    "onValue": "ON",
    "offValue": "OFF",
    "history": "true"
}
```

**Comment by arachnetech** [comment]
Excellent. Hopefully all working now.
