### ISSUE TITLE
TargetHeaterCoolerState - Int instead of String

### ISSUE THREAD

**Issue by markus-fischbacher** [arachnetech/homebridge-mqttthing#186]
Why is it necessary to use strings for the TargetHeaterCoolerState instead of the integers defined by Homekit?
I have to use 'OFF', 'HEAT' and so on instead of integer 0, 1, 2, 3 when feeding the getCurrentHeatingCoolingState and other HeatingCoolingState topics.

```
    "topics": {
        "getCurrentHeatingCoolingState": {
            "topic": "5C:CF:7F:B9:73:8D/thermostat/current",
            "apply": "return JSON.parse(message).CurrentHeatingCoolingState ? 'HEAT' : 'OFF';"
        }
    }
```

**Comment by arachnetech** [comment]
That just matched how I'd implemented the other accessories when I added it. Generally names are easier to remember than integers.

You might be able to change it to "integers" by specifying `heatingCoolingStateValues: [ '0', '1', '2', '3' ]` - I think values sent over MQTT are always strings anyway. I haven't tested this though.

**Comment by markus-fischbacher** [comment]
Thanks for your response. I changed the values to the string representations for the moment. I‘ll give your suggestion a try. MQTT is sending strings, sure.

**Comment by tobekas** [comment]
Try replace `typeof topic != 'string'` by `typeof topic === 'object'` In the code. Maybe this could do the job.

**Comment by arachnetech** [comment]
Is this still an issue in the latest version? I did change some value handling to support the use of JavaScript types better in version 1.1.1. I think this may allow you to use integers directly now.

**Comment by markus-fischbacher** [comment]
In the meanwhile I switched to HA. Not an issue for now.

**Comment by arachnetech** [comment]
Thanks
