### ISSUE TITLE
Temperature sensor decimal not showing

### ISSUE THREAD

**Issue by luisfosoares** [arachnetech/homebridge-mqttthing#190]
I'm using a temperature sensor DS18B20 connected into a Tasmota flashed device and sending temp value via Mqtt with a decimal point example 13.2ºC but when i check the dashboard i can only see the integer value ex 13ºC

Is it possible to have the decimal value as well? how? 

![111](https://user-images.githubusercontent.com/6531538/72620478-47def500-3937-11ea-98b0-f3ce610ca56b.PNG)
![hoobs](https://user-images.githubusercontent.com/6531538/72620484-49a8b880-3937-11ea-9928-34e385763454.PNG)

**Comment by hoenes** [comment]
I don‘t think this is a limitation of mqttthing. For me it is the same, just integers in homebridge UI while Apple Home and EVE App showing decimals.

**Comment by arachnetech** [comment]
Confirmed: decimals display correctly in Home app.
