### ISSUE TITLE
Garage Door  - Problems / Feature requests

### ISSUE THREAD

**Issue by iondarie** [arachnetech/homebridge-mqttthing#192]
Hello,

I am trying to use the "Garage Door Opener" but it gives me a little bit of pain. I will try to explain the best that i can what hardware i am using, and my settings/config.

### Hardware:

- 1 x Gate that needs just a pulse to open or close (one button)
- 1 x NodeMCU flashed with tasmota that controls the relay board witch sends the pulse to the gate for opening and closing
- 2 x Reed sensors 1 for fully open state and 1 for fully closed state

### Settings/Config:

So i got my NodeMCU flashed with Tasmota up and running with the 2 x reed switches set up as PIR's and i have applied the following 2 rules:

`Rule1 on switch1#state=0 do publish %topic%/stat/garage opening endon on switch1#state=1 do publish %topic%/stat/garage closed endon`

`Rule2 on switch2#state=0 do publish %topic%/stat/garage closing endon on switch2#state=1 do publish %topic%/stat/garage open endon`

This is my homebridge config:
```
{
            "accessory": "mqttthing",
            "type": "garageDoorOpener",
            "name": "Garage",
            "url": "mqtt://localhost",
            "username": "****",
            "password": "****",
            "caption": "<label (optional)>",
            "topics": {
                "getCurrentDoorState": "a_porti/stat/garage",
                "getTargetDoorState": "a_porti/stat/garage",
                "setTargetDoorState": "a_porti/cmnd/POWER1",
                "getObstructionDetected": ""
            },
            "doorValues": [
                "Open",
                "Closed",
                "Opening",
                "Closing",
                "Stopped"
            ]
        }
```
### Problems / feature requests

- If i monitor my mosquitto all seems to work perfect. Except in homebridge where the plugin decides to see my garage as open even if it is closed.
- There is no option for the command payload, my gate for example only needs ON payload (my relay board is set from tasmota to toggle ON command for 1 second)
- It would be nice to have an option of "running time" for example my gate opens in 44 seconds if i issue a command to open/close and it does not reach it's state in 44 seconds it would be nice to have the state say stopped or jammed

I am pretty sure that there are more users in the same situation as i am. I would be nice if a solution/improvement could be found.

If i can help in any way please let me know.

As an ending note i want to thank you for this awesome plugin, i am runing 90% of my accesories trough it.

**Comment by hoenes** [comment]
for me @tomtzeng gave the productive answer in this [issue](https://github.com/arachnetech/homebridge-mqttthing/issues/19#issuecomment-496100870)

**Comment by iondarie** [comment]
I tried but it does not work properly. 😕

**Comment by hoenes** [comment]
Is the tasmota/hardware part working probably?
If you toggle the relay your garage door opens/closes?
PIRs (I'm using switches) are showing you the state (both ON or OFF => the door is moving | one ON the other OFF the door is open respectively closed)?

do you (the NodeMCU) have to stop the door in open/closed state or does this your garage door opener on its own?

**Comment by iondarie** [comment]
Tasmota/hardware part is working properly in fact i am using it with another garage plugin right now and it is working withouth any issue.

If i toggle the relay (i have it set with PulseTime 1) it opens/closes the gate, the PIR's/switches are showing the proper on or off depending on the state of the gate.

We do not need to stop the gate manually as it has it's own mechanism for stopping when it reaches closed / open position (it has 2 switches that are toggled by a lever at the end of the line)

**Comment by hoenes** [comment]
So I don't see why tomtzeng's approach should not work for you. (please read the full issue/thread) 
on tasmota you should set up two rules:
rule1 for a state change of the open-reed-sensor(your PIR) and
rule2 for the close-sensor
use TOGGLE for close and ON for open

on the homebridge part check the mqtt message from tasmote (a you have setup a mqtt broker, right?) and toggle the relay with a mqtt command.
that's it - good luck

**Comment by iondarie** [comment]
I read the full issue a few times and have implemented tomtzeng's solution to the letter.

I have the rules setup and active on tasmota, mqtt is up and running (most of my devices work trough mqtt).

I got it to work once but it was seeing the gate open.

Ill try to have a try again tommorow.

**Comment by hoenes** [comment]
> I got it to work once but it was seeing the gate open.

It was 5he same for me, if you cycle the door once it should go in sync. If so, you can solve the ˋinitial door open issue’ like I did it: with the startPub command in the homebridge config.
