### ISSUE TITLE
Color temperature range

### ISSUE THREAD

**Issue by nixmeer** [arachnetech/homebridge-mqttthing#196]
Hello :)

What’s the output range of the „setColorTemperature“ topic or what’s the expected range for „getColorTemperature“? This light is no RGB, it just got 2 different color that mix the color temperature 

Is it documented anywhere? I could not find any specification. 

Best

**Comment by arachnetech** [comment]
I just pass the value on to homekit (and publish the value it gives me). I believe it's range is from 140 to 500 (from https://github.com/KhaosT/HAP-NodeJS/blob/HEAD/src/lib/gen/HomeKit.ts#L418).

**Comment by nixmeer** [comment]
Thank you very much!!
