### ISSUE TITLE
Konke Multi Function Button

### ISSUE THREAD

**Issue by noppie** [arachnetech/homebridge-mqttthing#197]
I've added the Konke Multi Funciotn Button.

output in Zigbee2MQTT:
payload '{"battery":"100.00","voltage":3100,"linkquality":39,"click":"single"}

In the Homebridge added the next to the configuration:

{
            "accessory": "mqttthing",
            "type": "statelessProgrammableSwitch",
            "name": "Konke Switch",
            "url": "mgtt://127.0.0.1",
            "logMqtt": true,
            "topics": {
                "getSwitch": {
                    "topic": "zigbee2mqtt/deviceID",
                    "apply": "return JSON.parse(message).click;"
                },
                "getBatteryLevel": {
                    "topic": "zigbee2mqtt/DeviceID",
                    "apply": "return JSON.parse(message).battery;"
                }
            }
        }

In Homekit, the Button is added and I get the Batterystate, but when I press the button,  nothing happens.

Anyone any idea?

**Comment by nitej** [comment]
Your click message after applying that function returns “single”, but mqttthing is expecting a “1” for a single press by default. Add the setting “switchValues” to change what is expected for a single click like this

"switchValues": [
                "single",
                “none”,
                "none"
            ],

**Comment by noppie** [comment]
> Your click message after applying that function returns “single”, but mqttthing is expecting a “1” for a single press by default. Add the setting “switchValues” to change what is expected for a single click like this
> 
> "switchValues": [
> "single",
> “none”,
> "none"
> ],

Thanks for the reply. 

My config now:

{
            "accessory": "mqttthing",
            "type": "statelessProgrammableSwitch",
            "name": "Konke Switch",
            "url": "mgtt://127.0.0.1",
            "logMqtt": true,
            "topics": {
                "getSwitch": {
                    "topic": "zigbee2mqtt/ID",
                    "apply": "return JSON.parse(message).click;"
                },
                "getBatteryLevel": {
                    "topic": "zigbee2mqtt/ID",
                    "apply": "return JSON.parse(message).battery;"
                },
                "switchValues": [
                    "single",
                    "double",
                    "long"
                ]
            }
        }


Result:

Jan 24 17:06:43 raspberrypi npm[7923]: zigbee2mqtt:info  2020-01-24 17:06:43: MQTT publish: topic 'zigbee2mqtt/ID', payload '{"battery":"100.00","voltage":3100,"linkquality":0,"click":"single"}'
Jan 24 17:06:43 raspberrypi homebridge[31082]: [1/24/2020, 17:06:43] [Konke Switch] Received MQTT: zigbee2mqtt/ID = {"battery":"100.00","voltage":3100,"linkquality":0,"click":"single"}

Is the config correct?

**Comment by nitej** [comment]
you need to have "switchValues" outside the "topics" brackets. try this

{
    "accessory": "mqttthing",
    "type": "statelessProgrammableSwitch",
    "name": "Konke Switch",
    "url": "mgtt://127.0.0.1",
    "logMqtt": true,
    "topics": {
        "getSwitch": {
            "topic": "zigbee2mqtt/ID",
            "apply": "return JSON.parse(message).click"
        },
        "getBatteryLevel": {
            "topic": "zigbee2mqtt/ID",
            "apply": "return JSON.parse(message).battery"
        }
    },
    "switchValues": [
        "single",
        "double",
        "long"
    ]
}

**Comment by noppie** [comment]
That worked!   Thanks a lot......
