### ISSUE TITLE
Ikea Tradfri Brightness

### ISSUE THREAD

**Issue by RealLittleSherman** [arachnetech/homebridge-mqttthing#20]
Hi, the Ikea Tradfri Brightness values must be in the 0-255 range format, but Homekit sends 0-100, can you add a new multiplier value (or something like that) for adapting the range mismatching? 

Thanks in advance

**Comment by arachnetech** [comment]
That should be straightforward. I'll add it when I get a moment.

Do the Tradfri lights use MQTT out of the box, or have you reprogrammed them?

**Comment by RealLittleSherman** [comment]
I use Zigbee2MQTT to access, this software uses a JSON representation of parameters, then I use node-red to convert the JSON to single string to be used in MQTT topics with your Homebridge plugin

**Comment by GSanCap** [comment]
Forget this Issue, i can "remap" value using Node-Red, but if you wish to add it for eliminate the needed of Node-Red will be great. Regards

**Comment by arachnetech** [comment]
This can now (in version 1.0.17) be achieved by writing a function to scale the message payload, e.g.

```
    "getBrightness": {
        "topic": "test/lightbulb/getBrightness",
        "apply": "return Math.round( message / 2.55 );"
    },
    "setBrightness": {
        "topic": "test/lightbulb/setBrightness",
        "apply": "return Math.round( message * 2.55 );"
    }
```

See https://github.com/arachnetech/homebridge-mqttthing#applying-functions-to-mqtt-messages-custom-payload-encodingdecoding for details.

Consequently, I won't add the ability to set a scale factor independently - so I'll close this issue.

**Comment by GSanCap** [comment]
Thats perfect and more flexible! Thanks!!!
