### ISSUE TITLE
Homebridge crash

### ISSUE THREAD

**Issue by ldellus** [arachnetech/homebridge-mqttthing#200]
#### at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
-------------------------------------------------
Here is my accessory definition:
        {
            "accessory": "mqttthing",
            "type": "outlet",
            "name": "Power-Switch-1",
            "url": "mqtt://192.168.1.xxx",
            "username": "xxxx",
            "password": "xxxx",
            "mqttOptions": {
                "keepalive": 30
            },
            "mqttPubOptions": {
                "retain": true
            },
            "topics": {
                "getOn": "stat/POW-R2-Switch-1/POWER",
                "setOn": "cmnd/POW-R2-Switch-1/power",
                "getOnline": "tele/POW-R2-Switch-1/LWT",
                "getWatts": {
                    "topic": "tele/POW-R2-Switch-1/SENSOR",
                    "apply": "return JSON.parse(message).ENERGY.Power;"
                },
                "getVolts": {
                    "topic": "tele/POW-R2-Switch-1/SENSOR",
                    "apply": "return JSON.parse(message).ENERGY.Voltage;"
                },
                "getAmperes": {
                    "topic": "tele/POW-R2-Switch-1/SENSOR",
                    "apply": "return JSON.parse(message).ENERGY.Current;"
                }
            },
            "history": "true",
            "logMqtt": true,
            "onValue": "ON",
            "offValue": "OFF",
            "onlineValue": "Online",
            "startPub": {
                "cmnd/POW-R2-Switch-1/power": ""
            },
            "manufacturer": "ITEAD",
            "model": "Sonoff POW R2",
            "serialNumber": "CC:50:E3:54:80:AF"
        },
Thanks for any help you can provide.**

**Comment by ldellus** [comment]
Hi,

I reinstalled homebridge and everything's fine now.

Thanks,

Laurent

**Comment by arachnetech** [comment]
Excellent, thanks for confirming.
