### ISSUE TITLE
Feature request - toggle accessory

### ISSUE THREAD

**Issue by dcaccount** [arachnetech/homebridge-mqttthing#206]
Hello arachnetech,
first of all thank you so much for your great plugin!
I have some Shellies switches connected to my MQTT server. Shelly's switches accept "toggle" command via MQTT in oder to change their state.

I have tried to create a toggle accessory using your plugin and following configuration:

`{
    "accessory": "mqttthing",
    "type": "switch",
    "name": "LED lamp",
     "url": "mqtt://localhost",
    "topics":{
        "getOn":"shellies/shelly1-xx/relay/0",
        "setOn":"shellies/shelly1-xx/relay/0/command",
        "getOnline":"shellies/shelly1-xx/online" 
    },
    "onValue": "toggle",
     "turnOffAfterms": "500",
    "onlineValue": "true",
    "logMqtt": true
}`

and it works.

When you press it, it makes Shelly switch change its state.

The problem is that **the accessory does not show the current status of the Shelly switch** (on or off). When you press it, it becomes on for 500 ms and then back off.

I would need that the accessory showed the actual state of the Shelly switch.

Can you please check if I am missing something and/or can you please implement it?

I think it would be useful for many.
Thanks!
Dan

**Comment by dcaccount** [comment]
Hello arachnetech,
do you think, there is any chance to implement this feature?

Please advise, thanks, Dan

**Comment by arachnetech** [comment]
To check I’m understanding correctly, you want to send the same message (toggle) to turn the switch on or off. Does the switch then use different messages to report its on/off state back to homebridge?

**Comment by dcaccount** [comment]
> To check I’m understanding correctly, you want to send the same message (toggle) to turn the switch on or off. Does the switch then use different messages to report its on/off state back to homebridge?

Thanks for the attention. Yes, I want to send the same message (toggle) to turn the switch on or off.

>Does the switch then use different messages to report its on/off state back to homebridge?
Actually I would say so, please find here below the MQTT specifications of the switch (Shelly 1):

> Shelly1 and Shelly1PM uses the following topics, where <model> is either shelly1 or shelly1pm:

shellies/<model>-<deviceid>/relay/0 to report status: on or off
shellies/<model>-<deviceid>/relay/0/command accepts on, off or toggle and applies accordingly

**Comment by dcaccount** [comment]
> > To check I’m understanding correctly, you want to send the same message (toggle) to turn the switch on or off. Does the switch then use different messages to report its on/off state back to homebridge?
> 
> Thanks for the attention.
> Yes, I want to send the same message (toggle) to turn the switch on or off.
> 
> > Does the switch then use different messages to report its on/off state back to homebridge?
> 
> Actually I would say so, please find here below the MQTT specifications of the switch (Shelly 1):
> 
> > Shelly1 and Shelly1PM uses the following topics, where  is either shelly1 or shelly1pm:
> > shellies/-/relay/0 to report status: on or off
> > shellies/-/relay/0/command accepts on, off or toggle and applies > accordingly
> 
> In other words instead of a switch I would like to have a push button with report of the status.
> Thanks!

Hello David,
is everything clear?
Should you need more info, please advise.
Thanks,
Dan

**Comment by arachnetech** [comment]
I think it should be possible to use the 'apply' functionality to send a toggle message whether the switch is turning on or off, but if Shelly can accept on/off commands too I don't really understand why you want to do this. Couldn't you just send an on command for on and an off command for off? You wrote:

> shellies/-/relay/0/command accepts on, off

Couldn't you just use:

```
{
    "accessory": "mqttthing",
    "type": "switch",
    "name": "<name of switch>",
    "url": "...",
    "username": "...",
    "password": "...",
    "topics":
    {
        "getOn": 	        "shellies/-/relay/0",
        "setOn": 	        "shellies/-/relay/0/command"
    },
    "onValue": "on",
    "offValue": "off"
}
```

I'll try the toggle thing when I get a chance, hopefully over the weekend. However to set your expectations while I'm happy to add new general purpose features when I get a chance, I have never tried to support specific hardware/firmware directly.

**Comment by dcaccount** [comment]
Hello,
I have implemented following switch:
`            "accessory": "mqttthing",
            "type": "switch",
            "name": "BSalaL",
            "url": "http://192.168.1.141:1883",
            "topics": {
                "getOn": "shellies/shelly1-C42287/relay/0",
                "setOn": "shellies/shelly1-C42287/relay/0/command"
            },
            "onValue": "toggle",
            "logMqtt": false`

**Comment by arachnetech** [comment]
Is there a reason that you can't use `on` and `off` as the on and off values?

**Comment by dcaccount** [comment]
> Is there a reason that you can't use `on` and `off` as the on and off values?

Yes! Instead of having to tell "Hey Siri, or Alexa switch on or switch off the light", I can just say, "Hey Siri, light" and it changes its status. It is much more convenient.

I have implemented following switch:

>         {
            "accessory": "mqttthing",
            "type": "switch",
            "name": "BCucinaL",
            "url": "http://X:1883",
            "topics": {
                "getOn": "shellies/shelly1-C49A8A/relay/0",
                "setOn": "shellies/shelly1-C49A8A/relay/0/command"
            },
            "onValue": "toggle",
            "logMqtt": false
        },

The problem is that is does not report the correct status of the accessory.

**Comment by arachnetech** [comment]
I don't think that will work. Presumably "Hey Siri, light" is turning the light on from a Homekit perspective - so if you try to reflect its true on/off status through homebridge then turning it off won't work.

**Comment by dcaccount** [comment]
> I don't think that will work. Presumably "Hey Siri, light" is turning the light on from a Homekit perspective - so if you try to reflect its true on/off status through homebridge then turning it off won't work.

I have used this switch with the toggle command for at least one month. It works perfectly, if the light is off, saying "Hey Siri light", it turns it on and vice versa.

**Comment by dcaccount** [comment]
In any case, even if we stick on the "ON" and "OFF" values, I think that it would be interesting for many if it there were a toggle button working as following:

- I press it, if the status is ON, it turn it off and display off
- I press it, if the status is OFF, it turn it on and display on

It would not be depending on the specific hardware!

**Comment by arachnetech** [comment]
You can publish `toggle` for both on and off while updating the state correctly when your shelly publishes `on` or `off` using a configuration like this:

```
    {
      "accessory": "mqttthing",
      "type": "switch",
      "name": "Toggle switch",
      "url": "http://X:1883",
      "topics": {
        "getOn": "test/shelly/relay/0",
        "setOn": { 
          "topic": "test/shelly/relay/0/command",
          "apply": "return 'toggle';"
        }
      },
      "onValue": "on",
      "offValue": "off"
    }
```

**Comment by dcaccount** [comment]
> You can publish `toggle` for both on and off while updating the state correctly when your shelly publishes `on` or `off` using a configuration like this:
> 
> ```
>     {
>       "accessory": "mqttthing",
>       "type": "switch",
>       "name": "Toggle switch",
>       "url": "http://X:1883",
>       "topics": {
>         "getOn": "test/shelly/relay/0",
>         "setOn": { 
>           "topic": "test/shelly/relay/0/command",
>           "apply": "return 'toggle';"
>         }
>       },
>       "onValue": "on",
>       "offValue": "off"
>     }
> ```

Thanks! I am not at home these days, I will immediately try upon return

**Comment by dcaccount** [comment]
> You can publish `toggle` for both on and off while updating the state correctly when your shelly publishes `on` or `off` using a configuration like this:
> 
> ```
>     {
>       "accessory": "mqttthing",
>       "type": "switch",
>       "name": "Toggle switch",
>       "url": "http://X:1883",
>       "topics": {
>         "getOn": "test/shelly/relay/0",
>         "setOn": { 
>           "topic": "test/shelly/relay/0/command",
>           "apply": "return 'toggle';"
>         }
>       },
>       "onValue": "on",
>       "offValue": "off"
>     }
> ```

Hello,
thanks but it is not what I am looking for. Maybe I have been not 100% clear, sorry. So to avoid any misunderstanding, please find here below what I would like to implement:

[https://www.amazon.com/BONATECH-Switches-Latching-Control-greenswitch/dp/B07PRMNLBH/ref=sr_1_17?keywords=push+button+toggle+switch&qid=1582617352&sr=8-17](url)

Thanks!

**Comment by arachnetech** [comment]
I thought that wouldn’t work, as I said earlier!

I think what you want is a switch that toggles on/off every time you turn it ‘on’ from homekit. That isn’t going to work because homekit won’t turn on a switch if it’s already on. This is homekit logic and nothing to do with mqttthing or even homebridge. 

The best I can suggest is that you use a pair of switches: one which toggles (as you already have set up) and another which responds to your Shelly state to show the on/off state back in homekit. You could configure it to publish the toggle message as above so that pressing it would work - but your original switch would be the one responding to Siri commands.
