### ISSUE TITLE
Outlet Status in Homebridge question and Eve App "chart" question

### ISSUE THREAD

**Issue by einencool** [arachnetech/homebridge-mqttthing#207]
Hello, at first of all, thank you for this great plugin.
Today I was testing very much and get my Outlet (Gosund Sp111 with Tasmota 8.1) working very good, but I've got some questions for understanding:

I can switch the Outlet via homebridge / Home App / EVE App and switch on the Outlet without Problems and the Status ist working fine.
When I unplug the Outlet, the Home App and Eve App show me the Outlet as not accessible.
But I can "switch" the Status in the homebridge Website. In the Logfile it shows that it's not accessible, but the Website says, that the outlet is set to "ON"

Is there any way I can change this?

-----
Second question is, I get all values in the EVE App, but can't get the "Charts" to work. It says always that there is no data... (The Values are all shown, but not the Chart)
What do I have to configure, to get it to work?
Thank you in Advance and now here are my Configs and Log-Messages

        {
            "accessory": "mqttthing",
            "type": "outlet",
            "name": "Test Dose 105",
            "url": "mqtt://127.0.0.1:1883",
            "mqttOptions": {
                "keepalive": 30
            },
            "mqttPubOptions": {
                "retain": true
            },
            "logMqtt": true,
            "topics": {
                "getOn": "stat/Dose105/POWER",
                "setOn": "cmnd/Dose105/power",
                "getOnline": {
                    "topic": "tele/Dose105/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
                },
                "getInUse": {
                    "topic": "tele/Dose105/STATE",
                    "apply": "return JSON.parse(message).POWER"
                },
                "getWatts": {
                    "topic": "tele/Dose105/SENSOR",
                    "apply": "return JSON.parse(message)['ENERGY'].Power;"
                },
                "getVolts": {
                    "topic": "tele/Dose105/SENSOR",
                    "apply": "return JSON.parse(message)['ENERGY'].Voltage;"
                },
                "getAmperes": {
                    "topic": "tele/Dose105/SENSOR",
                    "apply": "return JSON.parse(message)['ENERGY'].Current;"
                },
                "getTotalConsumption": {
                    "topic": "tele/Dose105/SENSOR",
                    "apply": "return JSON.parse(message)['ENERGY'].Total;"
                }
            },
            "onValue": "ON",
            "offValue": "OFF",
            "history": true,
            "startPub": {
                "cmnd/Dose105/power": "OFF",
                "stat/Dose105/POWER": "OFF"
            },
            "confirmationPeriodms": 2000,
            "retryLimit": 2
        },

Log-Message:
[2020-2-2 13:37:29] [Test Dose 105] Publishing MQTT: cmnd/Dose105/power = ON
[2020-2-2 13:37:31] [Test Dose 105] Publishing MQTT: cmnd/Dose105/power = ON
[2020-2-2 13:37:33] [Test Dose 105] Publishing MQTT: cmnd/Dose105/power = ON
[2020-2-2 13:37:35] [Test Dose 105] Unresponsive - no confirmation message received on stat/Dose105/POWER. Expecting [ON].
[2020-2-2 13:37:54] [Test Dose 105] Received MQTT: tele/Dose105/LWT = Offline

But the status on Homebridge Website says "ON"

Sorry if these questions were finished in other topics, but I read around 30 Topics but can't get it to work...

Greets Chris

**Comment by arachnetech** [comment]
@tobekas Any thoughts on this?

**Comment by tobekas** [comment]
Hi, this is related to issue #223.
Try to first leave out `getTotalConsumption` topic, so mqttthing will do the energy counting by itself. This should work at the moment. There is a bug in combination with `getTotalConsumption`, that prevents adding the history entries.
Hope I can fix this soon.

**Comment by arachnetech** [comment]
Fixed in version 1.1.6
