### ISSUE TITLE
No connection with MQTT

### ISSUE THREAD

**Issue by mediakon** [arachnetech/homebridge-mqttthing#208]
Please help me to connect with MQTT. I installed homebridge-config-ui-x v4.9.0 according to the instructions on the site, then configured the accessory and compiled the code for arduino. 

The program connects to my WI-FI network without any problems but I have a problem with connecting to MQTT.

With clean installation of homebridge + homebridge-config-ui-x v4.9.0 and homebridge-mqttthing something else needs to be installed? What do I possibly enter wrong in the configuration settings? Other IP addresses? Alternatively, how to set a password to connect to MQTT with arduino?

Thanks for help.

Working under

homebridge-config-ui-x v4.9.0
Raspbian GNU/Linux Buster (10)
raspberrypi
hombridge runing on IP 192.168.1.109
v12.14.1
v6.13.4
homebridge
/var/lib/homebridge
/var/lib/homebridge/config.json
Homebridge is running on port 51625

**ACCESSORY PART**

` {
            "accessory": "mqttthing",
            "type": "weatherStation",
            "name": "ESP8266ClientX",
            "url": "mqtt://192.168.1.109",
            "serviceNames": {
                "temperature": "Temperatura",
                "humidity": "Wilgotność",
                "airPressure": "Ciśnienie",
                "weather": "Pogoda"
            },
            "caption": "Stacja pogodowa",
            "topics": {
                "getCurrentTemperature": "sensor/temperature",
                "getCurrentRelativeHumidity": "sensor/humidity"
            },
            "history": false
        }`

**PART OF ARDUINO CODE**

`#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include "DHT.h"        

#define wifi_ssid "INEA-3xxx"
#define wifi_password "xxxxxx"

#define mqtt_server "192.168.1.109" 
#define mqtt_user ""  
#define mqtt_password ""

#define temperature_topic "sensor/temperature"  
#define humidity_topic "sensor/humidity"  

char message_buff[100];
long lastMsg = 0; 
long lastRecu = 0;
bool debug = false;  

#define DHTPIN 4    

// Dé-commentez la ligne qui correspond à votre capteur 
#define DHTTYPE DHT22     

IPAddress staticIP(192,168,1,108);
IPAddress gateway(192,168,1,1);
IPAddress subnet(255,255,255,0);

//Création des objets
DHT dht(DHTPIN, DHTTYPE);     
WiFiClient espClient;
PubSubClient client(espClient);

void setup() {
  Serial.begin(9600);     //Facultatif pour le debug
  pinMode(5,OUTPUT);     //Pin 2 
  setup_wifi();           //On se connecte au réseau wifi
  client.setServer(mqtt_server, 1883 );
  client.setCallback(callback);  
  dht.begin();
}

//Connexion au réseau WiFi
void setup_wifi() {
  delay(10);
  Serial.println();
  Serial.print("Connexion a ");
  Serial.println(wifi_ssid);

  //WiFi.begin(wifi_ssid, wifi_password);
  
  //WiFi.mode(WIFI_STA);
  WiFi.begin(wifi_ssid, wifi_password);
  WiFi.config(staticIP, gateway, subnet);
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("Connexion WiFi etablie ");
  Serial.print("=> Addresse IP : ");
  Serial.print(WiFi.localIP());
}

//Reconnexion
void reconnect() {
  //Boucle jusqu'à obtenur une reconnexion
  while (!client.connected()) {
    Serial.print("Connexion au serveur MQTT...");
    if (client.connect("ESP8266ClientX", mqtt_user, mqtt_password)) {
      Serial.println("OK");
    } else {
      Serial.print("KO, erreur : ");
      Serial.print(client.state());
      Serial.println(" On attend 5 secondes avant de recommencer");
      delay(5000);
    }
  }
}`

**Comment by einencool** [comment]
I‘m also not so firm with this, but you have to install a MQTT Broker like „Mosquito“.
That program will listen to the things your Outlet or what ever will send.

**Comment by arachnetech** [comment]
Assuming that your Arduino code can connect without a username or password, as per:

```
#define mqtt_server "192.168.1.109"
#define mqtt_user ""
#define mqtt_password ""
```

... then I would expect MQTT to be able to connect to using:

```
"url": "http://192.168.1.109:1883",
```

I think you may need the MQTT port number (1883 by default) at the end of the URL though - it's missing in your configuration.

**Comment by arachnetech** [comment]
Actually I might be wrong about that looking the documentation for the mqtt package on npm.

Does your MQTT server need a username/password?

What logging does homebridge give you in relation to your homebridge-mqttthing accessory?

It may be helpful to set `"logMqtt": true` to see exactly what is being send and received.

**Comment by mediakon** [comment]
It's all clear. It turned out that when I was connecting to a router that was connected to others with disabled DHCP, the MQTT was not working in such a network at that time. When I connected a standalone router with a different IP then MQTT started to work perfectly.

Maybe you have an idea what to do (some configuration for raspberry?) in a network where there are several routers, one of which is the main tool and the rest is with DHCP disabled?

Now MQTT on this single router on another pool of homebridge IP addresses connects as he wrote

arachnetech "url": "http://192.168.0.109:1883", without user and password.

Translated with www.DeepL.com/Translator (free version)

**Comment by arachnetech** [comment]
Glad you got this working. Closing issue.
