### ISSUE TITLE
Shutter with Tasmota

### ISSUE THREAD

**Issue by TonyPeperoni** [arachnetech/homebridge-mqttthing#211]
I have a Shelly 2.5 on Tasmota with shutter firmware. The mqqtthing plugin has become my default plugin, but I can not yet figure out how to use the mqttthing window covering accessory with Tasmota shutter functionality. The complexity is a bit over whelming. Are there community examples of working config.json for Tasmota shutter ?

Sorry for the Noob question

**Comment by GerSant** [comment]
Same here

**Comment by serbasan** [comment]
Look at my settings. Maybe I can help. A greeting.
#238

**Comment by GerSant** [comment]
Do you speak Spanish? Because the topic name “persiana” ;) ?

**Comment by rbswift** [comment]
try this:

```
        {
            "accessory": "mqttthing",
            "type": "windowCovering",
            "name": "Bedroom Shutter",
            "topics": {
                "setTargetPosition": "cmnd/bedroomshutter/shutterposition",
                "getTargetPosition": "stat/bedroomshutter/SHUTTER1",
                "getCurrentPosition": "stat/bedroomshutter/SHUTTER1",
                "getOnline": "tele/bedroomshutter/LWT"
            },
            "onlineValue": "Online",
            "logMqtt": true
        },
```

**Comment by GerSant** [comment]
Perfect! Thanks!
