### ISSUE TITLE
temperatureSensor

### ISSUE THREAD

**Issue by psmurashov** [arachnetech/homebridge-mqttthing#212]
Please help! 
 I'm trying to display the temperature.

**mosquitto_sub -d -t /ESP_Easy/Temp/Temperature :**
![1](https://user-images.githubusercontent.com/50335931/74538349-19136900-4f4d-11ea-9905-1f120bb7002c.jpg)

**HomeKit :**
![attachment](https://user-images.githubusercontent.com/50335931/74538554-845d3b00-4f4d-11ea-909e-eb2daee4baba.png)
Config:
{
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "Temp",
            "url": "http://192.168.1.10:1883",
            "topics": {
                "getCurrentTemperature": "/ESP_Easy/Temp/Temperature"
            },
            "history": true
        }

**Comment by arachnetech** [comment]
Does mqttthing receive the MQTT messages as expected if you set `"logMqtt": true` and look at your homebridge logs?

**Comment by psmurashov** [comment]
![1](https://user-images.githubusercontent.com/50335931/74554660-1d4e7f00-4f6b-11ea-9d29-6710238b96ab.jpg)

**Comment by arachnetech** [comment]
I can't see any sign of MQTT messages being received there.

**Comment by psmurashov** [comment]
What could be the problem?

**Comment by arachnetech** [comment]
With MQTT logging enabled, I would expect to see something like this (but for your accessory):
![image](https://user-images.githubusercontent.com/24389384/74556347-c0949980-4f55-11ea-8d41-e7198b0c2cfb.png)

**Comment by psmurashov** [comment]
In the first picture, mosquitto works. 
Messages are coming. It turns out the plugin is not able to read messages to mosquitto?

**Comment by arachnetech** [comment]
What does your mqttthing configuration look like?

**Comment by arachnetech** [comment]
Sorry, you sent that already!

**Comment by arachnetech** [comment]
Are you sure your URL is correct? I would expect an `mqtt` protocol rather than an `http` protocol, i.e. `"url": "mqtt://192.168.1.10:1883"`.

**Comment by psmurashov** [comment]
I have already tried mqtt, http. It doesn't help!

**Comment by psmurashov** [comment]
{
    "description": "JSON API",
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 7000,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "sudo": false,
            "log": {
                "method": "file",
                "path": "/var/log/homebridge.log"
            },
            "accessoryControl": {
                "debug": true
            }
        }
    ],
    "bridge": {
        "name": "Homebridge",
        "username": "0E:BC:1E:67:56:DB",
        "port": 51826,
        "pin": "539-43-378"
    },
    "accessories": [
        {
            "accessory": "Http",
            "name": "Living Room",
            "on_url": "http://192.168.1.10/control?cmd=GPIO,12,1",
            "off_url": "http://192.168.1.10/control?cmd=GPIO,12,0",
            "http_method": "GET"
        },
        {
            "accessory": "mqttthing",
            "type": "switch",
            "name": "switch",
            "url": "mqtt://192.168.1.10:1883",
            "topics": {
                "getOn": "ESP_Easy/Switch/State",
                "setOn": "ESP_Easy/gpio/12"
            },
            "integerValue": "true",
            "onValue": "0",
            "offValue": "1",
            "logMqtt": true
        },
        {
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "Temp",
            "url": "mqtt://192.168.1.10:1883",
            "topics": {
                "getCurrentTemperature": "ESP_Easy/Temp/Temperature"
            },
            "history": true,
            "logMqtt": true
        }
    ]
}

**Comment by psmurashov** [comment]
![1](https://user-images.githubusercontent.com/50335931/74557677-b385a380-4f71-11ea-954e-1a30ee3af35b.jpg)

**Comment by arachnetech** [comment]
Is the subject

**Comment by arachnetech** [comment]
Also, is the switch in your configuration working?

**Comment by psmurashov** [comment]
No
