### ISSUE TITLE
Would like to set the fakegato-history persistence path

### ISSUE THREAD

**Issue by zellneralex** [arachnetech/homebridge-mqttthing#213]
First thanks for the great plugin,

fakegato-history would allow to assign a storage location for the persistence data:
this.loggingService = new FakeGatoHistoryService(accessoryType, Accessory, {
	size:length, 				// optional - if you still need to specify the length
	storage:'fs',
	path:'/place/to/store/my/persistence/'  // if empty it will be used the -U homebridge option if present, or .homebridge in the user's home folder
});
I assume that you let the path empty at the moment. Could you consider to get this as a optional parameter for the history area

Thanks in advance Alex

**Comment by arachnetech** [comment]
I’ll add it to (new) the list of requested features that I’m compiling.

**Comment by arachnetech** [comment]
Added in 1.1.9
