### ISSUE TITLE
restrictHeatingCoolingState of the thermostat is not working

### ISSUE THREAD

**Issue by mwkchan** [arachnetech/homebridge-mqttthing#215]
Seems restrictHeatingCoolingState for the thermostat accessory is not working.

This is my setup and I still can see AUTO. I tried other combinations, too change. Homekit still can see all four target states:

        {
            "accessory": "mqttthing",
            "type": "thermostat",
            "name": "MR AC",
            "topics": {
                "getCurrentHeatingCoolingState": "homekit/MRAC/CurState",
                "setTargetHeatingCoolingState": "homekit/MRAC/CurState",
                "getTargetHeatingCoolingState": "homekit/MRAC/TrgState",
                "getCurrentTemperature": "weather/inTemp_C",
                "setTargetTemperature": "homekit/MRAC/TrgTemp",
                "getTargetTemperature": "homekit/MRAC/TrgTemp",
                "setTemperatureDisplayUnits": "homekit/MRAC/TempUnit",
                "getTemperatureDisplayUnits": "homekit/MRAC/TempUnit",
                "getCurrentRelativeHumidity": "weather/inHumidity",
                "restrictHeatingCoolingState": [
                    0,
                    1,
                    2
                ]
            },
            "minTemperature": 18,
            "maxTemperature": 26
        },

**Comment by arachnetech** [comment]
I’m only on my phone, but I don’t think it should be within “topics”.

**Comment by mwkchan** [comment]
The original config I pasted got error, I since edited my comment. Anyway, here' the config. And I still cannot restrict the state. Still can see all 4 states in my iPhone Home app or other HomeKit app. I tried other combination, e.g. [0,1] but no difference, still with 4 states.

        {
            "accessory": "mqttthing",
            "type": "thermostat",
            "name": "MR AC",
            "topics": {
                "getCurrentHeatingCoolingState": "homekit/MRAC/CurState",
                "setTargetHeatingCoolingState": "homekit/MRAC/CurState",
                "getTargetHeatingCoolingState": "homekit/MRAC/TrgState",
                "getCurrentTemperature": "weather/inTemp_C",
                "setTargetTemperature": "homekit/MRAC/TrgTemp",
                "getTargetTemperature": "homekit/MRAC/TrgTemp",
                "setTemperatureDisplayUnits": "homekit/MRAC/TempUnit",
                "getTemperatureDisplayUnits": "homekit/MRAC/TempUnit",
                "getCurrentRelativeHumidity": "weather/inHumidity",
                "restrictHeatingCoolingState": [
                    0,
                    1,
                    2
                ]
            },
            "minTemperature": 18,
            "maxTemperature": 26
        },

**Comment by arachnetech** [comment]
Move `restrictHeatingCoolingState` to OUTSIDE topics, i.e. something like this:

```

    {
        "accessory": "mqttthing",
        "type": "thermostat",
        "name": "MR AC",
        "topics": {
            "getCurrentHeatingCoolingState": "homekit/MRAC/CurState",
            "setTargetHeatingCoolingState": "homekit/MRAC/CurState",
            "getTargetHeatingCoolingState": "homekit/MRAC/TrgState",
            "getCurrentTemperature": "weather/inTemp_C",
            "setTargetTemperature": "homekit/MRAC/TrgTemp",
            "getTargetTemperature": "homekit/MRAC/TrgTemp",
            "setTemperatureDisplayUnits": "homekit/MRAC/TempUnit",
            "getTemperatureDisplayUnits": "homekit/MRAC/TempUnit",
            "getCurrentRelativeHumidity": "weather/inHumidity",
        },
        "restrictHeatingCoolingState": [
            0,
            1,
            2
        ]
        "minTemperature": 18,
        "maxTemperature": 26
    },

```

**Comment by mwkchan** [comment]
I did that, still not working. Here's my current config:

    {
            "accessory": "mqttthing",
            "type": "thermostat",
            "name": "MR AC",
            "topics": {
                "getCurrentHeatingCoolingState": "homekit/MRAC/CurState",
                "setTargetHeatingCoolingState": "homekit/MRAC/CurState",
                "getTargetHeatingCoolingState": "homekit/MRAC/TrgState",
                "getCurrentTemperature": "weather/inTemp_C",
                "setTargetTemperature": "homekit/MRAC/TrgTemp",
                "getTargetTemperature": "homekit/MRAC/TrgTemp",
                "setTemperatureDisplayUnits": "homekit/MRAC/TempUnit",
                "getTemperatureDisplayUnits": "homekit/MRAC/TempUnit",
                "getCurrentRelativeHumidity": "weather/inHumidity"
            },
            "restrictHeatingCoolingState": [
                0,
                1,
                2
            ],
            "minTemperature": 18,
            "maxTemperature": 26
        },

**Comment by arachnetech** [comment]
I have tested with your `restrictHeatingCoolingState` values and it does work: AUTO disappears. Note that these restrictions aren't intended to update dynamically - you may have to force-quit and restart the Home app before it notices your change.

![image](https://user-images.githubusercontent.com/24389384/79048698-d1405380-7c16-11ea-8b09-a6ad82b7f144.png)

**Comment by mwkchan** [comment]
You are right. And it took more than force quit my Home app. I actually needed to reboot both my iPhone and iPad to make it work. Thanks for looking into it.
