### ISSUE TITLE
Simple Button to trigger RF Bridge 433 signal not working

### ISSUE THREAD

**Issue by Jafalex** [arachnetech/homebridge-mqttthing#216]
Hi,

Similar to what’s been discussed in #67 I’m trying to use a ```statelessProgrammableSwitch``` in the iOS Home app to get my Sonoff RF Bridge (flashed with Tasmota 8.0) to open the outdoor gate. 

Homebridge button tile -> MQTT -> Tasmota -> Sonoff RF 433 signal to Gate

Same code “123456” for both opening and closing the gate. I’ve made Tasmota learn this code and store in ```RfKey1```. Things working perfectly when using Tasmota web UI directly.

All I’m trying to do is something like this:
```
        {
            "accessory": "mqttthing",
            "type": "statelessProgrammableSwitch",
            "name": "Gate2",
            "url": "192.168.8.25:1883",
            "username": "",
            "password": "",
            "topics": {
                "stateGet": "tele/rfbridge/STATE",
                "statusGet": "stat/rfbridge/POWER",
                "statusSet": "cmnd/rfbridge/RfKey1"
            }
        }
```
I can see the button in the Home app, but when I tap it this is all I get is the message [“There is an unconfigured button”](https://imgur.com/a/O1hYxqD). I’ve tried a whole lot of different variations of that JSON, to no avail.

I’m highly doubting my JSON above and would love someone pointing me in the right direction!
Thanks in advance.

**Comment by tobekas** [comment]
`statelessProgrammableSwitch` is the wrong type for your usecase. It’s a read-only accessory, which can just receive events from the switch accessory and cannot be set from Homekit.
Checkout Standard `switch` type in combination with `resetStateAfterms`

**Comment by arachnetech** [comment]
Thanks, @tobekas. Closing issue for now.
