### ISSUE TITLE
Temperature Range

### ISSUE THREAD

**Issue by voelkerb** [arachnetech/homebridge-mqttthing#221]
First thanks for this awesome plugin!

I wonder why the temperature is limited between 0-100 - is this a homekit thing? Even custom javascript functions seem to be restricted to 0-100.
I am currently monitoring the boiler temperature of my espresso machine which exceeds the 100°C limit, so allowing higher temperatures would be nice.

Thanks in advance.

**Comment by arachnetech** [comment]
HomeKit generally has default ranges, but these can generally be overridden. (I may need to add an option for this.) What accessory type are you using for this?

**Comment by voelkerb** [comment]
I am using the temperatureSensor type but ideally it should work for all types which have temperature readings.

**Comment by arachnetech** [comment]
Thanks, I’ll take a look.

**Comment by arachnetech** [comment]
Adding in version 1.1.7

**Comment by voelkerb** [comment]
Perfectly working. Thanks man!
