### ISSUE TITLE
FAN on Home APP after restart

### ISSUE THREAD

**Issue by deon-wentzel** [arachnetech/homebridge-mqttthing#224]
Hi,

I have configured a Sonoff iFan 02 with Tasmota v8.10, with the following configuration;
{
    "accessory": "mqttthing",
    "type": "fan",
    "name": "Sonoff Fan",
    "url": "mqtt://host.domain.com:1883",
    "username": "homemin",
    "password": "ppppppppp",
    "mqttPubOptions": {
        "retain": true
    },
    "topics": {
        "getOn": "stat/sonofffan/FanSpeed",
        "setOn": {
            "topic": "cmnd/sonofffan/FanSpeed",
            "apply": "return Math.round( message / 33.33);"
        }
        "getRotationSpeed": {
            "topic": "stat/sonofffan/FanSpeed",
            "apply": "return Math.round( message );"
        },
        "setRotationSpeed": {
            "topic": "cmnd/sonofffan/FanSpeed",
            "apply": "return Math.round( message / 33.33);"
        }
    },
    "confirmationPeriodms": "300",
    "logMqtt": true,
    "serialNumber": "xx:xx:xx:xx:xx:xx",
    "manufacturer": "ITEAD",
    "model": "Sonoff iFan02",
    "firmwareRevision": "8.10",
    "startPub": {
        "stat/sonofffan/Fanspeed": "ON",
        "cmnd/sonofffan/Fanspeed": "ON"
    }
}
The slider works fine, but tapping the fan in the HOME APP and the Fan is off it does not turn on.

**Comment by deon-wentzel** [comment]
Additional information, when you exit the HOME APP and load it again, the slide is OFF too.

**Comment by arachnetech** [comment]
Does Tasmota need ON to be published to Fanspeed, or would it be sufficient to publish a non-zero number to turn the fan on and 0 to turn it off? 

(I’m thinking that perhaps mqttthing should treat Fanspeed as it does brightness for lights - where a brightness of 0 can be used instead of separate on/off topics.)
