### ISSUE TITLE
Thermostat threshold values only integer?

### ISSUE THREAD

**Issue by mspiridakis** [arachnetech/homebridge-mqttthing#228]
Congrats on the brilliant work and the continuous support and effort for this project.
I have been meaning to ask about this for a long time. 
Thermostat (temp) threshold values can be only integer numbers. 
Is there a possibility of 0.5 increments? 
I think if would be a useful enhancement (especially for Celsius)

**Comment by arachnetech** [comment]
Mqttthing already treats HeatingThresholdTemperature as a float, and https://github.com/KhaosT/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts shows it as having a minimum step of 0.1 - so I’m surprised that decimals aren’t showing. I’ll have to test this.

**Comment by tobekas** [comment]
It may be that the Apple Home App only allows integer values ​​as the target temperature (if country settings configure ° F). With °C setting, I think you get 0,5°C. But this depends on the App. With other Apps (like Eve) or if you set this target temperature via mqtt, other steps might work.

**Comment by mspiridakis** [comment]
arachnetech I can see that now. 
My country settings are Celsius bus Home App only allows for 1 degree change. 
Weird though. When I use the Eve app which accesses the same data with the Home app, I can use 0.5 degrees.

**Comment by arachnetech** [comment]
I have tested, and I can set the target temperature externally to half-degree increments (e.g. 10.5 C) and it is correctly reflected in the Home app. However, this is just a limitation of the Home App. As you say, the Eve App allows the target temperature to be set in 0.5 C increments.
