### ISSUE TITLE
mqttthing does not connect to mosquitto

### ISSUE THREAD

**Issue by ryoko-sky** [arachnetech/homebridge-mqttthing#229]
when HB starts up, a message on the status of the sensor appears in the terminal
`[contact]``` Received MQTT: zigbee2mqtt/0x286d970001097a6d = {"contact":true,"tamper":false,"battery_low":false,"linkquality":60,"battery":40,"voltage":2700,"temperature":27.26}`

the topic "WillMsg" appears in the broker
with message
`Connection` Closed abnormally..!`
and after in the terminal a connection error
`[contact] Initializing mqttthing accessory...
[2020-4-6 0:28:46] [contact] MQTT options: {"keepalive":30,"clientId":"mqttthing_contact_0390dd4d","protocolId":"MQTT","protocolVersion":4,"clean":true,"reconnectPeriod":1000,"connectTimeout":30000,"will":{"topic":"WillMsg","payload":"Connection Closed abnormally..!","qos":0,"retain":false},"username":"yoko","rejectUnauthorized":false}`

![Аннотация 2020-04-06 003952](https://user-images.githubusercontent.com/14962706/78501557-3ae7da00-779f-11ea-858c-e18286b2dc66.png)
![Аннотация 2020-04-06 004020](https://user-images.githubusercontent.com/14962706/78501560-3cb19d80-779f-11ea-9fd5-6af04cd79667.png)

**Comment by ryoko-sky** [comment]
![image](https://user-images.githubusercontent.com/14962706/78501620-a3cf5200-779f-11ea-9501-33ab0ddf6cae.png)
such a configuration

**Comment by RaymondMouthaan** [comment]
Try without `http://`

**Comment by ryoko-sky** [comment]
I tried without, and did not indicate at all (since the broker is local)
nothing helps

**Comment by RaymondMouthaan** [comment]
Have you tried `mqtt://<ip_address>:1883`?

**Comment by ryoko-sky** [comment]
ye

**Comment by arachnetech** [comment]
Still a problem?

**Comment by caffeineflo** [comment]
@arachnetech 
I hate to bother you with this, but I happen to have the exact same issue.

I have a local mosquitto server an all combinations for an `url` failed so far. Happy to provide any logs if you tell me what you need

**Comment by arachnetech** [comment]
@caffeineflo I not sure I ever really understood what the issue was. Can you show me your config and the output from running `mosquitto_sub -v -t "#"` ?

**Comment by mitch7391** [comment]
@arachnetech I seem to have this error thrown, what can I do to get you more information?

**Comment by arachnetech** [comment]
It's not just logging your MQTT configuration, is it?

**Comment by mitch7391** [comment]
It looks like it sort of is:

[7/25/2020, 18:27:34] [Hisense] MQTT options: {"keepalive":30,"clientId":"mqttthing_Hisense_846c0baa","protocolId":"MQTT","protocolVersion":4,"clean":true,"reconnectPeriod":1000,"connectTimeout":30000,"will":{"topic":"WillMsg","payload":"Connection Closed abnormally..!","qos":0,"retain":false},"username":"hisenseservice","rejectUnauthorized":false}    

I have more info on my setup in issue #304
