### ISSUE TITLE
Best mqttthing accessory to capture this tele report

### ISSUE THREAD

**Issue by ceraz68** [arachnetech/homebridge-mqttthing#23]
Thanks for this great work and hope someone can provide some help. 

I use a sonoff SV (with tasmota) as garage opener.  I have a reed switch connected to GPIO14 of a sonoff SV configured as Switch2. The main mqtt topic is "svgaragerelay" and the switch2 dedicated mqtt topic is called "garagesensor".

I noticed that the sonoff broadcasts mqtt telemetry messages using the main topic. The second  reports the state of Switch2 (see "Switch2":"OFF"):
21:07:24 MQT: tele/svgaragerelay/STATE = {"Time":"2018-09-23T21:07:24","Uptime":"0T02:05:01","Vcc":3.151,"POWER1":"OFF","Wifi":{"AP":1,"SSId":"XXX","RSSI":100,"APMac":"XXX"}}
21:07:24 MQT: tele/svgaragerelay/SENSOR = {"Time":"2018-09-23T21:07:24","Switch2":"OFF"}

I'm trying to create an mqttthing accessory that is updated based on the reported ON/OFF status of Switch2 in the telemetry messages.

I can't find the right accessory or topic keyword to use. I'm wondering if this is possible as switch2 is embedded in the telemetry message.

Any suggestions ?  Thanks

**Comment by Damontir** [comment]
you could create a normal switch and parse the ON/OFF with 
node-red: mqtt->json(string to object) ->change(msg.payload.Switch2) and than publish it via mqtt to any topic where the switch is listening.... as workaround

**Comment by ceraz68** [comment]
Thanks you gave me the idea to simply use a basic mqtt-sensor plugin and json.parse() the tele message sent from the Sonoff.

this.client.on('message', function (topic, message) {
        data = JSON.parse(message);
       if (data.Switch2 == "ON") etc.
}

Maybe this would be an idea for mqttthing to add an accessory that detects specific JSON keywords in mqtt messages ;-)
