### ISSUE TITLE
Dimmers now Switches

### ISSUE THREAD

**Issue by mkormendy** [arachnetech/homebridge-mqttthing#232]
For some reason all of my light dimmers are now switches. They don’t have a graduated slider anymore, just a on/off toggle. Noticed this after the last update to the latest release.

**Comment by arachnetech** [comment]
That’s unexpected. Are you able to share your configuration?

**Comment by arachnetech** [comment]
Also is this the very latest release (1.1.6)?

**Comment by mkormendy** [comment]
My bad .. I had rewound back to a previous config file to fix something else .. but didn't carry those changes over. Closing this!

**Comment by arachnetech** [comment]
Excellent news, thanks.
