### ISSUE TITLE
Speaker not supported

### ISSUE THREAD

**Issue by Naruk-TUBK** [arachnetech/homebridge-mqttthing#233]
Hi,

i have added a speaker to my configuration. After a restart of homebridge it shows up in home app as not supported device. What ist wrong? (Sorry for Screenshot beeing german)

 `{
     "accessory": "mqttthing",
     "type": "speaker",
     "name": "Stereoanlage",
    "url": "xxx",
     "topics":
     {
         "getMute": "wohnzimmer/avr/mute",
          "setMute": "wohnzimmer/avr/mute/set",
         "getVolume": "wohnzimmer/avr/volume",
         "setVolume": "wohnzimmer/avr/volume/set"
     }
 }`

<img width="303" alt="image" src="https://user-images.githubusercontent.com/40832734/78866393-93d59d80-7a3f-11ea-9af5-e8f2fdb11826.png">

**Comment by tobekas** [comment]
See homebridge/homebridge#1326
Seems like speaker is not supported by Apples Home App, although this service exists.

**Comment by arachnetech** [comment]
Closing as Home app limitation.
