### ISSUE TITLE
Window Covering keeps saying "opening"

### ISSUE THREAD

**Issue by jonasborneland** [arachnetech/homebridge-mqttthing#236]
<img width="116" alt="Screen Shot 2020-04-11 at 11 12 44 PM" src="https://user-images.githubusercontent.com/6105278/79055033-0c0faf00-7c4a-11ea-89a2-eb4576fa1e98.png">
The Homekit keeps being on "opening".
On closing it works fine.

My log looks like its getting the statuses correct:
<img width="913" alt="Screen Shot 2020-04-11 at 11 14 55 PM" src="https://user-images.githubusercontent.com/6105278/79055069-46794c00-7c4a-11ea-8f37-4ae004076f32.png">

My config looks like this:
<img width="411" alt="Screen Shot 2020-04-11 at 11 15 34 PM" src="https://user-images.githubusercontent.com/6105278/79055084-601a9380-7c4a-11ea-896b-3b395618a3a5.png">

**Comment by arachnetech** [comment]
I think you need to decode the JSON object received in the getTargetPosition/getCurrentPosition topic.

**Comment by jonasborneland** [comment]
@arachnetech Thanks for the reply!.. so it should only be a number (int) ? 😊

**Comment by serbasan** [comment]
Look at my settings. Maybe I can help. A greeting.
[](https://github.com/arachnetech/homebridge-mqttthing/issues/238)

**Comment by jonasborneland** [comment]
@serbasan Thanks!!

**Comment by jonasborneland** [comment]
@arachnetech @serbasan I made it work now. Thanks for the help!! 👍 Both an issue with JSON decoding and also some direction issues. As you can see my first config has a "100 - message" to flip the direction - I also had to add this to the two other values... It works awesome now. @arachnetech Thanks for a really nice plugin!

My final config:
`"topics": {
                "getCurrentPosition": {
                    "topic": "/raw/esp8266/5657066/out",
                    "apply": "return (100 -  JSON.parse( message ).position);"
                },
                "getPositionState": "/raw/esp8266/5657066/status",
                "getTargetPosition": {
                    "topic": "/raw/esp8266/5657066/out",
                    "apply": "return (100 -  JSON.parse( message ).set);"
                },
                "setTargetPosition": {
                    "topic": "/raw/esp8266/5657066/in",
                    "apply": "return ( 100 - message );"
                }
            },`
