### ISSUE TITLE
[BUG] when using config UI X Settings on Plugins tab

### ISSUE THREAD

**Issue by produdegr** [arachnetech/homebridge-mqttthing#237]
Hi,
Wanted to test new min and max temp feature and went into the settings form on plugins tab (not the config editor) of config UI X. Set min and max temp and clicked save.
After restart no temp was shown although MQTT was reporting correctly.
Found out that the settings parser did remove the following line from the config.json:
                "getCurrentTemperature": {
                    "topic": "tele/boiler_temp/SENSOR",
                    "apply": "return ((JSON.parse(message).DS18B20.Temperature) + 6);"
                }
so that no temperature would show.

So there must be a small parser problem in the settings code.
Thank You (min max temp is really helpful)

**Comment by arachnetech** [comment]
Hi @produdegr. Unfortunately config-ui-x doesn't support editing of configurations with 'apply' functions, as mentioned at the end of https://www.npmjs.com/package/homebridge-mqttthing#applying-functions-to-mqtt-messages-custom-payload-encodingdecoding (although this probably needs to be made a bit clearer).

This is a config-ui-x limitation.
