### ISSUE TITLE
Shutters in Tasmota 8.2 problem witch topic RESULT and bad solution

### ISSUE THREAD

**Issue by serbasan** [arachnetech/homebridge-mqttthing#238]
Hi. Now with Tasmota 8.2 they have advanced with the blinds. There are changes. We have:

```
MQT: stat / persiana2 / RESULT = {"Shutter1": {"Position": 72, "Direction": 1, "Target": 100}}
MQT: stat / persiana2 / RESULT = {"POWER1": "OFF"}
```

It seems that now the right topic to read status is RESULT.

The problem is that RESULT has two different information and in homebridge logs it gives an error when it reads: 

` stat / persiana2 / RESULT = {"POWER1": "OFF"}`

 because it expects it to be:

` stat / persiana2 / RESULT = {"Shutter1": { "Position": 72, "Direction": 1, "Target": 100}}`

How can I indicate that I am not interested in `stat / persiana2 / RESULT = {"POWER1": "OFF"}`?

In HomeAssitant they have solved it like this:

`cover:
  - platform: mqtt
    name: "Balcony Blinds"
    availability_topic: "tele/%topic%/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    position_topic: "stat/%topic%/RESULT"
    value_template: >
      {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
        {{ value_json.Shutter1.Position }}
      {% else %}
        {% if is_state('cover.balcony_blinds', 'unknown') %}
          50
        {% else %}
          {{ state_attr('cover.balcony_blinds','current_position') }}
        {% endif %}
      {% endif %}    
    position_open: 100
    position_closed: 0
    set_position_topic: "cmnd/%topic%/ShutterPosition1"
    command_topic: "cmnd/%topic%/Backlog"
    payload_open: "ShutterOpen1"
    payload_close: "ShutterClose1"
    payload_stop: "ShutterStop1"
    retain: false
    optimistic: false
    qos: 1`

At the moment I have done a trick (ugly) which is to put teleperiod 10 in Tasmota and this configuration:
```
        {
            "accessory": "mqttthing",
            "type": "windowCovering",
            "name": "Despacho",
            "url": "mqtt://192.168.1.3:1883",
            "topics": {
                "getCurrentPosition": {
                    "topic": "tele/persiana2/SENSOR",
                    "apply": "return JSON.parse(message).Shutter1.Position;"
                },
                "setTargetPosition": "cmnd/persiana2/shutterposition1",
                "getTargetPosition": {
                    "topic": "tele/persiana2/SENSOR",
                    "apply": "return JSON.parse(message).Shutter1.Position;"
                },
                "getPositionState": {
                    "topic": "tele/persiana2/SENSOR",
                    "apply": "return JSON.parse(message).Shutter1.Direction;"
                }
            },
            "positionStateValues": [
                "-1",
                "1",
                "0"
            ],
            "startPub": {
                "cmnd/persiana2/shutterposition1": ""
            }
        },
```
Thanks

**Comment by serbasan** [comment]
I think the correct configuration would be:
        {
            "accessory": "mqttthing",
            "type": "windowCovering",
            "name": "Despacho",
            "url": "mqtt://192.168.1.3:1883",
            "topics": {
                "getCurrentPosition": {
                    "topic": "stat/persiana2/RESULT",
                    "apply": "return JSON.parse(message).Shutter1.Position;"
                },
                "setTargetPosition": "cmnd/persiana2/shutterposition1",
                "getTargetPosition": {
                    "topic": "stat/persiana2/RESULT",
                    "apply": "return JSON.parse(message).Shutter1.Target;"
                },
                "getPositionState": {
                    "topic": "stat/persiana2/RESULT",
                    "apply": "return JSON.parse(message).Shutter1.Direction;"
                }
            },
            "positionStateValues": [
                "-1",
                "1",
                "0"
            ],
            "startPub": {
                "cmnd/persiana2/shutterposition1": ""
            }
        },

But homebridge will complain about what I said earlier:
Note: Target has a problem. If I operate the blinds with the buttons of my hardware switch and for the blind, many times position is not equal to target per unit (position 56 target 57 for example). That makes a status problem always opening or closing. Solution, don't use target and use position:

        {
            "accessory": "mqttthing",
            "type": "windowCovering",
            "name": "Despacho",
            "url": "mqtt://192.168.1.3:1883",
            "topics": {
                "getCurrentPosition": {
                    "topic": "stat/persiana2/RESULT",
                    "apply": "return JSON.parse(message).Shutter1.Position;"
                },
                "setTargetPosition": "cmnd/persiana2/shutterposition1",
                "getTargetPosition": {
                    "topic": "stat/persiana2/RESULT",
                    "apply": "return JSON.parse(message).Shutter1.Position;"
                },
                "getPositionState": {
                    "topic": "stat/persiana2/RESULT",
                    "apply": "return JSON.parse(message).Shutter1.Direction;"
                }
            },
            "positionStateValues": [
                "-1",
                "1",
                "0"
            ],
            "startPub": {
                "cmnd/persiana2/shutterposition1": ""
            }
        },

**Comment by rbswift** [comment]
This works fine for me on tasmota 8.2:
                "setTargetPosition": "cmnd/bedroomshutter/shutterposition",
                "getTargetPosition": "stat/bedroomshutter/SHUTTER1",
                "getCurrentPosition": "stat/bedroomshutter/SHUTTER1",

**Comment by serbasan** [comment]
> Esto funciona bien para mí en tasmota 8.2:
> "setTargetPosition": "cmnd / bedroomshutter / shutterposition",
> "getTargetPosition": "stat / bedroomshutter / SHUTTER1",
> "getCurrentPosition": "stat / bedroomshutter / SHUTTER1",

With that configuration, if you restart homebridge, you lose the position of the blind. How do you solve it with that configuration?

"startPub": { "cmnd/persiana2/shutterposition1": ""  } return in RESULT

**Comment by rbswift** [comment]
see here: https://tasmota.github.io/docs/Blinds-and-Shutters/

"For shutter position to persist in Home Assistant through device reboots, execute PowerRetain 1"

This means that the mqtt broker will retain the latest message for the topic and when homebridge restarts it will receive it from the broker immediately.

**Comment by serbasan** [comment]
PowerRetain 1 in tasmota device does not work if the homebridge is restarted.
What do you put in the hombridge configuration so that it reads that data retained in the mqtt server?
I like more with  "startPub": { }

**Comment by rbswift** [comment]
Yes it can work. I just tested it. I am using Tasmota 8.3 but it should not make a difference. Each time homebridge is restarted it will subscribe to the relevant topic at the mqtt broker (e.g. mosquitto) and the broker will immediately send the most recent (retained) message for that topic. You can test it by running:

`mosquitto_sub -h localhost -t 'stat/persiana2/shutterposition1' -v`

and you should see your current shutter position (0-100)

**Comment by serbasan** [comment]
Ok, powerretain1 is working. I have many blinds and I got the blind wrong.
That's enough. I will continue researching to use all the information from Tasmota 8.2 and know if it is going up or down.

**Comment by ZoneMR** [comment]
FYI, I solved a similar problem (reading Mem1 from the stat only when it's provided) with this hack:

```
"getTargetHeatingCoolingState": {
                    "topic": "stat/garage/heater/RESULT",
                    "apply": "val = JSON.parse(message).Mem1; if(val) this.targetHeatingCoolingState = val; return this.targetHeatingCoolingState;"
                },
```

**Comment by rbswift** [comment]
Thanks @ZoneMR. It would be good to be able to just `return false;` in an `apply` function if the function can't obtain the required value from the `message` object. Maybe there's a technical reason why that's not suitable though.

**Comment by ZoneMR** [comment]
I’d second that feature request - although the behaviour could be ignoring the result if it’s undefined - since false is a valid state for many service characteristics.

**Comment by rbswift** [comment]
fair enough yes return false would have other uses. maybe return undefined or null could be ignored cheers
