### ISSUE TITLE
 Unsupported engine for homebridge-lib@4.5.7

### ISSUE THREAD

**Issue by vgr28** [arachnetech/homebridge-mqttthing#239]
Hello, I received two WARN on installation

1. Unsupported engine for homebridge-lib@4.5.7: wanted: {"homebridg                         e":"~0.4.53","node":"^12.16.2"} (current: {"node":"10.16.0","npm":"6.14.4"})

2.  Not compatible with your version of node/npm: homebridge-lib@4.5                         .7

How can I or your fix it?

**Comment by arachnetech** [comment]
Sounds like the version of homebridge-lib that we're using wants Node.js 12. Are you able to update to this? 

It may not be an issue in reality - I was using Node.js 8 on my home Homebridge until recently.

**Comment by vgr28** [comment]
Sorry, please tell me how than I can do it

 

Von: David Miller [mailto:notifications@github.com] 
Gesendet: Donnerstag, 16. April 2020 16:51
An: arachnetech/homebridge-mqttthing
Cc: vgr28; Author
Betreff: Re: [arachnetech/homebridge-mqttthing] Unsupported engine for homebridge-lib@4.5.7 (#239)

 

Sounds like the version of homebridge-lib that we're using wants Node.js 12. Are you able to update to this?

It may not be an issue in reality - I was using Node.js 8 on my home Homebridge until recently.

**Comment by abrownsword** [comment]
I'm trying to install (on Debian using apt) and am getting these messages (similar to what is above):

```npm WARN notsup Unsupported engine for homebridge-lib@4.7.16: wanted: {"homebridge":"^1.1.0","node":"^12.19.0"} (current: {"node":"14.15.1","npm":"6.14.9"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.7.16
```

Is this an issue?

**Comment by arachnetech** [comment]
As I understand it, homebridge-lib (part of homebridge) is saying that it might cause issues. I'd advise updating your Node.js if you can. https://nodejs.org/en/download/package-manager/

**Comment by abrownsword** [comment]
Have been trying to follow the instructions (and numerous variations), but still getting this error.  Here are the versions I have installed... seems like it ought to be recent enough?

```root@host:/home/a# npm list -g 
/usr/lib
├── homebridge-config-ui-x@4.35.0
├── homebridge-lib@5.0.0
├── homebridge@1.1.6
└── npm@7.0.14

root@host:/home/a# node --version
v15.3.0

root@host:/home/a# npm install -g homebridge-mqttthing
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge-lib@4.7.16',
npm WARN EBADENGINE   required: { homebridge: '^1.1.0', node: '^12.19.0' },
npm WARN EBADENGINE   current: { node: 'v15.3.0', npm: '7.0.14' }
npm WARN EBADENGINE }

added 154 packages, and audited 154 packages in 7s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@host:/home/a# 
```
