### ISSUE TITLE
Enhancement: Battery Level

### ISSUE THREAD

**Issue by GSanCap** [arachnetech/homebridge-mqttthing#24]
A good enhancement must be a topic for get the battery percent of an accessory, for example, i use zigbee2mqtt for connect the Xiaomi  Human Body Movement Sensor with MQTT, this software expose, also, the percent of battery life of the device in the JSON response.
If the plugin will support a topic for that will be great!
Now days i just use the low battery feature

Regards

**Comment by tobekas** [comment]
Hi,
to show battery level, one has to attach an additional “BatteryService”, which can contain characteristics like “BatteryLevel”, “ChargingState”, “StatusLow” to the accessory. This is different to the already available “StatusLow”, which is part of the “AccessoryInformationService”.

Best regards

**Comment by arachnetech** [comment]
Thanks, tobekas.

Added in 1.0.19.
