### ISSUE TITLE
Feature request - Sprinkler System

### ISSUE THREAD

**Issue by greg-bianchi** [arachnetech/homebridge-mqttthing#240]
Good afternoon, I am new to github and to post things. I hope I am doing right.

What I am requesting is an accessory that resembles the Sprinkler System on Home App.
A company, Rachio, released a compatible hardware few months ago. It would be greato to build an accessory with multiple zones, for watering the garden, all connected to a single accessory.

If someone can instruct me how to implement and what code is required for mqttthing implementation, I can contribute to it.
I am not new to programming, in the past I did a lot of websties with PHP, JS, CSS, SQL, HTML etc. but I am totally new to this platform and to Homebridge in general.

Here a link to an article of what I am talking about:
https://9to5mac.com/2018/09/25/rachio-3-homekit/

**Comment by tobekas** [comment]
I think I could implement this in the near future. I already played around with this some time ago bud did not published it yet. One have do deal with an IrrigationSystem Service and some Valve Services, which has to be linked to the IrrigationSystem.

For every zone (Valve service) there must be a mqtt topic pair: „active“ (on/off command) and „inUse“ (water is flowing).
One thing to clarify is how to handle with the main „active“ and „inUse“ characteristic. The main „inUse“ must be set, if any zone is in use. So maybe this should be detected automatically in this plugin and we do not need a separate topic for main-„inUse“.

**Comment by arachnetech** [comment]
Thanks, @tobekas - great if you have time.

**Comment by tobekas** [comment]
@greg-bianchi: Can you try code from my fork on branch "IrrigationSystem":
https://github.com/tobekas/homebridge-mqttthing/tree/IrrigationSystem

After some discussion we could merge this into the main project...

**Comment by tobekas** [comment]
Documentation is still missing... but you can see an example in `test/config.json` at the bottom.

**Comment by greg-bianchi** [comment]
@tobekas Hi, thank you for your work! For what I have tested, on my iPhone it works correctly!
Here is what I've done (as said, I am new to github so I don't know if this is the correct way): I manually changed the index.js , mqttlib.js files inside my plugin folder, and added the config as suggested. Then restarted homebridge. It is working , on Home app I can see the new sprinkler. Great!
There are a couple of strange behaviours:
- I added the config as you posted, with three zones. And actually on Home app I see the text "4 not active). In fact, it is as if the system itslef is counted as a sprinkler.
If I activate one sprinkler through mqtt, I see "2 active, 2 not active".
- Second, the mqtt settings for the zones are missing from the GUI of "homebridge-config-ui-x". Zones are of course adjustable via config file, but their setting is not present in the "user friendly" graphical menu that can be reached via "settings" button of the plugin

**Comment by tobekas** [comment]
- I could not see this with my device. Where do you see the text with the number of active devices? Can you post a screenshot?
- The second point is right, this has not yet been configured. Config-Ui-x option must be additionally specified. This will probably still come, but I’m not yet so familiar with these config schema.

Side note: For quick testing, it has been proven to set the getInUse topic to the same as setActive. Thus, inUse does not always have to be we by hand. Later with the real device it should be separated.

**Comment by greg-bianchi** [comment]
Well... actually I really don't know what happened! Yesterday I could see the number of active and not active zones. Now they are disappeared.
I saw them on the bottm line of the square tile inside Home app.
I think that it was like a sort of glitch or bug inside Home app, because I added zones by changing Homebridge config on the fly and restarting it, without closing app on my iPhone. The homebridge accessories go to "not responding" state and then back online. When this happens, it probably makes confusion with the zones count if I change the number on the fly, without closing Home app.

Problem solved. Bug is not inside Mqttthing I think.

As far as I can tell this accessory is functioning in the correct way

**Comment by EjvindHald** [comment]
@tobekas I am quite surprised by the speed, where you can implement new functionality. If you are interested in adding a completely new accessory type, then I made this #185 post.
Thanks for your many contributions including the history in mqtt which I use a lot.

**Comment by tobekas** [comment]
Available in version 1.1.14
