### ISSUE TITLE
rgb and brightness

### ISSUE THREAD

**Issue by zulu14** [arachnetech/homebridge-mqttthing#241]
hello,
im a manager of scintillement lighting technology,
we have found few days ago your great plugin.

but my team has an issues with it, 

we need to control a "lightbulb" (its a custom light on scintillement product project)

when the setON params and the setBrightness params has set, 
the on/off topic are Ok
and the brightness topic are OK
but when we add a color (SETRGB)
the brightness not working, and the brightness are apply by a mix of RGB values.

json with on/off and Brightness work but not color config
{
            "accessory": "mqttthing",
            "plugin_map": {
                "plugin_name": "homebridge-mqttthing",
                "index": 0
            },
            "type": "lightbulb",
            "url": "mqtt.scintillement.fr",
            "username": "MQTT1",
            "name": "bureau",
            "password": "836k4s260l4w5x746zrtvbk",
            "topics": {
                "setOn": {
                    "topic": "scintillement_*21102840*/in",
                    "apply": "return 'on' + message"
                },
                "setBrightness": {
                    "topic": "scintillement_*21102840*/in",
                    "apply": "return 'br' + message"
                },
                "getOnline": "scintillement_*21102840*/out"
            },
            "onlineValue": "OK",
            "onValue": "%255",
            "offValue": "%0",
            "otherValueOff": true,
            "hexPrefix": "#",
            "hex": true
        }

json with on/off and color  work but Brightness d'ont working.

{
            "accessory": "mqttthing",
            "plugin_map": {
                "plugin_name": "homebridge-mqttthing",
                "index": 0
            },
            "type": "lightbulb",
            "url": "mqtt.scintillement.fr",
            "username": "MQTT1",
            "name": "bureau",
            "password": "836k4s260l4w5x746zrtvbk",
            "topics": {
                "setOn": {
                    "topic": "scintillement_*21102840*/in",
                    "apply": "return 'on' + message"
                },
                "setBrightness": {
                    "topic": "scintillement_*21102840*/in",
                    "apply": "return 'br' + message"
                },
                "setRGB": {
                    "topic": "scintillement_*21102840*/in",
                    "apply": "return 'RGB' + message"
                },
                "getOnline": "scintillement_*21102840*/out"
            },
            "onlineValue": "OK",
            "onValue": "%255",
            "offValue": "%0",
            "otherValueOff": true,
            "hexPrefix": "#",
            "hex": true
        }

**Comment by arachnetech** [comment]
`setRGB` isn't for controlling colour; it's for controlling the red, green and blue levels (e.g. of an RGB strip) so also controls brightness and saturation. If you want colour irrespective of brightness and saturation you'll need to use `setHue` and convert this to RGB values yourself.
