### ISSUE TITLE
Heater Cooler -  getRotationSpeed

### ISSUE THREAD

**Issue by drschnalli** [arachnetech/homebridge-mqttthing#242]
Hello, can you tell me which values   "getRotationSpeed" is expecting? 

For the set command i'm using this and it works:

```
"setRotationSpeed": {
                "topic": "aircon/command/fan_speed",
                "apply": "return [ 'low', 'medium', 'max', 'auto' ][ Math.floor( message / 25 ) ];"
```
 So for Every 25% it will change to the next value.
But the Get command is not working. I set the topic to "aircon/status/fan_speed" but i dont know which values it's expecting. How can i manage to recalculate low,medium,max,auto to the percentages so that a change will also getting displayed in my Homekit App (when i change it from elsewhere)

**Comment by arachnetech** [comment]
Fan rotation speed is an integer between 0 (off) and 100 (full speed).

You should be able to use something like:

`return { low: 33: medium: 66, max: ‘100’ }[ message ];`

... in your apply function to map a received `low`, `medium` or `max` back to integer values of 33, 66 and 100 respectively. (I’m not sure that your outgoing mapping is quite right: it will map 0-24 to low, 25-49 to medium, 50-74 to max and 75-99 to auto if I’ve read that right.)
