### ISSUE TITLE
offline not working with "onValue" and "offValue" 

### ISSUE THREAD

**Issue by oigroigm** [arachnetech/homebridge-mqttthing#243]
offline it doesn't seem to work with "onValue": "ON" and "offvalue": "OFF" set

{
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Luce",
            "topics": {
                "getOn": "stat/sonoff/POWER",
                "setOn": "cmnd/sonoff/power",
                "getOnline": "tele/sonoff/LWT"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "onlineValue": "Online"
}

i already tried to restart homekit
to make it work I have to set it up like this

{
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Luce",
            "topics": {
                "getOn": "stat/sonoff/POWER",
                "setOn": "cmnd/sonoff/power",
                "getOnline": {
                    "topic": "tele/sonoff/LWT",
                    "apply": "return  ((message == 'Online') ? 'ON' : 'OFF');"
                }
            },
            "onValue": "ON",
            "offValue": "OFF",
}

**Comment by arachnetech** [comment]
Glad you found a solution.

What value gets published to `getOnline` when your accessory goes offline? I think your first config would only work if the offline value is ‘OFF’, whereas your second config will go offline is anything other the `ON` is received. You might have been able to fix your first config by also configuring an appropriate `offlineValue` (a configuration setting which seems to have missed being documented). Perhaps mqttthing should treat any value other than the configured `onlineValue` as _offline_ when `offlineValue` isn’t configured explicitly?

**Comment by oigroigm** [comment]
thanks, I didn't know about the existence of _offlineValue_, this solves my problem and then everything seems to work

**Comment by arachnetech** [comment]
Thanks, closing.
