### ISSUE TITLE
How do I change the power consumption refresh interval?

### ISSUE THREAD

**Issue by 0neiro** [arachnetech/homebridge-mqttthing#244]
I'm using tasmota flashed outlets and the refresh interval for the power consumption seems very high. In the EVE app I see the last value for exactly 5 minutes.

How can I change the refresh interval? The tasmota webpage shows the consumption very precisely.

Here is my config:

{
                        "accessory": "mqttthing",
                        "type": "outlet",
                        "name": "SP22-3",
                        "url": "mqtt://127.0.0.1",
                        "topics": {
                                "getOn": "stat/sp22-3/POWER",
                                "setOn": "cmnd/sp22-3/power",
                                "getInUse": "tele/sp22-3/STATE",
                                "getWatts": {
                                        "topic": "tele/sp22-3/SENSOR",
                                        "apply": "return JSON.parse(message).ENERGY.Power;"
                                        },
                                "getVolts": {
                                        "topic": "tele/sp22-3/SENSOR",
                                        "apply": "return JSON.parse(message).ENERGY.Voltage$
                                        },
                                "getAmperes": {
                                        "topic": "tele/sp22-3/SENSOR",
                                        "apply": "return JSON.parse(message).ENERGY.Current$
                                        }
                        },
                        "history": true,
                        "logMqtt": true,
                        "onValue": "ON",
                        "offValue": "OFF"
                },

**Comment by tobekas** [comment]
So you mean a refresh interval for the current value or for the history consumption?

**Comment by 0neiro** [comment]
The current value.

**Comment by tobekas** [comment]
Ok. The power value should actually update as soon as a new mqtt message arrives. It may be that the Eve app does not always update the displayed value directly.  Sometimes updating (swiping up) or restarting the app helps. From the perspective of HomeKit and of this plugin, the value should at least be updated directly.

**Comment by tobekas** [comment]
5min mqtt update rate is default in Tasmota. Try to change Tasmota‘s telemetry options: https://tasmota.github.io/docs/devices/Sonoff-Pow/#telemetry

**Comment by 0neiro** [comment]
That's exactly what I was looking for. Thank you for your help!
