### ISSUE TITLE
Homekit not triggering state change for devices

### ISSUE THREAD

**Issue by HumanSkunk** [arachnetech/homebridge-mqttthing#246]
I am having a bit of trouble getting this to work exactly how i want it. I have flashed 2 Sonoffs with Tasmota 8.2.0 and installed and configured MQTT Mosquitto and configured the Sonoffs to react to the published commands from the Mosquitto broker. Lights and Switches correctly appear within the Home App.

My Config is below within the Homebridge conf file

`   {
            "type": "lightbulb-OnOff",
            "name": "Cabinet Lights",
            "logMqtt": true,
            "topics": {
                "getOn": "stat/Cabinet_Lights/Power",
                "setOn": "cmnd/Cabinet_Lights/Power"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "accessory": "mqttthing"
        },
        {
            "type": "outlet",
            "name": "Test Lights",
            "topics": {
                "getOn": "stat/Test_Lights/Power",
                "setOn": "cmnd/Test_Lights/Power"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "accessory": "mqttthing"
        }`

When i send the command

`mosquitto_pub -h 192.168.0.180 -t cmnd/Cabinet_Lights/POWER -m on`

the sonoff will turn on as expected. Sending with the message Off, will also cause it to behave as expected.

When i toggle the switch within the Home app on the iPhone i can see the command being sent by the homebridge plugin in the log file but it does not change the state of the switch.

`[4/19/2020, 9:53:05 AM] [Cabinet Lights] Publishing MQTT: cmnd/Cabinet_Lights/Power = ON
[4/19/2020, 9:53:06 AM] [Cabinet Lights] Publishing MQTT: cmnd/Cabinet_Lights/Power = OFF`

The difference in the logs is i am not seeing a received message from the sonoff itself.

I still am not entirely sure what is wrong here, but considering the only part that isnt working correctly is this homebridge plugin may mean something isnt working as expected.

Any help would be much appreciated as i am currently banging my head against a wall...

**Comment by tobekas** [comment]
Maybe you forgot to configure the broker's URL? It may default to localhost.

**Comment by arachnetech** [comment]
Or because you have a lowercase `on` in your `mosquitto_pub` command, but uppercase `ON` and `OFF` in your config?

**Comment by HumanSkunk** [comment]
> Maybe you forgot to configure the broker's URL? It may default to localhost.

Thanks for responding. Are you referring to the broker URL in the Sonoff config? or within the MQTTThing config? The former is definitely set, the latter the MQTT server is on the same device as Homebridge Server (Raspberry Pi Zero). I will update it in the config just to check.

**Comment by HumanSkunk** [comment]
> Or because you have a lowercase `on` in your `mosquitto_pub` command, but uppercase `ON` and `OFF` in your config?

I will try this but when i sent 'On' or 'ON' using the mosquitto_pub command (on the Pi) it works with either. It is a good idea though. I will check it and report back.

**Comment by HumanSkunk** [comment]
Are you f**king kidding me! It was the URL missing. Thought it wasn't that because both the Homebridge Server and Mosquitto were on the same device. It now works.

Thanks very much.
