### ISSUE TITLE
Enhancement: Fake ElGato Support

### ISSUE THREAD

**Issue by GSanCap** [arachnetech/homebridge-mqttthing#25]
Some accessories, like move sensor, temperature, humidity, power consumption, etc. can be more useful if support the ElGato Feature or store historical data.

Thanks in advance!

**Comment by arachnetech** [comment]
What changes/enhancements would be required to mqtt-thing for this?

**Comment by GSanCap** [comment]
For example, the Aqara Switches reports "consumption" data, you can use ElGat support to store this values to obtain consumption graphs in Eve application, the same with temperature, humidity sensors, for example with the movement (presence) sensor in Eve if the sensor use ElGato you can view a timeline with the movement triggers


![](https://blog.evehome.com/wp-content/uploads/2017/05/050_EN_abb05.png)

Thanks in advance!

**Comment by arachnetech** [comment]
I agree that would be extremely useful, but unfortunately homebridge-mqttthing is just interfacing between MQTT-using accessories and Homebridge, which itself exposes state and control to Homekit. This would seem something best-implemented in Homekit (by Apple), or possibly implemented in a Homebridge add-on. However, I don't think it's relevant to homebridge-mqttthing.
