### ISSUE TITLE
Missing message attribute in startPub object breaks homebridge

### ISSUE THREAD

**Issue by LaserPew** [arachnetech/homebridge-mqttthing#253]
Via Homebridge Config UI X I configured a lightbulb accessory and set the `startPub` topic to `example` but left the value empty. This generates the following config:

```
{
 ...,
  "startPub": [
    {
      "topic": "example"
    }
  ],
  ...
}
```

When restarting homebridge it appears to start without errors (nothing in the logs) but the Home apps shows all accessories as not responding. When setting the `"message": ""` it works.

**Comment by arachnetech** [comment]
Thanks. Fixed in 1.1.11.
