### ISSUE TITLE
4 Button Remote via RF Bridge Config Help Plz...

### ISSUE THREAD

**Issue by JimmyEyeball** [arachnetech/homebridge-mqttthing#257]
Some help would really be appreciated with the config for a Sonoff 4 Button RF Remote via a Sonoff RF Bridge ... Can see the remote ok so I am assuming it's my config that is the issue why I'm getting no response and would really appreciate a 2nd opinion.....

 Both Topic as Received by Buttons and Config Below...

05:34:32 MQT: tele/RF/RESULT = {"Time":"2020-05-03T05:34:32","RfReceived":{"Sync":11030,"Low":380,"High":1080,"Data":"A56021","RfKey":"None"}}

{
		"accessory": "mqttthing",
		"type": "statelessProgrammableSwitch",
		"name": "4 Button Remote",
		"url": "mqtt://192.168.1.173",
		"username": "1111",
		"password": "1111",
		"caption": "4 Button Remote",
		"topics": {
			"getSwitch": [
				"tele/RF/RESULT",
				"tele/RF/RESULT",
				"tele/RF/RESULT",
				"tele/RF/RESULT"
			]
		},
		"switchValues": [
			"A56021",
			"A56022",
			"A56028",
			"A56024"
		],
		"restrictSwitchValues": [0]
	}

**Comment by arachnetech** [comment]
You'll need an apply function or codec to extract the `Data` from the JSON messages that you're receiving.

I think for a multiple-switch switch your `switchValues` needs to be an array of arrays.

**Comment by arachnetech** [comment]
This works for me:

```json
        {
            "accessory": "mqttthing",
            "type": "statelessProgrammableSwitch",
            "name": "4 Button Remote",
            "url": "http://192.168.10.35:1883",
            "caption": "4 Button Remote",
            "topics": {
                "getSwitch": [
                    { 
                        "topic": "tele/RF/RESULT",
                        "apply": "return JSON.parse( message ).RfReceived.Data;"
                    }, { 
                        "topic": "tele/RF/RESULT",
                        "apply": "return JSON.parse( message ).RfReceived.Data;"
                    }, { 
                        "topic": "tele/RF/RESULT",
                        "apply": "return JSON.parse( message ).RfReceived.Data;"
                    }, { 
                        "topic": "tele/RF/RESULT",
                        "apply": "return JSON.parse( message ).RfReceived.Data;"
                    }
                ]
            },
            "switchValues": [
                [ "A56021" ],
                [ "A56022" ],
                [ "A56028" ],
                [ "A56024" ]
            ],
            "restrictSwitchValues": [
                0
            ],
            "logMqtt": true
        }
```

**Comment by JimmyEyeball** [comment]
Tried and Tested Perfect Thank You VERY much......

**Comment by arachnetech** [comment]
Excellent, thanks for letting me know!
