### ISSUE TITLE
Compatibility with Homebridge 1.0.1

### ISSUE THREAD

**Issue by udovic2100** [arachnetech/homebridge-mqttthing#259]
How’s the plugin’s compatibility with the new major homebridge release? According to the list in the hombridge [wiki](https://github.com/homebridge/homebridge/wiki/Homebridge-Plugin-Status) it’s not supported yet.

**Comment by arachnetech** [comment]
Working for me. I'm not sure whether plugin developers are expected to update that page. I haven't been, but perhaps I should have...

I think as a validated plug-in, some testing is done by the Homebridge developers themselves too.

I will try to investigate further when I have more time. In the meantime, please do raise an issue if you encounter any problems.

**Comment by NorthernMan54** [comment]
I’m using it with some outlets and lightbulbs and no issues with the latest homebridge version.

**Comment by EjvindHald** [comment]
I tested it to be working very fine before upgrading and I also added a line with my findings in the very same wiki page you are referring to.

**Comment by arachnetech** [comment]
Thanks, @EjvindHald ! :-)
