### ISSUE TITLE
Accessory not showing up in app

### ISSUE THREAD

**Issue by box99h** [arachnetech/homebridge-mqttthing#262]
Hello,

I'm currently working on a project to post the sensor data of my power meter into HomeKit using the "outlet" accessory. 
As the power meter is read-only I somehow need to fake getOn, SetOn and getInUse values. 
The sensor data is received via a node red instance and send to a MQTT mosquitto server. GetOn, SetOn and getInUse are injected as boolean "true" using the inject node in node red.

This is my config.json in Homebridge:

```json
{
	"bridge": {
		"name": "Homebridge_Test2",
		"username": "CC:22:3D:D9:CE:31",
		"port": 5334,
		"pin": "031-45-144"
	},
	"description": "Home Smart Home",
	"platforms": [],
	"accessories": [{
		"type": "outlet",
		"name": "stromz",
		"mqttPubOptions": {
			"retain": true
		},
		"topics": {
			"getInUse": "verbrauch/InUse",
			"getOn": "verbrauch/GetOn",
			"setOn": "verbrauch/SetOn",
			"getWatts": "verbrauch/wert"
		},
		"history": "true",
		"onValue": "true",
		"offValue": "false",
		"mqttOptions": {
			"keepalive": 30
		},
		"logMqtt": true,
		"confirmationPeriodms": 1000,
		"accessory": "mqttthing"
	}]
}
```

I can see the values in Homebridge journalctl. But adding the Homebridge instance to the app is failing with an error "Couldn't add ... Home couldn't connect to this device".

As soon as I put another accessory in the config.json and delete the mqttthing outlet home is able to connect. Therefore something must be wrong with my mqtttthing configuration. 

I also tried mqttthing temperature sensor and it worked fine.

Hope someone can help.

**Comment by arachnetech** [comment]
I think the `url` config setting may be required even though it's marked as optional. I will check later, but you may wish to try adding: `"url": "http://localhost:1883"` to your configuration in the meantime.

**Comment by box99h** [comment]
Unfortunately adding the url didn't help. 
But MQTT Channels are received and can be monitored on the Homebridge journal

Mai 10 10:18:07 hbridge2 homebridge[9249]: [2020-5-10 10:18:07] [stromz] Received MQTT: verbrauch/wert = 2459.5
Mai 10 10:18:08 hbridge2 homebridge[9249]: [2020-5-10 10:18:08] [stromz] Received MQTT: verbrauch/geton = ON
Mai 10 10:18:08 hbridge2 homebridge[9249]: [2020-5-10 10:18:08] [stromz] Received MQTT: verbrauch/inuse = ON
Mai 10 10:18:08 hbridge2 homebridge[9249]: [2020-5-10 10:18:08] [stromz] Received MQTT: verbrauch/wert = 2454.3
Mai 10 10:18:10 hbridge2 homebridge[9249]: [2020-5-10 10:18:10] [stromz] Received MQTT: verbrauch/wert = 2451.8
Mai 10 10:18:11 hbridge2 homebridge[9249]: [2020-5-10 10:18:11] [stromz] Received MQTT: verbrauch/wert = 2461

Meanwhile I've tried to change the OnValue to "ON" and the OffValue to "OFF", also without success.

**Comment by arachnetech** [comment]
If mqttthing isn’t causing Homebridge to crash, there’s really nothing it can do that would affect adding it to the Home App.

However, once you’ve added it (which I think you said you could do with a different config), you can add new accessories without re-adding it. This will show up in the Home app automatically.

If you have multiple Homebridge instances don’t forget to set different usernames and pins.

**Comment by box99h** [comment]
Yes I can add a new instance using mqttthing e.g. temperature sensor. But mqttthing outlet is not showing up in the app, even if it is added subsequently.
Different usernames and pins are used.

I assume there is something wrong with setOn, getOn or getInUse statements.

**Comment by arachnetech** [comment]
Working fine for me with:

```json
    "accessories": [{
		"type": "outlet",
        "name": "stromz",
        "url": "http://192.168.10.35:1883",
		"mqttPubOptions": {
			"retain": true
		},
		"topics": {
			"getInUse": "verbrauch/InUse",
			"getOn": "verbrauch/GetOn",
			"setOn": "verbrauch/SetOn",
			"getWatts": "verbrauch/wert"
		},
		"history": "true",
		"onValue": "true",
		"offValue": "false",
		"mqttOptions": {
			"keepalive": 30
		},
        "logMqtt": true,
        "confirmationPeriodms": 1000,
		"accessory": "mqttthing"
    }
```

... although I did have to restart my iPad. Homebridge became unresponsive and wouldn't recognize anything. I've had this a few times before. Usually force-quitting the Home app is sufficient, but sometimes it seems to need a full restart to get things working again.

However, there's nothing wrong with your configuration as far as I can tell.

**Comment by arachnetech** [comment]
![Uploading 81495240...]()

**Comment by arachnetech** [comment]
![image](https://user-images.githubusercontent.com/24389384/81495249-edcbbc00-92a6-11ea-9bf5-1c5ba510a3a1.png)

**Comment by arachnetech** [comment]
```
[5/10/2020, 10:07:06] Homebridge is running on port 55555.
[5/10/2020, 10:07:06] [Config] Homebridge Config UI X v4.16.0 is listening on :: port 8080
[5/10/2020, 10:07:31] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:07:32] [stromz] Setting accessory state to offline
[5/10/2020, 10:07:32] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:07:33] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:07:34] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:07:35] [stromz] Unresponsive - no confirmation message received on verbrauch/GetOn. Expecting [true].
[5/10/2020, 10:07:53] [stromz] Received MQTT: verbrauch/GetOn = true
[5/10/2020, 10:07:58] [stromz] Received MQTT: verbrauch/GetOn = false
[5/10/2020, 10:08:02] [stromz] Received MQTT: verbrauch/GetOn = true
[5/10/2020, 10:08:03] [stromz] Publishing MQTT: verbrauch/SetOn = false
[5/10/2020, 10:08:04] [stromz] Publishing MQTT: verbrauch/SetOn = false
[5/10/2020, 10:08:05] [stromz] Publishing MQTT: verbrauch/SetOn = false
[5/10/2020, 10:08:06] [stromz] Publishing MQTT: verbrauch/SetOn = false
[5/10/2020, 10:08:07] [stromz] Unresponsive - no confirmation message received on verbrauch/GetOn. Expecting [false].
[5/10/2020, 10:08:07] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:08:08] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:08:09] [stromz] Received MQTT: verbrauch/GetOn = true
[5/10/2020, 10:08:09] [stromz] Setting accessory state to online
[5/10/2020, 10:08:12] [stromz] Publishing MQTT: verbrauch/SetOn = false
[5/10/2020, 10:08:13] [stromz] Received MQTT: verbrauch/GetOn = false
[5/10/2020, 10:10:53] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:10:54] [stromz] Setting accessory state to offline
[5/10/2020, 10:10:54] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:10:55] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:10:56] [stromz] Publishing MQTT: verbrauch/SetOn = true
[5/10/2020, 10:10:57] [stromz] Unresponsive - no confirmation message received on verbrauch/GetOn. Expecting [true].
[5/10/2020, 10:10:57] [stromz] Received MQTT: verbrauch/GetOn = true
```

Note that I'm manually publishing to `verbrauch/GetOn`, otherwise the device goes unresponsive because you have confirmation turned on (`"confirmationPeriodms": 1000,`)

**Comment by box99h** [comment]
Thank you very much for your effort.
After a step by step analysis I can report that getWatts is causing the problem.
Meanwhile I was able to get the outlet available in the app. But the Homebridge instance becomes unresponsive in the moment I add "getWatts".

**Comment by arachnetech** [comment]
Most odd. @tobekas Do you have any idea why this might upset Homekit? It’s fine in my test setup.

**Comment by tobekas** [comment]
Puh... no idea so far.
Does it work with getWatts and history=false? Strange if just getWatts would be the issue.
Which version of Homebridge do you use?

**Comment by box99h** [comment]
Setting history to false also doesn't work. I haven't finished testing but it seems any of the additional parameters like Watts, Amperes, etc. will crash the instance. 
Homebridge is 1.0.4
I assume that there is no need to have getVolts, getAmperes and getTotalConsumption defined when using getWatts?
Does getWatts expect a specific format? 

For testing I've triggered lightssensors "getCurrentAmbientLightLevel" using the "watts" value and it's working.

**Comment by tobekas** [comment]
There is no need to have getVolts, getAmperes and getTotalConsumption defined. getWatts expects a simple float string, so "2454.3" should be fine.
It will add a custom characteristics (not specified by apple) to this outlet service. But this should not be a problem, since Eve’s devices also do this.

Maybe something changed with the new homebridge release. 

Sehr merkwürdig...

**Comment by box99h** [comment]
Thank you very much for your assistance. Float string is delivered, so that's not the problem :-(.
Yeah it's really strange.

**Comment by tobekas** [comment]
Now, I also tested your configuration with Homebridge 1.0.4 and Homebridge-Mqttthing 1.1.12 
--> everything is working fine.

Can you try to unpair your homebridge instance, delete the persist folder (cache), change your main homebrige username and/or pin in config.json and re-pair it. Sometime Homekit will completely block your environment, if at any time there was an incorrect configuration. Even with a corrected configuration, it still remains blocked.

Otherwise, I have no further idea.
But your problem is actually that with "getWatts" the whole bridge will be broken, so all bridged accessories do not respond, and without "getWatts" everything is fine?
So it has nothing to do with "confirmationPeriodms", which will mark an accessory as offline und so does not respond (as a feature), if a confirmation message was missing.

Question to @arachnetech: How do you actually get a device back online after a missing confirmation message, if you don't use getOnline explicitly? It seems that the device will be shown as "not responding" for all eternity.

**Comment by arachnetech** [comment]
@tobekas You're quite right: currently a device will only go online if it receives the correct confirmation message before it's given up resending the `set` message. Once it times out, there's no way to get it online again. I'll change this so that **any** later message to the `get` topic will set it online again.

You can turn off the 'automatic offline' thing by setting `confirmationIndicateOffline` to `false`, which is probably advisable at the moment if using `confirmationPeriodms`.

David

**Comment by box99h** [comment]
Ok. I've cleaned the persists and the accessories folder. Edited config using new name, username, pin and port.

As long the config.json has the "getWatts" statement Home isn't able to connect to this instance. After removing "getWatts" I can connect and all accessories are working. Stopping the instance again and adding the "getWatts" statement will stop responding all accessories linked to that bridge. Removing the "getWatts" statement will bring all accessories linked to that bridge back to life.

**Comment by tobekas** [comment]
can you call `npm ls --depth=0` in your mqttthing folder, to see if all the dependencies are installed correctly?
This should output:
```
homebridge-mqttthing@1.1.12 /YOUR-PATH-TO-homebridge-mqttthing
├── fakegato-history@0.5.6
├── homebridge-lib@4.5.4
└── mqtt@2.18.8
```

I have tested it again with both iOS12 and iOS13 on iPhone. Both times it works perfectly with "getWatts". I am running out of ideas.

**Comment by box99h** [comment]
homebridge-mqttthing@1.1.12 /usr/local/lib/node_modules/homebridge-mqttthing
├── fakegato-history@0.5.6
├── homebridge-lib@4.7.0
└── mqtt@2.18.8

**Comment by tobekas** [comment]
Hm. My homebridge-lib was older. I updated, but 4.7.0 is still doing fine.

The issue seems to be related to #261
This seems to be strange, too.

Ah... please try history = false ( not history = "false")

What else could make the difference between your environment and ours? Node.js version?

**Comment by box99h** [comment]
`"history": false` doesn't solve the issue as well.

Node.js is running in Version 12.16.3. I remember that this node version was requested during installation by Homebridge-lib.

**Comment by box99h** [comment]
OK. I've installed a complete new Homebridge instance on another RPI and now it's working. There must be some glitch with my Homebridge installation. For the moment I will keep this as an interim solution.

Many thanks for all your effort. Great work!
