### ISSUE TITLE
online / offline status no longer working?

### ISSUE THREAD

**Issue by rbswift** [arachnetech/homebridge-mqttthing#265]
Using the following config I don't get to see the device offline (Not Responding) in Apple Home any more. I am pretty sure it used to work.

```
        {
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Stairs Lights",
            "topics": {
                "setOn": "cmnd/stairslight/POWER",
                "getBrightness": {
                    "topic": "stat/stairslight/RESULT",
                    "apply": "return JSON.parse(message).Dimmer;"
                },
                "setBrightness": "cmnd/stairslight/DIMMER",
                "getOn": "stat/stairslight/POWER",
                "getOnline": "tele/stairslight/LWT"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "onlineValue": "Online",
            "offlineValue": "Offline",
            "logMqtt": true
        },
```
I can see the device mqtt going online and offline:

```
# mosquitto_sub -h localhost -t 'tele/stairslight/LWT' -v
tele/stairslight/LWT Online
tele/stairslight/LWT Offline
tele/stairslight/LWT Online
```

Thanks for any suggestions!

**Comment by tobekas** [comment]
The "not responding" state is not updated immediately. This feature is a little hack... but there is no other possibility to achieve anything similar.
It will be visible after closing and reopening the App or sometimes by switching the room view. The trick is to respond to a get request from the App with an exception. But this is only possible when there *is* a get request.

**Comment by rbswift** [comment]
Great. thanks for the explanation. I've created a pr to add it to the documentation for others
