### ISSUE TITLE
show remaining time in Home-App

### ISSUE THREAD

**Issue by jnbht** [arachnetech/homebridge-mqttthing#266]
Hi! 
Amazing plugin and work!
Is it possible to get the Home-App show the remaining time, when Valve/Sprinkler ist used?

Now the Square shows 1. Room 2. Name 3. Off/Inactive

Inactive is not nessecary and it would be nice if in its place the timer is shown.

Thx for this great tool!

**Comment by tobekas** [comment]
Hi. It’s not possible to show the remaining time within the tile. This cannot be changes by homebridge. It’s up to the UI design of the Controller App, which is used.

Remaining time is shown in the detail view like this:
![](https://9to5mac.com/wp-content/uploads/sites/6/2018/06/homekit-sprinkler.jpeg)
