### ISSUE TITLE
Air Quality Not Changing in Air Quality Sensor

### ISSUE THREAD

**Issue by ODMerdin** [arachnetech/homebridge-mqttthing#272]
Hello,

I am using MQ135 and DHT21 sensors with ESP8266 for the air quality sensor. According to the ppm value, I am sending 1,2,3,4,5 to the " :"getAirQuality": "salon/salonkalite"," but nothing changes and it says unknown in the homekit tile. I can see the ppm, humidity, and temperature values change. On the esp side with serial.print and on mqttspy I can see the values change for the "salon/salonkalite". Any ideas on what is wrong?

        {
            "type": "airQualitySensor",
            "name": "Salon Hava Kalite",
            "topics": {
                "getAirQuality": "salon/salonkalite",
                "getCarbonDioxideLevel": "salon/salonppm",
                getCurrentRelativeHumidity": "salon/salonnem",
                "getCurrentTemperature": "salon/salonsıcaklık"
            },
            "airQualityValues": [
                "Unknown",
                "Excellent",
                "Good",
                "Fair",
                "Inferior",
                "Poor"
            ],
            "accessory": "mqttthing"
        }

**Comment by EjvindHald** [comment]
For the getAirQuality you will need to use strings with value "Unknown", "Excellent" and so on as you have defined - not integers.
For getAirQualityPPM you should be using integers.
I am using both and they are working fine.

**Comment by ODMerdin** [comment]
Thanks, @EjvindHald I will try that. Best Regards

**Comment by EjvindHald** [comment]
I had an Eve sensor to compare with. I think the actual ppm numbers leading to a category is country specific.

**Comment by jeylites** [comment]
Hi 

I'm trying to get the sensor (tasmota) to communicate with MQTT thing, for some reason the values are not showing on Homekit. Is there something wrong with the config?

I do see the temp values change on the sensor logs. 


```
],
    "accessories": [
        {
            "type": "weatherStation",
            "name": "MYSENSOR",
            "url": "192.168.1.200",
            "topics": {
                "getCurrentTemperature": "tele/mytemp/SENSOR"
            },
            "accessory": "mqttthing"
        }
    ]
}
```

**Comment by ODMerdin** [comment]
> Hi
> 
> I'm trying to get the sensor (tasmota) to communicate with MQTT thing, for some reason the values are not showing on Homekit. Is there something wrong with the config?
> 
> I do see the temp values change on the sensor logs.
> 
> ```
> ],
>     "accessories": [
>         {
>             "type": "weatherStation",
>             "name": "MYSENSOR",
>             "url": "192.168.1.200",
>             "topics": {
>                 "getCurrentTemperature": "tele/mytemp/SENSOR"
>             },
>             "accessory": "mqttthing"
>         }
>     ]
> }
> ```
> 
> ```
> 5:45:48 MQT: Attempting connection...
> 15:45:48 MQT: Connected
> 15:45:48 MQT: tele/mytemp/LWT = Online (retained)
> 15:45:48 MQT: cmnd/jeytemp/POWER = 
> 15:45:48 MQT: tele/mytemp/INFO1 = {"Module":"Generic","Version":"8.4.0(tasmota)","FallbackTopic":"cmnd/DVES_F6B1E0_fb/","GroupTopic":"cmnd/tasmotas/"}
> 15:45:48 MQT: tele/mytemp/INFO2 = {"WebServerMode":"Admin","Hostname":"JEY TEMP SENSOR ","IPAddress":"192.168.1.110"}
> 15:45:48 MQT: tele/jeytemp/INFO3 = {"RestartReason":"Software/System restart"}
> 15:45:52 MQT: tele/mytemp/STATE = {"Time":"2020-09-25T15:45:52","Uptime":"0T00:00:10","UptimeSec":10,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":28,"MqttCount":1,"Wifi":{"AP":1,"SSId":"SMILE","BSSId":"D8:47:32:0F:B8:32","Channel":11,"RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:04"}}
> 15:45:52 MQT: tele/mytemp/SENSOR = {"Time":"2020-09-25T15:45:52","DHT11":{"Temperature":21.4,"Humidity":57.0,"DewPoint":12.5},"TempUnit":"C"}
> 15:50:52 MQT: tele/mytemp/STATE = {"Time":"2020-09-25T15:50:52","Uptime":"0T00:05:10","UptimeSec":310,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"SMILE","BSSId":"D8:47:32:0F:B8:32","Channel":11,"RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:04"}}
> 15:50:52 MQT: tele/mytemp/SENSOR = {"Time":"2020-09-25T15:50:52","DHT11":{"Temperature":21.3,"Humidity":57.0,"DewPoint":12.4},"TempUnit":"C"}
> 15:55:42 APP: Serial logging disabled
> 15:55:52 MQT: tele/mytemp/STATE = {"Time":"2020-09-25T15:55:52","Uptime":"0T00:10:10","UptimeSec":610,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"SMILE","BSSId":"D8:47:32:0F:B8:32","Channel":11,"RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:04"}}
> 15:55:52 MQT: tele/mytemp/SENSOR = {"Time":"2020-09-25T15:55:52","DHT11":{"Temperature":21.3,"Humidity":57.0,"DewPoint":12.4},"TempUnit":"C"}
> ```

Hello Jeylites,

I don't know anything about tasmota sensor but I guess "tele/mytemp/SENSOR" outputs {"Time":"2020-09-25T15:45:52","DHT11":{"Temperature":21.4,"Humidity":57.0,"DewPoint":12.5},"TempUnit":"C"} . It should be only  temperature value for example "21.4".
You should install "paho.mqtt-spy-master" and subscribe to tele/mytemp/SENSOR and see what's coming from tasmota.  The correct path for temperature values might be "tele/mytemp/SENSOR/Temperature" you can subscribe to tele/mytemp/SENSOR/Temperature and see if the values show up. You can configure your way out.
