### ISSUE TITLE
Xiaomi Aquara temp sensor issue

### ISSUE THREAD

**Issue by Tamas92** [arachnetech/homebridge-mqttthing#273]
Hi All,

I added my temp/humidity sensor to the zigbee2mqtt CC2531 stick and now I want to show it in Home. 

 {
            "accessory": "mqttthing",
            "type": "humiditySensor",
            "name": "Xiaomi humidity sensor",
            "url": "mqtt://127.0.0.1",
            "username": "mqtt_user",
            "password": "password",
            "topics": {
                "getCurrentRelativeHumidity": {
                    "topic": "zigbee2mqtt/Temp_Sensor",
                    "apply": "return parseFloat(JSON.parse(message).humidity);"
                },
                "getStatusLowBattery": {
                    "topic": "zigbee2mqtt/Temp_Sensor",
                    "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
                }
            }
        }
Zigbee2mqtt output:

May 23 15:47:32 raspberrypi npm[486]: zigbee2mqtt:info  2020-05-23 15:47:32: MQTT publish: topic 'zigbee2mqtt/Temp_Sensor', payload '{"battery":80,"voltage":2965,"temperature":24.44,"humidity":28.44,"pressure":1004.9,"linkquality":134}'
May 23 15:47:32 raspberrypi npm[486]: zigbee2mqtt:info  2020-05-23 15:47:32: MQTT publish: topic 'zigbee2mqtt/Temp_Sensor', payload '{"battery":80,"voltage":2965,"temperature":24.44,"humidity":28.44,"pressure":1004.7,"linkquality":131}'

But I got 0% humidity. 
I tried to add with the ID as well. No luck.
Homebridge and Zigbee2mqtt is running from the same Raspberry

**Comment by rbswift** [comment]
I use this config

```
"getCurrentRelativeHumidity": {
                    "topic": "tele/tasmota/SENSOR",
                    "apply": "return JSON.parse(message).BME280.Humidity;"
}
```

maybe try without parseFloat, so

`"apply": "return JSON.parse(message).humidity;"`
