### ISSUE TITLE
Sonoff RF Bridge as Device in Homekit

### ISSUE THREAD

**Issue by JimmyEyeball** [arachnetech/homebridge-mqttthing#275]
Is there any way of using the data below to add the RF Bridge itself as a Device in Homekit to monitor the status???

23:58:50 MQT: tele/RF/LWT = Online (retained)
23:58:50 MQT: cmnd/RF/POWER = 
23:58:50 MQT: tele/RF/INFO1 = {"Module":"Sonoff Bridge","Version":"8.3.1(tasmota)","FallbackTopic":"cmnd/DVES_RF_fb/","GroupTopic":"cmnd/tasmotas/"}
23:58:50 MQT: tele/RF/INFO2 = {"WebServerMode":"Admin","Hostname":"RFBridge","IPAddress":"192.168.1.148"}
23:58:50 MQT: tele/RF/INFO3 = {"RestartReason":"Software/System restart"}
23:58:54 MQT: tele/RF/STATE = {"Time":"2020-05-24T23:58:54","Uptime":"0T00:00:12","UptimeSec":12,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"TALKxxxx","BSSId":"80:20:DA:xx:xx:xx","Channel":1,"RSSI":82,"Signal":-59,"LinkCount":1,"Downtime":"0T00:00:06"}}
00:03:54 MQT: tele/RF/STATE = {"Time":"2020-05-25T00:03:54","Uptime":"0T00:05:12","UptimeSec":312,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"TALKxxxx","BSSId":"80:20:xx:xx:xx:xx","Channel":1,"RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:06"}}

**Comment by rbswift** [comment]
The list of supported accessories is here:

https://github.com/arachnetech/homebridge-mqttthing#supported-accessories

You could possibly set it up as any of these if any is appropriate.

Adding new accessory types is down to Apple
