### ISSUE TITLE
Adding a valve, sprinkler or irrigation system causes homkit to crash.

### ISSUE THREAD

**Issue by GarrettTrott** [arachnetech/homebridge-mqttthing#278]
After a recent update of mqttthing all valves, sprinklers, and irrigation systems crash homekit. I can no longer see any hubs in my home. All of these valves were previously working fine and all switches and lights are working fine if remove all valves etc. JSON. They work fine in my homebridge UI. Any thoughts why? Thanks so much!

**Comment by arachnetech** [comment]
Very odd. My test sprinkler configuration is working. Can you share your config so I can try it here?

**Comment by ro-beard** [comment]
Same for me. 
I configured a sprinkler - all worked fine V1.1.13. But after updating to 1.1.16 a configured valve (a sprinkler in my case) will cause a crash of whole HomeKit (no responses of any devices, even native homekit-devices)

**Comment by arachnetech** [comment]
Thanks, I will see if I can reproduce.

**Comment by arachnetech** [comment]
Looking at your config, I think `minDuration` and `maxDuration` should be numbers not strings. Does changing them to:

```json
            "minDuration": 1,
            "maxDuration": 30
```

help?

**Comment by ro-beard** [comment]
Ah nice - changing both values to integer does help and now it works fine! Thank you very much :)

Homebridge itself works fine for the whole time. The HomeKit environment on my devices behaves totally weird. For all devices the "No response" error is shown - even for the homekit native devices that are not configured using homebridge.

**Comment by arachnetech** [comment]
Very interesting, thanks. Glad that fixed it anyway!
