### ISSUE TITLE
Is there a way to use this plugin as an platform.

### ISSUE THREAD

**Issue by Jeroen207** [arachnetech/homebridge-mqttthing#282]
Great plugin! Only thing I was not able to find is how to configure it as a separate platform, meaning I can configure multiple MQTT devices but show it in HomeKit as an separate device which you need to conned. I have two different HomeKit systems running independently form each other and I wish not to combine it. I hope there is an answer to my problem!

**Comment by arachnetech** [comment]
No, it won’t work as a plugin. However, you can configure different accessories in different Homebridge instances.
