### ISSUE TITLE
MQTT connection to Mosquitto established, yet data could be read

### ISSUE THREAD

**Issue by caffeineflo** [arachnetech/homebridge-mqttthing#285]
My setup is rather simple, take this example accessory:

```
        {
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "url": "192.168.1.115",
            "username": "user",
            "password": "test",
            "name": "Sunroom temperature sensor",
            "topics": {
                "getCurrentTemperature": {
                    "topic": "zigbee2mqtt/Humidity and Temperature Sensor",
                    "apply": "return parseFloat(JSON.parse(message).temperature);"
                },
                "getStatusLowBattery": {
                    "topic": "zigbee2mqtt/Humidity and Temperature Sensor",
                    "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
                }
            },
            "logMqtt": true
        }
```

As you can see, my MQTT server (Mosquitto, 1.6.10) is on the same local network as my homebridge instance and is working for every other server wonderfully. Yet, Homebridge is unable to read any values (everything stuck at 0).

The log looks like this

```
[6/8/2020, 4:23:08 PM] [Sunroom temperature sensor] Initializing mqttthing accessory...
[6/8/2020, 4:23:08 PM] [Sunroom temperature sensor] MQTT URL: mqtt://192.168.1.115
[6/8/2020, 4:23:08 PM] [Sunroom temperature sensor] MQTT options: {"keepalive":10,"clientId":"mqttthing_Sunroom temperature sensor_8b97ecd4","protocolId":"MQTT","protocolVersion":4,"clean":true,"reconnectPeriod":1000,"connectTimeout":30000,"will":{"topic":"WillMsg","payload":"Connection Closed abnormally..!","qos":0,"retain":false},"username":"user","rejectUnauthorized":false}
```

The Mosquitto server shows that Homebridge connects "correctly

`1591647788: New client connected from 192.168.1.115 as mqttthing_Sunroom temperature sensor_8b97ecd4 (p1, c1, k10, u'user').`

Yet, Homebridge immediately posts the lastWill message `Connection Closed abnormally..!` and since doesn't read any values.

Any suggestions on how to fix this are well appreciated

**Comment by arachnetech** [comment]
Homebridge doesn't send the lastWill message: that gets sent by your broker if/when the MQTT connection from mqttthing is lost.

Unless you're publishing with the retain flag set, mqttthing will only receive values when they are published. Can you run `mosquitto_sub -v -m "#"` to confirm that's being publishing on your MQTT while homebridge/mqttthing is running?

**Comment by caffeineflo** [comment]
Thanks for taking time to help with my issue! 

I'm using MQTT Explorer to subscribe to all topics already and see what values are being published which should be similar as to subscribing to `#` afaik.

Now for the lastWill message, I'm still not sure I understand this correctly?! MQTT.js is used to connect to my Mosquitto broker and should read the topics I specified for my accessories if I understand this correctly. But the connection should be held and the lastWill message shouldn't be sent until the MQTT.js/mqttthing, right?

Cause what happens is (looking at my logs throughout last night) that every 4 minutes or so the lastWill message is sent since the mqttthing connection had a socket error and disconnected.

See
`1591706941: Socket error on client mqttthing_Living Room Staircase_e65d6221, disconnecting.`

So I might have seen the lastWill message because MQTT.js was disconnecting as much or whenever I restarted homebridge.

Now how do we go about finding the error? 
I tried to put in `console.log` statements on all error paths and on the config paths, but didn't actually receive any errors. 
Do you have any clues?

**Comment by arachnetech** [comment]
Can you run `mosquitto_sub -v -t "#"` to confirm what is being published on your MQTT while homebridge/mqttthing is running, and compare this to the mqttthing logging (with `“logMqtt”: true`, which you already have set)? That will prove whether mqttthing is actually missing any MQTT messages.

**Comment by caffeineflo** [comment]
Hey @arachnetech,
I went ahead and looked into the MQTT messages with `mosquitto_sub -v -t "#"` and could confirm that the lastWill is posted upon restart after the sockets died and then every 4-8 minutes - but the Mosquitto logs show that the MQTTthing client immediately reconnects.
I'm not sure if this is meant to be the case, but after a couple of restarts or so, my accessories are showing values now!! 

I'll keep checking if these constant reconnects are putting my accessories out of sync, but I hope not so.

Thanks again for your help, since this is no longer a blocker for me but only (maybe) an unexpected behavior, I'm closing this issue.

**Comment by arachnetech** [comment]
No, I certainly wouldn’t expect it to disconnect every few minutes like that. Very odd.
