### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by ramirocaballero** [arachnetech/homebridge-mqttthing#286]
This is not an issue, but i really don't know what to do. Im a beginner whit all of this...
This is the message i recibe when i try to get the "value":4079. What should i have to write?

[Test] Decode function apply( message) { return JSON.parse( message ).Value.value; } failed for topic home/OpenMQTTGateway/433toMQTT with message {"value":4079,"protocol":24,"length":12,"delay":480} - TypeError: Cannot read property 'value' of undefined

Sorry for my bad english.

**Comment by arachnetech** [comment]
I think your decode function should be just:
`{ return JSON.parse( message ).value; }`

**Comment by ramirocaballero** [comment]
It Works!!!!! Thank you!!
