### ISSUE TITLE
Merge Humidity + Temp to a single tile

### ISSUE THREAD

**Issue by Tamas92** [arachnetech/homebridge-mqttthing#289]
Is it possible somehow to merge the tiles to a single one? For Xiaomi Temp sensor I have only one tile in Home App and it shows the Temp and Humidity. For the MQTT thing's one I cannot do that as there is no option for that.

**Comment by NorthernMan54** [comment]
Can you share a screen shot of how the Xiaomi sensor appears in the home app.  I aware of a couple of patterns around combined tiles, but have not seen this.

**Comment by Tamas92** [comment]
Sure, I created screenshots:
https://ibb.co/ncHW7Yq
https://ibb.co/qgkj0V5

Here you can see the settings section. There is an option to ,,Show as separate Tiles" if I select it then I can see the Temp tile and humidity tile separately (like the DHT22 sensor in my screenshot) and if I choose one of them there is an option to ,,Show as single Tile"
https://ibb.co/56YkRrN

**Comment by tobekas** [comment]
Please try `"type": "weatherStation"`. Temp/Humidity combination should be possible with that.

See also related discussion in #201. it’s the same topic!

**Comment by Tamas92** [comment]
Thanks tobekas! It is working for me.
