### ISSUE TITLE
Is MQTT with TLS  supported?

### ISSUE THREAD

**Issue by DeviousPenguin** [arachnetech/homebridge-mqttthing#29]
I tried to connect to my secure MQTT broker by using port 8883 in the URL but it didn't work.

I guess TLS isn't implemented, but if it is so I need to put a link to the cert file in the config?

Thanks

**Comment by arachnetech** [comment]
mqttthing uses https://www.npmjs.com/package/mqtt which appears to support TLS, but unfortunately it only passes through specific options currently.

**Comment by arachnetech** [comment]
mqttthing 1.0.16 allows any options accepted by https://www.npmjs.com/package/mqtt#client to passed through in a new configuration setting: **mqttOptions**. This should allow you to specify a certificate.

**Comment by DeviousPenguin** [comment]
Thanks, I'll try and specify my TLS cert using mqttOptions and see how it goes
