### ISSUE TITLE
Overwriting serial number from mqtt telemetry message?

### ISSUE THREAD

**Issue by ceraz68** [arachnetech/homebridge-mqttthing#295]
Hello, I'd like to overwrite the serial number from an incoming mqtt message. I don't know if this is possible

For a wemos mini D1 with 8 temperature sensors I use the apply function to retrieve the right temperature. Here is an example incoming message : {"Time":"2020-07-08T22:05:10","DS18B20-1":{"Id":"0119388FD26D","Temperature":23.8}, ....} and the config.json setting.

        {
            "type": "temperatureSensor",
            "name": "Boiler Cold",
            "url": "192.168.1.10:1883",
            "topics": {
                "getCurrentTemperature": {
                    "topic": "tele/jbl_2/SENSOR",
                    "apply": "return JSON.parse(message)['DS18B20-1'].Temperature;"
                }
            },
            "manufacturer": "Dallas",
            "model": "DS18B20",
            "serial": "123456789",
            "accessory": "mqttthing"
        }

Is it possible to overwrite the serial value by the Id value  "0119388FD26D" in the mqtt message using a JSON parse?

Thanks a lot!

**Comment by arachnetech** [comment]
Not possible currently, unfortunately: manufacturer, model, serial and accessory are all just configured strings.

**Comment by ceraz68** [comment]
Forgot to say thanks and close :-)
