### ISSUE TITLE
Request for Generic Device

### ISSUE THREAD

**Issue by VirtualPugwash** [arachnetech/homebridge-mqttthing#296]
Please excuse my ignorance as a newbie.

Would it be possible to create a "generic" class of device. One in which the MQTT payload is passed through homebridge-mqttthing without interpretation?

I am using Node-Red and was wondering if for the more obscure devices (e.g Tradfri Dimmer control / Tradfri Switch) if the JSON Payload could be passed through unaltered, then Node-Red could do the heavy lifting of interpreting that data and acting on it.
Thanks Steve

**Comment by arachnetech** [comment]
MQTT-Thing makes specific Homekit devices accessible through MQTT, but there isn't really the concept of a generic Homekit device.

However, you can certainly do the heavy lifting of converting between device-specific MQTT encodings and MQTT-Thing's representations in Node-RED if you prefer. You would just subscribe/publish to the 'real' topics from Node-RED then publish/subscribe separate topics used by MQTT-Thing.

Most of the examples for configuring devices using JSON over MQTT rely on 'apply' functions in MQTT-Thing, but it's also worth being aware of the [JSON Codec](https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Codecs.md#json-codec-json) which was added more recently. In theory this should allow some much simpler configurations, but unfortunately it's not something I've had time to look at (and all of my devices are custom-built anyway, and so use the MQTT formats most easily configured in MQTT-Thing).

**Comment by VirtualPugwash** [comment]
Hello David,

Many thanks for your swift and detailed replies, it's much appreciated.

With regards the Tradri Switch and Dimmer, sometimes one can get so fixated on fixing a problem you forget that you're trying to solve an issue that doesn’t exist!.

In this case I don’t need to expose the Switch and Dimmer on the HomeKit App through Homebridge as its is a slightly irrelevant!    I need them to just do their job.

In the end I figured out I could use Node-Red to directly query the MQTT Agent on my RPi and build a Flow accordingly. All working. I will out of curiosity try your amended config script and delve into your CODEC functionality. Thanks for the info.

Also I want to say “thank you” for writing Homebridge-mqttthing, it is a great product, again, much appreciated.

On a similar vein, in my explorations, I posted a Issue, (then found a solution myself) a request for a Configuration script for the Tradfri Dimmable Bulb with Colour temperature adjustment.

This device here:

 https://www.ikea.com/gb/en/p/tradfri-led-bulb-e27-806-lumen-wireless-dimmable-white-spectrum-white-spectrum-globe-clear-30408470/ <https://www.ikea.com/gb/en/p/tradfri-led-bulb-e27-806-lumen-wireless-dimmable-white-spectrum-white-spectrum-globe-clear-30408470/>



In order to get it to work, I plagiarised one of your Config scripts and using MQTT logs figured out that although it reports its colour temperature value as JSON {“ColorTemperature":140}. (140 is cool white, 498 is warm white)

Bizarrely, in order to actually set the colour temperature, you do not use “ColorTemperature”, but “color_temp”, hence the Bulb only responds to a change of temperature through the command {"color_temp”:140}

I can well understand peoples frustration with these type of inconsistencies, all very strange

That said all working.

I know you are collecting Configs for the Wiki, so my (tiny) contribution is a working Config for the above Bulb:

{
            "type": "lightbulb-ColTemp",
            "name": "ColTemp",
            "topics": {
                "getOnline": "IsOnLine",
                "getOn": {
                    "topic": “zigbee2mqtt/<id>",
                    "apply": "return JSON.parse(message).state"
                },
                "setOn": "zigbee2mqtt/<id>/set",
                "getBrightness": {
                    "topic": "zigbee2mqtt/<id>",
                    "apply": "return Math.round(JSON.parse(message).brightness / 2.55)"
                },
                "setBrightness": {
                    "topic": "zigbee2mqtt/<id>/set",
                    "apply": "return JSON.stringify({brightness: Math.round(message * 2.55)})"
                },
                "getColorTemperature": {
                    "topic": "zigbee2mqtt/<id>",
                    "apply": "return Math.round(JSON.parse(message).color_temp)"
                },
                "setColorTemperature": {
                    "topic": "zigbee2mqtt/<id>/set",
                    "apply": "return JSON.stringify({color_temp: message})"
                }
            },
            "onlineValue": "ON",
            "offlineValue": "ON",
            "onValue": "ON",
            "offValue": "OFF",
            "accessory": "mqttthing"
        }

The ranges of ColorTemp produced by Apples Home App produce a range of 140 - 498, which seems to match the colour gamut of the bulb, so without playing around further it seems that no scaling of the Apple values seems necessary.

Please feel free to sanitise it, and add it to the list of supported products on your Wiki.

Many thanks again and good luck with the project.

Best regards
Steve

**Comment by arachnetech** [comment]
Thanks, now added to wiki.

**Comment by VirtualPugwash** [comment]
Great, thank you David for creating a great tool !

Regards
Steve
