### ISSUE TITLE
Control HomeKit accessories through MQTT

### ISSUE THREAD

**Issue by lensherm** [arachnetech/homebridge-mqttthing#297]
I have a question, which might be silly, but is it possible to have statuses of HomeKit accessories in Homebridge be exported to MQTT and to use MQTT to control said accessories?

**Comment by NorthernMan54** [comment]
You can do something similar to this with node-red and the node homebridge-automation.

This works only with homebridge accessories though

**Comment by lensherm** [comment]
OBE. Using NodeRed at this point to accomplish same requested functionality.
