### ISSUE TITLE
Unable to control Shelly RGBW2

### ISSUE THREAD

**Issue by zuhair68** [arachnetech/homebridge-mqttthing#299]
I'm trying to use the plugin with Shelly RGBW2, I'm only able to turn on/off the light from HomeKit. Dim/Colors are not working.
Can someone please help?

This is my conf part for the Shelly:

{
            "type": "lightbulb-RGBW",
            "name": "Shelly Test Device",
            "url": "MQTT://192.168.3.100",
            "topics": {
                "getRGBW": "shellies/shellyrgbw2-1DFACF/color/0/status",
                "setRGBW": "shellies/shellyrgbw2-1DFACF/color/0/set",
                "getOn": "shellies/shellyrgbw2-1DFACF/color/0",
                "setOn": "shellies/shellyrgbw2-1DFACF/color/0/command"
            },
            "onValue": "on",
            "offValue": "off",
            "otherValueOff": false,
            "accessory": "mqttthing"
        }

I believe I have something wrong in setRGBW and getRGBW topics entry. This is the MQTT instruction for Shelly RGBW2 
[https://shelly-api-docs.shelly.cloud/?shell#shelly-rgbw2-color-mqtt](https://shelly-api-docs.shelly.cloud/?shell#shelly-rgbw2-color-mqtt)

Will I have better control if I flash the Shelly RGBW2 with Tasmota?

**Comment by dezral** [comment]
yes you need to read and output json to control it..

i do it like so..

{
    "accessory": "mqttthing",
    "type": "lightbulb",
    "name": "Shelly RGBW2",
    "logMqtt": true,
    "topics":
    {
        "getOn": "shellies/shellyrgbw2-xxxxx/color/0",
        "setOn": "shellies/shellyrgbw2-xxxxxx/color/0/command",
        "getRGBW": {
                "topic": "shellies/shellyrgbw2-xxxxxx/color/0/status",
                "apply": "if(JSON.parse(message).mode === \"color\"){ return JSON.parse(message).red + \",\" + JSON.parse(message).green + \",\" + JSON.parse(message).blue + \",\" + JSON.parse(message).white;}"
                  },

        "setRGBW":{
                "topic": "shellies/shellyrgbw2-XXXXXX/color/0/set",
                "apply": "var end = message.split(\",\"); return JSON.stringify({red: end[0],green: end[1],blue: end[2],white: end[3]});"
                }

   },

    "onValue": "on",
    "offValue": "off"
},

**Comment by zuhair68** [comment]
> yes you need to read and output json to control it..
> 
> i do it like so..
> 
> ```
> {
>     "accessory": "mqttthing",
>     "type": "lightbulb",
>     "name": "Shelly RGBW2",
>     "logMqtt": true,
>     "topics":
>     {
>         "getOn": "shellies/shellyrgbw2-xxxxx/color/0",
>         "setOn": "shellies/shellyrgbw2-xxxxxx/color/0/command",
>         "getRGBW": {
>                 "topic": "shellies/shellyrgbw2-xxxxxx/color/0/status",
>                 "apply": "if(JSON.parse(message).mode === \"color\"){ return JSON.parse(message).red + \",\" + JSON.parse(message).green + \",\" + JSON.parse(message).blue + \",\" + JSON.parse(message).white;}"
>                   },
> 
>         "setRGBW":{
>                 "topic": "shellies/shellyrgbw2-XXXXXX/color/0/set",
>                 "apply": "var end = message.split(\",\"); return JSON.stringify({red: end[0],green: end[1],blue: end[2],white: end[3]});"
>                 }
> 
>    },
> 
>     "onValue": "on",
>     "offValue": "off"
> },
> ```

Many thanks, working flawlessly!
