### ISSUE TITLE
understanding Security System configuration

### ISSUE THREAD

**Issue by cubilon** [arachnetech/homebridge-mqttthing#3]
hi there,
thanks for this plug in, works fine.
here: I've two MQTT commands, the first arms my Security System, the other one disams it. 
It's not clear what - and how, which syntax - to configure here:
  

> {
>         "getCurrentState":    "<topic used to get security system current state>",
>         "setTargetState":     "<topic used to set security system target state>"
>     },
>     "currentStateValues": "<array of 5 values corresponding to security system current states (optional)>",
>     "targetStateValues": "<array of 4 values corresponding to security system target states (optional)>"
> 

and, what about 

>  "onValue": "<value representing on (optional)>",
>     "offValue": "<value representing off (optional)>"

common fields?
can you please provide some kind of explanation/example?

thanks a lot!

**Comment by psyciknz** [comment]
I'd be interested as well.  I think I've got mine set up....but my alarm (or alarm integration scription), posts an ON for the alarm armed, and OFF for alarm off, so my config looks as follows:
```
 {
        "accessory": "mqttthing",
        "type": "securitySystem",
        "name": "Alarm State",
        "url": "mqtt://mqtt.andc.nz",
        "caption": "Alarm Arm State",
        "topics":
        {
           "getCurrentState":  "Paradox/Partition"
        },
        "currentStateValues": "OFF,ON"
      }
```

What I can't see is how to translate ON = AWAY_ARM and OFF= HOME - which seem to be desired state strings in homebridge.

**Comment by arachnetech** [comment]
Homebridge publishes a value to the topic specified in `getTargetState` to indicate that the user wants to change the status of the alarm system. The default values published are `SA` for STAY_ARM, `AA` for AWAY_ARM, `NA` for NIGHT_ARM and `D` for DISARM.

For example, if the homekit user chooses to arm the alarm in night mode, homebridge will publish `NA` to the `getTargetState` topic:

`test/security/target NA`

Once the alarm system has successfully entered the target mode, **it must then echo back the new state** to the topic specified in `getCurrentState`, e.g.:

`test/security/current NA`

Homekit will then confirm that arming has completed by changing from a state of "Arming..." to a state of "Night".

If the alarm is triggered, the alarm system should publish the value `T` representing the ALARM_TRIGGERED state to the topic specified in `getCurrentState`. When the alarm state is cleared, it should publish the last target state again to clear the triggered state.

I'm testing this with the following accessory configuration:

```
    {
      "accessory": "mqttthing",
      "type": "securitySystem",
      "name": "Test Security System",
      "url": "http://192.168.10.35:1883",
      "logMqtt": true,
      "topics": {
        "getCurrentState": "test/security/current",
        "setTargetState":  "test/security/target"
      }
    }
```

... here, and simulating changes to the current alarm state by using **mosquitto_pub**, e.g.

`mosquitto_pub -t "test/security/current" -m "NA"`

The `currentStateValues` and `targetStateValues` options are used to change the predefined default values for the 5 current states and 4 target states respectively.

Hopefully this is cleared, but please let me know if you have any questions (and I'll try to answer more quickly next time!).

**Comment by arachnetech** [comment]
@psyciknz 

`currentStateValues` must be an array of the five values representing homekit states `STAY_ARM`, `AWAY_ARM`, `NIGHT_ARM`, `DISARMED` and `ALARM_TRIGGERED` in that order, so your AWAY_ARM and DISARMED states would need to be specified as:

`currentStateValues: ["SA", "ON", "NA", "OFF", "T"]`

(using the default values as placeholders for the states that you don't wish to use).

However, I believe (from my experimentation in Homebridge) that Homekit only supports alarms where all control of the alarm state is done through homekit. If you tell it that the current state is AWAY_ARM by publishing ON to the current state with your config, it will understand that the alarm system in in the AWAY_ARM state and show a state of "Disarming...". This is because *it knows* that the alarm should be disarmed (because that's the last state that its user set) - so it waits for disarming to complete. When you publish OFF to the current state to confirm this (from its perspective), the displayed state will change back to "Off".

**Comment by matej** [comment]
@arachnetech Do you think this would deserve a separate ticket? I can write one up if needed. 

For completeness, here's the configuration I was using for the test setup. 

```json
{
	"accessory": "mqttthing",
	"type": "securitySystem",
	"name": "Alarm",
	"url": "mqtt://<my_ip>/",
	"caption": "Alarm",
	"topics": {
		"setTargetState": "test/security/target",
		"getTargetState": "test/security/current",
		"getCurrentState": "test/security/current"
	},
	"targetStateValues": [
		"StayArm",
		"AwayArm",
		"NightArm",
		"Disarmed"
	],
	"currentStateValues": [
		"StayArm",
		"AwayArm",
		"NightArm",
		"Disarmed",
		"Triggered"
	]
},
```

And the node-red nodes. 

```
[{"id":"149dcf66.f79549","type":"mqtt out","z":"3940b926.2133c6","name":"","topic":"","qos":"","retain":"","broker":"ea4cdc58.5e8c4","x":450,"y":1620,"wires":[]},{"id":"7f678051.13339","type":"inject","z":"3940b926.2133c6","name":"","topic":"test/security/current","payload":"Disarmed","payloadType":"str","repeat":"","crontab":"","once":false,"x":180,"y":1620,"wires":[["149dcf66.f79549"]]},{"id":"960ed9de.f5ec18","type":"mqtt in","z":"3940b926.2133c6","name":"","topic":"test/security/target","qos":"2","broker":"ea4cdc58.5e8c4","x":150,"y":1500,"wires":[["f33b9ba3.a4c2a"]]},{"id":"94cc5747.621e4","type":"mqtt out","z":"3940b926.2133c6","name":"","topic":"test/security/current","qos":"","retain":"","broker":"ea4cdc58.5e8c4","x":600,"y":1500,"wires":[]},{"id":"f33b9ba3.a4c2a","type":"delay","z":"3940b926.2133c6","name":"","pauseType":"delay","timeout":"3","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":360,"y":1500,"wires":[["94cc5747.621e4"]]},{"id":"655255cd.f11b94","type":"comment","z":"3940b926.2133c6","name":"Confirm HomeKit initiated changes (Works fine!)","info":"","x":240,"y":1460,"wires":[]},{"id":"43fd39da.6a169","type":"comment","z":"3940b926.2133c6","name":"Simulate an external chnage (Broken!)","info":"","x":210,"y":1580,"wires":[]},{"id":"ea4cdc58.5e8c4","type":"mqtt-broker","z":"","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"willTopic":"","willQos":"0","willRetain":"false","willPayload":"","birthTopic":"","birthQos":"0","birthRetain":"false","birthPayload":""}]
```

**Comment by mspiridakis** [comment]
Hello and thank you for your great efforts to make a really useful plugin!
In the Home Security section description you mention a "setCurrentState" which does not appear in the plugin's settings.
I am trying to build an "adapter" between homebridge and a custom system (in python) that includes a home security system.  Although I have read all the relevant posts I am still a little confused. Especially when one operates the Home alarm outside Homekit.
I do apologize but my english are not very good so I get confused 
What are the topics the plugin listens to and what are the topics it sends the commands.
Also what are the topics the actual alarm system must listen to and what are the topics it sends data to Homekit?

**Comment by josemalena** [comment]
Hi,
