### ISSUE TITLE
Need a sensor to read a voltage. 

### ISSUE THREAD

**Issue by rlust** [arachnetech/homebridge-mqttthing#301]
I am reading the voltage of my Jeeps battery voltage and cannot figure a way to display just a voltage reading. I tried an air quality sensor but I get back a %.

Thanks, well done on this integration!!!

**Comment by arachnetech** [comment]
There is a BatteryLevel characteristic (from 0-100 %) which you can add to any service, or you might be able to display a decimal as a temperature (although I think only to one decimal place), but I'm not aware of anything that would display voltage specifically.

**Comment by chinloon** [comment]
Where is this BatteryLevel characteristic?  Under which Accessory?

**Comment by arachnetech** [comment]
It's described in https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Configuration.md#mqtt-topics.
