### ISSUE TITLE
getOnline function

### ISSUE THREAD

**Issue by 3eshelon** [arachnetech/homebridge-mqttthing#302]
Hello.
Could you clear the situation with getOnline status for the device.
I really don't understand what I need to do to make HomeKit show (not response) status.
Now I trying to make a light switch as an example. It running wit ESP6288, working well but I can push on/off button in HomeKit app even if ESP6288 is powered off. 
I see many places in the plugin window like: 
Topic used to notify mqttthing of 'online' status,
Indicate offline ('No Response') when confirmation message not received,
Value representing that an accessory is online (as received through 'getOnline') if different to 'onValue',
Value representing that an accessory is offline (as received through 'getOnline') if different to 'offValue'
And I really don't understand what to do.
Please help me with that.

**Comment by arachnetech** [comment]
There are two options:

1. Set your MQTT broker to publish a 'not online' value to the `getOnline` topic as it's LWT message. This must be done by the accessory. MQTT-Thing is then configured to respond to the `getOnline` topic. The accessory must also indicate that it's online when it starts up. MQTT-Thing's configuration for this option is described in the `getOnline` topic in https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Configuration.md#mqtt-topics.

2. Use configuration, where your accessory must echo the on/off message published by MQTT-Thing. This is described in https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Configuration.md#confirmation.

In both cases, the Home App doesn't notice that an accessory has gone offline (or online) immediately - it only updates its state when the Home app is opened.
