### ISSUE TITLE
2 values for on & 2 values for off

### ISSUE THREAD

**Issue by Efiller91** [arachnetech/homebridge-mqttthing#305]
Is it possible to indicate lists of keywords that would trigger on or off instead of just one? 

Edit: to be clear I’m talking about a contact sensor and adding more values to the “onvalue”. So for example I want to to equal 1 or ON.

**Comment by piotrtobolski** [comment]
"getOn": {
      "topic": "stat/mydevice/mytopic",
      "apply": "['1', 'ON', 'OtherOnValue'].includes(message) ? 'ON' : 'OFF';"
    },
    "onValue": "ON"
You can try something like this

**Comment by arachnetech** [comment]
@piotrtobolski 's solution looks as it it would work (thanks!). You could also achieve something similar with a codec. Closing as I think this  is answered.
