### ISSUE TITLE
Fan don´t publish on "setRotationSpeed" when only  click on "on"

### ISSUE THREAD

**Issue by Jakohoho** [arachnetech/homebridge-mqttthing#310]
On the "setRotationSpeed" Topic nothing will be published when only click on "on", without go into the Fan and set the Speed, only on the seton Topic true ist published. The Problem is that my Fan only turn on and off with the "setRotationSpeed" topic,  because he can´t storage the last speed before power off.
Is there a way out?

**Comment by arachnetech** [comment]
Implement in v1.1.25.
