### ISSUE TITLE
No message comes from Homekit to topic "setRGB"

### ISSUE THREAD

**Issue by SEVSM** [arachnetech/homebridge-mqttthing#311]
I have RGB LED strip connected via MQTT RGB dimmer.
Here's my config for the dimmer light:
### 
       {     "type": "lightbulb-RGB",
            "name": "RGB",
            "accessory": "mqttthing",
            "logMqtt": true,
            "topics": {
                "getRGB": "/devices/wb-1/controls/rgb",
                "setRGB": "/devices/wb-1/controls/rgb/on"
            }
        }
I have a scenario in Homekit, witch changes color of RGB to 0,99,17

I turn on strip from Homekit:
```
[8/4/2020, 8:13:22 AM] [RGB] Publishing MQTT: /devices/wb-1/controls/rgb/on = 255,255,255
[8/4/2020, 8:13:22 AM] [RGB] Received MQTT: /devices/wb-1/controls/rgb = 255,255,255
```
Then I turn on scenario in Homekit, witch changes color of RGB:
```
[8/4/2020, 8:13:40 AM] [RGB] Publishing MQTT: /devices/wb-1/controls/rgb/on = 0,99,17
[8/4/2020, 8:13:40 AM] [RGB] Received MQTT: /devices/wb-1/controls/rgb = 0,99,17
```
After that I turn of strip from physical button:
```
[8/4/2020, 8:16:09 AM] [RGB] Received MQTT: /devices/wb-1/controls/rgb = 0,0,0
```

The problem is that, if I turned off led strip from the button with the color, set before in the Homekit scenario, and then try to run this scenario again in Homekit, no message comes from Homekit to topic "setRGB" and led strip does not turn on. However, Homekit app shows that led strip is enabled and the color is set the same as in the scenario.

However, if I change led strip color via Homekit to a different color from the one, set in the scenario before switching off from the button, turn it off from the button, and then run the script from Homekit, everything works correctly. Please tell me what the problem might be?

**Comment by arachnetech** [comment]
It looks as if your physical button is transmitting on the 'get' topic which tells mqttthing what the light status is but doesn't actually control the light. Mqtthing doesn't publish a set in response to a get.

I suspect it would work if you changed your switch to publish the set topic instead. The light would I think then echo the get topic which would update homekit status.
