### ISSUE TITLE
MQTTthing and iOS 14?

### ISSUE THREAD

**Issue by houser42** [arachnetech/homebridge-mqttthing#313]
Hello,

Just curious:
In preparation for iOS14, I just tested the latest beta with homebridge and mqttthing.
Still works flawlessly technically so that's great.
However, the new way iOS displays sensors as icons at the top of a room page means the way  some of us are using normal tiles in the home app to display things like battery voltage using the humidity parameters becomes less readable. Illustrating this by attached raw image showing the same data displayed in iOS 13 and in iOS 14. AT the bottom dark image show what is shown when tapping the icon at the top in iOS14: the old style tiles.
Any comments on how to possibly address or work around this is appreciated. Many thanks!

<img width="384" alt="Screenshot 2020-08-06 at 09 03 40" src="https://user-images.githubusercontent.com/15192440/89501509-beecb580-d7c3-11ea-84f9-91b280d76bdf.png">

**Comment by arachnetech** [comment]
Unfortunately I think that's solely a change to the Apple Home App, not something that can be manipulated from homebridge.

**Comment by houser42** [comment]
Many thanks @arachnetech 
I hear you. If new accessory types do become available it sure would be great if they can be added to mqttthing at some point. I, like many others are specifically looking for ways to display batteries for solar installs via Victron where the battery is standalone and not part of another device. So SOC (state of charge), amps and volts for this scenario would be really useful. Thanks again.

**Comment by houser42** [comment]
Just for clarity, another screenshot.
If there is a way to workaround with other accessory types than humidity and temperature so that this battery info is displayed correctly as SOC, volts and amps, that would be very much ok with me. 
Many thanks.

<img width="234" alt="Screenshot 2020-08-13 at 20 05 42" src="https://user-images.githubusercontent.com/15192440/90228799-27b4dd00-de17-11ea-866c-5b79db4c1cf3.png">

**Comment by arachnetech** [comment]
Unfortunately unless you can see alternative services in https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts that would work better, I don't think there's anything I can do within mqttthing.

**Comment by houser42** [comment]
Understood. Appreciate your replies!
I have (as I know others have) also reported the need for new HK accessory types to Apple's beta team. One can hope they listen at some point ..;)
It seems an obvious thing to add sooner or later IMHO.

**Comment by houser42** [comment]
@arachnetech 
I had a look at the link you gave. Not sure I understand this correctly, but there is actually one service that might do the trick. Around line 4237 there is mention of a new iOS 14 battery service. Also some stuff around line 220.
If you have time to have a look at some point, i would be very interested to give this a try in iOS 14, if at all possible.

` * Service "Battery Service"
 */

export class BatteryService extends Service {

  static UUID: string = '00000096-0000-1000-8000-0026BB765291';

  constructor(displayName?: string, subtype?: string) {
    super(displayName, BatteryService.UUID, subtype);

    // Required Characteristics
    this.addCharacteristic(Characteristic.BatteryLevel); // this is actually optional since iOS 14
    this.addCharacteristic(Characteristic.ChargingState); // this is actually optional since iOS 14
    this.addCharacteristic(Characteristic.StatusLowBattery);`

**Comment by arachnetech** [comment]
Interesting. I think I already support BatteryLevel, but I'd have to check.

**Comment by houser42** [comment]
I only see battery as part of other accessories, not standalone. FWIW. 
I'll keep my fingers crossed it can be done..Many thanks.

**Comment by arachnetech** [comment]
You're absolutely right! I'll see what it does...
