### ISSUE TITLE
Accessory with a dynamic name?

### ISSUE THREAD

**Issue by mientki** [arachnetech/homebridge-mqttthing#314]
Due to the fact that the homekit and the home application do not support the measurement of power current, just like kWh, I came up with an idea, I would like to add an accessory, eg Occupancy Sensor, which will have a dynamic name of the accessory. The accessory would get the read power value from mqtt and rename the accessory in homekit in the following format: $ value_from_mqtt + text (kWh).

Is it possible to add an accessory with a dynamic name?

**Comment by arachnetech** [comment]
There is a `getName` topic which attempts to allow the name of an accessory to be set dynamically, but unfortunately I can't get it to work.

**Comment by mientki** [comment]
can you give us an example of use?
