### ISSUE TITLE
How to set QOS level?

### ISSUE THREAD

**Issue by chinloon** [arachnetech/homebridge-mqttthing#318]
I want to set the QOS level of messages published to mosquitto broker from the default of 0 to 1.  How can I do that?

My issue is that i have devices that has long delays before checking for subscribed messages and will often be disconnected.  I need to messages to be queued and received on the ESP32 devices.

Any guidances appreciated.  Thanks

**Comment by arachnetech** [comment]
Details here:
https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Configuration.md#mqtt-settings

**Comment by chinloon** [comment]
Thanks.  Managed to set QOS to 1 on both sides.  However, the ESP32 still miss messages, though a bit less.  Also gets worst when using low power sleep modes.

More research required...

**Comment by arachnetech** [comment]
You might want to try the retain flag.
