### ISSUE TITLE
Shelly i3 MQTT 

### ISSUE THREAD

**Issue by spaggi** [arachnetech/homebridge-mqttthing#326]
Hi,

I aplogize if I missed something obvious or if this is not the right place to post this. In this case, please close this issue.

I'm currently evaluating to convert a regular Switch into a Smart Switch using the Shelly i3. The i3 can send Sortpress, Longpress, Doublepress Events via MQTT and be used as a StatelessProgrammableSwitch in HomeKit which is fantastic.

However, I'm unsure about mapping the Events to mqttthing.

As stated in the Shelly docs (https://shelly-api-docs.shelly.cloud/#shelly-i3-mqtt), the Shelly will send topic shellies/shellyix3-<deviceid>/input_event/<index> with Message content `{"event":"string","event_cnt":number}`

However, I'm not sure how I can map this to the Events of mqttthing. As stated in the documentation, I could use the "switchValues" Parameter to map these events, however the Shelly sends them nested in a JSON structure while I believe mqttthing expects a plain string.

As the Shelly JSON will contain a number which iterates with every press, the string will always be different. 

Any idea how this can be done? Or would this be a feature request?

Thanks!

**Comment by spaggi** [comment]
Nevermind, I just figured that's what apply functions are for

**Comment by arachnetech** [comment]
Possibly worth looking at the JSON codec too. It is intended to make JSON easier to decode, although apply functions can certainly still be used.

**Comment by spaggi** [comment]
Thanks a lot for your response. Is there any documentation or info regarding this topic? I’m not quite sure what JSON codec means here.

Thanks a lot!

**Comment by arachnetech** [comment]
There are some examples of its use in other issues here which may help:
https://github.com/arachnetech/homebridge-mqttthing/issues?q=%22json+codec%22

... and some documentation at: 
https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Codecs.md#json-codec-json
