### ISSUE TITLE
air purifier current and target state values

### ISSUE THREAD

**Issue by dvd2000k** [arachnetech/homebridge-mqttthing#329]
Hi, i have specified custom values for the air purifier, but in the log tell me is not configured:

[Homebridge] [8/31/2020, 4:11:13 PM] [Purificatore Camera] Warning: currentAirPurifierState received [ON] which is not in configured values {"INACTIVE":0,"IDLE":1,"PURIFYING":2}

my config:
{
            "accessory": "mqttthing",
            "plugin_map": {
                "plugin_name": "homebridge-mqttthing",
                "index": 0
            },
            "topics": {
                "setActive": "cmnd/Sonoff/POWER",
                "getActive": "stat/Sonoff/POWER",
                "getCurrentAirPurifierState": "stat/Sonoff/POWER",
                "getTargetAirPurifierState": "stat/Sonoff/POWER"
            },
            "type": "airPurifier",
            "name": "Purificatore Camera",
            "username": "",
            "password": "",
            "onValue": "ON",
            "offValue": "OFF",
            "logMqtt": true,
            "currentAirPurifierValues": [  "OFF",  "MM", "ON"  ]
        }

Something wrong in my json?

**Comment by arachnetech** [comment]
Should be currentAirPurifierStateValues rather than currentAirPurifierValues.

**Comment by dvd2000k** [comment]
Yes, now it's working. Thank you very much.

**Comment by arachnetech** [comment]
Excellent, thanks for letting me know. I'll correct the example configuration where that was wrong.
