### ISSUE TITLE
Sonoff Zigbee bridge

### ISSUE THREAD

**Issue by zuhair68** [arachnetech/homebridge-mqttthing#330]
Is there a plan to support Sonoff Zigbee bridge flashed with Tasmota? ZigBee-> Tasmota -> MQTT

**Comment by jdtsmith** [comment]
Anything that speaks MQTT is supported (the beauty of MQTT).  The only trick is learning what topics are relevant, and how to decode them.  There are lots of examples.  I personally use Zigbee-> Zigbee2MQTT -> MQTT -> mqttthing and it works great.
