### ISSUE TITLE
Sonoff Basic R3 Connection failed.

### ISSUE THREAD

**Issue by martintaborda** [arachnetech/homebridge-mqttthing#332]
Can someone help me to solve a connection issue between a sonoff basic r3 with tasmota and mqttthing (plugin homebridge-mqttthing v1.1.20) 

I have below error:
17:12:21 MQT: Attempting connection...
17:12:21 MQT: Connect failed to 10.0.4.106:1883, rc -2. Retry in 10 sec
17:12:22 RSL: tele/Bomba_de_riego/STATE = {"Time":"2020-09-04T17:12:22","Uptime":"0T00:40:04","UptimeSec":2404,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"CiroWifi","BSSId":"00:11:32:7C:3E:5C","Channel":10,"RSSI":70,"Signal":-65,"LinkCount":1,"Downtime":"0T00:00:03"}}
17:12:32 MQT: Attempting connection...
17:12:32 MQT: Connect failed to 10.0.4.106:1883, rc -2. Retry in 10 sec

This is my tasmota config.
![image](https://user-images.githubusercontent.com/64342460/92261853-90d8bf00-eeb0-11ea-8b24-eb79459f82b7.png)

And this the server config:
},
    "accessories": [
        {
            "accessory": "mqttthing",
            "type": "switch",
            "name": "Bomba de riego",
            "url": "mqtt://10.0.4.106",
            "username": "mqtt",
            "password": "2681",
            "topics": {
                "setOn": "cmnd/Bomba_de_riego/power",
                "getOn": "stat/Bomba_de_riego/POWER",
                "getOnline": {
                    "topic": "tele/Bomba_de_riego/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
                }
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "startPub": {
                "cmnd/Bomba_de_riego/power": "",
                "stat/Bomba_de_riego/POWER": ""
            },
            "logMqtt": true
        }

**Comment by arachnetech** [comment]
Looks like your device is failing to connect to your MQTT server, so you'd need to get help from someone who knows tasmota.
