### ISSUE TITLE
Switch control 

### ISSUE THREAD

**Issue by WayneKP** [arachnetech/homebridge-mqttthing#333]
Hello
I have installed the Homebridge-mqttthing plugin which I want to use for the basic "Switch" function for a Lenovo power socket which I have a fan plugged into so all I want is a basic "on/off" switch and have managed to get it showing on my home app and it indicates that it turns on and off BUT there must be a setting in the plug-in to actually connect to the actual plug right ? 
I must not have the settings correct but I don't know what exactly to get the communication between the plugin and the Lenovo plug if you could point me in the right direction please. I have attached a screen shot of my config and the Homebridge is using 192.168.1.72 but the plug itself uses an IP of 158.140.192.180 and has a MAC address cc:50:e3:72:71:d3  so I am thinking I need to input these somewhere into settings but don't know where if you could help thanks 

![image](https://user-images.githubusercontent.com/37004336/92662817-02968a00-f343-11ea-8815-aadaa176677d.png)

**Comment by arachnetech** [comment]
homebridge-mqttthing just sends and receives MQTT messages - so assuming  your Lenovo plug uses MQTT you'll need to find out the appropriate messages.
