### ISSUE TITLE
Convert Fahrenheit to Celsius, so that Apple Home doesn't display outrageous temperatures?

### ISSUE THREAD

**Issue by friesdan** [arachnetech/homebridge-mqttthing#336]
Hey there, thanks for this great work. 
I'm having an issue with the temp - I'm pulling info from my ambient weather sensors, only available in F, and homebridge assumes it is Celsius, so that it looks like 166 degrees in the apple home app. 
where can I insert a conversion? 
I have some very basic javascript skill, and if pointed to the right file can do this

**Comment by arachnetech** [comment]
You should be able to use an 'apply' function for this. Are you able to share your config for the accessory?

**Comment by friesdan** [comment]
{
            "type": "temperatureSensor",
            "name": "Studio Temp",
            "username": "redacted",
            "password": "redacted",
            "mqttOptions": {
                "keepalive": 120
            },
            "mqttPubOptions": {
                "retain": false
            },
            "logMqtt": true,
            "topics": {
                "getCurrentRelativeHumidity": "aw/data/humidity6",
                "getCurrentTemperature": "aw/data/temp6f"
            },
            "accessory": "mqttthing"
        },

**Comment by friesdan** [comment]
I'm using this to convert the ambientweather json to mqtt, hosting the broker locally on my mac: https://github.com/qbunt/ambient-mqtt

**Comment by friesdan** [comment]
so could I insert the below conversion function into the .config somewhere, then use:

 "getCurrentTemperature":  fToC("aw/data/temp6f")
?
If yes, where to define the function? 

function fToC(fahrenheit) {
  var fTemp = fahrenheit;
  var fToCel = (fTemp - 32) * 5 / 9;
  var message = fTemp+'\xB0F is ' + fToCel + '\xB0C.';
    console.log(message);
}

**Comment by friesdan** [comment]
I fixed it in the app.js file of ambient-mqtt, by changing this code (this is the changed code):


api.on('data', data => {
    console.log(`${ts()} - aw data`)
    if (jsonTopic) {
        mClient.publish('aw/data', JSON.stringify(data), publishHandler)
    } else {
        // delete device node to prevent topic spamming
        delete data.device
        // loop through properties and publish each one as it's own topic
        for (var prop in data) {
            if (data.hasOwnProperty(prop)) {
                //catch temperatures, transform, and send as celsius:
                if (prop.includes("temp")) {
                    mClient.publish('aw/data/' + prop, JSON.stringify(((data[prop]) - 32) * (5 / 9)), publishHandler)
                } else {
                    mClient.publish('aw/data/' + prop, JSON.stringify(data[prop]), publishHandler)
                }
            }
        }
    }
})

**Comment by arachnetech** [comment]
Sorry, didn't come back to you in time. You could also have scaled with MQTTThing 'apply' functions. I'll close this as you have it working.
