### ISSUE TITLE
2 topics to control 1 state - possible? codec maybe?

### ISSUE THREAD

**Issue by rbswift** [arachnetech/homebridge-mqttthing#339]
I would like to have a Contact Sensor getContactSensorState respond to two topics.

For example getContactSensorState=true only when topicA=true and topicB=false.

Is this possible with a codec perhaps? Thanks for any pointers!

**Comment by arachnetech** [comment]
It's not currently possible for a codec to subscribe directly to a topic, so you'd have to do something fairly horrible like using another configurable topic (e.g. getBatteryLevel) for your topicB.

If I get a chance, I'll add the ability for codecs to issue their own subscriptions independently - it would be a useful feature.

**Comment by rbswift** [comment]
I added node-red to my setup to do this so all good thanks.
