### ISSUE TITLE
temperatureSensor doesn't show below zero degree

### ISSUE THREAD

**Issue by fanlessfan** [arachnetech/homebridge-mqttthing#34]
Hello @arachnetech,

mqttthing is great and i convert my espeasy sensor for openhab to homebridge. however I found that it always show 0 when the temperature down to below zero. at the same time openhab is working find and if I manually subscribe to the topic, it shows the correct number.

Thanks for the help.

**Comment by arachnetech** [comment]
Added in 1.0.19.
