### ISSUE TITLE
Add generic devices with specified topic and command data

### ISSUE THREAD

**Issue by unixb0y** [arachnetech/homebridge-mqttthing#354]
Hello,  
I have an IR Blaster which subscribes to a single topic and commands sent to that topic of course cause different things to happen, depending on the `message` that you specify.  
An example usage using `mosquitto`:
```
mosquitto_pub -d -u username -P password -t cmnd/irblaster/IRsend -m "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":\"0xE13EA45B\"}"
```

Is there any way to accomplish this with `homebridge-mqttthing`?
For example, I'd like to set up a device representing my stereo system with commands like `on`, `off`, `volume-up`, `volume-down`. This would all  be the same topic but different `messages`.

Is it possible to send an MQTT command with a `message` like in mosquitto with the `-m` parameter?

**Comment by arachnetech** [comment]
mqtt-thing can only expose device types that Homekit supports - so you could add switches to send each IR command, but I don't believe there's a way to create a generic device.
