### ISSUE TITLE
Could you please add the ability to set the range of a lightbulb's "colortemeprature" range

### ISSUE THREAD

**Issue by Blackra1n5** [arachnetech/homebridge-mqttthing#357]
Could you please add the option to set the range of lightbulb's colour temperature. As Tasmota uses the value 153 - 500 It causes some issues, as mqttthing has a range of 140-500. Which doesn't allow a large part of the colour temperature spectrum to be used. 

Many Thanks

**Comment by arachnetech** [comment]
Mqttthing passes on the values used by Homekit, but it should be possible to scale these using an apply function in your configuration.
