### ISSUE TITLE
Cannot adress White LED with config

### ISSUE THREAD

**Issue by korri96** [arachnetech/homebridge-mqttthing#361]
I'm fairly new to MQTT and I simply cannot figure out how to adress my white LED in this LSC E14 RGBW Bulb. If you could please point me in the right direction.

Here is the config:

`    "accessories": [
        {
            "type": "lightbulb",
            "name": "Kommode",
            "url": "##",
            "username": "##",
            "password": "###",
            "logMqtt": true,
            "topics": {
                "setHSV": "cmnd/office/HSBCOLOR",
                "getHSV": "stat/office/HSBCOLOR",
                "getRGBW": "stat/office/rgbw/HSBCOLOR",
                "setRGBW": "cmnd/office/rgbw/HSBCOLOR",
                "getOn": "stat/office/POWER",
                "setOn": "cmnd/office/power",
                "getBrightness": "stat/office/DIMMER",
                "setBrightness": "cmnd/office/DIMMER"
            },
            "integerValue": false,
            "hex": true,
            "accessory": "mqttthing"
        },`

and the Tasmota-Template:

`{"NAME":"LSC RGBCW E14","GPIO":[0,0,0,0,0,0,0,0,181,0,180,0,0],"FLAG":0,"BASE":18}`

Here are my Tamsmota Console logs when i control it over the Tasmota WEBUI:

`10:42:20 MQT: stat/office/RESULT = {"POWER":"ON","Dimmer":100,"Color":"000000F807","HSBColor":"359,2,0","White":100,"CT":163,"Channel":[0,0,0,97,3]}
10:42:21 MQT: stat/office/RESULT = {"POWER":"ON","Dimmer":100,"Color":"000000FF00","HSBColor":"359,2,0","White":100,"CT":153,"Channel":[0,0,0,100,0]}`

But when I try to with homekit i get this:
`10:38:50 MQT: stat/office/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFE0C40000","HSBColor":"28,23,100","White":0,"CT":285,"Channel":[100,88,77,0,0]}
10:38:52 MQT: stat/office/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFFAFE0000","HSBColor":"313,2,100","White":0,"CT":285,"Channel":[100,98,100,0,0]}
10:38:52 MQT: stat/office/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFFAFF0000","HSBColor":"305,2,100","White":0,"CT":285,"Channel":[100,98,100,0,0]}`

It seems that as if it woudlnt adress the later two channels right? Maybe i should try with RGBWW?

EDIT:
I have got so far that i can control the whites only but dont know how to combine the RGB and the WW Channel:

`            "topics": {
                "getOn": "stat/living/POWER",
                "setOn": "cmnd/living/power",
                "getBrightness": "stat/living/DIMMER",
                "setBrightness": "cmnd/living/DIMMER",
                "getColorTemperature": "stat/living/CT",
                "setColorTemperature": "cmnd/living/CT"
            },
            "integerValue": true,
            "hex": true,
            "accessory": "mqttthing",
            "white": 100
        }`

i tried: 

`            "topics": {
                "getBrightness": "stat/office/DIMMER",
                "setBrightness": "cmnd/office/DIMMER",
                "getOn": "stat/office/POWER",
                "setOn": "cmnd/office/power",
                "getRGBWW": "stat/office/Channel",
                "setRGBWW": "cmnd/office/Channel",
                "setHSV": "cmnd/office/HSBCOLOR",
                "getHSV": "stat/office/HSBCOLOR",
                "getWhite": "stat/office/White",
                "setWhite": "cmnd/office/White"
            },
            "integerValue": false,
            "hex": true,
            "accessory": "mqttthing"
        },`

But this unfortunately didnt work either

**Comment by drpau** [comment]
Hi mate, i have been playing around too with a colored RGB downlight which I had found worked when using the RGBWW mode to address it.  Using that, enabled me to be able to address the cool -> warm white space. 

I did find that as you added anything to the "WW" section of `Color:` this would remove all the actual RGB and would only control the warm-coolwhite LED range.  

For example, I couldn't have `Color: FFFF00FFFF` set.... if I did, it ignored the first 4 F's and only did the last 4 F's to be the white and warm white space.
