### ISSUE TITLE
getOn Confirmation not registering.

### ISSUE THREAD

**Issue by d-0-k-6** [arachnetech/homebridge-mqttthing#363]
Hi, I dont think the getOn confirmations are working as intended. (It could also just be user error - sorry if thats the case.)

My settings are as follows.

```
"accessories": [
        {
            "type": "lightbulb-RGB",
            "name": "Color Light",
            "topics": {
                "getOnline": "getOnline",
                "getOn": "getState",
                "setOn": "setState"
            },
            "accessory": "mqttthing",
            "logMqtt": "true",
            "confirmationPeriodms": 2000
        }
    ],
```

I'm watching both getState & setState in terminal - when 'true' is published to setState, my device is immediatley responding by publishing 'true' to the getState channel. I can also see in the Homebridge logs that it is receiving the getState.

Unfortunatly despite receiving the getState 'true' every 2000ms setState is being triggered again up to the default max of 4 at which point the device is registered as unresponsive.

Any help would be greatly appretiated.

Thanks

**Comment by arachnetech** [comment]
That does sound like incorrect behaviour by MQTTThing. I'll see if I can reproduce later.

**Comment by d-0-k-6** [comment]
Perfect, thanks. I can't work out what causing it. Let me know if I can help.

**Comment by arachnetech** [comment]
Should be fixed in 1.1.21.

**Comment by d-0-k-6** [comment]
Hi arachnetech. Sorry for the slow response. No working perfectly. Thanks

**Comment by arachnetech** [comment]
Excellent, thanks for confirming!
