### ISSUE TITLE
no history persistence file with eve

### ISSUE THREAD

**Issue by fototeddy** [arachnetech/homebridge-mqttthing#364]
I have an Outlet an a TemperatureSensor with the following config

```
{
             "accessory": "mqttthing",
             "type": "outlet",
             "name": "Server",
             "url": "mqtt://192.168.5.102:1883",
             "topics": {
                 "getOn": "shellies/shellyplug-s-977F79/relay/0",
                 "setOn": "shellies/shellyplug-s-977F79/relay/0/command",
                 "getOnline": "shellies/shellyplug-s-977F79/online",
                 "getWatts": "shellies/shellyplug-s-977F79/relay/0/power",
                 "getTotalConsumption": "shellies/shellyplug-s-977F79/relay/0/energy"
             },
             "onValue": "on",
             "offValue": "off",
             "onlineValue": "true",
             "logMqtt": true,
             "history": "true"
         },
         {
             "accessory": "mqttthing",
             "type": "temperatureSensor",
             "name": "ServerPlugTemp",
             "url": "mqtt://192.168.5.102:1883",
             "history": "true",
             "topics": {
                 "getCurrentTemperature": "shellies/shellyplug-s-977F79/temperature",
                 "getStatusActive": "shellies/shellyplug-s-977F79/online"
             }
         },
```

Eve can show all the values but do not show history. 
Also I can not find any persistence files in the default directory in my HOOBS instance.

Are there any know issues with newest Homebridge, mqttthing, eve an iOS?

**Comment by arachnetech** [comment]
I did update the fakegato-history library in v.1.1.21 (to fix a security issue), but I don't use history/Eve myself. Was this working in the previous version mqttthing?

**Comment by fototeddy** [comment]
i do not know if it was working cause I just set it up this evening

**Comment by fototeddy** [comment]
well I played around with it for some hours.....nothing seemed to work so I wrote this post an now I have entries -.-

so ok I think it was somehow my fault

**Comment by arachnetech** [comment]
Most odd. Glad it's working now anyway!

**Comment by NorthernMan54** [comment]
Before the graphs appear you need to collect some data first, so this is expected.  It typically needs about 20 minutes plus to accumulate enough data for them to appear.
