### ISSUE TITLE
In RGBWW the option to swap "WW" around

### ISSUE THREAD

**Issue by drpau** [arachnetech/homebridge-mqttthing#365]
I have a light which i have now got to work correctly but the only issue is the WW is reversed.

Eg: Warm white is cool white in homekit selector and cool white is the warm white section of the color wheel.

Is it possible to have a tickbox in the plugin to select if your lights have WW reversed like mine?

**Comment by arachnetech** [comment]
Added `switchWhites` option in v1.1.22.
