### ISSUE TITLE
BME280 - Air pressure sensor

### ISSUE THREAD

**Issue by GeorgioT** [arachnetech/homebridge-mqttthing#367]
Hi all,
have a BME280 running with MQTTThing, temperature and humidity is running fine, Air pressure not. The Web UI does not show the pressure icon at all, HomeKit shows an icon with the comment 'not supported'.
Attached is my config:
{
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "Innentemperatur",
            "url": "192.168.178.89",
            "topics": {
                "getCurrentTemperature": "BME280/Temperature"
            }
        },
        {
            "accessory": "mqttthing",
            "type": "airPressureSensor",
            "name": "Luftdruck",
            "url": "192.168.178.89",
            "topics": {
                "getAirPressure": "BME280/Pressure"
            }
        },
        {
            "accessory": "mqttthing",
            "type": "humiditySensor",
            "name": "Luftfeuchtigkeit",
            "url": "192.168.178.89",
            "topics": {
                "getCurrentRelativeHumidity": "BME280/Humidity"
            }
        }

MQTT Message is fine : value of e.g. 1011 for the air pressure, so within the allowed range...
Any ideas?

**Comment by EfficientSetting** [comment]
The pressure sensor "only" shows up in the Eve app since HomeKit does not support it.

**Comment by GeorgioT** [comment]
Ah, ok - I see...
Thanks!
