### ISSUE TITLE
mqtthings is sending equal sign between topic and value, but Tasmota light doesn't accept it

### ISSUE THREAD

**Issue by thunderranch** [arachnetech/homebridge-mqttthing#368]
So in the console of my Tasmota light I can do:

stat/tasmota_lights/POWER ON
stat/tasmota_lights/POWER OFF

But NOT:

stat/tasmota_lights/POWER = ON
stat/tasmota_lights/POWER = OFF

Mqtthings is however sending:

stat/tasmota_lights/POWER = ON
stat/tasmota_lights/POWER = OFF

Is there a way to define the separator between the topic and the value?

**Comment by arachnetech** [comment]
MQTT-Thing doesn't publish the topic and value like that. This is just how it display it when you enable MQTT logging:

```javascript
log( 'Publishing MQTT: ' + topic + ' = ' + message );
```

You can confirm this using a utility like mosquitto_sub:
`mosquitto_sub -v -t "#"`

Remember that if you're running MQTT-Thing or mosquitto_sub on a different server to your MQTT broker, you'll need to tell them where the MQTT broker  is.
