### ISSUE TITLE
Sending object in message of startPub topic?

### ISSUE THREAD

**Issue by pandizajner** [arachnetech/homebridge-mqttthing#371]
I'm configuring https://www.zigbee2mqtt.io/devices/TS0505A.html device with `mqttthing`. That's my first device being configured so forgive me this issue a bit. I've already managed to set up the 'set' and 'get' calls for state, brightness and colorTemp. But now I'm facing the problem where after the Homebridge reboot I want to receive the current status of the device. 

I know I supposed to be using `startPub` but the thing is that what I need to publish to receive the status response is 
`zigbee2mqtt/FRIENDLY_NAME/get` with payload `{"state": ""}` – mentioned [here](https://www.zigbee2mqtt.io/devices/TS0505A.html#light).

I did a whole bunch of tests with MQTT Explorer and this seems like the only way I can get the device status without changing its state (by using `set` calls).

This is my configuration snippet:

```{
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Office-Light",
            "url": "mqtt://localhost:1883",
            "mqttPubOptions": {
                "retain": true
            },
            "logMqtt": true,
            "topics": {
                "getOn": {
                    "topic": "zigbee2mqtt/0x8X42e14fffe32cXXXX",
                    "apply": "return JSON.parse(message).state"
                },
                "setOn": "zigbee2mqtt/0x8X42e14fffe32cXXXX/set",
                "getBrightness": {
                    "topic": "zigbee2mqtt/0x8X42e14fffe32cXXXX",
                    "apply": "return Math.round(JSON.parse(message).brightness / 2.54)"
                },
                "setBrightness": {
                    "topic": "zigbee2mqtt/0x8X42e14fffe32cXXXX/set",
                    "apply": "return JSON.stringify({brightness: Math.round(message * 2.54)})"
                },
                "getColorTemperature": {
                    "topic": "zigbee2mqtt/0x8X42e14fffe32cXXX",
                    "apply": "return Math.round(140 + (JSON.parse(message).color_temp - 150) * 360 / 350)"
                },
                "setColorTemperature": {
                    "topic": "zigbee2mqtt/0x8X42e14fffe32cXXX/set",
                    "apply": "return JSON.stringify({color_temp: Math.round(150 + (message - 140) * 350 / 360)})"
                }
            },
            "whiteMix": true,
            "onValue": "ON",
            "offValue": "OFF",
            "startPub": [
                {
                    "topic": "zigbee2mqtt/0x8X42e14fffe32cXXX/get",
                    "message": {
                        "state": ""
                    }
                }
            ]
        }
```

and this is what Mosquitto sees

`zigbee2mqtt/0x8X42e14fffe32cXXX/get [object Object]`.

**What should be the proper way to send this kind of message in `startPub`?**
topic:`zigbee2mqtt/0x8X42e14fffe32cXXX/get` message: `{"state": ""}`

**Comment by kurtwarwick-new** [comment]
Hi @pandizajner 

I came across this exact issue. The way that I managed to resolve it is to send a message to the topic

`zigbee2mqtt/0x8X42e14fffe32cXXX/get/state`

where you could replace state with any other property you are looking to prep on startup. It seems to be working with Light properties such as color, color_temp etc.

Hopefully, this helps!

**Comment by pandizajner** [comment]
That's it! Thank you @kurtwarwick-new . It solves the problem.

**Comment by kurtwarwick-new** [comment]
Happy to help! 👍

**Comment by sambal0** [comment]
Hey!
I got the same issue with the state of my light bulb. Unfortunately, the hint by @kurtwarwick-new 

`"topic": "zigbee2mqtt/0x00158d0004aeXXXX/get/state"`

did not work.

This is my configuration snippet:

```
{
            "type": "lightbulb",
            "name": "Tint",
            "url": "mqtt://localhost:1883",
            "mqttPubOptions": {
                "retain": true
            },
            "topics": {
                "getOn": {
                    "topic": "zigbee2mqtt/0x00158d0004aeXXXX",
                    "apply": "return JSON.parse(message).state;"
                },
                "setOn": "zigbee2mqtt/0x00158d0004aeXXXX/set",
                "getBrightness": {
                    "topic": "zigbee2mqtt/0x00158d0004aeXXXX",
                    "apply": "return Math.round(JSON.parse(message).brightness / 2.54)"
                },
                "setBrightness": {
                    "topic": "zigbee2mqtt/0x00158d0004aeXXXX/set",
                    "apply": "return JSON.stringify({brightness: Math.round(message * 2.54)})"
                },
                "getColorTemperature": {
                    "topic": "zigbee2mqtt/0x00158d0004aeXXXX",
                    "apply": "return Math.round(140 + (JSON.parse(message).color_temp - 153) * 360 / 217)"
                },
                "setColorTemperature": {
                    "topic": "zigbee2mqtt/0x00158d0004aeXXXX/set",
                    "apply": "return JSON.stringify({color_temp: Math.round(153 + (message - 140) * 217 / 360)})"
                }
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "startPub": {
                "topic": "zigbee2mqtt/0x00158d0004aeXXXX/get/state",
                "message": {
                    "state": ""
                }
            },
            "logMqtt": true,
            "accessory": "mqttthing"
        }
```

and this is what Mosquitto sees:

`Publishing MQTT: message = [object Object]`

Anybody has an idea what is wrong or how to get the state in another way?

**Comment by tomppakoo** [comment]
Sometimes the double quotes are causing issues.
In case you want to publish simple message like
{"state": }

Then below should work

"startPub": [
    {
        "topic": "TEST\TOPIC",
        "message": "{\"STATUS\": }"
    }
