### ISSUE TITLE
OnValue = Brightness value possible ?

### ISSUE THREAD

**Issue by benjaminfrombe** [arachnetech/homebridge-mqttthing#375]
Hi,

I have a system (Openmotics) that does not use and on and off value, instead it only accepts dimmer values from 0 to 100. So when I switch on the light, the on value should be the dimmer value. Is this possible with this plugin ?

Thank you for your response !

**Comment by arachnetech** [comment]
The easiest way to create a dimmable lightbulb with a range from 0-100 is to configure `setBrightness`, e.g.

```
        {
            "type": "lightbulb-Dimmable",
            "name": "Light",
            "url": "homebridge",
            "logMqtt": true,
            "topics": {
                "getBrightness": "dimlight/get",
                "setBrightness": "dimlight/set"
            },
            "whiteMix": true,
            "accessory": "mqttthing"
        }
```

However, unfortunately this doesn't behave as you need - brightness is only published when it changes, not when the light is turned on or off. It should be a simple change to use brightness to indicate on/off state instead when no on topic is configured. I'll have a look later if I have time...

**Comment by arachnetech** [comment]
Changed on v1.1.24 - the above configuration should now work

**Comment by benjaminfrombe** [comment]
Thanks ! I have an issue with my mqtt client on my domotica system and it
got temporarily disabled, so I'm not able to test right now, but will do so
when I get the time ...
