### ISSUE TITLE
Add FaultStatus and TamperedStatus to Security System

### ISSUE THREAD

**Issue by EjvindHald** [arachnetech/homebridge-mqttthing#376]
Two optional general parameters called FaultStatus and TamperedStatus can be used together with the Security System. Currently, it is not displayed within the Apple Homekit app, but the EVE app shows these correct, if they are ON.

A typical scenario for a fault status is if a window or door is open, so you cannot arm the alarm system. 

This functionality is implemented in openhab homekit add-on and it works fine in that context.

**Comment by arachnetech** [comment]
MQTT-Thing already supports adding the `StatusFault` and/or `StatusTampered` characteristics to a **securitySystem** if their topics are configured, although this wasn't stated in the documentation. I've now corrected this:

```javascript
{
    "accessory": "mqttthing",
    "type": "securitySystem",
    "name": "<name of sensor>",
    "url": "<url of MQTT server (optional)>",
    "username": "<username for MQTT (optional)>",
    "password": "<password for MQTT (optional)>",
    "caption": "<label (optional)>",
    "topics": {
        "setTargetState":    "<topic used to set 'target state'>",
        "getTargetState":    "<topic used to get 'target state'>",
        "getCurrentState":   "<topic used to get 'current state'>",
        "getStatusFault":    "<topic used to provide 'fault' status (optional)>",
        "getStatusTampered": "<topic used to provide 'tampered' status (optional)>"
    },
    "targetStateValues": [ "StayArm", "AwayArm", "NightArm", "Disarmed" ],
    "currentStateValues": [ "StayArm", "AwayArm", "NightArm", "Disarmed", "Triggered" ],
    "restrictTargetState": [ 1, 3 ]
}
```

They're both Boolean values, working as described in https://github.com/arachnetech/homebridge-mqttthing/blob/HEAD/docs/Configuration.md#boolean-value-settings.

**Comment by EjvindHald** [comment]
@arachnetech : Thank you very much!
