### ISSUE TITLE
Why is scheme `http` in the MQTT url?

### ISSUE THREAD

**Issue by njh** [arachnetech/homebridge-mqttthing#377]
Hi,

In the [documentation](https://github.com/arachnetech/homebridge-mqttthing/blob/v1.1.22/docs/Configuration.md) and [examples](https://github.com/arachnetech/homebridge-mqttthing/blob/v1.1.22/test/config.json#L23), the example configurations use the `http` URL scheme when connecting to MQTT Servers. Is this because `mqttthing` uses WebSockets and not MQTT to connect to the server?
Or is the URL scheme actually ignored and the MQTT protocol used?

```json
{
    "accessory": "mqttthing",
    "type": "lightbulb",
    "name": "My lightbulb",
    "url": "http://192.168.1.235:1883",
    "username": "MQTT_username",
    "password": "MQTT_password",
    "mqttOptions": { "keepalive": 30 },
    "mqttPubOptions": { "retain": true },
    "logMqtt": true,
...
```

Thanks,

nick.

**Comment by arachnetech** [comment]
I think you're right: it would be more correct to use mqtt or mqtts as the protocol. That string mostly just gets passed straight through to the MQTT library that I'm using - so I'd have to check it's documentation to see whether it does anything different. https://www.npmjs.com/package/mqtt

**Comment by arachnetech** [comment]
Docs say "The URL can be on the following protocols: 'mqtt', 'mqtts', 'tcp', 'tls', 'ws', 'wss'.", so http certainly seems wrong!

**Comment by njh** [comment]
Thanks for confirming!

I will test and raise a PR 😀
