### ISSUE TITLE
LWT payload configurable values

### ISSUE THREAD

**Issue by Kepete** [arachnetech/homebridge-mqttthing#38]
As the #10 feature request about LWT was implemented it now would be good to have the possibilities to configure `onlineValue` and `offlineValue` values.
I'm using Tasmota and it needs "Online" and "Offline" as values. 
mqttthing already has configurable values for `onValue` and `offValue`. The same concept for LWT would make this plugin versatile.

**Comment by Dalbadel** [comment]
It would be great to have this setting.

**Comment by dezral** [comment]
yea, i have a sonoff basic with espurna, because i could not get it to go online with tasmota.. all my other sonoff work fine.. but not this one..

so i installed espurna and it works fine now, but its LWT is not online/offline but 0/1 on "ESPURNA-******/status"

**Comment by tzapu** [comment]
after a looooot of tinkering I was able to make this work with Tasmota

```
{
            "accessory": "mqttthing",
            "type": "outlet",
            "name": "socket-01",
....
            "caption": "socket",
            "topics": {
                "setOn": "cmnd/socket-01/power",
                "getOn": "stat/socket-01/POWER",
                "getOnline": {
                    "topic": "tele/socket-01/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
                }
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "logMqtt": true
        }
```

notice the transform function having to return the same values as onValue/offValue
this seems to work fine for me.

**Comment by arachnetech** [comment]
That's a great solution tzapu, thanks. I nearly just closed this issue as I think this is a perfectly acceptable solution, but since it makes the configuration a little harder to understand I've added an optional `onlineValue` configuration setting which can be set to the string representing an online state in version 1.0.20.
