### ISSUE TITLE
How to use Backlog Command 

### ISSUE THREAD

**Issue by einencool** [arachnetech/homebridge-mqttthing#388]
Hello and a happy and healthy new year.

I‘ve got one question, I would like to use the Backlog Command with MQTT to power off a switch with a delay via homebridge.
I always get the problem, that the command that is send has two „==„ symbols and I don‘t know how to clear them.

I also tried
"setOff": "cmnd/Dose124/backlog Power2 on;delay 100;power2 off",
But this also doesn‘t work, because then there was „== off“ added to the end of the line.

Can somebody please help me in this case? 
Maybe it‘s only a little thing that I‘m missing.

Thank you in advance.
Greets Chris

**Comment by ceraz68** [comment]
Never seen setOff as an mqttthing feature for its accessories, it's usually setOn. Backlog has nothing to do with mqtthing as it's a Tasmota command.

You mixed topic and payload. Normally mqtthing separates topics from payload so you could make a start on publish like:
```
"startPub": [
    { "topic": "cmnd/Dose124/backlog", "message": "Power2 on;delay 100;power2 off" }
]
```

If you are using a switch there is only an 'on' and 'off' status, so I would use an apply command as below when sending mqtt commands to the switch. Instead of the typical setOn topic of cmnd/Dose124/power use cmnd/Dose124/backlog instead. The apply code will execute before mqtt message publication and it will replace 'on' by the necessary backlog payload 'power on' and 'off' by the necessary backlog payload 'Power2 on;delay 100;power2 off'.

```
{
    "accessory": "mqttthing",
    "type": "switch",
    "name": "<name of switch>",
    "topics":
    {
        "getOn": 	        "stat/Dose124/power",
        "setOn": 	        {
                   "topic": "cmnd/Dose124/backlog",
                   "apply": "if (message=='off') return 'Power2 on;delay 100;power2 off'; return 'Power on'"
                                       }
    },
    "onValue": "on",
    "offValue": "off",
}
```

Note: as the switch is already on 'Power2 on;delay 100;power2 off' is the same as 'delay 100;power2 off'

**Comment by einencool** [comment]
Good morning @ceraz68 
Thank you very much for your help.
I'll try it today in the afternoon 👍 

The setoff command I've seen in any config, but it doesn't matter if it's there or not, it hasn't change anything...

Best regards 
Chris

**Comment by einencool** [comment]
Hello @ceraz68 
Thank you for your help, it works fine, except the status error, but I think that's ok and because of the "confirmationlimit".
I had to set 
"retryLimit": 0,
otherwise the command was send twice and then the outlet switches "OFF" for around one seconds and then returned "ON" for 10sec.

[7.1.2021, 16:41:42] [Handy laden] Publishing MQTT: cmnd/Dose124/backlog = Power2 on
[7.1.2021, 16:41:42] [Handy laden] Received MQTT: stat/Dose124/POWER2 = ON


[7.1.2021, 16:41:49] [Handy laden] Publishing MQTT: cmnd/Dose124/backlog = Power2 on;delay 100;power2 off
[7.1.2021, 16:41:49] [Handy laden] Received MQTT: stat/Dose124/POWER2 = ON
**[7.1.2021, 16:41:51] [Handy laden] Unresponsive - no confirmation message received on stat/Dose124/POWER2. Expecting [OFF].**
[7.1.2021, 16:41:59] [Handy laden] Received MQTT: stat/Dose124/POWER2 = OFF

This is my Config, maybe helpful for other people with the same "problem" :-)
        {
            "accessory": "mqttthing",
            "type": "outlet",
            "name": "Handy laden",
            "url": "mqtt://127.0.0.1:1883",
            "mqttOptions": {
                "keepalive": 30
            },
            "mqttPubOptions": {
                "retain": true
            },
            "topics": {
                "getOn": "stat/Dose124/POWER2",
                "setOn": {
                    "topic": "cmnd/Dose124/backlog",
                    "apply": "if (message=='OFF') return 'Power2 on;delay 100;power2 off'; return 'Power2 on'"
                },
                "getOnline": {
                    "topic": "tele/Dose124/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
                },
                "getInUse": {
                    "topic": "tele/Dose124/STATE",
                    "apply": "return JSON.parse(message).POWER"
                }
            },
            "onValue": "ON",
            "offValue": "OFF",
            "history": true,
            "confirmationPeriodms": 2000,
            "retryLimit": 0,
            "logMqtt": true,
            "manufacturer": "Gosund SP112 USB",
            "model": "Dose 124 USB",
            "serialNumberMAC": "Dose124 USB"
        },
