### ISSUE TITLE
Any chance of a troubleshooting FAQ?

### ISSUE THREAD

**Issue by petergreis** [arachnetech/homebridge-mqttthing#39]
I know I must be missing something simple, but with mosquitto I can issue

mosquitto_pub -h 192.168.1.201 -t cmnd/office-light/power -m 1
mosquitto_pub -h 192.168.1.201 -t cmnd/office-light/power -m 0

A sonoff flashed with tasmota firmware turns on and off without issue (as above). What (newbie warning here) is the appropriate line for the config.json file?

I currently have the following in the homebridge config file:

`{
      "accessory": "mqttthing",
      "type": "switch",
      "name": "office-light",
      "topics": {
        "getOn": "cmnd/office-light/status",
        "setOn": "cmnd/office-light/power"
      },
      "logMqtt": true,
      "integerValue": true,
      "turnOffAfterms": 20000
    },`

PS - Is there a forum for such issues?

**Comment by arachnetech** [comment]
We don't have a forum. Homebridge has a presence on reddit at https://www.reddit.com/r/homebridge/ but I don't know whether there are any homebridge-mqttthing users there.

You configuration looks correct to me if your MQTT server is running locally. If not, you'll need to add something like `"url": "http://192.168.1.201:1883",`.
