### ISSUE TITLE
Adaptive Lighting

### ISSUE THREAD

**Issue by nixmeer** [arachnetech/homebridge-mqttthing#393]
Hello :) 
Last year, Apple announced the adaptive lighting feature, which changes the light color throughout the day. Would it be possible to implement this into the light bulb accessory?
If so, would it just add another topic requiring the device to handle the color change or would it be handle by mqttthing? If the last option is the way to go, maybe there could be settings such as a temperature range and 4 time stamps (beginning of transition to daylight, ending of transition to daylight, beginning of transition to night light, ending of transition to night light)? 
To me, I’d would be easier since until now, none of my esp lights has internet access, just mqtt in the local network ➡️ they have no access to a current date and time

**Comment by arachnetech** [comment]
I did start looking at this, but work commitments mean it's still in a branch requiring completion. 

If I remember correctly, all colour temperature changes are generated automatically by Homebridge - so your ESP will receive notifications to change colour gradually. 

Supporting for a white light with colour temperature is pretty easy. Harder (and still to do) is generating the appropriate hue for coloured lights.

**Comment by christi-g** [comment]
I found this: https://developers.homebridge.io/HAP-NodeJS/classes/adaptivelightingcontroller.html
I hope this is helpful :)

**Comment by rcaceiro** [comment]
You already have adaptive lighting supoort?

**Comment by arachnetech** [comment]
Not yet, waiting for me to find time to complete still...

**Comment by ascl00** [comment]
Is it just the conversion of white colour to RGB? (like this https://tannerhelland.com/2012/09/18/convert-temperature-rgb-algorithm-code.html) ? There is an implementation here in javascript: https://gist.github.com/EDais/1ba1be0fe04eca66bbd588a6c9cbd666

Feel free to post what you have and I might be able to assist.

**Comment by kerberjg** [comment]
@ascl00 It's slightly more complicated, the Adaptive Lighting feature expects HomeKit devices to update the light color by themselves, and it has to be encoded in TLV8 instead of RGB or temperature

https://github.com/homebridge/homebridge/issues/2687
https://hexdocs.pm/tlv8/TLV8.html

**Comment by arachnetech** [comment]
That took longer than I'd hoped, sorry. However, this is now a release (1.1.27) which should support adaptive lighting - although I've only tested it on a very limited range of lights so far.

If config-ui-x doesn't offer the update, this may be because the previous version was a beta. Updating from the command line still works: `sudo npm update -g homebridge-mqttthing --unsafe-perms`
