### ISSUE TITLE
Smoke sensor doesn't work

### ISSUE THREAD

**Issue by sherazan** [arachnetech/homebridge-mqttthing#4]
Hi, I'm trying to use smoke sensor but it doesn't work.
I already use with success a lot of your other services.
I configured config.json and with a mqtt client I trying to alarm the sensor publishing 1 or 0 in the topic name, but nothing happen... (integervalue = true)
I thing that there is a missing comma at the endo of the following line:
""getSmokeDetected":      "<topic used to provide contact sensor state>"" but I already added.
Please, can you help me?
Thanks

**Comment by arachnetech** [comment]
There is an error in my implementation. 

Line 406 of index.js should read:

`return val ? Characteristic.SmokeDetected.SMOKE_DETECTED : Characteristic.SmokeDetected.SMOKE_NOT_DETECTED;`

not the existing:

`return val ? Characteristic.ContactSensorState.SMOKE_DETECTED : Characteristic.ContactSensorState.SMOKE_NOT_DETECTED;`

I will fix this in the next release.

**Comment by arachnetech** [comment]
Fixed in version 1.0.7.
