### ISSUE TITLE
No temperatureand no humidity ?

### ISSUE THREAD

**Issue by NoTrace-Kai** [arachnetech/homebridge-mqttthing#40]
Hi there ...
perhaps someone can help me ?!
I installed MQTT on a ESP8266/BME280 with ESPEasy and configured an OpenHAB MQTT Profile,
like in this howto:
https://www.bastelgarage.ch/index.php?route=extension/d_blog_module/post&post_id=15
Than I installed on another ESO8266 a MQTT Broker.
The Broker gets the Data from the other ESP:

received topic '/wohnung/xxx/temperature' with data '21.53'
received topic '/wohnung/xxx/humidity' with data '36.44'
received topic '/wohnung/xxx/pressure' with data '1015.76'

But when i put the config in my homebridge no temp and no humidity will be shown.

 {
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "ESP01 Test Temp",
            "url": "http://192.168.2.xxx:1883",
            "topics": {
                "getCurrentTemperature": "/wohnung/laura/temperature"
            }
        },
        {
            "accessory": "mqttthing",
            "type": "humiditySensor",
            "name": "ESP01 Test Humidity",
            "url": "http://192.168.2.xxx:1883",
            "username": "ESP_01",
            "password": "ESP_01",
            "topics": {
                "getCurrentRelativeHumidity": "/wohnung/laura/humidity"
            }
        }

What did i do wrong? Please hekp ;)

CU Kai

**Comment by arachnetech** [comment]
Closing for now as @pbksol's suggestion looks like a very likely solution, but please re-open if necessary.
