### ISSUE TITLE
Keepalive Read Request 

### ISSUE THREAD

**Issue by ipearx** [arachnetech/homebridge-mqttthing#41]
Hi I'm setting up Homebridge to connect to a Victron Color Controller (Venus OS) using your plugin.

The problem I've got is the device requires a keepalive publish sent every 30 seconds, otherwise it stops broadcasting anything. I have it working nicely manually by setting up a switch to send the suggested 'keepalive' broadcast (R/[myDeviceIDHere]/system/0/Serial), so activating the switch in the home app happily starts showing the other values for 30 seconds, then they go back to 0.

Any ideas what the best way to implement this is so it's regularly sending a broadcast?

Also a side note, your example code for applying functions doesn't work with the Victron gear, as it stops broadcasting the javascript fails with an error. I added a simple check to ensure the value exists before using it. Here's my config so far:

`
      {
        "accessory": "mqttthing",
        "type": "temperatureSensor",
        "name": "Voltage",
        "url": "http://192.168.1.101:1883",
        "mqttOptions": { "keepalive": 30 },
        "topics": {
          "getCurrentTemperature": {
            "topic": "N/[myDeviceIDHere]/battery/258/Dc/0/Voltage",
            "apply": "return (message!='') ? JSON.parse(message).value.toFixed(0) : 0;"
          }
        },
        "logMqtt": true
      },
      {
        "accessory": "mqttthing",
        "type": "humiditySensor",
        "name": "Battery",
        "url": "http://192.168.1.101:1883",
        "mqttOptions": { "keepalive": 30 },
        "topics": {
          "getCurrentRelativeHumidity": {
            "topic": "N/[myDeviceIDHere]/battery/258/Soc",
            "apply": "return (message!='') ? JSON.parse(message).value.toFixed(0) : 0;"
          }
        },
        "logMqtt": true
      },
      {
        "accessory": "mqttthing",
        "type": "outlet",
        "name": "Victron Keepalive",
        "url": "http://192.168.1.101:1883",
        "mqttOptions": { "keepalive": 30 },
        "topics": {
          "setOn": "R/[myDeviceIDHere]/system/0/Serial",
          "getOn": {
            "topic": "N/[myDeviceIDHere]/battery/258/Soc",
            "apply": "return (message!='') ? true : false;"
          }
        },
        "logMqtt": true
      }`

**Comment by ipearx** [comment]
In the end I simply added a CRON job to my Raspberry Pi to keep it alive. Two jobs, separated by 30 seconds because CRON only supports 1 second.

`
   * * * * * /home/pi/keep_victron_alive.sh
   * * * * * ( sleep 30 ; /home/pi/keep_victron_alive.sh )
`

**Comment by arachnetech** [comment]
Thanks. Closing as you have a solution.
