### ISSUE TITLE
Athom Power monitoring Tasmota plug

### ISSUE THREAD

**Issue by jat80** [arachnetech/homebridge-mqttthing#411]
Hi there,

Does anyone have a configuration for [this Athom Plug](https://www.aliexpress.com/item/1005001670435059.html?spm=a2g0o.productlist.0.0.3c4c2dffW4eFCL&algo_pvid=cdd02597-b6f9-43c5-a0d1-6f41cbf72d40&algo_expid=cdd02597-b6f9-43c5-a0d1-6f41cbf72d40-2&btsid=0bb0623a16139563242302405e642a&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_)

Any help would be appreciated.  It is flashed with Tasmota.

**Comment by jeankone** [comment]
check for the sonoff pow r2 in tested configurations - should work also for this plug

**Comment by jat80** [comment]
> check for the sonoff pow r2 in tested configurations - should work also for this plug

Thanks for the heads up. Will give it a go.

**Comment by jat80** [comment]
the Sonoff POW config seems to work!  Thanks @jeankone 
Power consumption seems to only show in EVE app not in native HOME app.  Is that the norm?

**Comment by NorthernMan54** [comment]
Yes, that is correct

**Comment by jat80** [comment]
Thanks everyone!  Will close.
