### ISSUE TITLE
turnOffAfter not working.....

### ISSUE THREAD

**Issue by petergreis** [arachnetech/homebridge-mqttthing#42]
Should turnOffAfter work for switches and lightbulbs? I have a few lights I would very much light to turn off automatically (after, say 20 minutes - the ones that the kids forget). And just to confirm, the command takes an argument in ms, not seconds?

My appropriate section below:

{
      "accessory": "mqttthing",
      "type": "switch",
      "name": "office-light",
      "url": "http://192.168.1.201:1883",
      "caption": "Office Light",
      "topics": {
        "getOn": "cmnd/office-light/status",
        "setOn": "cmnd/office-light/power",
        "setOff": "cmnd/office-light/power"
      },
      "turnOffAfter": 6000,
      "logMqtt": false,
      "integerValue": true,
      "manufacturer": "ITEAD"
    },

**Comment by AustinSnow** [comment]
Use turnOffAfterms instead of turnOffAfter.

**Comment by arachnetech** [comment]
Yes, the configuration setting is `turnOffAfterms`. (Thanks, AustinSnow.) There's an example in my test configuration (currently line 118).
