### ISSUE TITLE
Help with config/understanding topics

### ISSUE THREAD

**Issue by nicknicknickos** [arachnetech/homebridge-mqttthing#423]
Hi community,

I have recently installed several Aeotec Nano switches in behind wall light switches. These are working fine physically with a push button, and also in zwavejs2mqtt. I can see the switches and all of their values. However, I am having a hard time trying to get homebridge-mqttthing to work and turn a light on/off. Here's what I have so far:

- zwavejs2mqtt, mosquitto and homebridge-mqttthing all run in docker containers on a raspberry pi
- I can log into zwavejs2mqtt UI and can see the nano switch as a zwave device
- I see the topics of the BinarySwitch as 5-37-0-currentValue, 5-37-0-targetValue etc 
<img width="677" alt="Screen Shot 2021-03-24 at 10 55 44 am" src="https://user-images.githubusercontent.com/20041179/112234293-4f630200-8c90-11eb-8f03-e566ba17f85c.png">
- If I click on the 'On/Off' button from the above screenshot, I see the following mqtt message via MQTT Explorer, and the light goes on/off 
<img width="1011" alt="Screen Shot 2021-03-24 at 10 55 53 am" src="https://user-images.githubusercontent.com/20041179/112234370-80dbcd80-8c90-11eb-9207-545886a9667e.png">
- Here's my config in homebridge for this light: 

    "accessories": [
        {
            "type": "lightbulb-OnOff",
            "name": "Dining Room",
            "url": "mqtt://localhost:1883",
            "logMqtt": true,
            "topics": {
                "getOn": "zwave/dining_room/dining_room/37/0/targetValue",
                "setOn": "zwave/dining_room/dining_room/37/0/currentValue"
            },
            "onValue": "true",
            "offValue": "false",
            "accessory": "mqttthing"
    }
- Whenever I turn the light on/off via HomeKit, a MQTT message is posted:
`[3/24/2021, 10:56:22 AM] [Dining Room] Publishing MQTT: zwave/dining_room/dining_room/37/0/currentValue = true`
- I can see this change in MQTT Explorer, but the change is different to when clicking on the button in the UI above 
<img width="1005" alt="Screen Shot 2021-03-24 at 10 56 27 am" src="https://user-images.githubusercontent.com/20041179/112234617-02336000-8c91-11eb-922b-107cb24cdbfc.png">
- The light doesn't actually turn on or off.

Can anyone please guide me as to what I am doing wrong. I am 100% sure this is user error, but am at a bit of a loss as to what to do next.
Thanks!

**Comment by tuxthepenguin84** [comment]
I have this exact same question.

**Comment by nicknicknickos** [comment]
@tuxthepenguin84 I figured my issue out, hope this helps:

I was sending json timestamps, as well as the 'true'/'false' payload which meant this plugin wasn't able to properly parse the value and update HomeKit. You can see this in the above code:

`{"time":1616709411429,"value":false}`

I changed a setting on zwavejsmqtt in Settings -> Gateway -> Payload Value to 'Just Value' and that worked

**Comment by tuxthepenguin84** [comment]
Thanks for the reply and this helps. Do you know if it's possible to be able to send updates from Homekit -> Homebridge -> zwavejs2mqtt? So basically have Homekit turn things on and off through zwavejs2mqtt.

**Comment by nicknicknickos** [comment]
Yes, entirely possible. Here is my setup:
- Aeotc switches
- Zwave stick into pi, running zwavejs2mqtt
- mosquito broker on pi
- homebridge on pi

With the below config, I can send an mqtt message from HomeKit -> homebridge -> mqtt broker (mosquito) -> zwavejs2mqtt -> aeotc switch
`{
            "type": "lightbulb-OnOff",
            "name": "Dining Room Downlight",
            "url": "mqtt://localhost:1883",
            "logMqtt": true,
            "topics": {
                "getOn": "zwave/dining_room/Downlight/37/0/currentValue",
                "setOn": "zwave/dining_room/Downlight/37/0/targetValue/set"
            },
            "accessory": "mqttthing"
        },`

Important things: 
- getOn looks at zwavejs2mqtt and finds the current status of the switch. e.g., if you turn the switch on physically at the wall, this value is updated to 'on' and Homebridge will receive this message and display the light as 'on' in the home app
- setOn send a message to the switch, telling it to turn on or off (or whatever the mqtt path specifies). 

You need to have `/set` after the setOn command for it to work.

**Comment by tuxthepenguin84** [comment]
I got it working, thank you so much! I was missing the /get and /set values.

**Comment by jmac0027** [comment]
@nicknicknickos would you be willing to provide a bit more info on how to setup.

I have Homebridge running on a RPI3.  I just bought a Z-Stick Gen5.  Although I've been running homebridge for some time, I am a newbie with linux/Rasbian enviro.

Could you start from the beginning.  I've never used docker before.  I was looking at (https://phoenixnap.com/kb/docker-on-raspberry-pi).  If I follow those directions would that be correct for this project? I assume hombridge would not need to be installed in Docker. 

Then there are the questions about zwavejs2mqtt.  I've reviewed (https://zwave-js.github.io/zwavejs2mqtt/#/README).  What's the best setup running as a volume, local folder or service?

You said you have homebridge-mqttthing running in a docker container.  Isn't that a homebridge plugin?

As you can see I am looking for the Dummies guide for getting this up and running without toasting my current setup.  

Thanks for any and all help.
