### ISSUE TITLE
[Q] Irrigation - what is the concept?

### ISSUE THREAD

**Issue by andrasg** [arachnetech/homebridge-mqttthing#425]
What is the concept of `inUse` and `active` for the irrigation controller? I am 

If I simply echo the value received in `setActive` into `getActive`, the HomeKit UI will show the zone as `Idle`. Should the irrigation system simply start running after this and report `true` into `getInUse` while it is running, and report `false` into both `getInUse` and `getActive` at the end of a cycle?

Is there any way to control what values are showing up in the duration for the zone?

Similarly, what does `active` mean for the complete irrigation system and when would the `setActive` topic be addressed?

**Comment by BerndGewehr** [comment]
In my plugin, you can't even select irrigation system from the list of accessory types. Is this by intention?

**Comment by wunaidage** [comment]
I cannot select the irrigation system too. Is it only possible by setting in config?
