### ISSUE TITLE
Can't add a dimmable bulb with 0-255 brightness and on/off

### ISSUE THREAD

**Issue by Oleg-Rent4all** [arachnetech/homebridge-mqttthing#427]
How can I add a dimmable bulb with 0-255 brightness?
Config: "topics": {
                "getWhite": "/devices/wb-mrgb_157/controls/Brightness R",
                "setWhite": "/devices/wb-mrgb_157/controls/Brightness R/on",
                "getOn": "/devices/wb-mrgb_157/controls/Enable R",
                "setOn": "/devices/wb-mrgb_157/controls/Enable R/on"
                 }
I get a error: Ignoring invalid value [0] for On - not a Boolean
If I use getWhite->getBrightness everything works but I can't set brightness more then 100

**Comment by arachnetech** [comment]
Validation-related. Should be fixed in 1.1.28.
