### ISSUE TITLE
Mqtt retain.

### ISSUE THREAD

**Issue by dezral** [arachnetech/homebridge-mqttthing#43]
I use node-red to read a switch published on mqtt, but when i reload node-red it don't get the status in.. 

could it be an idea to be able to set MQTT "retain" on certain accessory in homebridge-mqttthing ;-).

**Comment by transistorgit** [comment]
I think this request ist valid. If you set a switch in homekit (Home app) and there was a connection problem to the (wifi) device or it has rebooted because of power outage, it needs manual action to set the switch again.

**Comment by arachnetech** [comment]
You can set the retain flag on messages published by mqttthing using `mqttPubOptions` (see https://github.com/arachnetech/homebridge-mqttthing#mqtt-settings). However, there's nothing that mqttthing can do about the retain flags on messages that it doesn't publish.
