### ISSUE TITLE
Air Quality sensor feedback on homebridge status

### ISSUE THREAD

**Issue by mleiva5** [arachnetech/homebridge-mqttthing#430]
@arachnetech First of all, thanks for the awesome plugin!

I'm set the Air Quality sensor MQQT sending strings as UNKNOWN, EXCELLENT, GOOD, FAIR, INFERIOR or POOR. It is working, however the homebridge status displays the following message:

[23/04/2021, 15:20:42] [Bathroom Air Quality] Unable to validate Air Quality, format [uint8] - {"_events":{},"_eventsCount":3,"iid":10,"value":2,"status":null,"statusCode":0,"subscriptions":2,"displayName":"Air Quality","UUID":"00000095-0000-1000-8000-0026BB765291","props":{"format":"uint8","perms":["ev","pr"],"minValue":0,"maxValue":5,"minStep":1,"validValues":[0,1,2,3,4,5]}}

I tried setting the Air Quality string to two other:
"airQualityValues": [ "0", "1", "2", "3", "4", "5" ],
"airQualityValues": [ 0,1,2,3,4,5 ],
Neither worked, the only working config is the following:

My current config is like this:

        {
            "accessory": "mqttthing",
            "type": "airQualitySensor",
            "name": "Bathroom Air Quality",
            "topics": {
                "getAirQuality": "Bathroom/Quality",
                "getVOCDensity": "Bathroom/VOC"
            }
        },

Is there a way to not get this warning from the plugin?
Also, how do I set custom values such as 0 through 5?

Thanks in advance!

**Comment by arachnetech** [comment]
Apologies for the delay. Hoping to address shortly...

**Comment by arachnetech** [comment]
Version 1.1.28 should fix the validation warnings.

**Comment by arachnetech** [comment]
Custom air quality values can be configured like this:

```
{
            "accessory": "mqttthing",
            "type": "airQualitySensor",
            "name": "Air Quality",
            "topics": {
                "getAirQuality": "test/airquality"
            },
            "airQualityValues": [ "0", "1", "2", "3", "4", "5" ]
        }
```

**Comment by mleiva5** [comment]
Thank you!!
