### ISSUE TITLE
No state for manual switch switching

### ISSUE THREAD

**Issue by JohannesPl** [arachnetech/homebridge-mqttthing#444]
Hi

I have a Sonoff Basic - flashed with **Tasmota 9.4.0**.
I also have a RaspberryPi 3B+ with **Raspbian Buster** and **Homebridge 1.3.4.**
And finally I have **homebridge-mqttthing v1.1.28** 

What I do not have is a state when turning on the switch manually.
I can change the state via IOS and WEB without any issue and therefore the state is shown correctly.
As soon I change the state manually it it not refreshed within homebridge.

Where is my mistake?
Here is the config - extract:
    
```
            "type": "switch",
            "name": "Testschalter",
            "url": "mqtt://127.0.0.1:1883",
            "username": "admin",
            "password": "admin",
            "topics": {
                "getOnline": "tele/tasmota06s/STATE",
                "getOn": "stat/tasmota06s/RESULT",
                "setOn": "cmnd/tasmota06s/POWER"
            },
            "integerValue": false,
            "history": false,
            "accessory": "mqttthing"
```

**Comment by JohannesPl** [comment]
Am I the only one who have this problem?

**Comment by arachnetech** [comment]
I don't use Tasmota, but I can't see anything obviously wrong in your configuration. Please would you capture some example messages that your switch publishes to stat/tasmota06s/RESULT when its state is changed manually.

**Comment by JohannesPl** [comment]
Here are the logs, when changing the statee manually.
```
13:38:08.127 MQT: stat/tasmota06s/RESULT = {"POWER":"ON"}
13:38:08.131 MQT: stat/tasmota06s/POWER = ON
13:38:11.472 MQT: stat/tasmota06s/RESULT = {"POWER":"OFF"}
13:38:11.476 MQT: stat/tasmota06s/POWER = OFF
```

**Comment by arachnetech** [comment]
Thanks. Mqttthing by default expects true and false rather than ON and OFF. You can change this using the onValue and offValue settings. See https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Configuration.md#boolean-value-settings for details.

**Comment by arachnetech** [comment]
You'll need to decode the JSON too. There's a JSON codec which will do this, or you can use an apply function.

**Comment by JohannesPl** [comment]
Ok. I am using the homebridge UI.
I added OnValue = ON  and OffValue = OFF.

```
        {
            "type": "switch",
            "name": "Tasmota05s",
            "username": "admin",
            "password": "admin",
            "topics": {
                "getOnline": "tele/tasmota05s/STATE",
                "getOn": "stat/tasmota05s/RESULT",
                "setOn": "cmnd/tasmota05s/POWER"
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "accessory": "mqttthing"
        }
```
But what about your second comment. I am quite not sure what to do here. My skills are not that extensive.

**Comment by arachnetech** [comment]
Unfortunately the additional features you need aren't supported by the GUI. I'll create you an example config when I get a chance - hopefully this evening.

**Comment by JohannesPl** [comment]
This would be great. Thanks in advance.

**Comment by NorthernMan54** [comment]
@JohannesPl Did you try homebridge-tasmota? It supports most tasmota devices without requiring per device configurations?

**Comment by JohannesPl** [comment]
@NorthernMan54 Not yet. I will have a look at it later. Thanks for the hint.

**Comment by arachnetech** [comment]
Using homebridge-tasmota sounds like it would be a lot easier (thanks, @NorthernMan54), but if you do want to try again with MQTTThing then the following apply function can be used to decode the JSON in the RESULT message:

```
        {
            "type": "switch",
            "name": "Tasmota05s",
            "username": "admin",
            "password": "admin",
            "topics": {
                "getOnline": "tele/tasmota05s/STATE",
                "getOn": {
                    "topic": "stat/tasmota05s/RESULT",
                    "apply": "return JSON.parse( message ).POWER"
                },
                "setOn": "cmnd/tasmota05s/POWER"
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "accessory": "mqttthing"
        },        
```

**Comment by JohannesPl** [comment]
Hi arachnetech,
Big thanks to you. Your code is working quite well. Awesome. Thank you very much!

J.P.
