### ISSUE TITLE
GetValues not reporting through to homekit(home.app

### ISSUE THREAD

**Issue by drpau** [arachnetech/homebridge-mqttthing#451]
Hi, firstly love the plugin and thanks for writing it.

I have a number of lights flashed with tasmota.  The lights themselves, work perfectly fine.  I can amend the brightness / CT / RGB / Dimmer without issue.  I also have automation which when motion is detected, to turn the light on, and set it at a specific color temp/brightnes.  Again these automation work fine.

The problem I'm having is "getValues" arent updating home.app

Example:
Lets assume I manually set my lights to be 50% bright and color purple.  I turn off the light through homeapp.  Then, someone walks into the room, motion is detected and turns the light on to 100% bright and color of bright white through automations.  Home.app will report that the light is ON, however it will still show the color as purple and the brightness at 50%.

Here is a copy of one of my lights (same config apart from the name/topic change from ensuite1 to ensuite2) configs.

```
{
            "type": "lightbulb",
            "name": "Ensuite1",
            "mqttPubOptions": {
                "retain": false
            },
            "logMqtt": true,
            "topics": {
                "getRGBWW": "stat/ensuite1/RESULT",
                "setRGBWW": "cmnd/ensuite1/Color",
                "getOn": "stat/ensuite1/POWER",
                "setOn": "cmnd/ensuite1/EVENT",
                "getBrightness": "stat/ensuite1/RESULT",
                "setBrightness": "cmnd/ensuite1/Dimmer",
                "getColorTemperature": "stat/ensuite1/RESULT",
                "setColorTemperature": "cmnd/ensuite1/CT"
            },
            "confirmationPeriodms": 1000,
            "onValue": "ON",
            "offValue": "OFF",
            "hex": true,
            "switchWhites": true,
            "accessory": "mqttthing"
        },
```

Here is me turning my lights on (homebridge log) You can see that topic stat/ensuite1/RESULT has the "Color" value
```
[6/11/2021, 9:17:20 AM] [Ensuite1] Publishing MQTT: cmnd/ensuite1/EVENT = ON
[6/11/2021, 9:17:20 AM] [Ensuite1] Received MQTT: stat/ensuite1/RESULT = {"Event":"Done"}
[6/11/2021, 9:17:20 AM] [Ensuite1] Received MQTT: stat/ensuite1/RESULT = {"If":"Done"}
[6/11/2021, 9:17:20 AM] [Ensuite1] Received MQTT: stat/ensuite1/POWER = ON
[6/11/2021, 9:17:20 AM] [Ensuite1] Received MQTT: stat/ensuite1/RESULT = {"POWER":"ON","Dimmer":100,"Color":"000000FF00","HSBColor":"0,0,0","White":100,"CT":153,"Channel":[0,0,0,100,0]}
```

Here is me changing the light's value through home.app
```
[6/11/2021, 9:19:35 AM] [Ensuite1] Received MQTT: stat/ensuite1/POWER = ON
[6/11/2021, 9:19:35 AM] [Ensuite1] Received MQTT: stat/ensuite1/RESULT = {"POWER":"ON","Dimmer":63,"Color":"A100830000","HSBColor":"311,100,63","White":0,"CT":153,"Channel":[63,0,51,0,0]}
```

Why is my stat/ensuite1/RESULT for getBrightness and getColorTemperature not flowing end to end?

**Comment by arachnetech** [comment]
I believe you'll need apply functions, like the example I gave in issue #444.

**Comment by drpau** [comment]
Great thank you so much for the response, however I have a new issue which I will open a new ticket for. Thank you!
