### ISSUE TITLE
Activate Notification Default

### ISSUE THREAD

**Issue by TheReiner** [arachnetech/homebridge-mqttthing#464]
Is it possible to enable by default Notification on the configuration ?

Exemple with a contact sensor and json element name like "notification"
```
{
            "accessory": "mqttthing",
            "type": "contactSensor",
            "name": "Door",
            "caption": "Door",
            "topics": {
                "getContactSensorState": "SmartDEN_Notifier/MACADRESS/DI1"
            },
            "integerValue": "true",
            "onValue": "Off",
            "offValue": "On",
            "notification":1
   }
```
And the result, it will turn on Notification, for all persons and all device...

![IMG_4336](https://user-images.githubusercontent.com/18024918/127055452-7a208c74-f6b6-48f6-a308-d465821e98cd.PNG)

I'm sorry for my english, this is not my native language. i hope you will understand me.

**Comment by arachnetech** [comment]
I don't believe HomeKit supports that, no.

**Comment by TheReiner** [comment]
i think it's supported... because, it already exists for the doorbell

**Comment by arachnetech** [comment]
In MQTTThing?

**Comment by TheReiner** [comment]
No, but in HomeBridge yes with the plug-in "homebridge-videodoorbell" for exemple.

**Comment by arachnetech** [comment]
Aha, I'll take a look - thanks.

**Comment by arachnetech** [comment]
I can't see any configuration for default notifications on https://www.npmjs.com/package/homebridge-videodoorbell. Are you sure the difference isn't just that doorbells give notifications by default?

**Comment by TheReiner** [comment]
It's "On" by default for every device  on HomeKit (iPhone, iPad, Mac, etc) and we can't change on HomeBridge configuration, but on your iPhone we can turn off notification for the devise...

**Comment by TheReiner** [comment]
https://developer.apple.com/documentation/homekit/hmcharacteristic/1624189-enablenotification

**Comment by arachnetech** [comment]
As a homebridge accessory, I have access to https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/definitions/ServiceDefinitions.ts and https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/definitions/CharacteristicDefinitions.ts. Can you see an equivalent there?

**Comment by TheReiner** [comment]
No, I don't see ... So I think we have to open a problem on HomeBridge to implement this function ^^

**Comment by NorthernMan54** [comment]
@TheReiner that piece of documentation you dug up applies to coding of an app for your iPhone or AppleTV and not the api that Homebridge uses.  Homebridge uses the HomeKit Accessory Protocol which does not include this.
