### ISSUE TITLE
AirQualitySensor Problem

### ISSUE THREAD

**Issue by burakcankose** [arachnetech/homebridge-mqttthing#465]
I'm building an air quality sensor with MQ135, I combined it with DHT22, it turned out a good result, I compiled it with ESPhome and MQTT and transferred it to Homebridge. I am trying to convert the value on the topic from which I received the data to the data of the quality sensor, but it does not work, can you help me? 

[30/07/2021, 15:01:17] [Hava Kalite Sensörü] Received MQTT: mq135/sensor/corrected_ppm_co2/state = 8.5
[30/07/2021, 15:01:17] [Hava Kalite Sensörü] Warning: airQuality received [8.5] which is not in configured values {"UNKNOWN":0,"EXCELLENT":1,"GOOD":2,"FAIR":3,"INFERIOR":4,"POOR":5}

I could not run the fix learner in the tested codes, what should I do?

            "apply": "eco2 = JSON.parse(message).CCS811.eCO2; return (eco2 > 2000 ? 'POOR' : eco2 > 1600 ? 'INFERIOR' : eco2 > 1100 ? 'FAIR' : eco2 > 700 ? 'GOOD' : eco2 <= 700 ? 'EXCELLENT' : 'UNKNOWN');"

**Comment by arachnetech** [comment]
You should be able to use an apply function like that, but I don't think you need the JSON.parse bit as your message isn't JSON.
