### ISSUE TITLE
Send a payload of "2,message"

### ISSUE THREAD

**Issue by RaffoNin** [arachnetech/homebridge-mqttthing#469]
I currently have a blinds controller flashed with Tasmota (https://templates.blakadder.com/zemismart_YH002.html) and it requires me to send a payload of **2,message** to cmnd/xx/TuyaSend2 in order to change the percentage. Is there a way to do this with the topic apply function?
   
Here is my current configuration right now but it only sends the payload of the percentage without "2," which does not control my blinds. 

 "accessory": "mqttthing",
    "type": "windowCovering",
    "name": "xx",
    "manufacturer": "Zemismart",
    "model": "xx",
    "serialNumber": "xx",
    "firmwareRevision": "Tasmota",
    "url": "xx",
    "username": "xx",
    "password": "xx",
    "logMqtt": true,
    "topics": {
        "getCurrentPosition": {
            "topic": "tele/xx/STATE",
            "apply": "return JSON.parse(message).Dimmer;"
        },
        "setTargetPosition": {
            "topic": "cmnd/xx/TuyaSend2",
            "apply": "return (2,message)"
        }
    }
} 

Here is the log in Homebrige with my current configuration:
[15/08/2021, 16:08:18] [xx] Publishing MQTT: cmnd/xx/TuyaSend2 = 37

Here is the payload that controls my blinds:
<img width="441" alt="Screen Shot 2021-08-15 at 4 07 51 PM" src="https://user-images.githubusercontent.com/85386859/129471642-83219159-204c-47a3-86f8-53c3a80435a2.png">

**Comment by rbswift** [comment]
if you want to send it as a string you could try `"return ('2,' + message);"`

**Comment by RaffoNin** [comment]
Sorry won't be able to try this as I was able to get it to work with Home Assistant. Thanks anyway!
