### ISSUE TITLE
Stop publishing to 'Set On' topic while changing speed

### ISSUE THREAD

**Issue by rithask** [arachnetech/homebridge-mqttthing#474]
Hey, how do I stop Mqttthing from publishing to 'Set On' topic while changing fan rotation speed? This causes my fan to turn off just after changing the rotatoin speed. 

![image](https://user-images.githubusercontent.com/74851056/132505595-d045f051-8649-4d1d-ace4-08214509ee06.png)

**Comment by arachnetech** [comment]
Mqttthing mostly just forwards the notifications that it receives from Homekit - so it's likely that Homekit is telling it that the fan is on whenever its speed is changed and mqttthing is simply publishing both. (This certainly appears to be the case, looking at the code.) However, I'll see if I can add an option to skp publishing of duplicate values.

It may still not be perfect using a 'toggle' topic, but if might make it better...

**Comment by arachnetech** [comment]
I've just added an `optimizePublishing` option in version 1.1.31.
