### ISSUE TITLE
Window and windows covering

### ISSUE THREAD

**Issue by i17brn** [arachnetech/homebridge-mqttthing#477]
These accessories are only designed to modify the top-down position, however, many windows and curtains open to the sides, that is, horizontally, is it possible that the type of window and curtain that one has is chosen when adding the accessory?

**Comment by arachnetech** [comment]
Not as far as I'm aware - homekit limitation. mqttthing can only expose 'services' defined here:
https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/definitions/ServiceDefinitions.ts

**Comment by rbswift** [comment]
you can use a WindowCovering and in the Apple Home app settings for the accessory click on the icon and change it to a horizontally opening type of covering

**Comment by i17brn** [comment]
> you can use a WindowCovering and in the Apple Home app settings for the accessory click on the icon and change it to a horizontally opening type of covering

I don’t have this option, I use a rpi like a bridge and esp32 devices for automation. In the windows covering device I have this options 

(it is in Spanish but it very similar) 

![BC63762B-8966-4353-9FB6-7ADA298C3F67](https://user-images.githubusercontent.com/44007105/134814154-645d6357-663d-477d-aece-57e9a3db1386.png)
