### ISSUE TITLE
Contact door sensor

### ISSUE THREAD

**Issue by i17brn** [arachnetech/homebridge-mqttthing#478]
Many people do not have electronic door closing mechanisms many times alone they are interested in knowing the status of the door, if it is open or closed, you could add a contact sensor for the door of a room

#feature:request

**Comment by arachnetech** [comment]
Already exists, I believe:
https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Accessories.md#contact-sensor

... or were you looking for something different?
