### ISSUE TITLE
RGBWW support for lightbulb

### ISSUE THREAD

**Issue by Kepete** [arachnetech/homebridge-mqttthing#48]
Great plugin. I soon have replaced all my plugins with only this one. But some features are still missing and this issue is about one of them :) 
I have a H801 RGBWW controller flashed with Tasmota. It has RGB, warm White and cold White channels.
Mqttthing currently doesn't support RGBWW so the temperature slider in home app does not change the temperature with the warm white and cold white channels. 
Would it be possible to add RGBWW support.

**Comment by GSanCap** [comment]
+1

**Comment by GerSant** [comment]
@Kepete can you share here the mqttthing accessory configuration for the Tasmota flashed Controller? Thanks in advance

**Comment by Kepete** [comment]
Here you go. But I'm not sure if it is the best configuration for it. 
Still waiting for RGBWW support for mqttthings :/ 

```
{
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "LED",
            "url": "mqtt://192.168.x.x",
            "username": "usr",
            "password": "psw",
            "caption": "<label (optional)>",
            "topics": {
                "getOn": "stat/sonoff/POWER",
                "setOn": "cmnd/sonoff/POWER",
                "getBrightness": "cmnd/sonoff/color",
                "setBrightness": "cmnd/sonoff/color",
                "getRGBW": "cmnd/sonoff/color",
                "setRGBW": "cmnd/sonoff/color",
                "getOnline": {
                    "topic": "tele/sonoff/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
                }
            },
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF"
        }
```

**Comment by GerSant** [comment]
I make it, now my only white CCT Led Strip (WWCW) works like a charm, i use an Sunix RGBWWCW Led Strip Controller with Tasmota 6.5 with my own custom Template (DWMs -> GPIOs bindings) and this MQTTThing Accessory Configuration:


```
    {
      "accessory": "mqttthing",
      "type": "lightbulb",
      "name": "LED Strip Controller",
      "url": "mqtt://192.168.0.253",
      "topics":
      {
        "getOn": "stat/sunix-a3ef/POWER",
        "setOn": "cmnd/sunix-a3ef/POWER",
        "getBrightness": "nodered/sunix-a3ef/dimmer/get",
        "setBrightness": "cmnd/sunix-a3ef/Dimmer",
        "getColorTemperature": "nodered/sunix-a3ef/colortemp/get",
        "setColorTemperature": "cmnd/sunix-a3ef/CT"
      },
      "onValue": "ON",
      "offValue": "OFF"
    }
```

Regards

**Comment by Kepete** [comment]
But without nodeRED it's not possible to get an RGBWW light working.

**Comment by GerSant** [comment]
Maybe With the feature of Applying funcions in the topic

**Comment by arachnetech** [comment]
@Kepete Thanks for the reminder! What format are you looking for RGBWW to be published in on MQTT?

**Comment by Kepete** [comment]
@arachnetech Hmm, can't remember what my idea was initially but I think all in one topic should work fine with Tasmota. As currently RGBW is also in one topic than RGBWW should be similarly built yes.

**Comment by Kepete** [comment]
But currently we the plugin has alos `"setWhite"` and `"getWhite"` for separately-published white levels. Adding this also for second white channel(RGBWW) probably would make sense.

**Comment by arachnetech** [comment]
I've been trying to find a way to support warm white and cold white with limited success by extracting them from hue/saturation/brightness values after conversion to RGB. While Homekit makes colour temperature available (as exposed separately already), its behaviour seems very buggy when this is used with coloured lights.

**Comment by arachnetech** [comment]
Wow, that was a struggle! :-)

Experimental support for RGBWWCW lights added in version 1.0.36. I don't have hardware supporting this to test against currently, but watching RGBWW values scroll past I think they're finally behaving how I wanted them to....

> If `topics.setRGBWW` is populated, a combined value is used in the format red,green,blue,warm_white,cold_white (each component ranging from 0-255). Warm and cold white components are set based on the colour values published by Homekit from the _Temperature_ control, and after warm and cold white are extracted any remaining white level in the RGB values is sent equally to both white channels. The RGB values used for warm white and cold white extraction can be configured with `warmWhite` and `coldWhite`, allowing calibration to RGBWW LED colours. (Homekit's warm white and cold white colours are used by default.) On/off may be set with `setOn` (otherwise "0,0,0,0,0" indicates off); brightness, hue, saturation and temperature topics are ignored. (Homekit's behaviour when a coloured (hue/saturation-supporting) light also attempts to support temperature can be unpredictable - so the RGBWW implementation does not use Homekit colour temperature.)

Please let me know how you get on with this, @Kepete.

Perhaps more usefully, I'll look at doing white lights with colour temperature as two components (warm_white,cold_white) next - maybe at the weekend. From my tests, colour temperature as published by homekit ranges from 140 (cold white) through 150 (neutral white) to 500 (warm white). I'd be interested to know how you're converting this to warm white/cold white components in Node Red. I assume the relationship is exponential?

**Comment by Kepete** [comment]
Ouh thanks! I will try to test this today evening or on the weekend.

**Comment by mientki** [comment]
How to set the accessory for use with Shelly RGBW2 with the mqtt protocol?
Topic mqtt looks like this:

**Comment by arachnetech** [comment]
@Kepete Did you ever get a chance to test `setRGBWW`? In theory I think this should do what you want.

I’ve been reviewing the many open mqttthing issues this afternoon and building a list of requested features - one of which is (still) outputting warm white and cold white components from HomeKit’s colour temperature.

**Comment by Kepete** [comment]
Sorry but no, I have not been able :( 
I myself requested it but then the light project which needed it went into dust. While I still believe I would need it in the future, so I hope you can keep this feature in mqttthing :) 

Thanks for your awesome work!

**Comment by arachnetech** [comment]
No problem! I’ll close this issue for now.
