### ISSUE TITLE
Add door accessory to avoid 2fa on homebridge-gsh plugin

### ISSUE THREAD

**Issue by renisganz** [arachnetech/homebridge-mqttthing#485]
Hi, congrats for great works!
What do you thing about to add DOOR (not garagedoor, not lock mechanism), to open, for example, a little garden gate?
I would like to avoid two factor autentication on google home application, considered that this gate is easily climbable.
what do you think?
any suggestion?
thanks

Renis

**Comment by FermedePommerieux** [comment]
use a switch accessory to control that door.

**Comment by arachnetech** [comment]
There is a Door service, which I'll add. It works just like Window (and has the same characteristics) - so you could also test with Window in the meantime.

**Comment by renisganz** [comment]
Hi, with the window sensor it's working fine. Only the icon associable in Apple Home it's a little bit sad, but it's working fine.
thanks

**Comment by renisganz** [comment]
Hi @FermedePommerieux , with the switch accessory it's working but it's not "elegant" say: "Turn on the gate".

**Comment by arachnetech** [comment]
I've added Door in 1.1.34.
