### ISSUE TITLE
How to prevent publishing switch topic without "= true"

### ISSUE THREAD

**Issue by djaytek** [arachnetech/homebridge-mqttthing#488]
I am trying to use with tasmota 1 relay switch and the command needs to be without =true/false or =1/0 but whatever I try in the plugin settings, I get the command as below that doesn't trigger the relay.

Publishing MQTT: cmnd/tasmotasw1/POWER toggle = true
Publishing MQTT: cmnd/tasmotasw1/POWER toggle = false

The command just needs to be:
Publishing MQTT: cmnd/tasmotasw1/POWER toggle
or
Publishing MQTT: cmnd/tasmotasw1/POWER on
or
Publishing MQTT: cmnd/tasmotasw1/POWER off

**Comment by Emilien-Lambert** [comment]
I have exactly the same problem I can't find a solution

**Comment by washcroft** [comment]
Share your topic config for this accessory

**Comment by FermedePommerieux** [comment]
Something like this ?
      "setOn": {
     "topic": "your topic";
     "apply": "if (message === true) {message = 'on'} else if (message === false) {message = 'off';} ; return message;"
    }

or 
 add

    "onValue": "on",
    "offValue": "off",

**Comment by arachnetech** [comment]
I think it's possible to return nothing (effectively undefined) from an apply function to suppress publishing.
