### ISSUE TITLE
please add pressure sensor

### ISSUE THREAD

**Issue by zmej-serow** [arachnetech/homebridge-mqttthing#49]
Hi!
It would be nice if you eventually add support for pressure sensor. I have an MQTT topic in which current atmospheric pressure is published as float number. For this moment I have to abuse "lightSensor" as this is the only accessory which can accept float number higher than 360 :)
Thanks.

**Comment by bartoszwas** [comment]
Pressure sensors are not supported by HomeKit. Only way is to use other kind of plugin.

**Comment by zmej-serow** [comment]
Oh. What a pity for HomeKit...
Thanks for info!
