### ISSUE TITLE
Best way to convert 0-99 value range to 0-100?

### ISSUE THREAD

**Issue by sofakng** [arachnetech/homebridge-mqttthing#494]
What's the best way (or only way?) to convert a value range of 0-99 to 0-100?

For example, my Z-Wave lights support a brightness of 0-99.  If you try to set a brightness of 100 it fails and ignores the value.

However, MQTT-Thing only supports values of 0-100.

How, or what is the best way, to convert these ranges between each other?

**Comment by washcroft** [comment]
In your apply function:

`return Math.max(message, 99);`
