### ISSUE TITLE
Latest 1.1.32 version cannot handle payload values of 0

### ISSUE THREAD

**Issue by washcroft** [arachnetech/homebridge-mqttthing#495]
```
[Front Door Lock] Received MQTT: zwave/nodeID_4/98/0/currentMode = {"time":1636392010660,"value":0,"nodeName":"","nodeLocation":""}

[Front Door Lock] Warning: lockCurrentState received [] which is not in configured values {"0":0,"254":3,"255":1,"Jammed":2}
```

Apply function: `return JSON.parse(message).value;`

Debug:

`console.log(message)`: 0
Version 1.1.31 `console.log(message?.toString() ?? '')`: 0
Version 1.1.32 `console.log(message ? message.toString() : '')`: (empty string)

https://github.com/arachnetech/homebridge-mqttthing/commit/b048d7023c0af35ccb92e350133730e36473fb30#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R1282

**Comment by arachnetech** [comment]
Should be fixed again in 1.1.33.
