### ISSUE TITLE
Help configuring Temp sensor

### ISSUE THREAD

**Issue by appleimperio** [arachnetech/homebridge-mqttthing#496]
Hi Im trying to get the Bed temp of my 3D printer through octoprint. Im getting this message in the homebridge logs after configuring the MQTThing temp sensor. 

```
[11/9/2021, 2:24:23 AM] [Genesis Bed Temp] Received MQTT: genesis/temperature/bed = {"actual": 22.1, "target": 0.0, "_timestamp": 1636442663}
[11/9/2021, 2:24:24 AM] [Genesis Bed Temp] Ignoring invalid value [NaN] for Current Temperature - not a number
```

I don't know how to get the number from actual I try this but Im pretty sure is wrong

```
   "topics": {
                "getCurrentTemperature": "genesis/temperature/bed",
                "apply": "return JSON.parse(message).actual;"
            }
```

but still having the second message, any help would be appreciate it
Thanks

**Comment by washcroft** [comment]
Try this apply function:

`return parseFloat(JSON.parse(message).actual);`

**Comment by appleimperio** [comment]
same error

**Comment by washcroft** [comment]
It's your config structure, it should look like this:

```
"topics": {
    "getCurrentTemperature": {
        "topic": "genesis/temperature/bed",
        "apply": "return parseFloat(JSON.parse(message).actual);"
}
```

**Comment by appleimperio** [comment]
Thank you thank you thank you!!!!!!! it workedddd just for learning the Float is to make sure not get as a string but a number? and if for example I want the target I just replaced the .actual for .target? Thanks again

**Comment by washcroft** [comment]
Yes, but you can probably remove the parseFloat() and have it as you originally did, it'll probably get handled/converted internally.

**Comment by andrelopesmrx** [comment]
I had the same issue, and without parseFloat I was getting 0 in the Home app.

**Comment by appleimperio** [comment]
@washcroft Hi Im trying to create dummy dimmable bulb that the 0-100 percent will represent the progress of the print. The bulb turn on when the print start and off when it stop but I'm not getting any percent from the brightness. This is the configuration:

```
{
            "type": "lightbulb-Dimmable",
            "name": "Genesis Print progress",
            "username": "user",
            "password": "pass",
            "logMqtt": true,
            "topics": {
                "getOnline": "genesis/mqtt",
                "getOn": {
                    "topic": "genesis/progress/printing",
                    "apply": "return JSON.parse(message).progress"
                },
                "getBrightness": {
                    "topic": "genesis/progress/printing",
                    "apply": "return parseFloat(JSON.parse(message).progress);"
                }
            },
            "onlineValue": "connected",
            "offlineValue": "disconnected",
            "onValue": "0",
            "offValue": "100",
            "accessory": "mqttthing"
        }
```
and this is the message from the broker:
```
[11/12/2021, 6:33:46 PM] [Genesis Print progress] Received MQTT: genesis/progress/printing = {"location": "local", "path": "Stuff/Bath trim/bath_trim_part_1_0.2mm_PETG_MK3S_2h42m.gcode", "progress": 87, "_timestamp": 1636760026}
```

Thanks

**Comment by washcroft** [comment]
Try this:

```
{
            "type": "lightbulb-Dimmable",
            "name": "Genesis Print progress",
            "username": "user",
            "password": "pass",
            "logMqtt": true,
            "topics": {
                "getOnline": "genesis/mqtt",
                "getOn": {
                    "topic": "genesis/progress/printing",
                    "apply": "return (JSON.parse(message).progress > 0);"
                },
                "getBrightness": {
                    "topic": "genesis/progress/printing",
                    "apply": "return JSON.parse(message).progress;"
                }
            },
            "onlineValue": "connected",
            "offlineValue": "disconnected",
            "accessory": "mqttthing"
}
```

**Comment by appleimperio** [comment]
For some reason keep seeing the bulb as an on/off light not dimmable
<img width="496" alt="Screen Shot 2021-11-12 at 7 17 21 PM" src="https://user-images.githubusercontent.com/72883739/141597736-d89f86d6-07ae-43b9-ae3e-3933b6c3bc71.png">

**Comment by washcroft** [comment]
It's because there are no set topics, even if there's nothing to set, try this:

{
            "type": "lightbulb-Dimmable",
            "name": "Genesis Print progress",
            "username": "user",
            "password": "pass",
            "logMqtt": true,
            "topics": {
                "getOnline": "genesis/mqtt",
                "setOn": "genesis/ignore",
                "setBrightness": "genesis/ignore",
                "getOn": {
                    "topic": "genesis/progress/printing",
                    "apply": "return (JSON.parse(message).progress > 0);"
                },
                "getBrightness": {
                    "topic": "genesis/progress/printing",
                    "apply": "return JSON.parse(message).progress;"
                }
            },
            "onlineValue": "connected",
            "offlineValue": "disconnected",
            "accessory": "mqttthing"
}

**Comment by appleimperio** [comment]
Yessss thanks again!!!!!!

**Comment by arachnetech** [comment]
Yes, assumption by me that a bulb is only useful if you can control it - which doesn't apply here. Thanks for helping, @washcroft .
