### ISSUE TITLE
Question about tasmota temperature readings

### ISSUE THREAD

**Issue by bartoszwas** [arachnetech/homebridge-mqttthing#51]
Hey.

I have managed to get working temperature from Sonoffs but I have a question about code, because I'm not java dev. Do I have to use "toFixed(1)"? For now I don't and it seems to be working...

`
 {
"accessory": "mqttthing",

"type": "temperatureSensor",

"name": "BartoszTemp",
"url": "mqtt://192.168.88.10",
"username": "",
"password": "",
"caption": "",

"topics": {
 "getCurrentTemperature": {
"topic": "tele/Bartosz/SENSOR",
"apply": "return JSON.parse(message).DS18B20.Temperature;"}
 }
 }`

@kepete I think you will be interested in this ;)

**Comment by arachnetech** [comment]
Fine to return it as a number (without `toFixed(1)`) or as a string with one decimal place (with `toFixed(1)`) I believe. It really just depends on whether you want to limit the precision passed to Homekit to one decimal place. I don't think Homekit apps typically display temperatures in steps of less than 0.5 anyway.
