### ISSUE TITLE
[Feature Request] Being able to use arrays as Values like in the photo

### ISSUE THREAD

**Issue by PalmTamino** [arachnetech/homebridge-mqttthing#522]
![grafik](https://user-images.githubusercontent.com/36358673/148293927-7bb27614-a8ed-481c-8d08-872d59d7a94f.png)

**Comment by rbswift** [comment]
You can use an apply function for the topic something like (not tested):

return (["idle","docked","paused"].includes(message) ? "OFF" : "ON");

see here for details https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Configuration.md

**Comment by PalmTamino** [comment]
Thanks! Got it

Screenshot: https://ibb.co/7R8fFSk
