### ISSUE TITLE
Enabling Wiki to allow users to store configuration for various devices?

### ISSUE THREAD

**Issue by NorthernMan54** [arachnetech/homebridge-mqttthing#53]
I was thinking that if the Wiki was enabled then people could share their settings for various devices.  For example, I'm using the CE Smart WIFI Smart Dimmer from Costco, flashed with Sonoff-Tasmota and thought others would like my configuration to me things easier for them to setup.

{
    "accessory": "mqttthing",
    "type": "lightbulb",
    "name": "Beside Stairs",
    "caption": "Test Caption",
    "topics":
    {
        "getOn":                "stat/sonoff-0685/POWER",
        "setOn":                "cmnd/sonoff-0685/power",
        "getBrightness": {
                "topic":        "stat/sonoff-0685/RESULT",
                "apply":        "return JSON.parse(message).Dimmer;"
                },
        "setBrightness":        "cmnd/sonoff-0685/dimmer"
    },
   "onValue": "ON",
   "offValue": "OFF"
},

**Comment by arachnetech** [comment]
Good idea. I've enabled the wiki (I think). Please feel free to add...

**Comment by NorthernMan54** [comment]
Take a look and see what you think.   If your okay with it, you may want to mention on the Wiki

PS Great plugin

**Comment by arachnetech** [comment]
Thanks, that's great. I've added a mention to the Home page.

I'm delighted that you're finding homebridge-mqttthing useful. I use it with your great homebridge-alexa plugin myself!

I don't suppose you know of a Google equivalent to homebridge-alexa? The one thing missing from the homebridge environment, for me at least, it easy integration with Google Home. I've considered moving to Home Assistant, but I'm really reluctant to leave the simplicity of Homebridge where I have everything set up and working so well with Homekit and Alexa.

**Comment by NorthernMan54** [comment]
Sorry, I’m not aware of a google equivalent of my homebridge-Alexa plugin.  I had originally thought of doing both, but for the amount of effort required it was too much for no improvement in my WAF score.
