### ISSUE TITLE
How to handle Homebridge restart

### ISSUE THREAD

**Issue by smhex** [arachnetech/homebridge-mqttthing#531]
Hi, I am using the plugin for my garage door controller. Everything works as expected except when Homebridge is restarted. Although the new and the current door state are retained messages (flag set by my controller) the HomeKit Status is always "opening...". I can easily fix this by periodically sending the door status, however I would like to understand the behavior first. What happens after a Homebridge restart? I enabled the log but there is not output after restart.

Thank you!

Maybe my issue is somehow related to [this](https://github.com/arachnetech/homebridge-mqttthing/issues/521#issue-1092045487)

**Comment by smhex** [comment]
Problem solved - I did not set the retained flag correctly. Now the status set as soon as the plugin is initialized.

**Comment by katrovman** [comment]
@smhex I am having the same issue, how do you set the retained flag? Thanks!

**Comment by smhex** [comment]
@katrovman I had to set in my own controller code (Arduino in my case). The respective function call has a flag for this.
