### ISSUE TITLE
Contact Sensor configuration problem

### ISSUE THREAD

**Issue by lulek2007** [arachnetech/homebridge-mqttthing#54]
Hi,

I have a very similar configuration to closed issue  https://github.com/arachnetech/homebridge-mqttthing/issues/27
```
{
"accessory": "mqttthing",
"type": "contactSensor",
"name": "sensor_1",
"url": "mqtt://192.168.4.10",
"username": "admin",
"password": "123456",
"caption": "sonoff_rf",
"topics":
{
    "getContactSensorState": {
	    "topic": "tele/sonoff_rf/RESULT",
        "apply": "return  JSON.parse(message).RfReceived.Data;"
    }
},
"onValue": "6F5321",
"offValue": "79FAE1",
"logMqtt": true    
}
```
my sonoff rf bridge in the console show

```
13:37:11 MQT: tele/sonoff_rf/RESULT = {"RfReceived":{"Sync":12380,"Low":400,"High":1210,"Data":"79FAE1","RfKey":"None"}}
13:37:13 MQT: tele/sonoff_rf/RESULT = {"RfReceived":{"Sync":12420,"Low":400,"High":1210,"Data":"6F5321","RfKey":"None"}}
```

and homebridge logMqtt show

```
[1/20/2019, 1:01:25 PM] [sensor_1] Received MQTT: tele/sonoff_rf/RESULT = {"RfReceived":{"Sync":12390,"Low":400,"High":1210,"Data":"79FAE1","RfKey":"None"}}
[1/20/2019, 1:01:28 PM] [sensor_1] Received MQTT: tele/sonoff_rf/RESULT = {"RfReceived":{"Sync":12410,"Low":400,"High":1210,"Data":"6F5321","RfKey":"None"}}
```

the problem is that the "onValue" option: "6F5321" works properly and triggers sensor_1 "open" while the "close" state triggers "offValue": "79FAE1" or any value eg "offValue": "111111".

This means that you can not assign specific 2 values to a specific sensor.

"offValue": "111111" or "offValue": "79FAE1" close all sensors

Can I ask for help in proper configuration

Regards

Marcin Kowalik

**Comment by arachnetech** [comment]
I think the issue was that homebridge-mqttthing was interpreting any received value other than the onValue as an offValue for Boolean characteristics. I've changed this in version 1.0.23.

**Comment by mientki** [comment]
My sensor also has an additional code, sent when the battery is weak (the voltage is below 5 volts). How do you define the additional code that will apply to the "getStatusLowBattery" state? My config looks like this:

       {
             "accessory": "mqttthing",
             "type": "contactSensor",
             "name": "contact sensor",
             "url": "mqtt://localhost",
             "username": "user",
             "password": "pass",
             "topics": {
                 "getContactSensorState": {
                     "topic": "tele/sonoff_rf/RESULT",
                     "apply": "return  JSON.parse(message).RfReceived.Data;"
                 },
                 "getStatusLowBattery": {
                     "topic": "tele/sonoff_rf/RESULT",
                     "apply": "return  JSON.parse(message).RfReceived.Data;"
                 }
             },
             "onValue": "6F5321",
             "offValue": "79FAE1"
         }

**Comment by lulek2007** [comment]
Try this,

```
{
        "getContactSensorState": {
    	    "topic": "tele/sonoff_rf/RESULT",
            "apply": "return JSON.parse(message).RfReceived.Data;"
        },
         "getStatusLowBattery": {
                 "topic": "tele/sonoff_rf/RESULT",
                 "apply": "return  JSON.parse(message).RfReceived.Data;"
             }
    },
            "integerValue": true,
            "onValue": "open code",
            "offValue": "close code",
            "statusLowBattery": "low battery code",
            "logMqtt": true
    }

```
it works and appears "!" on the sensors icon, and the message "low level battery.
but it looks like any code triggers this state, as in the previous version 10.0.22 "offValue"


![zrzut ekranu 2019-01-21 o 14 55 13](https://user-images.githubusercontent.com/46531106/51478740-9beae400-1d8c-11e9-829b-306e78b4a050.png)
![zrzut ekranu 2019-01-21 o 14 55 25](https://user-images.githubusercontent.com/46531106/51478745-a0170180-1d8c-11e9-8042-3df0638c8259.png)

Best regards, Marcin Kowalik

**Comment by mientki** [comment]
I still have a problem with the setting and correct operation of the sensors. getStatusLowBattery does not work, but also getStatusTampered. Although I have defined a separate rf code for Tempered state, it is not triggered. My config:

```
       {
            "accessory": "mqttthing",
            "type": "contactSensor",
            "name": "Sensor 19",
            "url": "mqtt://localhost",
            "username": "user",
            "password": "pass",
            "topics": {
                "getContactSensorState": {
                    "topic": "tele/rf-bridge/RESULT",
                    "apply": "return  JSON.parse(message).RfReceived.Data;"
                },
                "getStatusTampered": {
                    "topic": "tele/rf-bridge/RESULT",
                    "apply": "return  JSON.parse(message).RfReceived.Data;"
                },
                "getStatusLowBattery": {
                    "topic": "tele/rf-bridge/RESULT",
                    "apply": "return  JSON.parse(message).RfReceived.Data;"
                }
            },
            "integerValue": true,
            "onValue": "1E29EE",
            "offValue": "1E29E7",
            "getStatusTampered": "1E29EB",
            "getStatusLowBattery": "1E29EA"
        }
```
Any suggestions?

Is there a chance to introduce a correction in the next version?

**Comment by arachnetech** [comment]
`getStatusTampered` and `getStatusLowBattery` outside topics are not valid configuration settings so won't do anything

Could you not set onValue to 1 and offValue to 0, then put the mapping logic from your special values in the apply functions? I haven't tried this, but something like `"apply": "return JSON.parse(message).RfReceived.Data; == 0x1E29EA ? 1 : null"`

I think a message that decodes to null will be ignored rather than triggering the off value.

**Comment by lulek2007** [comment]
Hi, 
I did some tests
and the problem is confused boolean and string data

```
"topics":
    {
        "getContactSensorState": {
    	    "topic": "tele/DVES_B2AE5C/RESULT",
            "apply": "return( ( JSON.parse(message).RfReceived.Data == 'open_code' ) ? 1 : null );"
        },
        "getStatusLowBattery": {
    	    "topic": "tele/DVES_B2AE5C/RESULT",
            "apply": "return( ( JSON.parse(message).RfReceived.Data == 'low_battery_code' ) ? 1 : null );"
        }
    },
	    "integerValue": true,    
            "logMqtt": true
    },

```

work and trigger open status in home app and low battery

but if I change  "integerValue": to false and add 

```
"topics":
    {
        "getContactSensorState": {
    	    "topic": "tele/DVES_B2AE5C/RESULT",
            "apply": "return JSON.parse(message).RfReceived.Data;"
        },
        "getStatusLowBattery": {
    	    "topic": "tele/DVES_B2AE5C/RESULT",
            "apply": "return( ( JSON.parse(message).RfReceived.Data == 'low_battery_code' ) ? 1 : null );"
        }
    },
            "logMqtt": true,
            "integerValue": true,
            "onValue": "open_code",
            "offValue": "close_code"
    },
```
open and close work but not low_battery 


**and finally working solution** 

```
"topics":
    {
        "getContactSensorState": {
    	    "topic": "tele/DVES_B2AE5C/RESULT",
            "apply": "return( ( JSON.parse(message).RfReceived.Data == 'open_code' ) ? 1 : null || ( JSON.parse(message).RfReceived.Data == 'close_code' ) ? 0  : null);"

            },
        "getStatusLowBattery": {
    	    "topic": "tele/DVES_B2AE5C/RESULT",
            "apply": "return( ( JSON.parse(message).RfReceived.Data == 'low_battery_code' ) ? 1 : null );"
    	    }
    },
	    "integerValue": true,
            "logMqtt": false
    },
```
Regards
MK

**Comment by mientki** [comment]
works perfectly :) that's what it was about. One more suggestion ... In my sensors there is no separate code that says "the battery is good". The low battery condition must expire automatically after a certain time.
Dobra robota Marcinie !! :)

Regards
Paweł
