### ISSUE TITLE
Aqara Low Battery Not Working?

### ISSUE THREAD

**Issue by ashtonaut** [arachnetech/homebridge-mqttthing#543]
I can't seem to get low battery notifications working with my Aqara sensors in Homekit.

I run my sensors through zigbee2mqtt to mosquitto, and then use mqtt thing to bring them into Homebridge / Homekit.

My specific config for the Aqara temperature sensor looks like:

"type": "temperatureSensor",
"url": "mqtt://10.1.1.3",
            "name": "Aqara Lounge",
            "topics": {
                "getCurrentTemperature": {
                    "topic": "zigbee2mqtt/aqara_lounge",
                    "apply": "return JSON.parse(message).temperature.toFixed(1);"
                },
                "getStatusLowBattery": {
                    "topic": "zigbee2mqtt/aqara_lounge",
                    "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
                }
            }

This code works fine, and temperature values are reported correctly. However, even when the battery level reported by the sensor drops below the threshold (in this case 20, which I can confirm using MQTT Explorer), I get no indication within Homekit, it just shows the standard temperature sensor icon.

Do others have low battery notifications working with Aqara sensors? I don't know JSON but the battery status code in my config is exactly the same as I have seen others use.

Any ideas how I might troubleshoot this further?

**Comment by anthyz** [comment]
I had a similar issue with low battery status not being updated. Adding "integerValue": true to the config fixed the problem although messages like 'Ignoring invalid value [true] for Status Low Battery - not an integer' started getting logged.

**Comment by ashtonaut** [comment]
Thanks for replying, that sounds promising. Would you mind being more specific about where you added the `"integerValue": true` in the config file?
