### ISSUE TITLE
Toggling the physical switch on Sonoff Basic does not update its state in Homebridge

### ISSUE THREAD

**Issue by reinisb** [arachnetech/homebridge-mqttthing#557]
### What happens
When I press the physical button located on Sonoff Basic, then it toggles the switch, but the updated status is not reflected in Homebridge.

### What should happen
I expect the status to be reflected in Homebridge when using Sonoff Basic's physical button.

### Config
<img width="2053" alt="Screen Shot 2022-05-14 at 14 08 51" src="https://user-images.githubusercontent.com/6346595/168639745-1e66acd3-a51e-4047-96a9-1b46292685ce.png">

**Comment by KiwiV** [comment]
Try changing Get On MQTT topic to:
stat/sonoff-basic-r2-b/POWER

**Comment by reinisb** [comment]
> Try changing Get On MQTT topic to:
stat/sonoff-basic-r2-b/POWER

I tried, but that does not resolve the problem.

**Comment by reinisb** [comment]
I figured it out. The solution was neither documented, nor obvious.

You see, my Sonoff Basic is running Tasmota firmware. When the physical switch (or the tasmota web ui switch) is toggled, tasmota sends the following MQTT messages:
```
stat/sonoff-basic-r2-b/POWER = ON

or

stat/sonoff-basic-r2-b/POWER = OFF
```

What I realized is that homebridge-mqttthing does not understand what `ON` or `OFF` means. It expects the values to be `true` or `false`. I would expect homebridge-mqttthing to understand what `ON` or `OFF` means.

The solution is to go into homebridge-mqttthing _Advanced settings_ in Homebridge and add `ON` or `OFF` values to these fields.

<img width="1714" alt="Screen Shot 2022-06-03 at 19 34 57" src="https://user-images.githubusercontent.com/6346595/171907858-b298fe80-cf6e-4ff8-a5ae-4ddc91b8da25.png">


The final working config looks like:

```
    "accessories": [
        {
            "type": "lightbulb-OnOff",
            "name": "Lampa",
            "username": "reinis",
            "password": "macbook",
            "topics": {
                "getOnline": "tele/sonoff-basic-r2-b/LWT",
                "getOn": "stat/sonoff-basic-r2-b/POWER",
                "setOn": "cmnd/sonoff-basic-r2-b/POWER"
            },
            "onlineValue": "ON",
            "offlineValue": "OFF",
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "accessory": "mqttthing"
        }
    ]

```

**Comment by degudejung** [comment]
Thank you for posting this solution. I was struggling with the same and found the missing on=true off=false mapping too obvious to consider.

**Comment by sachasmart** [comment]
Gosh this was brutal. Same went for me when trying to integrate Nodered with Homebridge. Thank you for posting this!
