### ISSUE TITLE
multiple apply commands 

### ISSUE THREAD

**Issue by Luftloch80** [arachnetech/homebridge-mqttthing#56]
I use apply to read out Json
  "getBrightness": {
                    "topic": "zigbee2mqtt/0x8418260000073d64",
                    "apply": "return JSON.parse(message).brightness;"
                },	       
        "setBrightness": {
                     "topic":	"zigbee2mqtt/0x8418260000073d64/set",
                     "apply": "return JSON.stringify({ brightness: message});"
                     }
But i also Need to send brightness up to 255 value for 100%
Thx

**Comment by arachnetech** [comment]
You should be able to combine both operations in the same apply functions, e.g.

```
"getBrightness": {
    "topic": "zigbee2mqtt/0x8418260000073d64",
    "apply": "return Math.round( JSON.parse(message).brightness / 2.55 );"
},
"setBrightness": {
    "topic": "zigbee2mqtt/0x8418260000073d64/set",
    "apply": "return JSON.stringify({ brightness: Math.round( message * 2.55 ) });"
}
```
