### ISSUE TITLE
Security System not respecting defined state values

### ISSUE THREAD

**Issue by dresende** [arachnetech/homebridge-mqttthing#594]
- Homebridge 1.5.1 (on a Synology)
- MQTT Thing 1.1.42

The alarm (Paradox) is proxied to specific topics of my own, so I control the values. I configured the accessory like this:

```js
{
	accessory : "mqttthing",
	type      : "securitySystem",
	name      : "Alarm",
	topics    : {
		setTargetState      : "home/main/alarm/home/status/set",
		getTargetState      : "home/main/alarm/home/status/target",
		getCurrentState     : "home/main/alarm/home/status",
		targetStateValues   : [ "arm_stay", "arm", "armm_sleep", "disarm" ],
		currentStateValues  : [ "stay", "armed", "sleep", "disarmed", "alarm" ],
		restrictTargetState : [ 1, 2, 3 ],
	},
}
```

The test I did was arming/disarming using homekit and what I see are the default values, not the ones I specify.

![Screenshot 2022-10-31 at 15 35 06](https://user-images.githubusercontent.com/157494/199047340-e098fa19-1a43-4226-87c8-1a216a519681.png)

It should have published `arm` and not `AA`.

**Comment by arachnetech** [comment]
`targetStateValues` etc. should not be within `topics` - i.e. try

```
{
	accessory : "mqttthing",
	type      : "securitySystem",
	name      : "Alarm",
	topics    : {
		setTargetState      : "home/main/alarm/home/status/set",
		getTargetState      : "home/main/alarm/home/status/target",
		getCurrentState     : "home/main/alarm/home/status"
	},
	targetStateValues   : [ "arm_stay", "arm", "armm_sleep", "disarm" ],
	currentStateValues  : [ "stay", "armed", "sleep", "disarmed", "alarm" ],
	restrictTargetState : [ 1, 2, 3 ],
}
```

**Comment by dresende** [comment]
oh... how stupid of me. Sorry. Let me just test it out.

**Comment by dresende** [comment]
Perfect.

![Uploading IMG_F924E454D515-1.jpeg…]()

**Comment by arachnetech** [comment]
Excellent! Thanks for confirming.
