### ISSUE TITLE
Support for NodeJS 18

### ISSUE THREAD

**Issue by rionshin** [arachnetech/homebridge-mqttthing#596]
Could you please update the add-on to support v 18 as it is now supported by homebridge, and Homebridge nodes update install 18.12 but MQTT thing throw an error : 
The plugin "homebridge-mqttthing" requires Node.js version of ^14.18.0 || ^16.10.0 which does not satisfy the current Node.js version of v18.12.1. You may need to upgrade your installation of Node.js 

Thank you in advance

**Comment by reinisb** [comment]
@arachnetech Could you please address this?

Just like others I updated homebridge (includes NodeJS 18) and now homebridge-mqttthing does not work anymore.

**Comment by arachnetech** [comment]
Sorry, yes, I will update this soon.

**Comment by arachnetech** [comment]
Fixed in 1.1.43.

**Comment by reinisb** [comment]
I'm on 1.1.42. When I attempt to update to 1.1.43. it shows that update completed, but in reality it had not. I've not seen this before in homebridge. Any ideas?

https://user-images.githubusercontent.com/6346595/203247148-a1957834-2692-458f-9280-a962edbb528c.mp4

**Comment by arachnetech** [comment]
That's odd. I've not had time to try updating my 'production' instance yet. It took me lots of updating to get my development instance running with Node.js 18, but I hadn't updated anything in a while.

Maybe try removing then re-adding?

**Comment by reinisb** [comment]
> Maybe try removing then re-adding?

Uninstall fails
<img width="820" alt="Screenshot 2022-11-22 at 10 34 08" src="https://user-images.githubusercontent.com/6346595/203265308-5f268173-3cae-48d2-a061-778ca979feab.png">


[2022-11-22T08_29_06_526Z-debug-0.log](https://github.com/arachnetech/homebridge-mqttthing/files/10065455/2022-11-22T08_29_06_526Z-debug-0.log)

**Comment by reinisb** [comment]
I tried again today and the update to 1.1.43. worked.

**Comment by arachnetech** [comment]
That's great news. Thanks for confirming.
