### ISSUE TITLE
ESPurna compatibility?

### ISSUE THREAD

**Issue by matphillips** [arachnetech/homebridge-mqttthing#6]
You think there's any chance of adding a 'type' that it suitable for RGB devices programmed with the ESPurna firmware? It seems to want MQTT messages slightly incompatible with the current "Light" type.

On and Off can be made to work, but brightness wants a value between 0 and 255 instead of 0 and 100, and the colour controls won't work at all.

The message types are here https://github.com/xoseperez/espurna/wiki/MQTT#lights

**Comment by arachnetech** [comment]
Very happy to look at that and see what I can do.

I've only looked very briefly at the documentation you pointed me at. Would it be sufficient just to use the HSV topics `{root topic}/hsv` and `{root topic}/hsv/set` given that (I think!) the *value* of HSV is typically interpretted as *brightness* for lights - and homekit brightness is already in the correct 0-100 range for ESPurna *value*?

**Comment by matphillips** [comment]
I believe so, yes.
I just tested by sending messages direct to my MQTT server and:
`mosquitto_pub -h localhost -p 1883 -t 'hallway/hsv/set' -m '0,100,100'`
does make the bulb bright red. A message of "0,100,10" makes it red, but very dim (as expected) and "0,0,100" makes it full bright white.

I think the HSV is provided as an option, and RGB can be used instead, or directly manipulating each channel.

The firmware has a debug log which shows this when the message is sent:

```
[502293] [MQTT] Received hallway/hsv/set => 0,0,100
[502297] [LIGHT] HSV: 0,0,100
[502299] [MQTT] Sending hallway/rgb => #FFFFFF (PID 452)
[502300] [MQTT] Sending hallway/hsv => 0,0,100 (PID 453)
[502301] [MQTT] Sending hallway/brightness => 255 (PID 454)
[502303] [MQTT] Sending hallway/mired => 326 (PID 455)
[502304] [MQTT] Sending hallway/channel/0 => 255 (PID 456)
[502305] [MQTT] Sending hallway/channel/1 => 255 (PID 457)
[502306] [MQTT] Sending hallway/channel/2 => 255 (PID 458)
[502307] [MQTT] Sending hallway/channel/3 => 0 (PID 459)
```

So, the "0,0,100" for bright white message is activating the red, green and blue LED's in the bulb at full brightness, but not activating the white chips.
Sending a message of "hallway/channel/3/set 255" brings the white leds into play, which does have the curious effect of making the bulb stay on when a HSV of 0,0,0 is sent, because the color chips are turned off and the white is left on !

Anyway, being able to manipulate the RGB chips would be a great start!

I do have some Xiaomi Yeelight bulbs and HomeKit seems to support manipulating the color on one interface on the phone, and the brightness on another; so it looks like that is the "correct" way perhaps of handling RGBW(W) bulbs, so if you can manage to work out what the Apple API is expecting for that format then that would be great, but frankly, I appreciate you even considering to add basic support for just a HSV approach.

**Comment by arachnetech** [comment]
Thanks for the additional information.

In version 1.0.9, I've now added support for publishing hue, saturation and value as a comma-separated string as used by espurna. To configure this, use something like:

```
    {
      "accessory": "mqttthing",
      "type": "lightbulb",
      "name": "Test espurna Light",
      "topics": {
        "getHSV": "testlight/hsv",
        "setHSV": "testlight/hsv/set"
      },
      "logMqtt": true
    }
```

Here's some sample output:
```
testlight/hsv/set 0,0,100
testlight/hsv/set 0,0,0
testlight/hsv/set 0,0,0
testlight/hsv/set 0,0,26
testlight/hsv/set 0,0,33
testlight/hsv/set 0,0,33
testlight/hsv/set 0,0,89
testlight/hsv/set 0,0,89
testlight/hsv/set 0,98,89
testlight/hsv/set 355,98,89
testlight/hsv/set 355,89,89
testlight/hsv/set 348,89,89
testlight/hsv/set 348,87,89
testlight/hsv/set 334,87,89
testlight/hsv/set 334,87,89
testlight/hsv/set 333,87,89
testlight/hsv/set 333,88,89
testlight/hsv/set 333,88,89
testlight/hsv/set 333,93,89
testlight/hsv/set 319,93,89
testlight/hsv/set 319,96,89
```

This will only control the RGB LEDs. I'll look at a way to pull the white component out and pass that to the white LEDs in a future update.

**Comment by matphillips** [comment]
Looks great, thanks!
I will try this out in a few days when I return.

**Comment by arachnetech** [comment]
Currently using the `setHSV` option causes mqttthing to ignore any *brightness* and *on* topics - so it will neither respond to your `getBrightness` and `getOn` topics nor publish to `setBrightness` and `setOn`. I suspect this is what is causing the problems.

'Off' is represented by a 0 brightness (i.e. third component of HSV).

It would be simpler to publish the hue, saturation and brightness as they are, and treat on/off state independently (through `getOn`/`setOn` topics) - so I'll look at adding support for this.

**Comment by matphillips** [comment]
Thank you.
Mqttthing is a very useful general purpose plugin for homebridge, and the Espurna firmware runs on almost anything with an ESP, so they're a good match.

Many cheap LED bulbs use an ESP and run custom firmware communicating to overseas servers for control, but they can be refreshed with ESPurna to improve security. It's nice to have a common platform for many devices. Shame it does not work on YeeLight's..... yet ^^

**Comment by arachnetech** [comment]
Can you recommend an LED bulb that I could easily flash with Espurna so that I can give it go? This sounds worth trying!

**Comment by matphillips** [comment]
I've used the AriluxE27 and 'Magic Home LED controllers' and the AI-Thinker bulbs. But you mention "easy".... most if not all require opening the device and performing the initial flash by connecting to test points on the boards. From there they can be updated via their web console.

If hardware hacking is your thing, it's trivial, if not, it won't fit you definition of 'easy' !!

If you have an ESP8266 dev board and an RGB led laying around, you could build a 'bulb simulator' quite easily though. Also, an ESP without the LED attached would work, the web console will show you the state that the "bulb" is in, so changing color and turning it off etc can be done by seeing what the bulb is thinking.

**Comment by arachnetech** [comment]
Thanks. Software is more my thing! Good idea about running it on an ESP - I might look into that.

**Comment by arachnetech** [comment]
Version 1.0.11 can now use RGB values (either in hexadecimal or as comma-separated decimals) with the new `topics.setRGB`. It can also extract a white level  from the RGB, which can be published separately with `topics.setWhite`. Please see *Test RGB Light* and *Test RGBW Light 2* in `test/config.json` for example configurations.

**Comment by matphillips** [comment]
1.0.11 working really well with both the LED strip and the generic bulbs running ESPurna.
Really great work @arachnetech thank you !!

**Comment by arachnetech** [comment]
Excellent - thanks for confirming! I will close this issue for now, but please do re-open (or open another) if you have any other questions/requests.
