### ISSUE TITLE
How to use this plug-in with zigbee2mqtt?

### ISSUE THREAD

**Issue by testosious** [arachnetech/homebridge-mqttthing#60]
Hello,

Please, help...
How to use this plug-in with [zigbee2mqtt](https://koenkk.github.io/zigbee2mqtt/information/mqtt_topics_and_message_structure.html)?
How to find right topic of device in config file?

Thank you!

**Comment by testosious** [comment]
[https://koenkk.github.io/zigbee2mqtt/information/mqtt_topics_and_message_structure.html](url)

**Comment by vekunz** [comment]
You have to install a MQTT server. Then zigbee2mqtt sends the data to the MQTT server and this plugin receives the data from the MQTT server.

**Comment by arachnetech** [comment]
Closing as inactive.
