### ISSUE TITLE
Make switch for Siren On and Off 

### ISSUE THREAD

**Issue by lucaesse** [arachnetech/homebridge-mqttthing#615]
Hi,
I have this siren https://www.zigbee2mqtt.io/devices/TS0224.html#tuya-ts0224 and I need to expose it as a switch or two for on and off but I don’t know how to do it. 
Can somebody help me?

This should be ON:
{"warning": {"mode": burglar, "level": low, "strobe_level": high, "strobe": true, "strobe_duty_cycle": 10, "duration": 3600}}

and this should be OFF:
{"warning": {"mode": stop, "level": low, "strobe_level": high, "strobe": false, "strobe_duty_cycle": 10, "duration": 3600}}

both published on topic:
zigbee2mqtt/Sirena/set

**Comment by lucaesse** [comment]
Solved by myself

**Comment by remussamoila** [comment]
Hi, Lucaesse
Can you explain how you solved?
Thank you!

**Comment by lucaesse** [comment]
Hi, sorry for the long wait.
I solved with this config:

 

>         {
>             "type": "switch",
>             "name": "Sirena",
>             "url": "mqtt://192.168.3.8:1883",
>             "topics": {
>                 "setOn": "zigbee2mqtt/Sirena/set"
>             },
>             "onValue": "{\"warning\":{\"duration\":3600,\"level\":\"very_high\",\"mode\":\"burglar\",\"strobe\":false,\"strobe_duty_cycle\":1,\"strobe_level\":\"low\"}}",
>             "offValue": "{\"warning\":{\"duration\":60,\"level\":\"low\",\"mode\":\"stop\",\"strobe\":false,\"strobe_duty_cycle\":1,\"strobe_level\":\"low\"}}",
>             "history": false,
>             "manufacturer": "Meian",
>             "model": "TS0224",
>             "serialNumber": "TUYA-TS0224",
>             "accessory": "mqttthing"
>         }

It's a single switch with ON/OFF on tap.

**Comment by Romadhonfajar** [comment]
Hi Lucas, how about the siren WiFi version (tuya) not zigbee version. Is that configuration can be implemented to? I'm sorry before asking out of topic here. Thank you.
