### ISSUE TITLE
open the window

### ISSUE THREAD

**Issue by Dalbadel** [arachnetech/homebridge-mqttthing#62]
Hello! maybe you can help!
I want to connect a device to open the window. can I make a picture with a window? while configured as a "curtain"

**Comment by Dalbadel** [comment]
I'm sorry! at night in the application "house" in the word "window" made a typo and Siri did not understand me. Fixed a mistake and it turns out to open the phrase "open the window."

Now there is a small inconvenience - picture of curtains)

**Comment by arachnetech** [comment]
I've added support for the *Window* Service in version 1.0.26.
