### ISSUE TITLE
please add power sensors?

### ISSUE THREAD

**Issue by marcoschmidt79** [arachnetech/homebridge-mqttthing#63]
Hello, i use sonoff pow with tasmota. can you add sensors for sonoff pow as outlet?

16:34:57 MQT: tele/sonoff/SENSOR = {"Time":"2019-02-06T16:34:57","ENERGY":{"TotalStartTime":"2018-12-22T23:58:00","Total":6.108,"Yesterday":1.692,"Today":0.000,"Period":0,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":238,"Current":0.000}}

i need:

Total in kwh, Yesterday in kwh, Today in kw, Power 1 or 0, Voltage in volts and current in watts.

thank you

**Comment by bartoszwas** [comment]
Homkit doesn’t support power meters i believe so theres no way to do that.

**Comment by marcoschmidt79** [comment]
eve support power meters.

**Comment by bartoszwas** [comment]
In eve’s apllication not in homekit.

**Comment by arachnetech** [comment]
I believe @bartoszwas is correct, and Homekit doesn't support this - so closing for now.

**Comment by tobekas** [comment]
have a look at the new optional Eve characteristics for outlet type, which are now implemented in homebridge-mqttthing
