### ISSUE TITLE
MotionSensor please help

### ISSUE THREAD

**Issue by iondarie** [arachnetech/homebridge-mqttthing#635]
Hello,

I have a Zigbee motion sensor that publishes to mqtt the following: 

```
{"battery":100,"battery_low":false,"linkquality":52,"occupancy":false,"tamper":false,"voltage":3200}
```

I am trying to make it work on homebridge with the following code:

```
        {
            "accessory": "mqttthing",
            "type": "motionSensor",
            "name": "Magazie",
            "url": "mqtt://192.168.***.***:1883",
            "username": "*********",
            "password": "*********",
            "topics": {
                "getMotionDetected": {
                    "topic": "zigbee2mqtt/magazie",
                    "apply": "return parseFloat(JSON.parse(message). occupancy);"
                }
            },
            "integerValue": false,
            "onValue": "true",
            "offValue": "false"
        }
```

It will not work, it refuses to update the sensor. Please help.

Thank you,

**Comment by arachnetech** [comment]
I don't think you need the `parseFloat` there, because `true` and `false` are Booleans not floating-point numbers.

Since the on and off values are strings, you might need something like:
`"apply": "return JSON.parse(message).occupancy + '';"`

**Comment by iondarie** [comment]
THANK YOU!!!! all works perfect now!
