### ISSUE TITLE
add ServiceLabel support

### ISSUE THREAD

**Issue by zipleen** [arachnetech/homebridge-mqttthing#64]
Hi!

Is it possible to add support for the service ServiceLabel ? 

I'm assuming this would create a fake service which just updates the label in HomeKit.

It would be useful to display random pieces of information, for example I would like to display the current kW usage and also my remaining energy credits.

(I'm currently somewhat working around this by using a temperature sensor to display the numbers, but they get rounded and it's not really temperature hehe)

**Comment by arachnetech** [comment]
I don't really understand the ServiceLabel service:

```
Service.ServiceLabel = function(displayName, subtype) {
  Service.call(this, displayName, '000000CC-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.ServiceLabelNamespace);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Name);
};
```

It's only characteristic is ServiceLabelNamespace - but that's just one of these enumerated values:

```
Characteristic.ServiceLabelNamespace.DOTS = 0;
Characteristic.ServiceLabelNamespace.ARABIC_NUMERALS = 1;
```

How would you actually update a display value?

**Comment by zipleen** [comment]
I have a very limited understanding of HomeKit protocol yet, so I was leaning on your knowledge to double check if it's doable.

I would assume this service has a displayName... which you could update when a value changed? 
I'm not sure how to test it, so that's why I asked.

Feel free to close the ticket if this doesn't make sense :)

**Comment by arachnetech** [comment]
I can't see a way to do this, so closing for now.

**Comment by tobekas** [comment]
This service can be added to stateless programmable switch accessories with multiple „StatelessProgrammableSwitch“ services (multiple buttons) to specify the  naming schema for the buttons. In this case, every StatelessProgrammableSwitch service should be linked to this service.

see: #120
