### ISSUE TITLE
Startpub Usage?

### ISSUE THREAD

**Issue by pliesenfeld** [arachnetech/homebridge-mqttthing#647]
Here is my current config for the back porch light that I’d like to know the status of the light when I restart homebridge. I read that startpub will accomplish this, but I’m not very savvy at programming this.. here is my current config, can somebody tell me where to put the startpub and what it should look like? Thank you! 
        {
            "type": "switch",
            "name": "Back Porch",
            "url": "192.168.",
            "username": "",
            "password": "",
            "topics": {
                "getOnline": "tele/tasmota_2E3CC3/LWT",
                "getOn": "stat/tasmota_2E3CC3/POWER",
                "setOn": "cmnd/tasmota_2E3CC3/POWER"
            },
            "onlineValue": "Online",
            "offlineValue": "Offline",
            "onValue": "ON",
            "offValue": "OFF",
            "accessory": "mqttthing"
        },

**Comment by arachnetech** [comment]
Unfortunately startPub can publish a known state to the light on restart, but it doesn't help with storing the existing state. There's another ticket for a feature request to add that, so I'll close this one.
