### ISSUE TITLE
After updating node.js to version 20.9, the plugin displays a message when running homebridge

### ISSUE THREAD

**Issue by AdamVR7** [arachnetech/homebridge-mqttthing#650]
Subj 

[05/11/2023, 12:43:59]
The plugin "homebridge-mgttthing" requires Node.js version of ^14.18.0 || ^16.10.0 || ^18.12.0 which does not satisfy the current Node.js version of v20.9.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

**Comment by MattParkerDev** [comment]
I just got this also, does the plugin still function correctly?

**Comment by tim-hilt** [comment]
Yep - unfortunately it seems like the plugin is not working with the newest version of Homebridge (1.7.0) which requires node > 18.21.0 (if I remember correctly)

**Comment by arachnetech** [comment]
Sorry, I've had no time to work on mqttthing recently and I'd missed the homebridge move to Node.js 20. As far as I'm aware, mqttthing will work with it, so I've updated the compatibility string in the latest release.
