### ISSUE TITLE
Accessory Type Thermostat

### ISSUE THREAD

**Issue by giggo** [arachnetech/homebridge-mqttthing#66]
Please add accessory type "thermostat" (for heating/cooling thermostats). Topics:
getCurrentTemperature
getTemperature
setTemperature
getPreset
setPreset (typically a string)

**Comment by mspiridakis** [comment]
I second that. Is is a must have.

**Comment by alexair777** [comment]
that would be awesome!

**Comment by arachnetech** [comment]
If I get some time this weekend I might have a look at this.

**Comment by arachnetech** [comment]
Thermostat added in version 1.0.37.

**Comment by mspiridakis** [comment]
Thanx man. This is just great.

**Comment by giggo** [comment]
Brilliant. Thanks.
Will test as soon as I will be back.

Am Mo., 6. Mai 2019 um 01:43 Uhr schrieb arachnetech <
notifications@github.com>:

**Comment by cbrandlehner** [comment]
Feature works for me. You may close this issue.
