### ISSUE TITLE
RF Bridge 433 + HomeKit

### ISSUE THREAD

**Issue by IamStadam** [arachnetech/homebridge-mqttthing#67]
Hi guys!
Please help to write the code in config.json. I am fully noob, it is my first experience.
Task: send to RF Bridge 433 two commands: 
"RfKey1" - open
"RfKey2" - close

brocker - 192.168.88.39:1883   no login, no pass
topic - cmnd/sonoff_bridge/

Tried this, but HomeKit says "additional device is needed":

"accessories": [{
		"accessory": "mqttthing",
		"type": "statelessProgrammableSwitch",
		"name": "BRIDGE",
		"url": "192.168.88.39:1883",
		"topics": {
			"getSwitch": "cmnd/sonoff_bridge/RfKey1"
		}
	}]

**Comment by lulek2007** [comment]
Hi,

Meyby like this topic

```
 
          
            "topics": {
 
                "setOn": {
                    "topic": "cmnd/sonoff_bridge/",
                    "apply": "return JSON.stringify({ mode: message ? 'open_rg_key' : 'close_rf_key'  });"
                },
               
```
refer to https://github.com/arachnetech/homebridge-mqttthing/pull/32

**Comment by IamStadam** [comment]
Hi,
Thank you for reply!

Added your code like this:

"accessory": "mqttthing",
		"type": "statelessProgrammableSwitch",
		"name": "Yard Gates",
		"url": "http://192.168.88.39:1883",
		"logMqtt": true,
		"topics": {
			"setOn": {
				"topic": "cmnd/sonoff_bridge/",
				"apply": "return JSON.stringify({ mode: message ? 'rfkey1' : 'rfkey2'  });"
			}
But the result is the same:  "This accessory requires a home hub to be used with the Home app."

**Comment by lulek2007** [comment]
could you describe your configuration more accurately?
I understand that you have sonoff RF 433 bridge with tasmota pre-installed https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-RF-Bridge-433
which has MQTT
and remote controler or rf433 switch. 
This switch send to rf433 bridge command like
ie.
```
10:49:06 MQT: tele / sonoff_rf / RESULT = {"RfReceived": {"Sync": 12270, "Low": 410, "High": 1170, "Data": "", "RfKey": "1234 "}}

10:49:06 MQT: tele / sonoff_rf / RESULT = {"RfReceived": {"Sync": 12270, "Low": 410, "High": 1170, "Data": "", "RfKey": "4321 "}}
```
where 1234 is the code to open and 4321 to close

you must have these codes to let homebridge read them

**Comment by bitsacer** [comment]
> Hi,
> Thank you for reply!
> 
> Added your code like this:
> 
> "accessory": "mqttthing",
> "type": "statelessProgrammableSwitch",
> "name": "Yard Gates",
> "url": "http://192.168.88.39:1883",
> "logMqtt": true,
> "topics": {
> "setOn": {
> "topic": "cmnd/sonoff_bridge/",
> "apply": "return JSON.stringify({ mode: message ? 'rfkey1' : 'rfkey2' });"
> }
> But the result is the same: "This accessory requires a home hub to be used with the Home app."

This worked for me : https://github.com/miskui/homebridge-mqtt-sonoffrf-transmitter

**Comment by arachnetech** [comment]
Where do you see the message "This accessory requires a home hub to be used with the Home app"?

**Comment by marcelkordek** [comment]
Hi @IamStadam,

the message "This accessory requires a home hub to be used with the Home app" appears because the statelessProgrammableSwitch requires a HomeHub, for example: Apple TV 4, HomePod or an iPad with activated HomeHub. This Type of switch is not directly controlled via the iPhone, only over the HomeHub.

Something like this should work:
```
{
    "accessory": "mqttthing",
    "type": "switch",
    "name": "Yard Gates",
    "url": "http://192.168.88.39:1883",
    "topics":
    "topics": {
                "getOn": {
                    "topic": "tele/sonoff_bridge/RESULT",
                    "apply": "return( ( JSON.parse(message).RfReceived.RfKey == '1' ) ? 1 : null || ( JSON.parse(message).RfReceived.RfKey == '2' ) ? 0 : null);"
                },
                "setOn": {
                    "topic": "cmnd/sonoff_bridge/Backlog",
                    "apply": "return message == 1 ? 'RfKey1' : 'RfKey2';"
                }
            },
    "integerValue": true,
    "logMqtt": true
}
```

**Comment by arachnetech** [comment]
Closing as answered, I believe.
