### ISSUE TITLE
Security System state lost after mqttthing restart

### ISSUE THREAD

**Issue by Kepete** [arachnetech/homebridge-mqttthing#693]
Hi, 
First I need to mention once again that it's an amazing plugin! 

I have been testing the security system accessory and it works well for most part, except when
-  a restart on mqttthing bridge/plugin or; 
- significant time has passed since arming/disarming. (not sure yet exactly what the timefram here is, but around 3-7 days) 

I assume these are related. 

In those cases, the last state is lost and in homekit the accessory is reverted to off/disarmed state, while actually the security system is armed. 
The easiest is to replicate by first arming the security system and then doing a restart of the plugin. 

Is there any way for the plugin to remember or request the last state from the security system? 

getCurrentState is used to echo back the alarm state is achieved, but this echo comes in just once after the state is changed. 
Would publishing periodic updates of the state to this topic help? (would maybe prevent time issue, but not restart issue)
Would sending this message with a retain flag help? After the plugin does a restart, it would get the last state from the MQTT channel 

All control is through homekit. 
Config I use: 

           
            "accessory": "mqttthing",
            "type": "securitySystem",
            "name": "Security",
            "url": "mqtt",
            "onValue": "ON",
            "offValue": "OFF",
            "topics": {
                "setTargetState": "cmnd/tasmota/POWER1",
                "getTargetState": "tele/tasmota/POWER1",
                "getCurrentState": "tele/tasmota/getCurrentState",
                "getOnline": {
                    "topic": "tele/tasmota/LWT",
                    "apply": "return message == 'Online' ? 'ON' : 'OFF';"
                }
            },
            "targetStateValues": [
                "StayArm",
                "ON",
                "NightArm",
                "OFF"
            ],
            "currentStateValues": [
                "StayArm",
                "ON",
                "NightArm",
                "OFF",
                "Triggered"
            ],
            "restrictTargetState": [
                1,
                3
            ]

**Comment by rbswift** [comment]
yes, publish tele/tasmota/getCurrentState with the retain flag set to true so when homebridge starts it will receive a copy of the retained message from your mqtt broker straight away

**Comment by Kepete** [comment]
Yes I tried that- publish _tele/tasmota/getCurrentState_ with the retain flag set to true. Once homebridge restarts, then the security system state in homekit will be `Disarming...`. 

I assume, it got the latest current state (ON=armed) from MQTT channel as the retain flag was set, but the correct target state is by default OFF=disarmed after restart? So it's now after restart thinking it's disarming. 

Should _setTargetState_ or _getTargetState_ also be published with retain flag true?

**Comment by Kepete** [comment]
I also used the retain flag true on _getTargetState_  and now it seems to be having the correct state after the restart of homebridge. 
Thanks for thinking along. It maybe worth adding the hint to security system documentation as well.
