### ISSUE TITLE
Cannot read property 'Temperature' of undefined

### ISSUE THREAD

**Issue by Kepete** [arachnetech/homebridge-mqttthing#70]
Using this plugin to read temperature readings from Tasmota. 
Configured as discussed in #51 and has been working fine for a good time. 
Today added a new temperature sensor and configured it in the config.json file exactly like all other are configured. Only changed the mqtt topic address. 
After this homebridge crashes every start. Even after going back to old configuration. 

Maybe @bartoszwas you have encountered this? 

```
Feb 24 15:48:44 raspberrypi homebridge[369]: TypeError: Cannot read property 'Temperature' of undefined
Feb 24 15:48:44 raspberrypi homebridge[369]:     at eval (eval at mqttSubscribe (/usr/lib/node_modules/homebridge-mqttthing/index.js:85:31), <anonymous>:3:35)
Feb 24 15:48:44 raspberrypi homebridge[369]:     at Array.handler (/usr/lib/node_modules/homebridge-mqttthing/index.js:87:44)
Feb 24 15:48:44 raspberrypi homebridge[369]:     at MqttClient.<anonymous> (/usr/lib/node_modules/homebridge-mqttthing/index.js:66:34)
Feb 24 15:48:44 raspberrypi homebridge[369]:     at emitThree (events.js:136:13)
Feb 24 15:48:44 raspberrypi homebridge[369]:     at MqttClient.emit (events.js:217:7)
Feb 24 15:48:44 raspberrypi homebridge[369]:     at MqttClient._handlePublish (/usr/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/client.js:987:12)
Feb 24 15:48:44 raspberrypi homebridge[369]:     at MqttClient._handlePacket (/usr/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/client.js:336:12)
Feb 24 15:48:44 raspberrypi homebridge[369]:     at work (/usr/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/client.js:292:12)
Feb 24 15:48:44 raspberrypi homebridge[369]:     at Writable.writable._write (/usr/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/client.js:302:5)
Feb 24 15:48:44 raspberrypi homebridge[369]:     at doWrite (/usr/lib/node_modules/homebridge-mqttthing/node_modules/readable-stream/lib/_stream_writable.js:428:64)
```

**Comment by bartoszwas** [comment]
Wierd... I got 5 and no problems at all.
I wonder why it’s „undefined type”.

Show me your config please

**Comment by Kepete** [comment]
Temperature sensor config: 
```
        {
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "Room Temperatuur",
            "url": "mqtt://192.x.x.x",
            "username": "usr",
            "password": "psw",
            "caption": "Room Temperatuur",
            "topics": {
                "getCurrentTemperature": {
                    "topic": "tele/sonoff_room/SENSOR",
                    "apply": "return JSON.parse(message).DS18B20.Temperature;"
                }
            }
        },
```

**Comment by bartoszwas** [comment]
Config seems to be fine. I don’t know what „caption” is. 

Another wierd thing is that it’s not working with old config... Make a backup and try to cut off all temperature sensors from it.

**Comment by Kepete** [comment]
The issue is interesting. After I add more than 4 temperature sensors I get the error and Homebridge crashes. Even if I remove the 5th temperature config, it doesn't start working again. 
I need to remove all temperature sensors from config to get it working. 
After this I can add again 4 sensors without problems. 

Also it is not dependent on a specific sensor.

**Comment by arachnetech** [comment]
That's a very strange error. I'll try adding multiple temperature sensors to my test config and see whether I can reproduce it.

@bartoszwas `caption` was in the homebridge-mqttswitch and homebridge-mqttlightbulb plugins which homebridge-mqttthing was originally based on, but while mentioning it in the description of mqttthing's configuration I've never actually done anything with it. Checking the source of the mqttswitch and mqttlightbulb, I'm not convinced that they actually use it either. Unless homebridge itself uses it directly when creating the accessory, I don't believe it has any effect!

**Comment by arachnetech** [comment]
@Kepete You mention updating a plugin to version 0.9.5, but that's not a homebridge-mqttthing version. Which plugin was that?

I've just tried running 6 temperature sensors and not been able to reproduce your issue.

Looking at the error more closely (`Cannot read property 'Temperature' of undefined`, I think while it's running your `apply` function), given that your apply function is `return JSON.parse(message).DS18B20.Temperature;` I suspect that you may be receiving messages that do *not* contain a DS18B20. I would suggest turning on MQTT logging (with `logMqtt: true` on all temperature sensors) and checking exactly what messages are being received by mqttthing.

**Comment by Kepete** [comment]
Sorry I don't know where I got the 0.9.5 version number, I meant Version 1.0.27. 
So I updated the plugin to the newest, updated Homebridge itself to the newest and removed Caption. 
Furthermore I turned on logMqtt and these log's where clearly pointing to the error. 

```
Mar 03 16:49:36 raspberrypi homebridge[2777]: [2019-3-3 16:49:36] [1 Temperatuur] Received MQTT: tele/sonoff_1/SENSOR = {"Time":"2019-03-03T17:49:36","Switch1":"ON","Switch2":"OFF","DS18B20":{"Temperature":-1.9},"TempUnit":"C"}
Mar 03 16:49:51 raspberrypi homebridge[2777]: [2019-3-3 16:49:51] [2 Temperatuur] Received MQTT: tele/sonoff_2/SENSOR = {"Time":"2019-03-03T17:49:50","Switch1":"OFF","Switch2":"ON","DS18B20":{"Temperature":7.4},"TempUnit":"C"}
Mar 03 16:49:52 raspberrypi homebridge[2777]: [2019-3-3 16:49:52] [3 Temperatuur] Received MQTT: tele/sonoff_3/SENSOR = {"Time":"2019-03-03T17:49:52","Switch1":"OFF","Switch2":"OFF","Switch3":"OFF","Switch4":"ON","DS18B20":{"Temperature":23.4},"TempUnit":"C"}
Mar 03 16:49:53 raspberrypi homebridge[2777]: [2019-3-3 16:49:53] [4 Temperatuur] Received MQTT: tele/sonoff_4/SENSOR = {"Time":"2019-03-03T17:49:53","Switch1":"ON","Switch2":"ON"}
Mar 03 16:49:53 raspberrypi homebridge[2777]: TypeError: Cannot read property 'Temperature' of undefined
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at eval (eval at mqttSubscribe (/usr/lib/node_modules/homebridge-mqttthing/index.js:88:31), <anonymous>:3:35)
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at Array.handler (/usr/lib/node_modules/homebridge-mqttthing/index.js:90:46)
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at MqttClient.<anonymous> (/usr/lib/node_modules/homebridge-mqttthing/index.js:69:34)
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at emitThree (events.js:136:13)
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at MqttClient.emit (events.js:217:7)
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at MqttClient._handlePublish (/usr/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/client.js:987:12)
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at MqttClient._handlePacket (/usr/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/client.js:336:12)
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at work (/usr/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/client.js:292:12)
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at Writable.writable._write (/usr/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/client.js:302:5)
Mar 03 16:49:53 raspberrypi homebridge[2777]:     at doWrite (/usr/lib/node_modules/homebridge-mqttthing/node_modules/readable-stream/lib/_stream_writable.js:428:64)
Mar 03 16:49:53 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 16:49:53 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Mar 03 16:49:53 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

Sonoff_4 did not recieve the `Temperature` value. Strangely it was not always sent by the sonoff tasmota. Now I restarted and reconfigured the sonoff_4 and it is working nicely for an hour with 5 sensors. 

@arachnetech Here comes the request to fix the problem, that when something is undefined than it crashes. 
And thanks for everyones help!

**Comment by RaymondMouthaan** [comment]
Hello @Kepete 

You could try to replace the apply.

**Before**
```
{
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "Room Temperatuur",
            "url": "mqtt://192.x.x.x",
            "username": "usr",
            "password": "psw",
            "caption": "Room Temperatuur",
            "topics": {
                "getCurrentTemperature": {
                    "topic": "tele/sonoff_room/SENSOR",
                    "apply": "return JSON.parse(message).DS18B20.Temperature;"
                }
            }
        },
```

**After**
Before parsing the temperature from DS18B20, first check if it has this property, else return null
```
{
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "Room Temperatuur",
            "url": "mqtt://192.x.x.x",
            "username": "usr",
            "password": "psw",
            "caption": "Room Temperatuur",
            "topics": {
                "getCurrentTemperature": {
                    "topic": "tele/sonoff_room/SENSOR",
                    "apply": "return ((message).hasOwnProperty('DS18B20') ? JSON.parse(message).DS18B20.Temperature : null);"
                }
            }
        },
```

**Comment by dodavies** [comment]
I cannot get my temp from a TH16 to show in HomeKit.
MQTT logs from homebridge show

[3/15/2019, 9:51:03 PM] [FirePitAir] Received MQTT: tele/th16/SENSOR = {"Time":"2019-03-15T22:51:03","DS18B20":{"Temperature":21.6},"TempUnit":"C"}

home kit shows the temp as 0.0

sonoff module says on the webpage

DS18B20 Temperature | 22.0°C

config is

{
    "accessory": "mqttthing",
    "type": "temperatureSensor",
    "name": "FirePitAir",
    "url": "mqtt://192.168.0.57",
    "username": "snip",
    "password": "snip",
    "logMqtt": "True",
    "topics":
    {
        "getCurrentTemperature": "tele/th16/SENSOR",
        "apply": "return (JSON.parse(message).hasOwnProperty('DS18B20') ? JSON.parse(message).DS18B20.Temperature : null);"
    }

any idea ?

**Comment by arachnetech** [comment]
I don't think the syntax of your `getCurrentTemperature` topic is quite right - it needs to be a JSON object containing `topic` and `apply`, like:

```
{
    "accessory": "mqttthing",
    "type": "temperatureSensor",
    "name": "FirePitAir",
    "url": "mqtt://192.168.0.57",
    "username": "snip",
    "password": "snip",
    "logMqtt": "True",
    "topics": {
        "getCurrentTemperature": { 
            "topic": "tele/th16/SENSOR",
            "apply": "return (JSON.parse(message).hasOwnProperty('DS18B20') ? JSON.parse(message).DS18B20.Temperature : null);"
        }
    }
}
```

**Comment by arachnetech** [comment]
@Kepete I did read (and agree with!) your request:
> Here comes the request to fix the problem, that when something is undefined than it crashes.
If I get a chance this weekend... :-)

**Comment by dodavies** [comment]
Fantastic, thank you, that works
