### ISSUE TITLE
Color temperature support

### ISSUE THREAD

**Issue by SebDominguez** [arachnetech/homebridge-mqttthing#71]
Would be really nice to be able to getTemp and setTemp on lightbulb for both RGB lightbulb and white / warm white only lightbulb (with color wheel on the home app disable leaving only the temp wheel for white only lights)

**Comment by arachnetech** [comment]
I'm not sure that it's possible to create a bulb that only supports temperature but not arbitrary RGB colours in homekit. From mqttthing's perspective, colour temperature is just received as RGB values. This makes it harder than you might expect to pass colour temperature on too - because I'd need to calculate it from RGB.

**Comment by SebDominguez** [comment]
I'm actually using [homebridge-mqtt](https://github.com/cflurin/homebridge-mqtt) for that.

Please give it a try:
To create a dummy temperature controlled only lightbulb publish this payload to `homebridge\to\add`

```json
{
    "name": "Temp Light",
    "service": "Lightbulb",
    "Brightness": "default",
    "ColorTemperature": "default",
    "Saturation": "default"
}
```

This is the result compared to a regular RGB lightbulb


![ezgif-3-1f83eea80ec5](https://user-images.githubusercontent.com/4247648/53692320-c6698d00-3d8d-11e9-90af-b0123353799e.gif)

**Comment by arachnetech** [comment]
Thanks, @SebDominguez - my apologies: I was completely wrong!

I had completely missed the optional ColorTemperature characteristic of Lightbulb. I'll see what I can do with it...

**Comment by arachnetech** [comment]
Thanks, @SebDominguez - my apologies: I was completely wrong!

I had completely missed the optional ColorTemperature characteristic of Lightbulb. I've now added support for this in 1.0.27 via `getColorTemperature` and `setColorTemperature` topics.

**Comment by SebDominguez** [comment]
Thanks for considering this features.

Keep in mind that Homekit / Home.app is really glitchy when a lightbulb is set with **both** color temperature **and** HSV characteristic **at the same time**. I think those 2 need to be mutually exclusive.

This is a short clip showing this "bug" (always using [homebridge-mqtt](
https://github.com/cflurin/homebridge-mqtt)):

Payload used
```json
{
    "name": "RGB + Temp",
    "service": "Lightbulb",
    "Brightness": "default",
    "Hue": "default",
    "Saturation": "default",
    "ColorTemperature": "default"
}
```

![ezgif-3-40cde5d0c302](https://user-images.githubusercontent.com/4247648/53694299-35a2a980-3dad-11e9-9ecc-241f25cbdb0b.gif)

Notice how home.app is skipping certain colors on the wheel and how the temperature color selector is always ignored and rollback to the last set color?

Unfortunately a lot of implementation of color lightbulb are done like that and therefore home.app is just a pain to use.

For instance I've try to reach Homeassistant developers to change this behavior, but they just considering this as a "homekit bug, and that this has nothing to do with homeassistant"

https://github.com/home-assistant/home-assistant/issues/19251

**Comment by arachnetech** [comment]
Yes, I think you're right: I tried a lightbulb with both hue/saturation and color temperature enabled, and it behaved a little strangely at times. I should probably document that _either_ hue/saturation _or_ color temperature should be used, not both. I'd certain suggest avoiding them in the configuration.

**Comment by SebDominguez** [comment]
Thanks a lot!

**Comment by alexdobry** [comment]
Hi, is `getColorTemperature`and `setColorTemperature` similar to brightness control, where you need to pass a value between 0 and 100?

**Comment by Naruk-TUBK** [comment]
Sorry for my late comment on this. But as @alexdobry asked. What is the range of the color temperature values? It is not specified in the documentation

**Comment by arachnetech** [comment]
@Naruk-TUBK @alexdobry The range comes from Homekit - mqttthing just passes it straight through - and appears to be in the range 140-500 where 140 is cold white and 500 is warm white. The range appears not to be linear - the 'middle' of the Homekit colour temperature wheel has values of around 151.
