### ISSUE TITLE
adding light sensor

### ISSUE THREAD

**Issue by kilbamoo** [arachnetech/homebridge-mqttthing#72]
Trying to add a light sensor, TSL2561.
log in tasmota console shows result from sensor like this:
`tele/sonoff12/SENSOR = {"Time":"2019-03-03T18:40:05","TSL2561":{"Illuminance":5.708}}` 

I'm not sure how to write the config.json. Since the result is not just the value, but a whole string, I need to apply a function to decode the payload, marked in bold below. Which function do I need to use? Is integerValue required or can I drop it?

"accessory": "mqttthing",
    "type": "lightSensor",
    "name": "LookHowBright",
    "url": "mqtt://ipFromServer",
    "topics":
    {
        "getCurrentAmbientLightLevel":  "tele/sonoff12/SENSOR",
        **"apply": "return JSON.parse(message);"**
    },
    "integerValue": "true to use 1|0 instead of true|false default onValue and offValue",
    "onValue": "<value representing on (optional)>",
    "offValue": "<value representing off (optional)>"
}

**Comment by nicoh88** [comment]
@kilbamoo 

What was the solution?

**Comment by nicoh88** [comment]
https://github.com/arachnetech/homebridge-mqttthing/issues/101
