### ISSUE TITLE
Questions about the "window"

### ISSUE THREAD

**Issue by Dalbadel** [arachnetech/homebridge-mqttthing#73]
Thanks for adding a window control!
But I have a few questions.
1) “opening” or “closing” is constantly displayed
[example in the picture1](https://yadi.sk/i/ECnksmrcGoAGkQ)
[example in the picture2](https://yadi.sk/i/5ACnQawqFcL2wQ)
Publish for /esp/State, value: DECREASING
Publish for /esp/State, value: STOPPED

        {
            "accessory": "mqttthing",
            "type": "window",
            "name": "esp",
            "url": "mqtt://127.0.0.1",
            "username": "admin",
            "password": "admin",
            "topics": {
                "getCurrentPosition": "/esp/CurrentPosition",
                "setTargetPosition": "/esp/TargetPosition",
                "getPositionState": "/esp/State",
                "setHoldPosition": "/esp/1",
                "getObstructionDetected": "/esp/2"
            },
            "positionStateValues": [
                "DECREASING",
                "INCREASING",
                "STOPPED"
            ]
        }

2) how to use "setHoldPosition"? 
3) I send "0" and "1" to the topic "getObstructionDetected" but no notification comes.

**Comment by Dalbadel** [comment]
I found my mistake with the first problem. I did not send "getCurrentPosition": "/esp/CurrentPosition",

**Comment by jvhtec** [comment]
I have this same problem, my home app acknowledges the shutters as closed and moves them to the right position but the status shows opening all the time when set to full open or even set to a % value after being stopped.

**Comment by virgafox** [comment]
I have a similar problem: when I control my window from the Home app it is all perfect, but when I use the buttons, the states on the home app aren't updated correctly.
I'm using a shelly2.5 device correctly calibrated. The HB logs I think that are ok, this is what I see when I open using the button:
```
[1/13/2020, 9:41:36 AM] [Persiane soggiorno] Received MQTT: shellies/shellyswitch25-XXXXXX/roller/0/pos = 0
[1/13/2020, 9:41:36 AM] [Persiane soggiorno] Received MQTT: shellies/shellyswitch25-XXXXXX/roller/0 = stop
[1/13/2020, 9:41:36 AM] [Persiane soggiorno] State positionState is now: 2
[1/13/2020, 9:42:06 AM] [Persiane soggiorno] Received MQTT: shellies/shellyswitch25-XXXXXX/roller/0/pos = 0
[1/13/2020, 9:42:08 AM] [Persiane soggiorno] Received MQTT: shellies/shellyswitch25-XXXXXX/roller/0 = open
[1/13/2020, 9:42:08 AM] [Persiane soggiorno] State positionState is now: 1
[1/13/2020, 9:42:22 AM] [Persiane soggiorno] Received MQTT: shellies/shellyswitch25-XXXXXX/roller/0/pos = 100
[1/13/2020, 9:42:22 AM] [Persiane soggiorno] Received MQTT: shellies/shellyswitch25-XXXXXX/roller/0 = stop
[1/13/2020, 9:42:22 AM] [Persiane soggiorno] State positionState is now: 2
```
This should correspond in closed -> opening -> open, but instead in the home app I see closed for the whole opening time, and then in the end it goes to "closing" and keeps that value.

this is my config:
```
{   
    "accessory": "mqttthing",
    "type": "window",
    "name": "Persiane soggiorno",
    "logMqtt": true,
    "topics": {
        "getOnline": "shellies/shellyswitch25-XXXXXX/online",
        "getPositionState": "shellies/shellyswitch25-XXXXXX/roller/0",
        "getCurrentPosition": "shellies/shellyswitch25-XXXXXX/roller/0/pos",
        "setTargetPosition": "shellies/shellyswitch25-XXXXXX/roller/0/command/pos"
    },
    "positionStateValues": [
        "close",
        "open",
        "stop"
    ],
    "manufacturer": "ALLTERCO",
    "model": "Shelly 2.5"
}
```
Any suggestions? Many thanks

**Comment by arachnetech** [comment]
When you use your buttons to control the window, you need to tell the home app that the target position has changed in addition to updating the current position. In other words, you need to publish to `shellies/shellyswitch25-XXXXXX/roller/0/command/pos` in addition to `shellies/shellyswitch25-XXXXXX/roller/0/pos`.

**Comment by virgafox** [comment]
shouldn't this be the purpose of the getPositionState topic? If I need to communicate always the target and current position, simply comparing the two should give me the positionState (bigger, smaller, equal), making the positionState topic useless

**Comment by arachnetech** [comment]
Maybe it _should be_ how it works, but it's not! homebrige-mqttthing exposes homebridge topics over MQTT. This is how Homebridge behaves with these types of device.

Remember that you don't need to publish the target position when Homebridge is controlling the window target position - only when your button is controlling the window target position.

I find it helpful to think of as:

- your button is changing the target position, so it must update the target position
- your window responds to the changed target position (whether by your button or by homebridge) and updates the current state and current position as it moves

**Comment by virgafox** [comment]
I understand, but the window moves while I keep the button pressed, so there is no "target position" when I use the buttons, the only information available is that the window is opening, when I release the button the window publishes that it has stopped and the new position.

**Comment by galzil** [comment]
@arachnetech Any chance of re-opening this issue?
I'm using the same config and get the same result.
When using MQTT explorer I can see there's the correct value under:
`shellies/shellyswitch25-XXXXXX/roller/0/pos`
but in the App it shows "closing" whether the curtain is opening\closing or set to any position.

Works great if I'm only using the app

**Comment by virgafox** [comment]
> @arachnetech Any chance of re-opening this issue?
> I'm using the same config and get the same result.
> When using MQTT explorer I can see there's the correct value under:
> `shellies/shellyswitch25-XXXXXX/roller/0/pos`
> but in the App it shows "closing" whether the curtain is opening\closing or set to any position.
> 
> Works great if I'm only using the app

I wrote this node-red flow that creates the missing MQTT topic about the target position. Now I have the issue only the first time after I restart homebridge, then it works ok. You only have to change the shelly id in the topics.

https://gist.github.com/virgafox/a72e8d8d798c648153159048eb1a9a45
