### ISSUE TITLE
Fakegato history

### ISSUE THREAD

**Issue by Fearraiser** [arachnetech/homebridge-mqttthing#74]
Thanks for you work, guys!
If it's possible, can you add a [fakegato-history](https://www.npmjs.com/package/fakegato-history) module to some accessories: temperature, humidity sensors at fist time? And on|off option in config to control this feature.

**Comment by tobekas** [comment]
Hey, I‘m working on a simple fakegato-history solution based on mqttthing. It is doing well so far. I will share this solution very soon to you after a few cleanups.

**Comment by Fearraiser** [comment]
Sounds great! Thanks.

**Comment by arachnetech** [comment]
Thanks - this sounds useful.

**Comment by tobekas** [comment]
Here is my solution...
I opened a Pull request #76 

You can test this from my [fork](https://github.com/tobekas/homebridge-mqttthing/tree/feature/historyService) (on branch "feature/historyService"):

I hope you like it.

**Comment by tobekas** [comment]
Done, can be closed...
