### ISSUE TITLE
windowCovering

### ISSUE THREAD

**Issue by Denny5667** [arachnetech/homebridge-mqttthing#75]
if the window covering triggered externally, the homekit app does not update it's target position.
For example, the target position = 25 has been set by homekit. If i try to set another position using MQTT, for example 50 as target, the homekit displays continuously "closing" state. Even if the target and current = 50, the homekit still displays "closing". It seems that the previous version is cached by homekit.

**Comment by tobekas** [comment]
`setTargetPosition` is the command-topic, homebridge will send to the MQTT device, if anyone sets this Characteristic in Homekit. `getTargetPosition` is the status-topic, received by homebridge from the MQTT device. If you send the command-topic directly via MQTT to the accessory, you have to make sure, your accessory will response with the corresponding status-topic. If your window covering will never send a `getTargetPosition` (status) try to configure `setTargetPosition` and `getTargetPosition` in your config.json to the same topic.

**Comment by Denny5667** [comment]
> 
> 
> `setTargetPosition` is the command-topic, homebridge will send to the MQTT device, if anyone sets this Characteristic in Homekit. `getTargetPosition` is the status-topic, received by homebridge from the MQTT device. If you send the command-topic directly via MQTT to the accessory, you have to make sure, your accessory will response with the corresponding status-topic. If your window covering will never send a `getTargetPosition` (status) try to configure `setTargetPosition` and `getTargetPosition` in your config.json to the same topic.

Thank you! It works fine now!

**Comment by alexmuntean** [comment]
shouldn't this value be set by "getCurrentPosition" ? that's the one I'm setting periodically...

**Comment by tobekas** [comment]
CurrentPosition is really the current position. This should be updated periodically, yes. Target position may be different and might also be changed externally. If Target > Current, state should be increasing. If you use the hold command, state can also be STOPPED in this situation.

**Comment by tobekas** [comment]
I recommend you download MQTT.fx and experiment with the different topics a bit. You will get it quickly.

Ticket can be closed.

**Comment by serbasan** [comment]
Hi. I have my windows configured with this fantastic plugin.
From homekit, everything is handled and represented perfectly.

When I act manually and the blind ends, the percentage, closed or open in homekit is represented perfectly.

I just need to show the status (decreasing increasing stopped) when I operate manually and the blind is moving.


In my sonoff with tasmota I have a rule that sends to "getPositionState" status "decreasing"."increasing" or "stopped" when going up or down.

With Node-red I have also sent the topic "getPositionState" but it doesn't change in Homekit

Where is the problem?

Thank you.

This is my config:

 {
            "accessory": "mqttthing",
            "type": "window",
            "name": "Habitación Invitados",
            "url": "mqtt://192.168.1.3:1883",
            "topics": {
                "getCurrentPosition": "stat/persiana3/SHUTTER1",
                "setTargetPosition": "cmnd/persiana3/shutterposition",
                "getTargetPosition": "stat/persiana3/SHUTTER1",
                "getPositionState": "stat/persiana3/status"
            },
            "positionStateValues": [
                "decreasing",
                "increasing",
                "stopped"
            ]
        },
