### ISSUE TITLE
IKEA Tradfri RGB and Brightness Topics / conversions

### ISSUE THREAD

**Issue by odx** [arachnetech/homebridge-mqttthing#80]
Hello,

i am configuring my IKEA Tradfri Light Bulb that supports color, as well as dimming. It is connected through zigbee2mqtt to the MQTT server. Since zigbee2mqtt reports the color as xy I have implemented a conversion that works quite well except the turquoise tones.. (I assume its not in the bulbs gamut).

Nevertheless after implementing the getRGB and setRGB topics and conversions the getBrightness and setBrightness stopped working.

Any hint what's wrong?

This is my accessory config:

{
        "accessory": "mqttthing",
        "type": "lightbulb",
        "name": "bulb",
        "topics":
        {
                "getOn": {
                        "topic": "zigbee/bulb",
                        "apply": "return JSON.parse(message).state;"
                },
                "setOn": {
                        "topic": "zigbee/bulb/set",
                        "apply": "return JSON.stringify({ state: message})"
                },
                "getBrightness":   {
                        "topic": "zigbee/bulb",
                        "apply": "return (JSON.parse(message).brightness / 2.54);"
                },
                "setBrightness":   {
                        "topic": "zigbee/bulb/set",
                        "apply": "return JSON.stringify({ brightness: (parseInt(message) * 2.54)})"
                },
		"getRGB": {
			"topic": "zigbee/bulb",
			"apply": "var x = JSON.parse(message).color.x; var y = JSON.parse(message).color.y; var z = 1.0 - x - y; var Y1 = JSON.parse(message).brightness / 2.54; var X1 = (Y1 / y) * x; var Z1 = (Y1 / y) * z; var r = X1 * 1.612 - Y1 * 0.203 - Z1 * 0.302; var g = -X1 * 0.509 + Y1 * 1.412 + Z1 * 0.066; var b = X1 * 0.026 - Y1 * 0.072 + Z1 * 0.962; return r.toString() + ',' + g.toString() + ',' + b.toString();"
		},
		"setRGB": {
			"topic": "zigbee/bulb/set",
			"apply": "return JSON.stringify({ color: { r:parseInt(message.split(',')[0]), g:parseInt(message.split(',')[1]), b:parseInt(message.split(',')[2])}});"
                },
                "getWhite": {
			"topic": "zigbee/bulb",
			"apply": "return (JSON.parse(message).brightness / 2.54).toString"
		},
		"setWhite": {
			"topic": "zigbee/bulb/set",
			"apply": "return JSON.stringify({ brightness: parseInt(message) * 2.54 });"
		}
        },
        "onValue": "ON",
        "offValue": "OFF"
}

**Comment by odx** [comment]
Another remark: When I set { "brightness": 50 } through MQTT directly it works as expected. But then I change it with HomeKit through mqttthing I notice that the brightness is directly incorporated into the RGB values which does not have any effect on the brightness of the bulb directly.

Is there any reason why the setBrightness topic is not called when the setRGB is defined?

**Comment by arachnetech** [comment]
Currently if you use RGB the brightness is expected to be encoded in the RGB values - e.g. 255,0,0 is red and full brightness and 128,0,0 is red at 50% brightness.

**Comment by odx** [comment]
Thanks. I managed to configure the tradfri through HSV topics. Brightness Color and Color Temperature Picker in Home App work as expected from what I can see. Nevertheless I had to implement quite complex conversions in the apply functions. I transformed HSV to RGB and then from RGB to CIE and back. HSV conversion is based on mqttthing code but for CIE I had to add some other code. I used this: https://github.com/usolved/cie-rgb-converter/blob/master/cie_rgb_converter.js
Maybe it would be a good idea to add CIE topics to the bulb configurations. That would simplify the apply transformation for this integration a lot.
Here is my config for the curious:


{
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Sofalampe",
            "topics":
            {
                    "getOn": {
                            "topic": "zigbee/sofalampe",
                            "apply": "return JSON.parse(message).state;"
                    },
                    "setOn": {
                            "topic": "zigbee/sofalampe/set",
                            "apply": "return JSON.stringify({ state: message})"
                    },
                    "getHSV": {
                        "topic": "zigbee/sofalampe",
                        "apply":"function cie_to_rgb(r,s,t){void 0===t&&(t=254);var a=1-r-s,h=(t\/254).toFixed(2),o=h\/s*r,e=h\/s*a,v=1.656492*o-.354851*h-.255038*e,i=.707196*-o+1.655397*h+.036152*e,n=.051713*o-.121364*h+1.01153*e;return v>n&&v>i&&v>1?(i\/=v,n\/=v,v=1):i>n&&i>v&&i>1?(v\/=i,n\/=i,i=1):n>v&&n>i&&n>1&&(v\/=n,i\/=n,n=1),v=v<=.0031308?12.92*v:1.055*Math.pow(v,1\/2.4)-.055,i=i<=.0031308?12.92*i:1.055*Math.pow(i,1\/2.4)-.055,n=n<=.0031308?12.92*n:1.055*Math.pow(n,1\/2.4)-.055,v=Math.round(255*v),i=Math.round(255*i),n=Math.round(255*n),isNaN(v)&&(v=0),isNaN(i)&&(i=0),isNaN(n)&&(n=0),[v,i,n]}function RGBtoHSV(r,s,t){1===arguments.length&&(s=r.g,t=r.b,r=r.r);var a,h=Math.max(r,s,t),o=Math.min(r,s,t),e=h-o,v=0===h?0:e\/h,i=h\/255;switch(h){case o:a=0;break;case r:a=s-t+e*(s<t?6:0),a\/=6*e;break;case s:a=t-r+2*e,a\/=6*e;break;case t:a=r-s+4*e,a\/=6*e}return{h:a,s:v,v:i}}var m=JSON.parse(message),rgb=cie_to_rgb(m.color.x,m.color.y,m.brightness\/2.55),hsv=RGBtoHSV(rgb[0],rgb[1],rgb[2]);hsv.h=360*hsv.h,hsv.s=100*hsv.s,hsv.v=254*hsv.v;var result=hsv.h.toString()+\",\"+hsv.s.toString()+\",\"+(m.brightness\/2.54).toString();return result;"
                },
                    "setHSV": {
                        "topic": "zigbee/sofalampe/set",
                        "apply": "function HSVtoRGB(r,a,e){var t,s,o,b,c,n,i,u;switch(1===arguments.length&&(a=r.s,e=r.v,r=r.h),n=e*(1-a),i=e*(1-(c=6*r-(b=Math.floor(6*r)))*a),u=e*(1-(1-c)*a),b%6){case 0:t=e,s=u,o=n;break;case 1:t=i,s=e,o=n;break;case 2:t=n,s=e,o=u;break;case 3:t=n,s=i,o=e;break;case 4:t=u,s=n,o=e;break;case 5:t=e,s=n,o=i}return{r:Math.round(255*t),g:Math.round(255*s),b:Math.round(255*o)}}function ScaledHSVtoRGB(r,a,e){return HSVtoRGB(r\/360,a\/100,e\/100)}function rgb_to_cie(r,a,e){var t=.664511*(r=r>.04045?Math.pow((r+.055)\/1.055,2.4):r\/12.92)+.154324*(a=a>.04045?Math.pow((a+.055)\/1.055,2.4):a\/12.92)+.162028*(e=e>.04045?Math.pow((e+.055)\/1.055,2.4):e\/12.92),s=.283881*r+.668433*a+.047685*e,o=88e-6*r+.07231*a+.986039*e,b=(t\/(t+s+o)).toFixed(4),c=(s\/(t+s+o)).toFixed(4);return isNaN(b)&&(b=0),isNaN(c)&&(c=0),[b,c]}var params=message.split(\",\"),result={},rgb=ScaledHSVtoRGB(params[0],params[1],100),xy=rgb_to_cie(rgb.r,rgb.g,rgb.b);result.color={x:xy[0],y:xy[1]};var b=2.54*params[2];result.brightness=b;return JSON.stringify(result);"
                }
            },
            "onValue": "ON",
            "offValue": "OFF"
    }

**Comment by apauly** [comment]
@odx Works like a charm! After hours of trial and error this one saved me probably a lot more hours of trial and error ;) Thanks a lot!
