### ISSUE TITLE
Request: Dimmer Switch

### ISSUE THREAD

**Issue by Lethegrin** [arachnetech/homebridge-mqttthing#81]
A dimmer switch would be a useful option. It can subscribe and publish to brightness as well as having  an on off state. 

This is better than a light bulb because a dimmer switch has the option of being categorized as a light, fan, or switch which helps with siri commands.

**Comment by dylexrocks** [comment]
This would also help me, since I integrated my Logitech Media Server speakers as dimmable bulbs in order to control the volume.

**Comment by Lethegrin** [comment]
In fact this is my exact use. Not Logitech, but speakers. I use a dimable bulb currently, however every time I instruct siri to turn off all of the lights, my speaker turns off as well.

Seeing that speakers are not supported, this would be the next best thing.

**Comment by mkormendy** [comment]
@arachnetech any chance we could get this added to the list? I have a dimmer switch that is not used for a light bulb.

**Comment by arachnetech** [comment]
Very to happy to add if I can work out what 'Service' it is in Homekit. Can you see it on https://github.com/KhaosT/HAP-NodeJS/blob/HEAD/src/lib/gen/HomeKit.ts?

**Comment by mkormendy** [comment]
@arachnetech asking me if I can see it in that list comes across as heavily rhetorical. If it doesn't fall in that list, does that mean you can't augment the HAP-NODEJS with a new device/service with characteristics that already exist on that list?

**Comment by arachnetech** [comment]
I don’t think it’s possible to define new services and characteristics - at least not ones that the Home app will understand. (Eve seem to have added custom ones for use in their own app.)

Very happy to be corrected by anyone who knows better, of course. I know very little about HomeKit, to be honest!

**Comment by mkormendy** [comment]
You know more than I do at this point so I’m just curious if anything.

I’ve heard the Eve app messes with HomeKit accessories in the Home app. I’ve uninstalled it since, I don’t want it screwing up my device configurations.

**Comment by arachnetech** [comment]
I don’t think HomeKit supports the concept of a dimmer switch - at least I can’t see one. The standard Switch only has an On characteristic. Light appears to be your only option.
