### ISSUE TITLE
Issue: Speaker and Microphone unsupported in home app

### ISSUE THREAD

**Issue by Lethegrin** [arachnetech/homebridge-mqttthing#82]
Both the speaker and microphone are listed as being unsupported in the homekit app. I realize this is an apple problem, I am just curious if there is a way around this issue seeing you have taken the time to code it in.

**Comment by arachnetech** [comment]
I’m not aware of a workaround, unfortunately. I added support to see whether they would work, and unfortunately they didn’t!

I’m rather disappointed by Apple’s support of HomeKit. It’s a great platform but they just don’t appear to be fixing issues and enhancing it as fast as I’d hoped.

**Comment by Lethegrin** [comment]
Definitely. Okay thank you for the response.
