### ISSUE TITLE
Can't parse octoprint readings

### ISSUE THREAD

**Issue by m4gn3to** [arachnetech/homebridge-mqttthing#83]
Hi.

I'm noob with JSON.parse... 
I'm sure I'm doing something wrong but I'm not able to find what or where...

My octoprint publish this topics:
 - octoprint/temperature/tool0

whit this value:
 - {"_timestamp": 1552931581, "actual": 23.2, "target": 0.0}

I have this configuration:

{
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "Temperatura del hotend test",
            "url": "mqtt://xxx.xxx.xxx.xxx",
            "username": "knownuser",
            "password": "correctpassword",
            "caption": "Temperatura del hotend test",
            "logMqtt": true,
            "topics": {
                "getCurrentTemperature": "octoprint/temperature/tool0",
                "apply": "return JSON.parse(message).actual;"
            }
        },

But in my iPhone I always get 0.0 as current temperature.

Anyone can help me? Sorry if this is not the right place to ask...

**Comment by Lethegrin** [comment]
Not the author of this plugin but you'll definitely need to parse it BEFORE sending. Which octoprint plugin are you using to send the value VIA MQTT?

**Comment by m4gn3to** [comment]
I don't know how to do that and I think that all the people parse the message on receiving, as is very likely that you don't have access to the source code of the sending plugin.

I'm using: https://github.com/OctoPrint/OctoPrint-MQTT/blob/master/README.md

Thanks

**Comment by ScharV** [comment]
Have you found a solution for it?

**Comment by arachnetech** [comment]
Your topic configuration format is wrong. Try:

```
"topics": {
    "getCurrentTemperature": {
        “topic”: "octoprint/temperature/tool0",
        "apply": "return JSON.parse(message).actual;"
    }
}
```
