### ISSUE TITLE
Air Quality

### ISSUE THREAD

**Issue by mientki** [arachnetech/homebridge-mqttthing#89]
I have a device based on NodeMCU and sensors: air quality PMS7003 and BMP280. A MQTT topics alert device that looks like this:

![IMG_1997](https://user-images.githubusercontent.com/37380727/55681411-a85ff100-5926-11e9-857a-93268939eec6.png)

How can I configure the accessory to show me the air quality based on measurements?

```
        {
            "accessory": "mqttthing",
            "type": "airQualitySensor",
            "name": "AirQuality",
            "url": "mqtt://localhost",
            "username": "user",
            "password": "pass",
            "logMqtt": "true",
            "topics": {
                "getAirQuality": "Smogomierz-675863/sensor/PM2.5",
                "getAirQualityPPM": "Smogomierz-675863/sensor/PM2.5"
            },
            "history": true
        }
```

**Comment by tobekas** [comment]
There are optional AirQuality characteristics to show actual values for PM10, PM2.5, Co2, pressure, ... but not all of them are supported in homebridge-mqttthing yet.

Unfortunately, the Eve history graph is only supported for VOC density [ppm], not for PM.

**Comment by mientki** [comment]
Is it possible to display the current PM2.5 and PM10 values?   I do not need a history of any of these values, only the current measurement.

**Comment by tobekas** [comment]
Yes, it should be possible to add those optional characteristics for AirQuality service. Many of them are already Homekit-standard and are available in https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

**Comment by arachnetech** [comment]
Added in 1.0.33.
