### ISSUE TITLE
"doorbell" mode incorrectly defined

### ISSUE THREAD

**Issue by matphillips** [arachnetech/homebridge-mqttthing#9]
The 'Doorbell' mode, is defined as
`service = new Service.Doorbell(name);`
but causes an error, it should be:
`service = new Service.StatelessProgrammableSwitch(name);`

https://github.com/arachnetech/homebridge-mqttthing/blob/6a3fd0a1b58c6051fe01ea5bc66aa39da1fd6695/index.js#L464

**Comment by arachnetech** [comment]
My Doorbell is attempting to use the **Doorbell** Service, as defined in https://github.com/KhaosT/HAP-NodeJS/blob/HEAD/lib/gen/HomeKitTypes.js:

```
/**
 * Service "Doorbell"
 */

Service.Doorbell = function(displayName, subtype) {
  Service.call(this, displayName, '00000121-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.ProgrammableSwitchEvent);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Brightness);
  this.addOptionalCharacteristic(Characteristic.Volume);
  this.addOptionalCharacteristic(Characteristic.Name);
};
```

However, HomeKit doesn't seem to like it, simply displaying "Not Supported".

I'll try adding a **StatelessProgrammableSwitch**, but as a separate accessory type as it supports fewer characteristics than **Doorbell**:

```
/**
 * Service "Stateless Programmable Switch"
 */

Service.StatelessProgrammableSwitch = function(displayName, subtype) {
  Service.call(this, displayName, '00000089-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.ProgrammableSwitchEvent);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Name);
  this.addOptionalCharacteristic(Characteristic.ServiceLabelIndex);
};
```

**Comment by arachnetech** [comment]
@matphillips You say **Doorbell** "causes an error". Do you mean the HomeKit "Not Supported", or is there an error somewhere else that might help to explain *why* it's not supported? (I'm keen to get Doorbell working if I can.)

**Comment by matphillips** [comment]
I edited the file a while ago and didn’t make a not of the specifics. I will revert it and see exactly what happens but I’m away from the installation currently and won’t have access to it for two weeks. Will update when I can. Thanks.

**Comment by arachnetech** [comment]
Thanks. Absolutely no rush from my perspective - just interested to get this working better if I can. (I'm sorry it's taken me so long to come back to you - I'd accidentally stopped watching the project, and while I use HomeBridge and homebridge-mqttthing daily I've not needed to make any changes to it for my own purposes for a while.)

**Comment by arachnetech** [comment]
Stateless Programmable Switch added in 1.0.8.

**Comment by arachnetech** [comment]
I'll close this for now, but please re-open if you believe that there are changes required. Thanks.
