### ISSUE TITLE
Nodecmu with tasmota firmware and Mqtt

### ISSUE THREAD

**Issue by PieterDes** [arachnetech/homebridge-mqttthing#92]
Hi all,

I flashed a generic nodecmu device with the tasmoto firmware and connected a relay to it. 
Changed the config to generic board, set up the Mqtt in homebridge and everything works fine.

Now, what if I add another sensor or relay or whatever to the nodecmu board.

How can I set/get the value for that sensor or relay ... via Mqtt ? 

there is only one topic so how can I target one specific gpio pin ? 

Thanks in advance !

**Comment by tobekas** [comment]
Just add another accessory to your config.json with a new MQTT topic. Accessories with more than one Switch Service are not possible, as far as I know. In any case, it would be displayed as a separate device.

**Comment by PieterDes** [comment]
Hi,
I know I need to add another accessory to my config.json.

Only thing I do not know is the topic name. I have no idea what the topic name is for a specific pin.

Thanks a lot !

**Comment by tobekas** [comment]
You can set Power1, Power2,...
Have a closer look at https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#control

This is more a Tasmota specific question...
