### ISSUE TITLE
Error: Missing protocol

### ISSUE THREAD

**Issue by desq42** [arachnetech/homebridge-mqttthing#94]
What am i doing wrong? I tested your plugin on 2 different platforms (Raspbian/Linux) and 
I´m getting the same error-msg on Homebridge restart. I tried to install "missing" modules. No cigar.

Apr 14 10:43:57 hyperion homebridge[6389]: [2019-4-14 10:43:57] [Contact] Initializing mqttthing accessory...
Apr 14 10:43:57 hyperion homebridge[6389]: [2019-4-14 10:43:57] Error: Missing protocol
Apr 14 10:43:57 hyperion homebridge[6389]:     at Object.connect (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/connect/index.js:64:13)
Apr 14 10:43:57 hyperion homebridge[6389]:     at mqttInit (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:65:31)
Apr 14 10:43:57 hyperion homebridge[6389]:     at new makeThing (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:88:22)
Apr 14 10:43:57 hyperion homebridge[6389]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
Apr 14 10:43:57 hyperion homebridge[6389]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Apr 14 10:43:57 hyperion homebridge[6389]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Apr 14 10:43:57 hyperion homebridge[6389]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)`

**Comment by desq42** [comment]
What am i doing wrong. I tested your plugin on 2 different platforms (Raspbian/Linux) and 
I´m getting the same error-msg on Homebridge restart.
I tried to install "missing" modules. No cigar.

`        Apr 14 10:43:57 hyperion homebridge[6389]: [2019-4-14 10:43:57] [Contact] Initializing mqttthing accessory...
Apr 14 10:43:57 hyperion homebridge[6389]: [2019-4-14 10:43:57] Error: Missing protocol
Apr 14 10:43:57 hyperion homebridge[6389]:     at Object.connect (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/connect/index.js:64:13)
Apr 14 10:43:57 hyperion homebridge[6389]:     at mqttInit (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:65:31)
Apr 14 10:43:57 hyperion homebridge[6389]:     at new makeThing (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:88:22)
Apr 14 10:43:57 hyperion homebridge[6389]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
Apr 14 10:43:57 hyperion homebridge[6389]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Apr 14 10:43:57 hyperion homebridge[6389]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Apr 14 10:43:57 hyperion homebridge[6389]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)`

**Comment by arachnetech** [comment]
Solved?

**Comment by desq42** [comment]
Sadly no. ;-)

**Comment by desq42** [comment]
…has anybody a clue?

**Comment by arachnetech** [comment]
The 'Missing protocol' error seems to be coming from MQTT (`node_modules/mqtt/lib/connect/index.js`). What MQTT configuration are you specifying?

**Comment by desq42** [comment]
Mea culpa. There was a problem with my mqtt-Broker. Closing Issue…
"nothing to see here folks move along"… ;-)

**Comment by jhandke** [comment]
Hi! I´m having the same problem. @desq42 Can you tell me what solved it for you?

**Comment by g30r93g** [comment]
yes same here. using mosquitto and latest version
