### ISSUE TITLE
Loading Fakegato-History can crash

### ISSUE THREAD

**Issue by tobekas** [arachnetech/homebridge-mqttthing#95]
This line can crash after history data storage has reached it's maximum memory size and the ring buffer is wrapping around:
https://github.com/arachnetech/homebridge-mqttthing/blob/73ddfbd44d12f521da285a937fcbc6782b1f4b97/index.js#L877

`lastEntry` will become way too high, so this element does not exist and thus there is no property "time". I had not considered this wrap-around.

The right code must be:
`let lastTime = historySvc.history[historySvc.lastEntry % historySvc.memorySize].time - historySvc.getInitialTime();`

It would be even better to add a hasOwnProperty('time') check.

**Comment by arachnetech** [comment]
How about:
```
            if (historySvc.lastEntry && historySvc.memorySize) {
                let entry = historySvc.history[historySvc.lastEntry % historySvc.memorySize];
                if(entry && entry.hasOwnProperty('time')) {
                    let lastTime = entry.time - historySvc.getInitialTime();
                    addCharacteristic(service, 'lastActivation', Eve.Characteristic.LastActivation, lastTime);
                    log.debug('lastActivation time loaded');
                }
            }
```

**Comment by tobekas** [comment]
Yes, that‘s good!
