### ISSUE TITLE
Request: history folder

### ISSUE THREAD

**Issue by mcboeck** [arachnetech/homebridge-mqttthing#97]
Hey,

first: awesome Plug-in.
Would it be possible to add the path to the history settings? I'd like to write the history to a Ram-Disk.

Thank you.

mcboeck

**Comment by tobekas** [comment]
After this line https://github.com/arachnetech/homebridge-mqttthing/blob/d01d4f8bc16ef30dd661ebbfe50b145812937116/index.js#L153
there would just have to be added:
`if(config.history.path) {
    this.path = config.history.path;
}`

**Comment by tobekas** [comment]
But @mcboeck: keep in mind that this history file is only meant as a ring buffer and you have to open the Eve App after a while to get the latest entries.

The complete history is then stored within the app and you can export it from the App as .xslx file.

**Comment by mcboeck** [comment]
Awesome. Thanks. Just tried it and it works perfectly.

**Comment by arachnetech** [comment]
Added persistencePath to historyOptions in 1.1.9
