### ISSUE TITLE
RGBW Controller Settings (Tasmota)

### ISSUE THREAD

**Issue by jakobsudau** [arachnetech/homebridge-mqttthing#98]
Hello!
Love your plugin so far, working really well and I've been integrating all my smart home devices.

But now I have a problem with my RGBW LED Controller and I was hoping someone here could help me out!

So I have the Luminea ZX-2844 RGBW LED Controller and have flashed it with Tasmota. I tried setting it up with [this](https://github.com/arendst/Sonoff-Tasmota/wiki/Luminea-ZX-2844-675-(RGBW-LED-Controller)) config and [this](https://blakadder.github.io/templates/luminea_zx-2844.html) one.
d
I then tried to set it up in mqttthing with this config:
```
{
   "accessory": "mqttthing",    
   "type": "lightbulb", 
   "name": "My Device", 
   "username": "", 
   "password": "", 
   "topics": { 
      "getOn": "stat/MyDeviceTopic/POWER", 
      "setOn": "cmnd/MyDeviceTopic/POWER", 
      "getHSV": "stat/MyDeviceTopic/HSBCOLOR", 
      "setHSV": "cmnd/MyDeviceTopic/HSBCOLOR" 
   }, 
   "onValue": "ON", 
   "offValue": "OFF",
   "startPub": {
      "cmnd/MyDeviceTopic/POWER": ""
   }
}
```

But the colours are not really working, it is showing different colours (mostly blue and green, no red).

Any idea on how I could fix this? 
Should I rather use getRGBW and setRGBW?
What command should I use? according to the [Tasmota docs](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#light), there is the COLOR and HSBCOLOR command (and variants of it) - tried these two with basically the same results.
Should I look at the config of the tasmota firmware and try different GPIO settings?

Any help would be appreciated!

**Comment by tobekas** [comment]
First please check if your controller is working properly. You can test and debug with MQTT.fx software. Try sending HSBCOLOR cmnd MQTT messages by yourself and check the responding stat messages. The payload must be A comma separated triple `<0-360>,<0-100>,<0-100>`.

**Comment by tobekas** [comment]
I think rather, that this is a tasmota issue. The right GPIO configuration order is important.
Does the controller do his job, if you set the color from Tasmota WebUI directly?

**Comment by jakobsudau** [comment]
Hello,
Thanks for all your feedback! 
I've worked this issue out by using my older MagicHome RGB LED Controller and flashing it manually (not over the air) with the Tasmota firmware. For the MagicHome device there were plenty of resources online to get it working.

**Comment by ceraz68** [comment]
> 
> 
> Hello,
> Thanks for all your feedback!
> I've worked this issue out by using my older MagicHome RGB LED Controller and flashing it manually (not over the air) with the Tasmota firmware. For the MagicHome device there were plenty of resources online to get it working.

Hi Jakobsudau, I have a MagicHome RGB controller running Tasmota also and a bit confused with the config.sys settings to get it working. In Tasmota, did you configure the controller as a generic device or a ready-made template ? Can you post your final working config.sys?

Thanks a lot :-)

**Comment by ceraz68** [comment]
OK managed to get it working for a MagicHome RGB + IR controller with Tasmota 6.6.0.

The predefined tasmota Magichome template didn't work for me as Red and Green were inverted, so I selected the generic module with these colour settings (GPIO5 = PWM1 (red), GPIO14 = PWM2 (green), GPIO12 = PWM3 (blue)). In the tasmota console check GPIOs by typing "color 1" and check strip is red, type "color 2" and check strip is green, type "color 3" and check strip is blue. IOs can change depending on LED module.

My config.json is as follows:

        {
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Kitchen LED",
            "url": "mqtt://x.x.x.x",
            "username": "xxx",
            "password": "xxx",
            "topics": {
                "getOn": "stat/LED/POWER",
                "setOn": "cmnd/LED/POWER",
                "getRGB": "stat/LED/COLOR",
                "setRGB": "cmnd/LED/COLOR"
            },
            "onValue": "ON",
            "offValue": "OFF"
        },



Caveats so far (but not important for me):
1) via web access using console to set a color (eg command "color 1")does not update the color of the home app lightbulb color. It would imply parsing the stat mqtt broadcast for "Color".
CMD: color 1
MQT: stat/LED/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FF0000","HSBColor":"0,100,100","Channel":[100,0,0]}

2) via web access adjusting the brightness level on the module does not update the home app lightbulb icon. It would imply parsing the stat mqtt broadcast for "Dimmer".
stat/LED/RESULT = {"POWER":"ON","Dimmer":43,"Color":"6E0000","HSBColor":"0,100,43","Channel":[43,0,0]}

**Comment by Batyushin** [comment]
Tell me, can anyone implement the scene mode? I did so, but not very correctly.

        {
            "accessory": "mqttthing",
            "type": "switch",
            "name": "scheme",
            "url": "mqtt://127.0.0.1",
            "username": "admin",
            "password": "admin",
            "topics": {
                "getOn": "stat/MagicHome/RESULT",
                "setOn": "cmnd/MagicHome/RESULT/scheme"
            },
            "integerValue": "true",
            "onValue": "2",
            "offValue": "0"
        }
